"""Standard POSIX error symbols used by Python filesystem libraries."""

# Stable Python/POSIX values.  Host-specific Node errno values are normalized
# by :mod:`os` before they become Python exceptions.
EPERM = 1
ENOENT = 2
ESRCH = 3
EINTR = 4
EIO = 5
ENXIO = 6
E2BIG = 7
ENOEXEC = 8
EBADF = 9
ECHILD = 10
EAGAIN = 11
ENOMEM = 12
EACCES = 13
EFAULT = 14
EBUSY = 16
EEXIST = 17
EXDEV = 18
ENODEV = 19
ENOTDIR = 20
EISDIR = 21
EINVAL = 22
ENFILE = 23
EMFILE = 24
ENOTTY = 25
ETXTBSY = 26
EFBIG = 27
ENOSPC = 28
ESPIPE = 29
EROFS = 30
EMLINK = 31
EPIPE = 32
EDOM = 33
ERANGE = 34
EDEADLK = 35
ENAMETOOLONG = 36
ENOLCK = 37
ENOSYS = 38
ENOTEMPTY = 39
ELOOP = 40
ENOMSG = 42
EIDRM = 43
ENOSTR = 60
ENODATA = 61
ETIME = 62
ENOSR = 63
ENOLINK = 67
EPROTO = 71
EMULTIHOP = 72
EBADMSG = 74
EOVERFLOW = 75
EILSEQ = 84
ENOTSOCK = 88
EDESTADDRREQ = 89
EMSGSIZE = 90
EPROTOTYPE = 91
ENOPROTOOPT = 92
EPROTONOSUPPORT = 93
ENOTSUP = 95
EOPNOTSUPP = ENOTSUP
EAFNOSUPPORT = 97
EADDRINUSE = 98
EADDRNOTAVAIL = 99
ENETDOWN = 100
ENETUNREACH = 101
ENETRESET = 102
ECONNABORTED = 103
ECONNRESET = 104
ENOBUFS = 105
EISCONN = 106
ENOTCONN = 107
ETIMEDOUT = 110
ECONNREFUSED = 111
EHOSTUNREACH = 113
EALREADY = 114
EINPROGRESS = 115
ESTALE = 116
EDQUOT = 122
ECANCELED = 125
EWOULDBLOCK = EAGAIN

errorcode = {
    EPERM: 'EPERM', ENOENT: 'ENOENT', ESRCH: 'ESRCH', EINTR: 'EINTR',
    EIO: 'EIO', ENXIO: 'ENXIO', E2BIG: 'E2BIG', ENOEXEC: 'ENOEXEC',
    EBADF: 'EBADF', ECHILD: 'ECHILD', EAGAIN: 'EAGAIN', ENOMEM: 'ENOMEM',
    EACCES: 'EACCES', EFAULT: 'EFAULT', EBUSY: 'EBUSY', EEXIST: 'EEXIST',
    EXDEV: 'EXDEV', ENODEV: 'ENODEV', ENOTDIR: 'ENOTDIR', EISDIR: 'EISDIR',
    EINVAL: 'EINVAL', ENFILE: 'ENFILE', EMFILE: 'EMFILE', ENOTTY: 'ENOTTY',
    EFBIG: 'EFBIG', ENOSPC: 'ENOSPC', ESPIPE: 'ESPIPE', EROFS: 'EROFS',
    EMLINK: 'EMLINK', EPIPE: 'EPIPE', EDOM: 'EDOM', ERANGE: 'ERANGE',
    EDEADLK: 'EDEADLK', ENAMETOOLONG: 'ENAMETOOLONG', ENOLCK: 'ENOLCK',
    ENOSYS: 'ENOSYS', ENOTEMPTY: 'ENOTEMPTY', ELOOP: 'ELOOP',
    ENOMSG: 'ENOMSG', EIDRM: 'EIDRM', ENOSTR: 'ENOSTR', ENODATA: 'ENODATA',
    ETIME: 'ETIME', ENOSR: 'ENOSR', ENOLINK: 'ENOLINK', EPROTO: 'EPROTO',
    EMULTIHOP: 'EMULTIHOP', EBADMSG: 'EBADMSG', EOVERFLOW: 'EOVERFLOW',
    EILSEQ: 'EILSEQ', ENOTSOCK: 'ENOTSOCK', EDESTADDRREQ: 'EDESTADDRREQ',
    EMSGSIZE: 'EMSGSIZE', EPROTOTYPE: 'EPROTOTYPE',
    ENOPROTOOPT: 'ENOPROTOOPT', EPROTONOSUPPORT: 'EPROTONOSUPPORT',
    ENOTSUP: 'ENOTSUP', EAFNOSUPPORT: 'EAFNOSUPPORT',
    EADDRINUSE: 'EADDRINUSE', EADDRNOTAVAIL: 'EADDRNOTAVAIL',
    ENETDOWN: 'ENETDOWN', ENETUNREACH: 'ENETUNREACH',
    ENETRESET: 'ENETRESET', ECONNABORTED: 'ECONNABORTED',
    ECONNRESET: 'ECONNRESET', ENOBUFS: 'ENOBUFS', EISCONN: 'EISCONN',
    ENOTCONN: 'ENOTCONN', ETIMEDOUT: 'ETIMEDOUT',
    ECONNREFUSED: 'ECONNREFUSED', EHOSTUNREACH: 'EHOSTUNREACH',
    EALREADY: 'EALREADY', EINPROGRESS: 'EINPROGRESS', ESTALE: 'ESTALE',
    EDQUOT: 'EDQUOT', ECANCELED: 'ECANCELED',
}

__all__ = list(errorcode.values()) + ['errorcode']
