"use strict";

const assert = require("node:assert/strict");
const test = require("node:test");

const { createSage } = require("../dist/tools/kernel.js");

test(
  "hyperelliptic periods recover the real lattice and preserve honest status",
  { timeout: 300_000 },
  async () => {
    const session = await createSage();
    try {
      const result = await session.evaluate(String.raw`
from sagejs.hyperelliptic_curves.periods import (
    HyperellipticPeriodCapabilityError,
    clear_period_cache,
    period_cache_info,
    real_period,
)
clear_period_cache()
R = PolynomialRing(QQ, "x")
x = R.gen()
C = HyperellipticCurve((x+3)*(x+2)*(x+1)*(x-1)*(x-2))
P = real_period(C, prec=64)
assert P.genus == 2 and P.period_matrix().nrows() == 2
assert P.period_matrix().ncols() == 4 and P.siegel_matrix().nrows() == 2
assert P.real_components() == 4
assert not P.rigorous and not P.arithmetic_balls_rigorous
assert P.normalization_status == "model_normalized"
assert P.verify()["verified"] and P.diagnostics()["refinement_stable"] is not False
record = P.to_dict()
assert record["schema"] == "sagejs.hyperelliptic/real-period-v1"
assert record["root_isolation_status"].startswith("exact_QQbar_identity")
assert record["normalization"]["neron_differential_determinant"] is None

Q = real_period(C, prec=64)
assert Q.cache_hit and period_cache_info()["model_hits"] == 1
N = real_period(
    C,
    prec=64,
    normalization="neron",
    neron_lattice_index=2,
    provenance={"kind": "test", "source": "supplied exact lattice index"},
)
assert abs(float(N.neron_period() / P.model_period()) - 0.5) < 1e-14
assert N.to_dict()["normalization"]["neron_lattice_index"] == 2
try:
    real_period(C, prec=64, normalization="neron")
    raise AssertionError("missing Neron normalization was silently accepted")
except HyperellipticPeriodCapabilityError as error:
    assert error.code == "neron_normalization_unavailable"
True
`);
      assert.equal(result.repr, "True");
    } finally {
      await session.close();
    }
  },
);

test(
  "mixed, even, generalized, and genus-3 models pass period capability gates",
  { timeout: 300_000 },
  async () => {
    const session = await createSage();
    try {
      const result = await session.evaluate(String.raw`
from sagejs.hyperelliptic_curves.periods import real_period
R = PolynomialRing(QQ, "x")
x = R.gen()
mixed = real_period(HyperellipticCurve(x^5-x+1), prec=64)
even = real_period(HyperellipticCurve(x^6+x+1), prec=64)
f = x^5 + x^3 + 2
h = x^2 + 1
generalized_curve = HyperellipticCurve(f, h)
completed_curve = HyperellipticCurve((h^2 + 4*f)/4)
generalized = real_period(generalized_curve, prec=64)
completed = real_period(completed_curve, prec=64)
genus_three = real_period(HyperellipticCurve(x^7-x+1, x^2), prec=64)
assert mixed.real_components() == 1
assert even.genus == generalized.genus == completed.genus == 2
assert genus_three.genus == 3 and genus_three.period_matrix().ncols() == 6
assert all(item.verify()["verified"] for item in [mixed, even, generalized, completed, genus_three])
assert abs(float(generalized.model_period() - completed.model_period())) < 1e-9
True
`);
      assert.equal(result.repr, "True");
    } finally {
      await session.close();
    }
  },
);

test(
  "Abel--Jacobi lifts reuse periods and add split rational support",
  { timeout: 300_000 },
  async () => {
    const session = await createSage();
    try {
      const result = await session.evaluate(String.raw`
from sagejs.hyperelliptic_curves.periods import abel_jacobi, real_period
R = PolynomialRing(QQ, "x")
x = R.gen()
C = HyperellipticCurve(x^5-x+1)
periods = real_period(C, prec=64)
positive = C([0, 1])
negative = C([0, -1])
u = abel_jacobi(C, positive, period_result=periods, prec=64)
v = periods.abel_jacobi(negative, prec=64)
zero = abel_jacobi(C, [positive, negative], period_result=periods, prec=64)
assert u.genus == 2 and len(u.vector()) == 2
assert u.period_matrix() == periods.period_matrix()
assert u.verify()["verified"] and v.verify()["verified"] and zero.verify()["verified"]
assert max(abs(float(value.real())) + abs(float(value.imag())) for value in zero.vector()) < 1e-9
again = abel_jacobi(C, positive, period_result=periods, prec=64)
assert again.cache_hit
assert u.to_dict()["basepoint"] == "infinity"
assert not u.to_dict()["rigorous"]
True
`);
      assert.equal(result.repr, "True");
    } finally {
      await session.close();
    }
  },
);

test(
  "real periods match the versioned PARI genus-2 and genus-3 corpus",
  { timeout: 300_000 },
  async () => {
    const session = await createSage();
    try {
      const result = await session.evaluate(String.raw`
from sagejs.hyperelliptic_curves.periods import clear_period_cache, real_period
clear_period_cache()
R = PolynomialRing(QQ, "x")
# Exact rows from test/hyperelliptic-bsd-oracles/corpus.json, generated by the
# pinned PARI/GP 2.18.1.alpha transcript.  Arrays are ascending coefficients.
rows = [
    ("g2-N169-r0", [0,1,1], [1,0,1,1], "32.667031090507096110005902370143563809"),
    ("g2-N196-r0", [1,3,6,7,6,3,1], [0,1,1], "11.777147840612829156092291191048779085"),
    ("g2-N249-r0-quarter", [0,-1,0,1,1,3,2], [1,0,0,1], "25.783703374249836805826663230386351080"),
    ("g2-N277-r0-nine", [-6,11,-19,14,-9,1], [1], "3.5784165137752872538928802498095740031"),
    ("g2-N295-r0-49", [-38,-109,-50,53,15,1], [1,1,1], "0.59707347553287283623528285559846346231"),
    ("g2-N587-positive-rank", [0,-1,-1], [1,1,0,1], "29.510964061093545829670229541376376217"),
    ("g3-period-odd-1", [0,1,1,0,-2,-1,1,1], [1,0,1], "69.081200998004027497103951240276008092"),
    ("g3-period-odd-2", [0,1,-3,4,-3,3,-3,1], [0,0,1], "59.739112915049974362789703126695402159"),
]
field = RealField(64)
for identifier, f_coefficients, h_coefficients, expected_text in rows:
    curve = HyperellipticCurve(R(f_coefficients), R(h_coefficients))
    periods = real_period(curve, prec=64)
    expected = field(expected_text)
    relative_error = abs(periods.model_period() - expected) / expected
    assert relative_error < field("1e-15"), (identifier, relative_error)
    assert periods.verify()["verified"], identifier
True
`);
      assert.equal(result.repr, "True");
    } finally {
      await session.close();
    }
  },
);
