packages:
  - packages/*
allowBuilds:
  esbuild: true
  tree-sitter-cli: true
  tree-sitter-macaulay2: false
  wasi-js: false
  zeromq: true
minimumReleaseAgeExclude:
  - '@cortex-js/compute-engine@0.98.0'
supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64
  libc:
    - glibc
