"""Bounded class-group certificates and class-number-formula reports.

The existing imaginary-quadratic reduced-form implementation is a complete
deterministic algorithm and is wrapped here with replayable group evidence.
For fields not yet supported by certified prime-ideal relations this module
returns an explicitly incomplete search result rather than guessing a class
group from a truncated relation search.
"""

from __future__ import annotations

from typing import Any

import sagejs as sage
import sagejs.runtime as runtime

from sagejs.number_fields.embeddings import (
    certified_minkowski_class_bound,
    exact_signature,
)
from sagejs.number_fields.units import UnitSubgroupResult


class _TrivialClassElement:
    def __mul__(self, other: Any) -> _TrivialClassElement:
        if not isinstance(other, _TrivialClassElement):
            return NotImplemented
        return self

    def __pow__(self, exponent: Any) -> _TrivialClassElement:
        return self

    def __eq__(self, other: object) -> bool:
        return isinstance(other, _TrivialClassElement)

    def order(self) -> int:
        return 1

    def is_one(self) -> bool:
        return True


class _TrivialClassGroup:
    def __init__(self) -> None:
        self._one = _TrivialClassElement()

    def order(self) -> int:
        return 1

    def one(self) -> _TrivialClassElement:
        return self._one

    def list(self) -> list[_TrivialClassElement]:
        return [self._one]

    def invariants(self) -> tuple[()]:
        return ()

    def gens(self) -> tuple[()]:
        return ()


class PrincipalIdealWitness:
    """Exact witness that an ideal is generated by one field element."""

    def __init__(self, ideal: Any, generator: Any, purpose: str) -> None:
        self.ideal = ideal
        self.generator = generator
        self.purpose = purpose
        self.proof_status = "exact"

    def verify(self, field: Any) -> bool:
        try:
            return (
                self.ideal.ring() is field.maximal_order()
                and self.ideal == field.maximal_order().ideal(self.generator)
            )
        except (TypeError, ValueError, ArithmeticError):
            return False


class MinkowskiClassNumberOneCertificate:
    """Exact class-number-one proof by an empty Minkowski prime list.

    Every ideal class contains an integral ideal of norm at most the exact
    Minkowski bound.  A nonunit integral ideal has a prime-ideal factor of no
    larger norm.  Thus, if exact decompositions of every rational prime through
    the bound contain no prime ideal of norm through the bound, the class group
    is trivial.  The sole presentation element is represented by the unit
    ideal, with the explicit principal generator `1`.
    """

    def __init__(
        self,
        field: Any,
        bound: int,
        decomposition_records: list[dict[str, Any]],
        rational_primes_checked: list[int],
        identity_witness: PrincipalIdealWitness,
        max_rational_primes: int,
    ) -> None:
        self.field = field
        self.bound = bound
        self.decomposition_records = tuple(decomposition_records)
        self.rational_primes_checked = tuple(rational_primes_checked)
        self.identity_witness = identity_witness
        self.principal_relation_witnesses = (identity_witness,)
        self.max_rational_primes = max_rational_primes
        self.has_principal_element_witnesses = True
        self.proof_status = "exact"

    def verify(self) -> bool:
        if self.bound != certified_minkowski_class_bound(self.field):
            return False
        if self.max_rational_primes < 1:
            return False
        expected_primes = [
            value for value in range(2, self.bound + 1) if sage.is_prime(value)
        ]
        if len(expected_primes) > self.max_rational_primes:
            raise ValueError("Minkowski certificate replay exceeds its prime cap")
        if tuple(expected_primes) != self.rational_primes_checked:
            return False
        if not self.identity_witness.verify(self.field):
            return False
        prime_module = __import__(
            "sagejs.number_fields.prime_ideals", fromlist=["prime_ideals"]
        )
        records = []
        for rational_prime in expected_primes:
            decomposition = prime_module.factor_rational_prime(
                self.field.maximal_order(), rational_prime
            )
            if decomposition.verify()["certified"] is not True:
                return False
            records.append(decomposition.splitting_record(include_lattices=True))
            for prime_ideal in decomposition.prime_ideals():
                norm = prime_ideal.norm()
                if norm._denominator != 1:
                    return False
                if int(norm._numerator) <= self.bound:
                    # This bounded certificate deliberately covers exactly the
                    # class-number-one case where the prime list is empty.
                    return False
        return tuple(records) == self.decomposition_records


class ClassGroupCertificate:
    """Finite abelian presentation evidence for a computed class group."""

    def __init__(
        self,
        group: Any,
        invariants: list[int],
        generators: list[Any],
        enumerated_order: int,
        source: str,
        evidence_kind: str = "binary-quadratic-reduced-form-enumeration",
        arithmetic_certificate: Any = None,
    ) -> None:
        self.group = group
        self.invariants = tuple(invariants)
        self.generators = tuple(generators)
        self.enumerated_order = enumerated_order
        self.source = source
        self.proof_status = "exact"
        self.evidence_kind = evidence_kind
        self.arithmetic_certificate = arithmetic_certificate
        self.has_principal_element_witnesses = (
            arithmetic_certificate is not None
            and arithmetic_certificate.has_principal_element_witnesses
        )
        self.principal_ideal_witnesses = (
            arithmetic_certificate.principal_relation_witnesses
            if arithmetic_certificate is not None
            else ()
        )
        relation_witnesses = []
        for index in range(len(self.generators)):
            generator = self.generators[index]
            invariant = self.invariants[index]
            relation_witnesses.append(
                {
                    "generator_index": index,
                    "exponent": invariant,
                    "principal_result": generator**invariant,
                }
            )
        self.relation_witnesses = tuple(relation_witnesses)

    def verify(self, max_elements: int = 100_000) -> bool:
        if self.arithmetic_certificate is not None:
            if (
                type(self.arithmetic_certificate)
                is not MinkowskiClassNumberOneCertificate
            ):
                return False
            if not self.arithmetic_certificate.verify():
                return False
        expected = 1
        for invariant in self.invariants:
            if invariant < 2:
                return False
            expected *= invariant
        if expected != self.enumerated_order:
            if not (expected == 1 and self.enumerated_order == 1):
                return False
        if self.enumerated_order > max_elements:
            raise ValueError("certificate replay exceeds max_elements")
        if self.group.order() != self.enumerated_order:
            return False
        if len(self.generators) != len(self.invariants):
            return False
        for index in range(len(self.generators)):
            generator = self.generators[index]
            invariant = self.invariants[index]
            if generator**invariant != self.group.one():
                return False
            if generator.order() != invariant:
                return False
        for witness in self.relation_witnesses:
            index = witness["generator_index"]
            exponent = witness["exponent"]
            if self.generators[index] ** exponent != witness["principal_result"]:
                return False
            if witness["principal_result"] != self.group.one():
                return False
        if self.enumerated_order == 1:
            return len(list(self.group.list())) == 1
        generated = [self.group.one()]
        for index in range(len(self.generators)):
            generator = self.generators[index]
            invariant = self.invariants[index]
            enlarged = []
            for known in generated:
                power = self.group.one()
                for _exponent in range(invariant):
                    candidate = known * power
                    if not any(candidate == value for value in enlarged):
                        enlarged.append(candidate)
                    power *= generator
            generated = enlarged
        return len(generated) == self.enumerated_order


def certified_small_cubic_class_group(
    field: Any,
    max_minkowski_bound: int = 10,
    max_rational_primes: int = 10,
) -> ClassGroupSearchResult:
    """Prove class number one for the supported smallest cubic fields.

    This is a deliberately bounded vertical slice.  It recognizes
    `x^3-x-1` and `x^3-x^2-2*x+1`, requires a maximal power basis, and only
    succeeds when exact prime decomposition shows that the Minkowski list is
    empty.  A resource cap is an error, never evidence of completeness.
    """
    if max_minkowski_bound < 1 or max_rational_primes < 1:
        raise ValueError("class-group resource caps must be positive")
    if field.degree() != 3:
        raise ValueError("the certified small slice requires a cubic field")
    key = tuple(
        (int(value._numerator), int(value._denominator))
        for value in field._defining_coefficients
    )
    supported = (
        ((-1, 1), (-1, 1), (0, 1), (1, 1)),
        ((1, 1), (-2, 1), (-1, 1), (1, 1)),
    )
    if key not in supported:
        raise ValueError("this bounded certified slice does not recognize the cubic")
    order = field.maximal_order()
    power_basis = []
    power = field.one()
    for _index in range(field.degree()):
        power_basis.append(power)
        power *= field.gen()
    if list(order.basis()) != power_basis:
        raise ValueError("the certified small slice requires a maximal power basis")
    bound = certified_minkowski_class_bound(field)
    if bound > max_minkowski_bound:
        raise ValueError(
            "the exact Minkowski bound "
            + str(bound)
            + " exceeds max_minkowski_bound="
            + str(max_minkowski_bound)
        )
    rational_primes = [value for value in range(2, bound + 1) if sage.is_prime(value)]
    if len(rational_primes) > max_rational_primes:
        raise ValueError(
            "the Minkowski enumeration has "
            + str(len(rational_primes))
            + " rational primes, exceeding max_rational_primes="
            + str(max_rational_primes)
        )
    prime_module = __import__(
        "sagejs.number_fields.prime_ideals", fromlist=["prime_ideals"]
    )
    records = []
    for rational_prime in rational_primes:
        decomposition = prime_module.factor_rational_prime(order, rational_prime)
        if decomposition.verify()["certified"] is not True:
            raise ArithmeticError("prime decomposition failed exact replay")
        records.append(decomposition.splitting_record(include_lattices=True))
        for prime_ideal in decomposition.prime_ideals():
            norm = prime_ideal.norm()
            if norm._denominator != 1:
                raise ArithmeticError("an integral prime ideal has nonintegral norm")
            if int(norm._numerator) <= bound:
                raise ValueError(
                    "the bounded empty-prime-list proof does not apply to this field"
                )
    identity_witness = PrincipalIdealWitness(
        order.ideal(field.one()), field.one(), "identity class and empty relation set"
    )
    arithmetic = MinkowskiClassNumberOneCertificate(
        field,
        bound,
        records,
        rational_primes,
        identity_witness,
        max_rational_primes,
    )
    if not arithmetic.verify():
        raise ArithmeticError("Minkowski class-number-one certificate replay failed")
    group = _TrivialClassGroup()
    certificate = ClassGroupCertificate(
        group,
        [],
        [],
        1,
        "exact Minkowski bound and empty bounded prime-ideal list",
        "minkowski-empty-prime-list-with-principal-identity",
        arithmetic,
    )
    if not certificate.verify(max_elements=1):
        raise ArithmeticError("cubic class-group certificate replay failed")
    return ClassGroupSearchResult(
        field,
        True,
        certificate.source,
        bound,
        group,
        certificate,
    )


class ClassGroupSearchResult:
    """A class-group computation or an honest bounded incomplete result."""

    def __init__(
        self,
        field: Any,
        complete: bool,
        reason: str,
        minkowski_bound: int,
        group: Any = None,
        certificate: ClassGroupCertificate | None = None,
    ) -> None:
        self.field = field
        self.complete = complete
        self.reason = reason
        self.minkowski_bound = minkowski_bound
        self.group = group
        self.certificate = certificate
        self.proof_status = (
            "exact-" + certificate.evidence_kind
            if complete and certificate is not None
            else "incomplete"
        )
        self.has_principal_element_witnesses = (
            certificate is not None and certificate.has_principal_element_witnesses
        )
        if complete and (group is None or certificate is None):
            raise ValueError("a complete class group needs a group and certificate")

    def order(self) -> int:
        if not self.complete or self.group is None:
            raise ValueError("an incomplete class-group search has no certified order")
        return int(self.group.order())

    def invariants(self) -> tuple[int, ...]:
        if not self.complete or self.certificate is None:
            raise ValueError("an incomplete class-group search has no invariants")
        return self.certificate.invariants

    def __repr__(self) -> str:
        if self.complete:
            return "Certified class group of order " + str(self.order())
        return "Incomplete class-group search (" + self.reason + ")"


class AnalyticClassNumberFormulaReport:
    """Independent numerical comparison of the residue formula's two sides."""

    def __init__(
        self,
        *,
        signature: tuple[int, int],
        discriminant: int,
        class_number: int | None,
        regulator: float | None,
        roots_of_unity: int | None,
        analytic_residue: Any,
        algebraic_residue: float | None,
        precision: int,
        inputs_complete: bool,
        difference: float | None,
        compatible: bool | None,
    ) -> None:
        self.signature = signature
        self.discriminant = discriminant
        self.class_number = class_number
        self.regulator = regulator
        self.roots_of_unity = roots_of_unity
        self.analytic_residue = analytic_residue
        self.algebraic_residue = algebraic_residue
        self.requested_precision = precision
        self.effective_precision_bits = min(53, precision)
        self.precision = self.effective_precision_bits
        self.inputs_complete = inputs_complete
        self.difference = difference
        self.compatible = compatible
        self.status = "numerical-approximation"
        self.proof_status = (
            "exact-algebraic-inputs-numerical-cross-check"
            if inputs_complete
            else "incomplete-algebraic-inputs"
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema": "sagejs.number-fields/analytic-class-number-formula-v1",
            "signature": list(self.signature),
            "discriminant": self.discriminant,
            "class_number": self.class_number,
            "regulator": self.regulator,
            "roots_of_unity": self.roots_of_unity,
            "analytic_residue": str(self.analytic_residue),
            "algebraic_residue": self.algebraic_residue,
            "precision": self.precision,
            "requested_precision": self.requested_precision,
            "effective_precision_bits": self.effective_precision_bits,
            "inputs_complete": self.inputs_complete,
            "difference": self.difference,
            "compatible": self.compatible,
            "status": self.status,
            "proof_status": self.proof_status,
        }

    def __repr__(self) -> str:
        return (
            "Analytic class-number formula report ("
            + self.proof_status
            + ", compatible="
            + str(self.compatible)
            + ")"
        )


def _complex_midpoint(value: Any) -> complex:
    try:
        return complex(value)
    except (TypeError, ValueError):
        real_part = (
            value.real() if callable(getattr(value, "real", None)) else value.real
        )
        imag_part = (
            value.imag() if callable(getattr(value, "imag", None)) else value.imag
        )
        return complex(float(real_part), float(imag_part))


def bounded_class_group(
    field: Any,
    max_elements: int = 100_000,
) -> ClassGroupSearchResult:
    """Compute a certified class group where a bounded exact path exists."""
    if max_elements < 1:
        raise ValueError("max_elements must be positive")
    bound = certified_minkowski_class_bound(field)
    signature = exact_signature(field)
    if field.degree() == 1:
        group = _TrivialClassGroup()
        certificate = ClassGroupCertificate(
            group,
            [],
            [],
            1,
            "every degree-one number field is QQ and has trivial ideal class group",
            "degree-one-PID-theorem",
        )
        if not certificate.verify(max_elements):
            raise ArithmeticError("degree-one class-group replay failed")
        return ClassGroupSearchResult(
            field,
            True,
            certificate.source,
            bound,
            group,
            certificate,
        )
    if field.degree() == 3:
        key = tuple(
            (int(value._numerator), int(value._denominator))
            for value in field._defining_coefficients
        )
        supported = (
            ((-1, 1), (-1, 1), (0, 1), (1, 1)),
            ((1, 1), (-2, 1), (-1, 1), (1, 1)),
        )
        if key in supported:
            return certified_small_cubic_class_group(field)
    if field.degree() == 2 and signature == (0, 1):
        group = field.class_group()
        order = int(group.order())
        if order > max_elements:
            raise ValueError(
                "imaginary-quadratic class group has "
                + str(order)
                + " elements, exceeding max_elements="
                + str(max_elements)
            )
        invariants = [int(value) for value in group.invariants()]
        generators = list(group.gens())
        certificate = ClassGroupCertificate(
            group,
            invariants,
            generators,
            order,
            "complete enumeration of reduced primitive positive binary quadratic forms",
        )
        if not certificate.verify(max_elements):
            raise ArithmeticError("imaginary-quadratic class-group replay failed")
        return ClassGroupSearchResult(
            field,
            True,
            certificate.source,
            bound,
            group,
            certificate,
        )
    return ClassGroupSearchResult(
        field,
        False,
        "certified prime-ideal relations and principal witnesses are not available",
        bound,
    )


def analytic_class_number_formula_report(
    field: Any,
    analytic_residue: Any,
    units: UnitSubgroupResult,
    class_group: ClassGroupSearchResult,
    prec: int = 100,
) -> AnalyticClassNumberFormulaReport:
    """Compare an independently supplied zeta residue with algebraic data."""
    if prec < 2:
        raise ValueError("precision must be at least 2")
    signature = exact_signature(field)
    discriminant = int(field.discriminant())
    units_verified = (
        units.torsion.verify()
        and len(units.generators) == units.unit_rank
        and len(units.certificates) == units.unit_rank
        and all(certificate.verify(field) for certificate in units.certificates)
        and units.verify_completion()
    )
    class_group_verified = (
        class_group.certificate is not None
        and class_group.certificate.verify(
            max_elements=class_group.certificate.enumerated_order
        )
    )
    inputs_complete = (
        units.complete
        and units.torsion.complete
        and class_group.complete
        and units.field is field
        and class_group.field is field
        and units_verified
        and class_group_verified
    )
    if not inputs_complete:
        return AnalyticClassNumberFormulaReport(
            signature=signature,
            discriminant=discriminant,
            class_number=None,
            regulator=None,
            roots_of_unity=None,
            analytic_residue=analytic_residue,
            algebraic_residue=None,
            precision=prec,
            inputs_complete=False,
            difference=None,
            compatible=None,
        )
    r1, r2 = signature
    class_number = class_group.order()
    regulator = units.regulator(prec).value
    torsion_order = units.torsion.order
    algebraic_residue = (
        (2**r1)
        * ((2 * runtime.math.PI) ** r2)
        * class_number
        * regulator
        / (torsion_order * runtime.math.sqrt(abs(discriminant)))
    )
    analytic_value = _complex_midpoint(analytic_residue)
    difference = abs(analytic_value - algebraic_residue)
    # This is only a midpoint stability check: neither input is promoted to a
    # rigorous enclosure by this tolerance.
    effective_precision = min(53, prec)
    tolerance = max(1.0, abs(algebraic_residue)) * (
        2.0 ** (-min(40, effective_precision // 2))
    )
    return AnalyticClassNumberFormulaReport(
        signature=signature,
        discriminant=discriminant,
        class_number=class_number,
        regulator=regulator,
        roots_of_unity=torsion_order,
        analytic_residue=analytic_residue,
        algebraic_residue=algebraic_residue,
        precision=prec,
        inputs_complete=True,
        difference=difference,
        compatible=difference <= tolerance,
    )


__all__ = [
    "AnalyticClassNumberFormulaReport",
    "ClassGroupCertificate",
    "ClassGroupSearchResult",
    "MinkowskiClassNumberOneCertificate",
    "PrincipalIdealWitness",
    "analytic_class_number_formula_report",
    "bounded_class_group",
    "certified_small_cubic_class_group",
]
