"""Certified rational-prime decomposition in maximal number-field orders.

The producer has two exact routes.  Dedekind--Kummer is used only after the
integral equation order is proved `p`-maximal.  Every other supported case is
handled in the presentation-independent finite algebra `O/pO`: its
nilradical is the kernel of a sufficiently high Frobenius power, the reduced
quotient is generated by a bounded deterministic primitive-element search,
and its irreducible factors lift to exact HNF ideal lattices.

Both routes feed :func:`verify_prime_decomposition`, which only consumes the
returned lattices and compact residue presentations.  In particular, producer
branch metadata is never accepted as a proof of its own output.
"""

from __future__ import annotations

from typing import Any, Iterator

import sagejs as sage
import sagejs.runtime as runtime

_nf = __import__("sagejs._baselib.number_fields", fromlist=["number_fields"])
_maximal = __import__("sagejs.number_fields.maximal_order", fromlist=["maximal_order"])
_om = __import__("sagejs.number_fields.om_types", fromlist=["om_types"])

NumberFieldIdeal = _nf.NumberFieldIdeal
_nf_coordinates = _nf._nf_coordinates
_nf_element_from_row = _nf._nf_element_from_row
_nf_global = _nf._nf_global

SCHEMA = "sagejs.number-fields.prime-decomposition.v1"
SERIALIZATION_SCHEMA = "sagejs.number-fields.prime-ideal.v1"
MAX_DEGREE = 16
# All public scalar coercions preserve exact integers through this bound on
# every supported JavaScript host.  The ordinary algorithms themselves use
# exact integer operations; the bound prevents an accidental lossy transport
# through a host API while still covering genuinely large rational primes.
MAX_RATIONAL_PRIME = 9_007_199_254_740_991
DEFAULT_MAX_PRIMITIVE_CANDIDATES = 4096
MAX_CACHE_ENTRIES = 256

_decomposition_cache: list[tuple[Any, int, Any]] = []
_identity_tokens: list[Any] = []


def _freeze_tree(value: Any) -> Any:
    if isinstance(value, (list, tuple)):
        return tuple(_freeze_tree(entry) for entry in value)
    if isinstance(value, dict):
        return tuple(sorted((key, _freeze_tree(entry)) for key, entry in value.items()))
    return value


def _normalize_prime(prime: Any) -> int:
    value = runtime.integer_bigint(prime)
    if value < 2:
        raise ValueError("a rational prime must be at least 2")
    if value > MAX_RATIONAL_PRIME:
        raise NotImplementedError(
            "rational-prime decomposition currently requires p <= 2^53-1"
        )
    if not sage.is_prime(value):
        raise ValueError(str(prime) + " is not a rational prime")
    return int(value)


def _mod_inverse(value: int, prime: int) -> int:
    value %= prime
    if value == 0:
        raise ZeroDivisionError("zero is not invertible modulo p")
    return pow(value, prime - 2, prime)


def _rref(
    rows: list[list[int]], columns: int, prime: int
) -> tuple[list[list[int]], list[int]]:
    matrix = [[int(value) % prime for value in row[:columns]] for row in rows]
    matrix = [row + [0] * (columns - len(row)) for row in matrix]
    pivot_row = 0
    pivots: list[int] = []
    for column in range(columns):
        selected = pivot_row
        while selected < len(matrix) and matrix[selected][column] == 0:
            selected += 1
        if selected == len(matrix):
            continue
        matrix[pivot_row], matrix[selected] = matrix[selected], matrix[pivot_row]
        inverse = _mod_inverse(matrix[pivot_row][column], prime)
        matrix[pivot_row] = [value * inverse % prime for value in matrix[pivot_row]]
        for index in range(len(matrix)):
            if index == pivot_row:
                continue
            scalar = matrix[index][column]
            if scalar:
                matrix[index] = [
                    (matrix[index][entry] - scalar * matrix[pivot_row][entry]) % prime
                    for entry in range(columns)
                ]
        pivots.append(column)
        pivot_row += 1
        if pivot_row == len(matrix):
            break
    return matrix[:pivot_row], pivots


def _row_basis(rows: list[list[int]], columns: int, prime: int) -> list[list[int]]:
    return _rref(rows, columns, prime)[0]


def _rank(rows: list[list[int]], columns: int, prime: int) -> int:
    return len(_row_basis(rows, columns, prime))


def _transpose(rows: list[list[int]], columns: int) -> list[list[int]]:
    return [
        [rows[row][column] for row in range(len(rows))] for column in range(columns)
    ]


def _nullspace(rows: list[list[int]], columns: int, prime: int) -> list[list[int]]:
    reduced, pivots = _rref(rows, columns, prime)
    pivot_set = set(pivots)
    answer: list[list[int]] = []
    for free in range(columns):
        if free in pivot_set:
            continue
        vector = [0] * columns
        vector[free] = 1
        for row_index in range(len(pivots) - 1, -1, -1):
            pivot = pivots[row_index]
            vector[pivot] = (
                -sum(
                    reduced[row_index][column] * vector[column]
                    for column in range(pivot + 1, columns)
                )
                % prime
            )
        answer.append(vector)
    return answer


def _matrix_inverse(rows: list[list[int]], prime: int) -> list[list[int]]:
    degree = len(rows)
    if any(len(row) != degree for row in rows):
        raise ValueError("only square matrices can be inverted")
    augmented = [
        [value % prime for value in row]
        + [1 if index == column else 0 for column in range(degree)]
        for index, row in enumerate(rows)
    ]
    pivot = 0
    for column in range(degree):
        selected = pivot
        while selected < degree and augmented[selected][column] == 0:
            selected += 1
        if selected == degree:
            raise ZeroDivisionError("matrix is singular modulo p")
        augmented[pivot], augmented[selected] = augmented[selected], augmented[pivot]
        inverse = _mod_inverse(augmented[pivot][column], prime)
        augmented[pivot] = [value * inverse % prime for value in augmented[pivot]]
        for index in range(degree):
            if index != pivot and augmented[index][column]:
                scalar = augmented[index][column]
                augmented[index] = [
                    (augmented[index][entry] - scalar * augmented[pivot][entry]) % prime
                    for entry in range(2 * degree)
                ]
        pivot += 1
    return [row[degree:] for row in augmented]


def _row_times_matrix(row: list[int], matrix: list[list[int]], prime: int) -> list[int]:
    if not matrix:
        return []
    return [
        sum(row[index] * matrix[index][column] for index in range(len(row))) % prime
        for column in range(len(matrix[0]))
    ]


def _quotient_map(
    subspace: list[list[int]], degree: int, prime: int
) -> tuple[list[list[int]], list[list[int]]]:
    """Return a quotient-coordinate matrix and standard-coordinate lifts."""
    basis = _row_basis(subspace, degree, prime)
    annihilator = _nullspace(basis, degree, prime)
    dimension = len(annihilator)
    coordinate_matrix = _transpose(annihilator, degree)
    if dimension == 0:
        return coordinate_matrix, []

    selected: list[int] = []
    images: list[list[int]] = []
    for index in range(degree):
        candidate = images + [coordinate_matrix[index]]
        if _rank(candidate, dimension, prime) > len(images):
            selected.append(index)
            images.append(coordinate_matrix[index])
        if len(images) == dimension:
            break
    if len(images) != dimension:
        raise ArithmeticError("failed to select quotient-coordinate lifts")
    inverse = _matrix_inverse(images, prime)
    lifts: list[list[int]] = []
    for coordinate in range(dimension):
        lift = [0] * degree
        for index, source in enumerate(selected):
            lift[source] = inverse[coordinate][index]
        lifts.append(lift)
    return coordinate_matrix, lifts


def _modular_product(
    left: list[int],
    right: list[int],
    table: list[list[list[int]]],
    prime: int,
) -> list[int]:
    degree = len(left)
    answer = [0] * degree
    for i in range(degree):
        if left[i] == 0:
            continue
        for j in range(degree):
            scalar = left[i] * right[j] % prime
            if scalar == 0:
                continue
            for k in range(degree):
                answer[k] = (answer[k] + scalar * table[i][j][k]) % prime
    return answer


def _modular_power(
    value: list[int],
    exponent: int,
    one: list[int],
    table: list[list[list[int]]],
    prime: int,
) -> list[int]:
    answer = list(one)
    power = list(value)
    remaining = exponent
    while remaining:
        if remaining % 2:
            answer = _modular_product(answer, power, table, prime)
        remaining //= 2
        if remaining:
            power = _modular_product(power, power, table, prime)
    return answer


def _order_one_coordinates(order: Any) -> list[int]:
    degree = order.degree()
    row = [sage.QQ(0)] * degree
    row[0] = sage.QQ(1)
    coordinates = list(
        _nf_global("vector")(sage.QQ, row) * order.basis_matrix().inverse()
    )
    answer: list[int] = []
    for value in coordinates:
        if value._denominator != 1:
            raise ArithmeticError(
                "the maximal-order identity has nonintegral coordinates"
            )
        answer.append(int(value._numerator))
    return answer


def _modular_table(order: Any, prime: int) -> list[list[list[int]]]:
    table = _maximal._nf_order_multiplication_table(order)
    return [
        [[int(value) % prime for value in product] for product in left]
        for left in table
    ]


def _nilradical(
    degree: int,
    prime: int,
    one: list[int],
    table: list[list[list[int]]],
) -> list[list[int]]:
    exponent = prime
    while exponent < degree:
        exponent *= prime
    images: list[list[int]] = []
    for index in range(degree):
        basis = [0] * degree
        basis[index] = 1
        images.append(_modular_power(basis, exponent, one, table, prime))
    # Input row vectors act on the Frobenius image rows from the left.
    return _row_basis(
        _nullspace(_transpose(images, degree), degree, prime), degree, prime
    )


def _encoded_vector(encoded: int, degree: int, prime: int) -> list[int]:
    vector: list[int] = []
    value = encoded
    for _index in range(degree):
        vector.append(value % prime)
        value //= prime
    return vector


def _primitive_presentation(
    degree: int,
    prime: int,
    table: list[list[list[int]]],
    one: list[int],
    kernel: list[list[int]],
    max_candidates: int,
) -> dict[str, Any]:
    coordinate_matrix, _lifts = _quotient_map(kernel, degree, prime)
    quotient_degree = len(coordinate_matrix[0]) if coordinate_matrix else 0
    if quotient_degree < 1:
        raise ArithmeticError("the requested quotient is the zero algebra")
    one_image = _row_times_matrix(one, coordinate_matrix, prime)
    if not any(one_image):
        raise ArithmeticError("the quotient killed the identity")

    for encoded in range(1, max_candidates + 1):
        candidate = _encoded_vector(encoded, degree, prime)
        powers: list[list[int]] = []
        power = list(one)
        for _index in range(quotient_degree):
            powers.append(_row_times_matrix(power, coordinate_matrix, prime))
            power = _modular_product(power, candidate, table, prime)
        if _rank(powers, quotient_degree, prime) != quotient_degree:
            continue
        next_image = _row_times_matrix(power, coordinate_matrix, prime)
        inverse = _matrix_inverse(powers, prime)
        coefficients = _row_times_matrix(next_image, inverse, prime)
        coefficients = [(-value) % prime for value in coefficients]
        modulus = tuple(coefficients + [1])
        return {
            "primitive": tuple(candidate),
            "quotient_matrix": tuple(tuple(row) for row in coordinate_matrix),
            "power_inverse": tuple(tuple(row) for row in inverse),
            "modulus": modulus,
        }
    raise NotImplementedError(
        "finite-algebra decomposition exceeded the bounded primitive-element search"
    )


def _minimal_polynomial(
    value: list[int],
    degree: int,
    prime: int,
    table: list[list[list[int]]],
    one: list[int],
    kernel: list[list[int]],
) -> tuple[int, ...]:
    """Return the exact minimal polynomial in one finite quotient algebra."""
    coordinate_matrix, _lifts = _quotient_map(kernel, degree, prime)
    quotient_degree = len(coordinate_matrix[0]) if coordinate_matrix else 0
    powers: list[list[int]] = []
    power = list(one)
    for _polynomial_degree in range(quotient_degree + 1):
        image = _row_times_matrix(power, coordinate_matrix, prime)
        if powers and _rank(powers + [image], quotient_degree, prime) == len(powers):
            _reduced, pivots = _rref(powers, quotient_degree, prime)
            selected = pivots[: len(powers)]
            square = [[row[column] for column in selected] for row in powers]
            inverse = _matrix_inverse(square, prime)
            selected_image = [image[column] for column in selected]
            coefficients = _row_times_matrix(selected_image, inverse, prime)
            return tuple([(-entry) % prime for entry in coefficients] + [1])
        powers.append(image)
        power = _modular_product(power, value, table, prime)
    raise ArithmeticError("a finite-algebra element has no bounded minimal polynomial")


def _lift_quotient_coordinates(
    coordinates: list[int], lifts: list[list[int]], degree: int, prime: int
) -> list[int]:
    answer = [0] * degree
    for index, scalar in enumerate(coordinates):
        for column in range(degree):
            answer[column] = (answer[column] + scalar * lifts[index][column]) % prime
    return answer


def _reduced_field_kernels(
    kernel: list[list[int]],
    degree: int,
    prime: int,
    table: list[list[list[int]]],
    one: list[int],
) -> list[list[list[int]]]:
    """Recursively split a reduced quotient into its field-factor kernels.

    A product of finite fields need not be monogenic (for example `F_2^3`).
    The Frobenius-fixed subalgebra has one dimension per field factor.  A
    nonscalar fixed element has a squarefree product of linear factors as its
    minimal polynomial, and adjoining each factor to the current kernel gives
    strictly smaller reduced quotient components.
    """
    kernel = _row_basis(kernel, degree, prime)
    coordinate_matrix, lifts = _quotient_map(kernel, degree, prime)
    quotient_degree = len(lifts)
    if quotient_degree < 1:
        return []
    frobenius_rows = [
        _row_times_matrix(
            _modular_power(lift, prime, one, table, prime),
            coordinate_matrix,
            prime,
        )
        for lift in lifts
    ]
    fixed_matrix = [
        [
            (frobenius_rows[row][column] - (1 if row == column else 0)) % prime
            for column in range(quotient_degree)
        ]
        for row in range(quotient_degree)
    ]
    fixed = _nullspace(
        _transpose(fixed_matrix, quotient_degree), quotient_degree, prime
    )
    if len(fixed) == 1:
        return [kernel]

    one_image = _row_times_matrix(one, coordinate_matrix, prime)
    splitter_coordinates = None
    for candidate in fixed:
        if _rank([one_image, candidate], quotient_degree, prime) == 2:
            splitter_coordinates = candidate
            break
    if splitter_coordinates is None:
        raise ArithmeticError(
            "the reduced algebra has no nonscalar Frobenius fixed point"
        )
    splitter = _lift_quotient_coordinates(splitter_coordinates, lifts, degree, prime)
    minimal = _minimal_polynomial(splitter, degree, prime, table, one, kernel)
    factors = _om.factor_mod_prime(minimal, prime)
    if len(factors) < 2 or any(
        int(factor.multiplicity) != 1 or len(factor.polynomial) != 2
        for factor in factors
    ):
        raise ArithmeticError(
            "a Frobenius-fixed splitter did not have distinct linear factors"
        )
    answer: list[list[list[int]]] = []
    for factor in factors:
        factor_value = _evaluate_polynomial(
            tuple(int(entry) for entry in factor.polynomial),
            splitter,
            one,
            table,
            prime,
        )
        child = _subspace_ideal_generated_by(
            kernel + [factor_value], degree, table, prime
        )
        if len(child) <= len(kernel) or len(child) >= degree:
            raise ArithmeticError(
                "a reduced-algebra split did not make strict progress"
            )
        answer.extend(_reduced_field_kernels(child, degree, prime, table, one))
    return answer


def _evaluate_polynomial(
    polynomial: tuple[int, ...],
    value: list[int],
    one: list[int],
    table: list[list[list[int]]],
    prime: int,
) -> list[int]:
    answer = [0] * len(value)
    for coefficient in reversed(polynomial):
        answer = _modular_product(answer, value, table, prime)
        for index in range(len(value)):
            answer[index] = (answer[index] + coefficient * one[index]) % prime
    return answer


def _subspace_ideal_generated_by(
    generators: list[list[int]],
    degree: int,
    table: list[list[list[int]]],
    prime: int,
) -> list[list[int]]:
    rows = list(generators)
    for generator in generators:
        for index in range(degree):
            basis = [0] * degree
            basis[index] = 1
            rows.append(_modular_product(generator, basis, table, prime))
    return _row_basis(rows, degree, prime)


def _subspace_product(
    left: list[list[int]],
    right: list[list[int]],
    degree: int,
    table: list[list[list[int]]],
    prime: int,
) -> list[list[int]]:
    return _row_basis(
        [_modular_product(a, b, table, prime) for a in left for b in right],
        degree,
        prime,
    )


def _ideal_from_modular_subspace(
    order: Any, subspace: list[list[int]], prime: int
) -> Any:
    degree = order.degree()
    order_rows = order._basis_rows
    rows = [[sage.QQ(prime) * value for value in row] for row in order_rows]
    for coordinates in subspace:
        row = [sage.QQ(0)] * degree
        for index in range(degree):
            for column in range(degree):
                row[column] += sage.QQ(coordinates[index]) * order_rows[index][column]
        rows.append(row)
    return NumberFieldIdeal(order, rows)


def _ideal_mod_p_subspace(ideal: Any, prime: int) -> list[list[int]]:
    order = ideal.ring()
    inverse = order.basis_matrix().inverse()
    rows: list[list[int]] = []
    for row in ideal._basis_rows:
        coordinates = list(_nf_global("vector")(sage.QQ, row) * inverse)
        modular: list[int] = []
        for value in coordinates:
            if value._denominator != 1:
                raise ValueError("the ideal is not integral at the requested prime")
            modular.append(int(value._numerator) % prime)
        rows.append(modular)
    return _row_basis(rows, order.degree(), prime)


def _field_element_order_coordinates(order: Any, value: Any) -> list[Any]:
    element = order.number_field()(value)
    row = _nf_coordinates(element, order.degree())
    return list(_nf_global("vector")(sage.QQ, row) * order.basis_matrix().inverse())


def _polynomial_remainder(
    polynomial: list[int], modulus: tuple[int, ...], prime: int
) -> list[int]:
    remainder = [value % prime for value in polynomial]
    while len(remainder) > 1 and remainder[-1] == 0:
        remainder.pop()
    degree = len(modulus) - 1
    while len(remainder) > degree:
        leading = remainder[-1]
        shift = len(remainder) - len(modulus)
        for index, value in enumerate(modulus):
            remainder[index + shift] = (
                remainder[index + shift] - leading * value
            ) % prime
        while len(remainder) > 1 and remainder[-1] == 0:
            remainder.pop()
    return remainder + [0] * (degree - len(remainder))


class NumberFieldPrimeIdeal(NumberFieldIdeal):
    """A prime ideal whose canonical identity remains its exact HNF lattice."""

    def __init__(
        self,
        order: Any,
        rows: list[list[Any]],
        rational_prime: int,
        ramification_index: int,
        residue_degree: int,
        presentation: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(order, rows)
        self._rational_prime = int(rational_prime)
        self._ramification_index = int(ramification_index)
        self._residue_degree = int(residue_degree)
        self._residue_presentation = presentation

    def rational_prime(self) -> Any:
        return sage.ZZ(self._rational_prime)

    def ramification_index(self) -> int:
        return self._ramification_index

    def residue_class_degree(self) -> int:
        return self._residue_degree

    residue_degree = residue_class_degree

    def residue_field(self, names: Any = None) -> Any:
        if self._residue_degree == 1:
            return _nf_global("GF")(self._rational_prime)
        presentation = self._require_residue_presentation()
        base = _nf_global("GF")(self._rational_prime)
        ring = sage.PolynomialRing(base, "x")
        modulus = ring(list(presentation["modulus"]))
        name = "z" if names is None else names
        return _nf_global("GF")(
            self._rational_prime**self._residue_degree,
            name=name,
            modulus=modulus,
        )

    def _require_residue_presentation(self) -> dict[str, Any]:
        if self._residue_presentation is None:
            self._residue_presentation = _residue_presentation_for_prime(self)
        return self._residue_presentation

    def residue_coordinates(self, value: Any) -> tuple[int, ...]:
        """Return coordinates in the certified polynomial residue presentation."""
        coordinates = _field_element_order_coordinates(self.ring(), value)
        integral: list[int] = []
        for coordinate in coordinates:
            if coordinate._denominator != 1:
                raise TypeError("only maximal-order elements have a residue class")
            integral.append(int(coordinate._numerator) % self._rational_prime)
        presentation = self._require_residue_presentation()
        quotient_matrix = [list(row) for row in presentation["quotient_matrix"]]
        power_inverse = [list(row) for row in presentation["power_inverse"]]
        quotient = _row_times_matrix(integral, quotient_matrix, self._rational_prime)
        polynomial = _row_times_matrix(quotient, power_inverse, self._rational_prime)
        remainder = _polynomial_remainder(
            polynomial,
            tuple(presentation["modulus"]),
            self._rational_prime,
        )
        return tuple(remainder)

    def reduce(self, value: Any) -> Any:
        coordinates = self.residue_coordinates(value)
        residue_field = self.residue_field()
        if self._residue_degree == 1:
            return residue_field(coordinates[0])
        generator = residue_field.gen()
        answer = residue_field(0)
        power = residue_field(1)
        for coefficient in coordinates:
            answer += residue_field(coefficient) * power
            power *= generator
        return answer

    def uniformizer(self) -> Any:
        square = self * self
        for element in self.basis():
            if element not in square:
                return element
        raise ArithmeticError("failed to find a prime-ideal uniformizer witness")

    def valuation(self, value_or_ideal: Any) -> int:
        arithmetic = __import__(
            "sagejs.number_fields.ideal_arithmetic", fromlist=["ideal_arithmetic"]
        )
        if isinstance(value_or_ideal, NumberFieldIdeal):
            return arithmetic.ideal_valuation(value_or_ideal, self)
        return arithmetic.element_valuation(value_or_ideal, self)

    def splitting_record(self) -> dict[str, Any]:
        return {
            "prime": self._rational_prime,
            "e": self._ramification_index,
            "f": self._residue_degree,
        }

    def to_dict(self) -> dict[str, Any]:
        return serialize_prime_ideal(self)

    def __repr__(self) -> str:
        return (
            "Prime ideal above "
            + str(self._rational_prime)
            + " (e="
            + str(self._ramification_index)
            + ", f="
            + str(self._residue_degree)
            + ") generated by ("
            + ", ".join(str(element) for element in self.basis())
            + ")"
        )

    __str__ = __repr__
    toString = __repr__


class PrimeIdealDecomposition(sage.Factorization):
    """A Sage-style factorization carrying a compact exact certificate."""

    def __init__(
        self,
        order: Any,
        prime: int,
        factors: list[NumberFieldPrimeIdeal],
        producer: str,
    ) -> None:
        self._order = order
        self._prime = prime
        self._producer = producer
        self._certificate_cache: Any = None
        self._prime_pairs = [
            [factor, runtime.number(factor.ramification_index())] for factor in factors
        ]
        super().__init__(
            self._prime_pairs,
            unit=order.ideal(1),
            cr=False,
            sort=False,
            simplify=False,
        )

    def rational_prime(self) -> Any:
        return sage.ZZ(self._prime)

    def __iter__(self) -> Iterator[list[Any]]:
        return iter(self._prime_pairs)

    def producer(self) -> str:
        return self._producer

    def prime_ideals(self) -> tuple[NumberFieldPrimeIdeal, ...]:
        return tuple(pair[0] for pair in self)

    def splitting_record(self, include_lattices: bool = False) -> dict[str, Any]:
        factors: list[Any] = []
        for prime, exponent in self:
            record: dict[str, Any] = {
                "e": exponent,
                "f": prime.residue_class_degree(),
            }
            if include_lattices:
                record["basis"] = _encode_rows(prime._basis_rows)
            factors.append(record)
        return {
            "version": 1,
            "prime": self._prime,
            "factors": factors,
        }

    def certificate(self) -> dict[str, Any]:
        if self._certificate_cache is None:
            self._certificate_cache = {
                "schema": SCHEMA,
                "prime": self._prime,
                "producer": self._producer,
                "degree": self._order.degree(),
                "factors": [
                    {
                        "e": exponent,
                        "f": prime.residue_class_degree(),
                        "basis": _encode_rows(prime._basis_rows),
                        "residue_modulus": list(
                            prime._require_residue_presentation()["modulus"]
                        ),
                    }
                    for prime, exponent in self
                ],
            }
        return self._certificate_cache

    def verify(self) -> dict[str, Any]:
        return verify_prime_decomposition(self._order, self._prime, self)


def _residue_presentation_for_prime(
    prime_ideal: NumberFieldPrimeIdeal,
) -> dict[str, Any]:
    order = prime_ideal.ring()
    prime = prime_ideal._rational_prime
    degree = order.degree()
    table = _modular_table(order, prime)
    one = [value % prime for value in _order_one_coordinates(order)]
    kernel = _ideal_mod_p_subspace(prime_ideal, prime)
    return _primitive_presentation(
        degree,
        prime,
        table,
        one,
        kernel,
        DEFAULT_MAX_PRIMITIVE_CANDIDATES,
    )


def _prime_from_ideal(
    ideal: Any, prime: int, ramification: int, residue_degree: int
) -> NumberFieldPrimeIdeal:
    result = NumberFieldPrimeIdeal(
        ideal.ring(),
        ideal._basis_rows,
        prime,
        ramification,
        residue_degree,
    )
    result._residue_presentation = _residue_presentation_for_prime(result)
    return result


def _dedekind_kummer(order: Any, prime: int) -> list[NumberFieldPrimeIdeal] | None:
    field = order.number_field()
    if not _maximal.equation_order_is_p_maximal(field, prime):
        return None
    polynomial = _maximal.integral_equation_polynomial(field)
    coefficients = tuple(int(value) for value in polynomial.list())
    factors = _om.factor_mod_prime(coefficients, prime)
    scale = runtime.integer_bigint(field._integral_equation_scale_cache)
    beta = field.gen() * scale
    answer: list[NumberFieldPrimeIdeal] = []
    for factor in factors:
        value = field.zero()
        for coefficient in reversed(factor.polynomial):
            value = value * beta + int(coefficient)
        ideal = order.ideal(prime, value)
        answer.append(
            _prime_from_ideal(
                ideal,
                prime,
                int(factor.multiplicity),
                len(factor.polynomial) - 1,
            )
        )
    return answer


def _finite_algebra_fallback(
    order: Any, prime: int, max_candidates: int
) -> list[NumberFieldPrimeIdeal]:
    degree = order.degree()
    table = _modular_table(order, prime)
    one = [value % prime for value in _order_one_coordinates(order)]
    radical = _nilradical(degree, prime, one, table)
    field_kernels = _reduced_field_kernels(radical, degree, prime, table, one)
    answer: list[NumberFieldPrimeIdeal] = []
    for maximal_subspace in field_kernels:
        # This bounded presentation search now runs only in one finite field,
        # never in a possibly nonmonogenic product of fields.
        presentation = _primitive_presentation(
            degree,
            prime,
            table,
            one,
            maximal_subspace,
            max_candidates,
        )
        residue_degree = len(presentation["modulus"]) - 1
        power = maximal_subspace
        for _exponent in range(degree + 1):
            next_power = _subspace_product(
                power, maximal_subspace, degree, table, prime
            )
            if next_power == power:
                break
            power = next_power
        else:
            raise ArithmeticError("a local maximal-ideal power did not stabilize")
        local_dimension = degree - len(power)
        if local_dimension < 1 or local_dimension % residue_degree:
            raise ArithmeticError("a local algebra has inconsistent e/f dimensions")
        ramification = local_dimension // residue_degree
        ideal = _ideal_from_modular_subspace(order, maximal_subspace, prime)
        answer.append(
            NumberFieldPrimeIdeal(
                order,
                ideal._basis_rows,
                prime,
                ramification,
                residue_degree,
                presentation,
            )
        )
    return answer


def _cache_get(order: Any, prime: int) -> Any:
    for cached_order, cached_prime, result in _decomposition_cache:
        if cached_order is order and cached_prime == prime:
            return result
    return None


def _cache_put(order: Any, prime: int, result: Any) -> None:
    _decomposition_cache.append((order, prime, result))
    if len(_decomposition_cache) > MAX_CACHE_ENTRIES:
        del _decomposition_cache[0]


def _prime_sort_key(prime_ideal: NumberFieldPrimeIdeal) -> tuple[int, ...]:
    answer: list[int] = []
    for row in prime_ideal._basis_rows:
        for value in row:
            answer.extend([int(value._numerator), int(value._denominator)])
    return tuple(answer)


def factor_rational_prime(
    order: Any,
    prime: Any,
    *,
    verify: bool = True,
    algorithm: str = "auto",
    max_primitive_candidates: int = DEFAULT_MAX_PRIMITIVE_CANDIDATES,
) -> PrimeIdealDecomposition:
    """Factor `p*order` into certified prime ideals.

    The generic route is intentionally bounded by degree, rational-prime size,
    and primitive-element candidates.  Exceeding a bound raises before an
    unbounded enumeration or allocation begins.
    """
    p = _normalize_prime(prime)
    if order.degree() > MAX_DEGREE:
        raise NotImplementedError(
            "finite-algebra prime decomposition currently supports degree <= 16"
        )
    if not order.is_maximal():
        raise ValueError("prime-ideal decomposition requires a certified maximal order")
    if max_primitive_candidates < 1:
        raise ValueError("the primitive-element candidate bound must be positive")
    if algorithm not in ("auto", "dedekind-kummer", "finite-algebra"):
        raise ValueError("unknown prime-decomposition algorithm: " + str(algorithm))
    if algorithm == "auto":
        cached = _cache_get(order, p)
        if cached is not None:
            return cached

    factors = None
    producer = "finite-algebra"
    if algorithm != "finite-algebra":
        factors = _dedekind_kummer(order, p)
        if factors is not None:
            producer = "dedekind-kummer"
        elif algorithm == "dedekind-kummer":
            raise ValueError("the equation order is not certified p-maximal")
    if factors is None:
        factors = _finite_algebra_fallback(order, p, max_primitive_candidates)
    factors.sort(key=_prime_sort_key)
    result = PrimeIdealDecomposition(order, p, factors, producer)
    if verify:
        verification = verify_prime_decomposition(order, p, result)
        if verification["certified"] is not True:
            raise ArithmeticError("prime-decomposition verification failed")
    if algorithm == "auto":
        _cache_put(order, p, result)
    return result


def primes_above(order: Any, prime: Any) -> tuple[NumberFieldPrimeIdeal, ...]:
    return factor_rational_prime(order, prime).prime_ideals()


def _quotient_is_field(
    order: Any, ideal: NumberFieldPrimeIdeal, prime: int, residue_degree: int
) -> bool:
    degree = order.degree()
    subspace = _ideal_mod_p_subspace(ideal, prime)
    coordinate_matrix, lifts = _quotient_map(subspace, degree, prime)
    if len(lifts) != residue_degree:
        return False
    table = _modular_table(order, prime)
    one = [value % prime for value in _order_one_coordinates(order)]
    frobenius_rows = [
        _row_times_matrix(
            _modular_power(lift, prime, one, table, prime),
            coordinate_matrix,
            prime,
        )
        for lift in lifts
    ]
    if _rank(frobenius_rows, residue_degree, prime) != residue_degree:
        return False
    fixed = [
        [
            (frobenius_rows[row][column] - (1 if row == column else 0)) % prime
            for column in range(residue_degree)
        ]
        for row in range(residue_degree)
    ]
    # Left fixed vectors form the nullspace of the transpose.
    fixed_dimension = len(
        _nullspace(_transpose(fixed, residue_degree), residue_degree, prime)
    )
    return fixed_dimension == 1


def verify_prime_decomposition(
    order: Any, prime: Any, decomposition: Any
) -> dict[str, Any]:
    """Independently verify quotient fields and exact lattice reconstruction."""
    failures: list[str] = []
    try:
        p = _normalize_prime(prime)
    except Exception as error:
        return {"certified": False, "failures": [str(error)]}
    if not order.is_maximal():
        failures.append("the order is not independently certified maximal")
    factors = list(decomposition)
    if not factors:
        failures.append("the decomposition has no prime factors")
    p_ideal = order.ideal(p)
    product = order.ideal(1)
    degree_sum = 0
    seen: list[Any] = []
    for pair in factors:
        if len(pair) != 2:
            failures.append("a factor is not a prime/exponent pair")
            continue
        ideal, exponent = pair
        if not isinstance(ideal, NumberFieldPrimeIdeal):
            failures.append("a factor is not a NumberFieldPrimeIdeal")
            continue
        if ideal.ring() is not order or ideal._rational_prime != p:
            failures.append(
                "a prime ideal belongs to the wrong order or rational prime"
            )
            continue
        if exponent != ideal.ramification_index() or exponent < 1:
            failures.append("a ramification exponent is inconsistent")
        residue_degree = ideal.residue_class_degree()
        if residue_degree < 1:
            failures.append("a residue degree is not positive")
        if not all(element in ideal for element in p_ideal.basis()):
            failures.append("a prime lattice does not contain p*O")
        if not ideal.is_integral():
            failures.append("a prime lattice is not integral")
        expected_norm = runtime.bigint(p) ** runtime.bigint(residue_degree)
        if ideal.norm() != expected_norm:
            failures.append("a prime lattice has the wrong exact norm")
        try:
            if not _quotient_is_field(order, ideal, p, residue_degree):
                failures.append("a prime quotient is not a field")
            presentation = ideal._require_residue_presentation()
            recomputed_presentation = _residue_presentation_for_prime(ideal)
            for key in (
                "primitive",
                "quotient_matrix",
                "power_inverse",
                "modulus",
            ):
                if _freeze_tree(presentation[key]) != _freeze_tree(
                    recomputed_presentation[key]
                ):
                    failures.append(
                        "a residue presentation differs from its canonical recomputation"
                    )
                    break
            modular_factors = _om.factor_mod_prime(
                tuple(int(value) for value in presentation["modulus"]), p
            )
            if (
                len(modular_factors) != 1
                or int(modular_factors[0].multiplicity) != 1
                or len(modular_factors[0].polynomial) - 1 != residue_degree
            ):
                failures.append("a residue presentation modulus is not irreducible")
            for basis_element in ideal.basis():
                if any(ideal.residue_coordinates(basis_element)):
                    failures.append("a residue-map kernel omits a prime-ideal basis")
                    break
        except Exception as error:
            failures.append("residue verification failed: " + str(error))
        for previous in seen:
            if ideal == previous:
                failures.append("the decomposition repeats a prime ideal")
            if ideal + previous != order.ideal(1):
                failures.append("two prime ideals are not comaximal")
        seen.append(ideal)
        product = product * (ideal**exponent)
        degree_sum += exponent * residue_degree
    if product != p_ideal:
        failures.append("the exact product lattice is not p*O")
    if degree_sum != order.degree():
        failures.append("the sum of e*f does not equal the field degree")
    return {
        "certified": not failures,
        "schema": SCHEMA,
        "prime": p,
        "degree": order.degree(),
        "failures": failures,
        "checks": [
            "prime",
            "maximal-order",
            "p-containment-and-integrality",
            "quotient-field",
            "residue-map-kernel",
            "pairwise-comaximal",
            "exact-product-lattice",
            "degree-sum",
        ],
    }


def splitting_records(
    order: Any,
    start: Any,
    stop: Any,
    *,
    include_lattices: bool = False,
) -> Iterator[dict[str, Any]]:
    """Stream compact splitting records for primes in `[start, stop)`."""
    lower = max(2, int(runtime.integer_bigint(start)))
    upper = int(runtime.integer_bigint(stop))
    if upper < lower:
        raise ValueError("a splitting-record interval has reversed endpoints")
    if upper > MAX_RATIONAL_PRIME + 1:
        raise NotImplementedError("the splitting interval exceeds the prime bound")
    if upper - lower > 1_000_000:
        raise ValueError(
            "a single splitting-record interval is limited to length 1000000"
        )
    for candidate in range(lower, upper):
        if sage.is_prime(candidate):
            yield factor_rational_prime(order, candidate).splitting_record(
                include_lattices
            )


def _encode_rows(rows: list[list[Any]]) -> list[list[list[int]]]:
    return [
        [[int(value._numerator), int(value._denominator)] for value in row]
        for row in rows
    ]


def _decode_rows(rows: list[list[list[int]]]) -> list[list[Any]]:
    return [[sage.QQ(value[0]) / sage.QQ(value[1]) for value in row] for row in rows]


def _identity_token(value: Any) -> int:
    for index, existing in enumerate(_identity_tokens):
        if existing is value:
            return index + 1
    _identity_tokens.append(value)
    return len(_identity_tokens)


def _field_order_fingerprint(order: Any) -> dict[str, Any]:
    field = order.number_field()
    return {
        "defining_polynomial": [
            [int(value._numerator), int(value._denominator)]
            for value in field._defining_coefficients
        ],
        "variable": field.variable_name(),
        "maximal_order_basis": _encode_rows(order._basis_rows),
        "discriminant": int(order.discriminant()),
    }


def serialize_prime_ideal(prime_ideal: NumberFieldPrimeIdeal) -> dict[str, Any]:
    presentation = prime_ideal._require_residue_presentation()
    return {
        "schema": SERIALIZATION_SCHEMA,
        "field_instance": _identity_token(prime_ideal.number_field()),
        "order_instance": _identity_token(prime_ideal.ring()),
        "field_order_fingerprint": _field_order_fingerprint(prime_ideal.ring()),
        "prime": prime_ideal._rational_prime,
        "e": prime_ideal._ramification_index,
        "f": prime_ideal._residue_degree,
        "basis": _encode_rows(prime_ideal._basis_rows),
        "residue": {
            "primitive": list(presentation["primitive"]),
            "quotient_matrix": [list(row) for row in presentation["quotient_matrix"]],
            "power_inverse": [list(row) for row in presentation["power_inverse"]],
            "modulus": list(presentation["modulus"]),
        },
    }


def prime_ideal_from_dict(order: Any, data: dict[str, Any]) -> NumberFieldPrimeIdeal:
    if data.get("schema") != SERIALIZATION_SCHEMA:
        raise ValueError("unsupported prime-ideal serialization schema")
    if data.get("field_order_fingerprint") != _field_order_fingerprint(order):
        raise ValueError("a prime ideal has a different exact field/order fingerprint")
    if data.get("field_instance") != _identity_token(order.number_field()):
        raise ValueError("a prime ideal cannot be loaded into another field instance")
    if data.get("order_instance") != _identity_token(order):
        raise ValueError("a prime ideal cannot be loaded into another order instance")
    candidate = NumberFieldPrimeIdeal(
        order,
        _decode_rows(data["basis"]),
        _normalize_prime(data["prime"]),
        int(data["e"]),
        int(data["f"]),
        dict(data["residue"]),
    )
    # Authenticate e, f, lattice, and residue data against a complete exact
    # decomposition.  A lone prime component cannot certify its own
    # ramification exponent.
    decomposition = factor_rational_prime(order, candidate._rational_prime)
    for authentic, _exponent in decomposition:
        if authentic == candidate:
            if (
                authentic._ramification_index != candidate._ramification_index
                or authentic._residue_degree != candidate._residue_degree
                or _freeze_tree(authentic._require_residue_presentation())
                != _freeze_tree(candidate._require_residue_presentation())
            ):
                raise ValueError(
                    "serialized prime-ideal metadata failed authentication"
                )
            return authentic
    raise ValueError("serialized prime-ideal lattice is not above the stated prime")


__all__ = [
    "NumberFieldPrimeIdeal",
    "PrimeIdealDecomposition",
    "factor_rational_prime",
    "prime_ideal_from_dict",
    "primes_above",
    "serialize_prime_ideal",
    "splitting_records",
    "verify_prime_decomposition",
]
