"""Differential Evolution: population-based global minimization.

Rainer Storn and Kenneth Price, *Differential Evolution - A Simple and
Efficient Heuristic for Global Optimization over Continuous Spaces*,
Journal of Global Optimization 11:341-359 (1997). This module implements
the classic `DE/rand/1/bin` variant — one difference vector, binomial
crossover — which is also exactly the algorithm Wolfram `NMinimize` documents
for `Method -> "DifferentialEvolution"`:

> "During each iteration of the algorithm, a new population of `m` points is
> generated. The `j`-th new point is generated by picking three random
> points, `x_u`, `x_v`, and `x_w`, from the old population, and forming
> `x_s = x_w + s (x_u - x_v)`, where `s` is a real scaling factor. Then a new
> point `x_new` is constructed from `x_j` and `x_s` by taking the `i`-th
> coordinate from `x_s` with probability `rho` and otherwise taking the
> coordinate from `x_j`. If `f(x_new) < f(x_j)`, then `x_new` replaces `x_j`
> in the population."

`differential_evolution` targets that documented behavior — including its
defaults (`"ScalingFactor" -> 0.6`, `"CrossProbability" -> 0.5`,
`"SearchPoints" -> Automatic = Min[10*d, 50]`, `"RandomSeed" -> 0`,
`"Tolerance" -> 0.001`) and its convergence test (below) — rather than the
Storn/Price paper's own `F = 0.8`, `CR = 0.9` "classical settings" advice,
which the paper offers as a starting point for hand-tuning, not as the
algorithm's defaults.

## The forced crossover index

A literal reading of the quoted update — "taking the `i`-th coordinate from
`x_s` with probability `rho`" for every coordinate independently — allows
the degenerate outcome that *no* coordinate is drawn from the mutant, so
`x_new` is `x_j` verbatim and the "new" point never had a chance to differ
from the old one. Storn and Price's own reference code avoids this by
forcing one coordinate, chosen uniformly at random, to always come from the
mutant regardless of the crossover draw; every other DE implementation
descended from it (including scipy's `_differentialevolution.py`, whose
`_mutate`/`_mutate_many` compute a `fill_point` and then set
`crossovers[fill_point] = True` before applying the mask) does the same.
This module follows suit: `_forced_index` below picks that one guaranteed
coordinate before the per-coordinate crossover draws run.

## Reproducible randomness

Every random decision in one generation for one population member — which
three points seed the mutation, which coordinate is the forced one, and
which coordinates cross over — is drawn from a single `RandomStream`
dedicated to that `(generation, member)` pair:

```python
stream = derive_stream(seed, generation * population_size + member_index)
```

`population_size` is fixed for the whole run, so this map from
`(generation, member_index)` to a stream index is a bijection fixed before
the run starts — it does not depend on the order in which members are
mutated, evaluated, or replaced, so the generation can be computed in any
order, including in parallel across workers, and still reproduce bit-for-bit
the sequence a serial run would produce. The initial population (generation
`0`) draws from the same map, `derive_stream(seed, member_index)`, which
matches the scheme `random_stream`'s own docstring illustrates.

## Convergence

Wolfram's documented stopping rule (shared with `"NelderMead"`) compares
consecutive populations: the run stops once *both* the difference between
the best function values of the new and old population, and the distance
between the new and old best points, fall below `tolerance`. Read as a
one-generation test that rule is unusable for `DE/rand/1/bin`, and the same
page says why:

> "Because the methods used by NMinimize may not improve every iteration,
> convergence is only checked after several iterations have occurred."

DE improves *some* population member most generations, but only rarely the
incumbent best one. In every generation that improves an ordinary member
the two gaps above are exactly `0.0` — below any positive tolerance — so a
literal one-generation test declares victory on the first generation that
does not happen to displace the best member, typically generation `1` or
`2`, long before the population has found anything. What that test actually
measures is "the best did not move this generation", not "the search has
converged".

This module therefore tests whether the *population* has collapsed, which
is what convergence of a population method means, using the same two-part
spread test its sibling `nelder_mead` uses on the simplex (there: maximum
coordinate spread `<= xatol` and maximum function-value spread `<= fatol`).
The run stops successfully once *both*

* the spread of function values across the population — the largest
  `abs(f(x_best) - f(x_j))` over all members `j` — is at most `tolerance`,
  and
* the geometric spread of the population — the largest absolute coordinate
  difference between the best point and any member — is at most
  `tolerance`.

Both conditions describe the whole polytope, so no single stagnant
generation can end the run: the members that DE is still improving keep the
spread wide until the population has genuinely contracted onto one point.

One narrow case cannot be caught by contraction, because the population
never contracts in it: an objective that is flat (or flat to within
`tolerance`) across the whole population, where no trial is ever strictly
better than its parent, so the population is frozen and stays as scattered
as it was drawn. For that case the incumbent-gap test above is kept as a
second, windowed clause — Wolfram's rule with the "several iterations"
qualifier made explicit: the run also stops once the value spread across
the population is at most `tolerance` *and* both incumbent gaps have stayed
below `tolerance` for `_STAGNATION_GENERATIONS` (`10`) consecutive
generations. The window is what makes this safe; the value-spread guard is
what keeps it from firing while the population still disagrees about where
the minimum is.

The run also stops once `max_iterations` generations have completed,
whichever happens first.

## Edge cases

* **`d == 1`.** No coordinate is special-cased; a length-1 point degenerates
  correctly (the forced index is always coordinate `0`, and crossover has
  only one coordinate to choose from anyway).
* **A fixed coordinate (`low == high`).** Mutation and crossover still write
  to that coordinate, but clipping always maps it back to the single
  allowed value, so the variable stays fixed without extra code.
* **A constant objective.** No trial vector is ever strictly better than the
  parent it is compared against (`f(x_new) < f(x_j)` is never true when
  every value is equal), so every generation leaves the population
  unchanged and the population never contracts. The stagnation clause of
  the convergence test covers exactly this: the value spread is `0.0` and
  the incumbent never moves, so the run stops after
  `_STAGNATION_GENERATIONS` generations — correctly, since every point is
  already optimal.
* **`f` returning NaN.** A NaN trial value is never treated as an
  improvement, and a NaN *incumbent* value is always treated as worse than
  any real value that replaces it (see `_is_better`), so a NaN evaluation
  can neither be selected into the population nor permanently block a real
  improvement from replacing it.
* **`search_points < 4`.** `DE/rand/1/bin` mutation needs three population
  members distinct from each other and from the target, i.e. a population
  of at least `4`. This module treats an explicit `search_points < 4` as a
  caller error and raises `ValueError` naming the offending value, rather
  than silently inflating the population — `search_points` is a direct,
  explicit argument here (unlike `NMinimize`'s internal Automatic sizing),
  and the codebase's convention for direct explicit arguments (see
  `nelder_mead`'s `initial_simplex` shape check) is to reject rather than
  reinterpret. The `Automatic` default, `min(10*d, 50)`, is never below `4`
  for any `d >= 1`, so this only fires when a caller passes a value by hand.
"""

from __future__ import annotations

import math
from collections.abc import Callable, Sequence
from dataclasses import dataclass

from .global_result import GlobalResult
from .random_stream import derive_stream

_INFINITY = float("inf")
"""IEEE `+inf`; the Sage.js `math` module has no `math.inf` attribute."""

_MIN_POPULATION = 4
"""`DE/rand/1/bin` needs 3 distinct donors plus the target: 4 members."""

_STAGNATION_GENERATIONS = 10
"""Consecutive stagnant generations the windowed incumbent test needs.

Wolfram's "convergence is only checked after several iterations have
occurred", made explicit. Only the flat-objective clause of `_has_converged`
uses it (see the module docstring); `10` generations of a completely
motionless incumbent, on a population whose function values already agree to
within `tolerance`, is well past the point where a stall could still be one
unlucky generation of `DE/rand/1/bin` not displacing its best member.
"""


@dataclass(frozen=True)
class _Bound:
    """One validated `(low, high)` pair, kept together for clarity."""

    low: float
    high: float


def differential_evolution(
    f: Callable[[Sequence[float]], float],
    bounds: Sequence[tuple[float, float]],
    *,
    scaling_factor: float = 0.6,
    cross_probability: float = 0.5,
    search_points: int | None = None,
    max_iterations: int = 100,
    tolerance: float = 0.001,
    seed: int = 0,
    initial_points: Sequence[Sequence[float]] | None = None,
) -> GlobalResult:
    """Minimize scalar-valued `f` over the box `bounds` by differential evolution.

    `bounds` is one `(low, high)` pair per coordinate; its length fixes the
    dimension `d`. Every generated point is clipped back into `bounds`
    before `f` ever sees it, so `f` is never called outside the box.

    `scaling_factor` (Wolfram `"ScalingFactor"`, Storn/Price's `F`) scales
    the difference vector in the mutation `x_w + scaling_factor * (x_u -
    x_v)`. `cross_probability` (Wolfram `"CrossProbability"`, Storn/Price's
    `CR`) is the per-coordinate probability of taking the mutant's
    coordinate over the target's in binomial crossover — see the module
    docstring for the forced-index guarantee that keeps a trial from ever
    degenerating to the unmodified target.

    `search_points` (Wolfram `"SearchPoints"`) is the population size; `None`
    (the `Automatic` default) resolves to `min(10 * d, 50)`. An explicit
    value below `4` raises `ValueError` (see module docstring).

    `initial_points`, when given, seeds the population: point `i` becomes
    population member `i` for `i < len(initial_points)` (clipped into
    `bounds` like any other point), and any remaining population slots are
    filled by uniform random draws as usual. Points beyond the resolved
    population size are ignored. Each point must have exactly `d`
    coordinates, or `ValueError` names the offending index.

    `max_iterations` bounds the number of generations. `tolerance` is both
    the function-value and the coordinate convergence threshold: the run
    stops early once the population has collapsed to within `tolerance` in
    both function value and coordinates (see the module docstring, which
    also covers the flat-objective clause and why a single generation that
    fails to improve the incumbent is not convergence). `tolerance = 0.0`
    demands an exactly collapsed population and so effectively runs the
    full `max_iterations` budget. `seed` derives every `RandomStream` this
    run consumes and is echoed back on the result unchanged.
    """
    resolved_bounds = _validate_bounds(bounds)
    dimension = len(resolved_bounds)
    population_size = _resolve_population_size(search_points, dimension)

    population = _initial_population(
        resolved_bounds, population_size, seed, initial_points
    )
    function_calls = 0
    values: list[float] = []
    for point in population:
        values.append(float(f(point)))
        function_calls += 1

    best_index = _best_index(values)
    best_point = population[best_index]
    best_value = values[best_index]

    iterations = 0
    converged = False
    flag = "maxiter"
    stagnant_generations = 0

    for generation in range(1, max_iterations + 1):
        new_population: list[list[float]] = [list(point) for point in population]
        new_values = list(values)

        for member in range(population_size):
            stream = derive_stream(seed, generation * population_size + member)
            u, v, w = stream.sample_distinct(3, population_size, exclude=member)

            target = population[member]
            mutant = [
                population[w][i]
                + scaling_factor * (population[u][i] - population[v][i])
                for i in range(dimension)
            ]

            # Force exactly one coordinate to come from the mutant so that
            # independent per-coordinate draws below can never leave the
            # trial identical to the target (see module docstring).
            forced_index = stream.randint(0, dimension)
            trial = [
                mutant[i]
                if i == forced_index or stream.uniform() < cross_probability
                else target[i]
                for i in range(dimension)
            ]
            trial = _clip(trial, resolved_bounds)

            trial_value = float(f(trial))
            function_calls += 1
            if _is_better(trial_value, values[member]):
                new_population[member] = trial
                new_values[member] = trial_value

        new_best_index = _best_index(new_values)
        new_best_point = new_population[new_best_index]
        new_best_value = new_values[new_best_index]
        iterations = generation

        # Wolfram's incumbent-gap test, counted rather than acted on: one
        # stagnant generation says nothing (most generations improve an
        # ordinary member, leaving both gaps at exactly 0.0), a long run of
        # them is evidence. See the module docstring.
        value_gap = _value_gap(new_best_value, best_value)
        point_gap = _distance(new_best_point, best_point)
        if value_gap < tolerance and point_gap < tolerance:
            stagnant_generations += 1
        else:
            stagnant_generations = 0

        population, values = new_population, new_values
        best_point, best_value = new_best_point, new_best_value

        if _has_converged(
            population, values, new_best_index, tolerance, stagnant_generations
        ):
            converged = True
            flag = "converged"
            break

    return GlobalResult(
        x=list(best_point),
        fun=best_value,
        iterations=iterations,
        function_calls=function_calls,
        converged=converged,
        flag=flag,
        seed=seed,
    )


def _validate_bounds(bounds: Sequence[tuple[float, float]]) -> list[_Bound]:
    """Validate and normalize `bounds`, raising `ValueError` naming any bad index."""
    if len(bounds) == 0:
        raise ValueError("bounds must not be empty")

    resolved: list[_Bound] = []
    for index, pair in enumerate(bounds):
        low, high = float(pair[0]), float(pair[1])
        if not math.isfinite(low) or not math.isfinite(high):
            raise ValueError(
                "bounds[%d] must be finite (got (%r, %r))" % (index, pair[0], pair[1])
            )
        if low > high:
            raise ValueError(
                "bounds[%d] must have low <= high (got (%r, %r))"
                % (index, pair[0], pair[1])
            )
        resolved.append(_Bound(low, high))
    return resolved


def _resolve_population_size(search_points: int | None, dimension: int) -> int:
    """Resolve `search_points`, Wolfram's `min(10*d, 50)` default, or reject it.

    An explicit value below `_MIN_POPULATION` is rejected outright (see the
    "search_points < 4" entry in the module docstring for why this raises
    rather than silently raising the population).
    """
    if search_points is None:
        return min(10 * dimension, 50)
    if search_points < _MIN_POPULATION:
        raise ValueError(
            "search_points must be at least %d (DE/rand/1/bin needs 3 donors "
            "distinct from the target); got %d" % (_MIN_POPULATION, search_points)
        )
    return search_points


def _clip(point: list[float], bounds: list[_Bound]) -> list[float]:
    """Clip `point` componentwise into `bounds`."""
    return [
        min(max(coord, bound.low), bound.high)
        for coord, bound in zip(point, bounds, strict=True)
    ]


def _initial_population(
    bounds: list[_Bound],
    population_size: int,
    seed: int,
    initial_points: Sequence[Sequence[float]] | None,
) -> list[list[float]]:
    """Build the generation-`0` population: seeded points first, random fill after.

    Member `i` comes from `initial_points[i]` when that index exists (clipped
    into `bounds`, and validated to have one coordinate per bound); every
    other member is drawn uniformly at random from `derive_stream(seed, i)`,
    matching the `(generation, member_index)` stream map the module
    docstring describes (`generation == 0` here).
    """
    dimension = len(bounds)
    population: list[list[float]] = []

    seeded_count = 0
    if initial_points is not None:
        seeded_count = min(len(initial_points), population_size)
        for index in range(seeded_count):
            point = initial_points[index]
            if len(point) != dimension:
                raise ValueError(
                    "initial_points[%d] must have %d coordinates (got %d)"
                    % (index, dimension, len(point))
                )
            population.append(_clip([float(v) for v in point], bounds))

    for member in range(seeded_count, population_size):
        stream = derive_stream(seed, member)
        point = [stream.uniform_range(bound.low, bound.high) for bound in bounds]
        population.append(_clip(point, bounds))

    return population


def _is_better(candidate: float, current: float) -> bool:
    """`True` if `candidate` should replace `current` under DE selection.

    A NaN `candidate` is never an improvement. A NaN `current` is always
    beaten by any real `candidate` (plain `candidate < current` is `False`
    whenever `current` is NaN, which would otherwise let a NaN incumbent
    block every future improvement forever).
    """
    if math.isnan(candidate):
        return False
    if math.isnan(current):
        return True
    return candidate < current


def _best_index(values: list[float]) -> int:
    """Return the index of the best (least, NaN-last) value in `values`.

    Ties keep the earliest index: `_is_better` uses a strict `<`, so a later
    value equal to the current best never displaces it. This makes the
    choice a deterministic function of `values` alone.
    """
    best = 0
    for index in range(1, len(values)):
        if _is_better(values[index], values[best]):
            best = index
    return best


def _value_gap(new_value: float, old_value: float) -> float:
    """Return `abs(new_value - old_value)`, or `+inf` if either is NaN.

    Plain subtraction would make a NaN gap register as "not less than
    tolerance" only by accident (NaN comparisons are always `False`, so
    `nan < tolerance` silently reads as converged); returning `+inf` instead
    fails the convergence test explicitly.
    """
    if math.isnan(new_value) or math.isnan(old_value):
        return _INFINITY
    return abs(new_value - old_value)


def _max_value_spread(values: list[float], best_index: int) -> float:
    """Return the largest `abs(values[best_index] - v)`, or `+inf` if any is NaN.

    Mirrors `nelder_mead._max_abs_diff`, NaN handling included: a plain
    `max()` over values containing NaN silently drops the NaN (every
    comparison against it is `False`, so it neither wins nor loses), which
    would let a NaN evaluation read as a converged spread. Returning `+inf`
    fails every tolerance test explicitly.
    """
    best = values[best_index]
    if math.isnan(best):
        return _INFINITY
    worst = 0.0
    for value in values:
        if math.isnan(value):
            return _INFINITY
        diff = abs(best - value)
        if diff > worst:
            worst = diff
    return worst


def _max_coordinate_spread(best: list[float], population: list[list[float]]) -> float:
    """Return the largest absolute coordinate difference from `best` to any member.

    The population counterpart of `nelder_mead._max_coordinate_spread`; the
    best member is included in the sweep, contributing `0.0`. A NaN
    coordinate yields `+inf` rather than being skipped, for the same reason
    `_max_value_spread` does.
    """
    worst = 0.0
    for point in population:
        for coord, best_coord in zip(point, best, strict=True):
            diff = abs(coord - best_coord)
            if math.isnan(diff):
                return _INFINITY
            if diff > worst:
                worst = diff
    return worst


def _has_converged(
    population: list[list[float]],
    values: list[float],
    best_index: int,
    tolerance: float,
    stagnant_generations: int,
) -> bool:
    """Report whether the population — not merely its best member — has converged.

    The primary test is `nelder_mead`'s two-part spread test transplanted
    from the simplex to the population: the function values across the
    population, and the population's coordinates, must both be within
    `tolerance` of the best member's. The secondary test covers the one case
    contraction cannot reach, an objective flat to within `tolerance` over
    the whole population, in which the population is frozen: there, a value
    spread within `tolerance` plus `_STAGNATION_GENERATIONS` consecutive
    generations of a motionless incumbent also counts as converged.

    A small value spread is necessary either way, so it is checked first and
    short-circuits the more expensive coordinate sweep. See the module
    docstring for why no single stagnant generation can pass this.
    """
    if _max_value_spread(values, best_index) > tolerance:
        return False
    if stagnant_generations >= _STAGNATION_GENERATIONS:
        return True
    return _max_coordinate_spread(population[best_index], population) <= tolerance


def _distance(a: Sequence[float], b: Sequence[float]) -> float:
    """Return the Euclidean distance between points `a` and `b`.

    A NaN coordinate on either side propagates through `math.sqrt` to a NaN
    result, and a NaN distance fails `point_gap < tolerance` (never true for
    NaN), so it never registers as convergence.
    """
    return math.sqrt(sum((x - y) ** 2 for x, y in zip(a, b, strict=True)))
