[package]
name = "sagejs-rust-wasm-arithmetic-probe"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "sagejs-rust-wasm-arithmetic-probe"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
