from typing import Any, Callable, Sequence, TypeVar

_Class = TypeVar("_Class", bound=type[Any])
_Callable = TypeVar("_Callable", bound=Callable[..., Any])


class _Array:
    prototype: Any

    @staticmethod
    def isArray(value: object) -> bool: ...


class _Number:
    MAX_SAFE_INTEGER: int
    MIN_SAFE_INTEGER: int

    @staticmethod
    def isInteger(value: object) -> bool: ...

    @staticmethod
    def isSafeInteger(value: object) -> bool: ...

    def __call__(self, value: object) -> Any: ...


class _Object:
    prototype: Any

    @staticmethod
    def assign(target: Any, *sources: Any) -> Any: ...

    @staticmethod
    def create(prototype: Any) -> Any: ...

    @staticmethod
    def defineProperties(value: object, properties: object) -> None: ...

    @staticmethod
    def defineProperty(value: object, name: str, descriptor: object) -> None: ...

    @staticmethod
    def freeze(value: object) -> object: ...

    @staticmethod
    def getOwnPropertyDescriptor(value: object, name: Any) -> Any: ...

    @staticmethod
    def getOwnPropertyNames(value: object) -> Any: ...

    @staticmethod
    def getPrototypeOf(value: object) -> Any: ...

    @staticmethod
    def keys(value: object) -> Any: ...

    @staticmethod
    def setPrototypeOf(value: object, prototype: Any) -> Any: ...


class _Reflect:
    @staticmethod
    def apply(
        function: Any,
        receiver: Any,
        arguments: Sequence[Any],
    ) -> Any: ...

    @staticmethod
    def construct(
        constructor: Any,
        arguments: Sequence[Any],
        new_target: Any = ...,
    ) -> Any: ...

    @staticmethod
    def deleteProperty(target: Any, property_name: Any) -> bool: ...

    @staticmethod
    def get(
        target: Any,
        property_name: Any,
        receiver: Any = ...,
    ) -> Any: ...

    @staticmethod
    def has(target: Any, property_name: Any) -> bool: ...

    @staticmethod
    def set(
        target: Any,
        property_name: Any,
        value: Any,
        receiver: Any = ...,
    ) -> bool: ...


class _Element:
    _parent: Any


class _Error:
    constructor: Any
    message: str
    name: str
    stack: str

    def __init__(self, message: str = ...) -> None: ...


array: _Array
console_object: Any
element: type[_Element]
error: type[_Error]
float_builtin: Any
global_object: Any
number: _Number
object: _Object
int_builtin: Any
list_constructor: Any
list_contains: Any
map_class: Any
math: Any
modules: Any
integer_factorization: Any
set_class: Any
polynomial_ring: Any
proxy_class: Any
qq: Any
rational_class: Any
reflect: _Reflect
reference_error: type[_Error]
string_class: Any
string_builtin: Any
undefined: Any
coercion_model: Any
kwargs_symbol: Any
iterator_symbol: Any
json: Any
zero_division_error: Any


def bigint(value: object) -> int: ...
def arraylike(value: object) -> bool: ...
def bigint_divexact(numerator: int, denominator: int) -> int: ...
def bigint_gcd(left: int, right: int) -> int: ...
def bigint_fields(*names: str) -> Callable[[_Class], _Class]: ...
def callable_instance_class(cls: _Class) -> _Class: ...
def equals(left: object, right: object) -> bool: ...
def factor_pair(factor: Any, exponent: int) -> list[Any]: ...
def flint_backend() -> Any: ...
def integer_bigint(value: object) -> int: ...
def instance_of(value: object, constructor: Any) -> bool: ...
def is_exact_integer(value: object) -> bool: ...
def is_math_element(value: object) -> bool: ...
def is_nan(value: Any) -> bool: ...
def jstype(value: object) -> str: ...
def lightweight_math_class(cls: _Class) -> _Class: ...
def map(*args: Any) -> Any: ...
def math_tuple(values: list[Any]) -> tuple[Any, ...]: ...
def modular_inverse(value: int, modulus: int) -> int: ...
def modular_power(value: int, exponent: int, modulus: int) -> int: ...
def native_add(left: Any, right: Any) -> Any: ...
def native_div(left: Any, right: Any) -> Any: ...
def native_method(method: _Callable) -> _Callable: ...
def native_method_adapter(method: _Callable) -> _Callable: ...
def native_mul(left: Any, right: Any) -> Any: ...
def native_neg(value: Any) -> Any: ...
def native_pow(left: Any, right: Any) -> Any: ...
def native_sub(left: Any, right: Any) -> Any: ...
def normalize_integer(value: int) -> int: ...
def operator_add_exact(left: Any, right: Any) -> Any: ...
def operator_mul_exact(left: Any, right: Any) -> Any: ...
def operator_pow_exact(left: Any, right: Any) -> Any: ...
def parse_float(value: Any) -> Any: ...
def parse_int(value: Any, radix: int = ...) -> Any: ...
def regexp(pattern: str, flags: str | None = ...) -> Any: ...
def real_literal(text: str) -> Any: ...
def require_module(name: str) -> Any: ...
def repr(value: object) -> str: ...
def sequence_class(cls: _Class) -> _Class: ...
def set_class_repr(cls: type[Any], text: str) -> None: ...
def strict_equal(left: object, right: object) -> bool: ...
def string(value: object) -> str: ...
def string_find(value: str, needle: str) -> int: ...
