from typing import Any, Callable, TypeVar

_Class = TypeVar("_Class", bound=type[Any])


class _Array:
    prototype: Any

    @staticmethod
    def isArray(value: object) -> bool: ...


class _Number:
    MAX_SAFE_INTEGER: int
    MIN_SAFE_INTEGER: int

    @staticmethod
    def isSafeInteger(value: object) -> bool: ...

    def __call__(self, value: object) -> Any: ...


class _Object:
    @staticmethod
    def defineProperties(value: object, properties: object) -> None: ...

    @staticmethod
    def defineProperty(value: object, name: str, descriptor: object) -> None: ...

    @staticmethod
    def freeze(value: object) -> object: ...


class _Reflect:
    @staticmethod
    def apply(
        function: Any,
        receiver: Any,
        arguments: list[Any],
    ) -> Any: ...

    @staticmethod
    def construct(constructor: Any, arguments: list[Any]) -> Any: ...

    @staticmethod
    def get(target: Any, property_name: str) -> Any: ...


class _Element:
    _parent: Any


class _Error:
    constructor: Any
    message: str
    name: str
    stack: str

    def __init__(self, message: str = ...) -> None: ...


array: _Array
element: type[_Element]
error: type[_Error]
number: _Number
object: _Object
map_class: Any
polynomial_ring: Any
qq: Any
rational_class: Any
reflect: _Reflect
reference_error: type[_Error]
string_class: Any
undefined: Any
coercion_model: Any
kwargs_symbol: Any
zero_division_error: Any


def bigint(value: object) -> int: ...
def bigint_divexact(numerator: int, denominator: int) -> int: ...
def bigint_gcd(left: int, right: int) -> int: ...
def bigint_fields(*names: str) -> Callable[[_Class], _Class]: ...
def callable_instance_class(cls: _Class) -> _Class: ...
def equals(left: object, right: object) -> bool: ...
def factor_pair(factor: Any, exponent: int) -> list[Any]: ...
def flint_backend() -> Any: ...
def integer_bigint(value: object) -> int: ...
def is_exact_integer(value: object) -> bool: ...
def iterator_symbol() -> Any: ...
def jstype(value: object) -> str: ...
def lightweight_math_class(cls: _Class) -> _Class: ...
def map(*args: Any) -> Any: ...
def math_tuple(values: list[Any]) -> tuple[Any, ...]: ...
def modular_inverse(value: int, modulus: int) -> int: ...
def modular_power(value: int, exponent: int, modulus: int) -> int: ...
def normalize_integer(value: int) -> int: ...
def operator_add_exact(left: Any, right: Any) -> Any: ...
def operator_mul_exact(left: Any, right: Any) -> Any: ...
def operator_pow_exact(left: Any, right: Any) -> Any: ...
def regexp(pattern: str, flags: str | None = ...) -> Any: ...
def require_module(name: str) -> Any: ...
def repr(value: object) -> str: ...
def sequence_class(cls: _Class) -> _Class: ...
def set_class_repr(cls: type[Any], text: str) -> None: ...
def string(value: object) -> str: ...
def string_find(value: str, needle: str) -> int: ...
