from typing import Any, Callable, Sequence, TypeVar

_Class = TypeVar("_Class", bound=type[Any])
_Callable = TypeVar("_Callable", bound=Callable[..., Any])


class _Array:
    prototype: Any

    @staticmethod
    def isArray(value: object) -> bool: ...


class _Number:
    MAX_SAFE_INTEGER: int
    MIN_SAFE_INTEGER: int
    NaN: float
    NEGATIVE_INFINITY: float
    POSITIVE_INFINITY: float
    prototype: Any

    @staticmethod
    def isInteger(value: object) -> bool: ...

    @staticmethod
    def isFinite(value: object) -> bool: ...

    @staticmethod
    def isNaN(value: object) -> bool: ...

    @staticmethod
    def isSafeInteger(value: object) -> bool: ...

    def __call__(self, value: object) -> Any: ...


class _Object:
    prototype: Any

    def __call__(self, value: object = ...) -> Any: ...

    @staticmethod
    def assign(target: Any, *sources: Any) -> Any: ...

    @staticmethod
    def create(prototype: Any) -> Any: ...

    @staticmethod
    def defineProperties(value: object, properties: object) -> None: ...

    @staticmethod
    def defineProperty(value: object, name: str, descriptor: object) -> None: ...

    @staticmethod
    def freeze(value: object) -> object: ...

    @staticmethod
    def isFrozen(value: object) -> bool: ...

    @staticmethod
    def getOwnPropertyDescriptor(value: object, name: Any) -> Any: ...

    @staticmethod
    def getOwnPropertyNames(value: object) -> Any: ...

    @staticmethod
    def getPrototypeOf(value: object) -> Any: ...

    @staticmethod
    def keys(value: object) -> Any: ...

    @staticmethod
    def setPrototypeOf(value: object, prototype: Any) -> Any: ...


class _Reflect:
    @staticmethod
    def apply(
        function: Any,
        receiver: Any,
        arguments: Sequence[Any],
    ) -> Any: ...

    @staticmethod
    def construct(
        constructor: Any,
        arguments: Sequence[Any],
        new_target: Any = ...,
    ) -> Any: ...

    @staticmethod
    def deleteProperty(target: Any, property_name: Any) -> bool: ...

    @staticmethod
    def get(
        target: Any,
        property_name: Any,
        receiver: Any = ...,
    ) -> Any: ...

    @staticmethod
    def has(target: Any, property_name: Any) -> bool: ...

    @staticmethod
    def set(
        target: Any,
        property_name: Any,
        value: Any,
        receiver: Any = ...,
    ) -> bool: ...


class _WeakRef:
    def deref(self) -> Any: ...


class _WeakRefClass:
    def __call__(self, target: object) -> _WeakRef: ...


class _FinalizationRegistry:
    def register(
        self,
        target: object,
        held_value: object,
        unregister_token: object = ...,
    ) -> None: ...

    def unregister(self, unregister_token: object) -> bool: ...


class _FinalizationRegistryClass:
    def __call__(
        self,
        callback: Callable[[object], None],
    ) -> _FinalizationRegistry: ...


class _Element:
    _parent: Any


class _Error:
    constructor: Any
    message: str
    name: str
    stack: str

    def __init__(self, message: str = ...) -> None: ...


array: _Array
console_object: Any
element: type[_Element]
error: type[_Error]
finalization_registry_class: _FinalizationRegistryClass
function_class: Any
float_builtin: Any
global_object: Any
native_number_class: _Number
number: _Number
object: _Object
int_builtin: Any
bool_builtin: Any
list_constructor: Any
list_contains: Any
map_class: Any
math: Any
modules: Any
integer_factorization: Any
set_class: Any
polynomial_ring: Any
proxy_class: Any
qq: Any
rational_class: Any
reflect: _Reflect
reference_error: type[_Error]
syntax_error: type[_Error]
type_error: type[_Error]
string_class: Any
string_builtin: Any
tuple_builtin: Any
undefined: Any
weak_ref_class: _WeakRefClass
coercion_model: Any


def register_doc(
    name: str,
    value: Any,
    metadata: Any = None,
) -> None: ...


def documentation_registry() -> list[list[Any]]: ...
kwargs_symbol: Any
iterator_symbol: Any
json: Any
zero_division_error: Any


def bigint(value: object) -> int: ...
def arraylike(value: object) -> bool: ...
def bigint_divexact(numerator: int, denominator: int) -> int: ...
def bigint_gcd(left: int, right: int) -> int: ...
def bigint_fields(*names: str) -> Callable[[_Class], _Class]: ...
def callable_instance_class(cls: _Class) -> _Class: ...
def equals(left: object, right: object) -> Any: ...
def dynamic_eval(
    javascript: str,
    input_namespace: Any,
    module_id: str,
) -> Any: ...
def factor_pair(factor: Any, exponent: int) -> list[Any]: ...
def fast_closed_binary(left: Any, right: Any, operation: str, missing: Any) -> Any: ...
def fast_machine_residue_recurrence(
    accumulator: Any,
    multiplier: Any,
    increment: Any,
    count: int,
) -> Any: ...
def ffi_call(
    declaration_identity: str,
    package_name: str,
    export_name: str,
    values: list[Any],
    parameter_types: list[str],
    return_type: str,
    result_domain: list[Any],
    error_exception: str | None,
    error_message: str | None,
    constraints: list[Any],
) -> Any: ...
def ffi_resource_create(
    declaration_identity: str,
    resource_identity: str,
    package_name: str,
    create_export: str,
    close_export: str,
    values: list[Any],
    parameter_types: list[str],
    parameter_minimums: list[str | None],
    error_policy: str,
    error_exception: str | None,
    error_message: str | None,
) -> Any: ...
def ffi_resource_borrow(token: Any, resource_identity: str) -> Any: ...
def ffi_resource_close(token: Any) -> None: ...
def ffi_resource_closed(token: Any) -> bool: ...
def ffi_resource_copy_bytes(
    token: Any,
    resource_identity: str,
    copy_export: str,
) -> Any: ...
def ffi_view_create(
    declaration_identity: str,
    view_identity: str,
    owner_identity: str,
    owner_token: Any,
    package_name: str,
    create_export: str,
    values: list[Any],
    parameter_types: list[str],
    error_policy: str,
    error_exception: str | None,
    error_message: str | None,
) -> Any: ...
def ffi_view_valid(token: Any) -> bool: ...
def flint_backend() -> Any: ...
def integer_bigint(value: object) -> int: ...
def immutable_uint64_capsule(
    source: Any, owner: object, model: str, format: str, count: int
) -> Any: ...
def immutable_uint64_capsule_lease(
    capsule: Any, owner: object, model: str, format: str, count: int
) -> Any: ...
def immutable_uint64_capsule_copy(
    capsule: Any, owner: object, model: str, format: str, count: int
) -> Any: ...
def immutable_uint64_capsule_gather(
    destination_owner: object,
    source_owners: tuple[object, ...],
    source_model: str,
    source_format: str,
    source_count: int,
    item_words: int,
    destination_model: str,
    destination_format: str,
    destination_count: int,
) -> Any: ...
def integer_buffer(source: Any, minimum_word_capacity: int = ...) -> Any: ...
def integer_buffer_from_packed_bytes(source: Any, length: int) -> Any: ...
def integer_buffer_prefix(source: Any, length: int) -> Any: ...
def integer_buffer_to_packed_bytes(source: Any) -> Any: ...
def exact_integer_values_to_packed_bytes(values: Any) -> Any: ...
def canonical_rational_values_to_packed_bytes(
    values: Any, rational_class: Any, parent: Any
) -> Any: ...
def exact_integer_values_from_packed_bytes(
    source: Any, count: int, start: int = ...
) -> Any: ...
def exact_integer_range_values(start: int, step: int, length: int) -> Any: ...
def exact_integer_range_iterator(start: int, step: int, length: int) -> Any: ...
def reduced_rational_values_from_parts(
    parts: Any, rational_class: Any, parent: Any
) -> Any: ...
def reference_matrix_transpose(
    rows: Any, row_count: int, column_count: int
) -> Any: ...
def reference_matrix_flatten(
    rows: Any, row_count: int, column_count: int
) -> Any: ...
def rational_buffers_from_packed_bytes(source: Any, length: int) -> Any: ...
def integer_buffer_used_word_capacity(source: Any) -> int: ...
def instance_of(value: object, constructor: Any) -> bool: ...
def is_exact_integer(value: object) -> bool: ...
def is_math_element(value: object) -> bool: ...
def is_nan(value: Any) -> bool: ...
def jstype(value: object) -> str: ...
def lightweight_math_class(cls: _Class) -> _Class: ...
def map(*args: Any) -> Any: ...
def math_tuple(values: list[Any]) -> tuple[Any, ...]: ...
def named_tuple(
    values: list[Any],
    type_name: str,
    field_names: list[str],
) -> tuple[Any, ...]: ...
def output_write(text: object) -> None: ...
def modular_inverse(value: int, modulus: int) -> int: ...
def modular_power(value: int, exponent: int, modulus: int) -> int: ...
def native_add(left: Any, right: Any) -> Any: ...
def native_bitand(left: Any, right: Any) -> Any: ...
def native_bitor(left: Any, right: Any) -> Any: ...
def native_bitxor(left: Any, right: Any) -> Any: ...
def native_div(left: Any, right: Any) -> Any: ...
def native_method(method: _Callable) -> _Callable: ...
def native_method_adapter(method: _Callable) -> _Callable: ...
def unbound_method_adapter(method: _Callable) -> _Callable: ...
non_exception_throw: Any
def native_mul(left: Any, right: Any) -> Any: ...
def native_mod(left: Any, right: Any) -> Any: ...
def native_neg(value: Any) -> Any: ...
def native_pow(left: Any, right: Any) -> Any: ...
def native_sub(left: Any, right: Any) -> Any: ...
def native_lshift(left: Any, right: Any) -> Any: ...
def native_rshift(left: Any, right: Any) -> Any: ...
def native_lt(left: Any, right: Any) -> bool: ...
def native_le(left: Any, right: Any) -> bool: ...
def native_gt(left: Any, right: Any) -> bool: ...
def native_ge(left: Any, right: Any) -> bool: ...
def native_get(value: Any, property_name: Any) -> Any: ...
def native_freeze_tuple(values: list[Any], prototype: Any) -> tuple[Any, ...]: ...
def json_scalar_sequence(source: Any) -> list[Any] | None: ...
def canonical_json_exact(source: Any) -> str | None: ...
def blocking_sleep(seconds: float) -> None: ...
def check_interrupt() -> None: ...
def normalize_integer(value: int) -> int: ...
def operator_add_exact(left: Any, right: Any) -> Any: ...
def operator_mul_exact(left: Any, right: Any) -> Any: ...
def operator_pow_exact(left: Any, right: Any) -> Any: ...
def parse_float(value: Any) -> Any: ...
def parse_int(value: Any, radix: int = ...) -> Any: ...
def regexp(pattern: str, flags: str | None = ...) -> Any: ...
def real_literal(text: str) -> Any: ...
def require_module(name: str) -> Any: ...
def repr(value: object) -> str: ...
def sequence_class(cls: _Class) -> _Class: ...
def scope_dict(values: Any) -> Any: ...
def set_class_repr(cls: Any, text: str) -> None: ...
def strict_equal(left: object, right: object) -> bool: ...
def string(value: object) -> str: ...
def string_find(value: str, needle: str) -> int: ...
def wall_time() -> float: ...
def uint64_buffer(source: Any) -> Any: ...
def uint64_buffer_prefix(source: Any, length: int) -> Any: ...
def uint64_matrix_format(source: Any, rows: int, columns: int) -> str: ...
def uint64_polynomial_format(source: Any, variable: str) -> str: ...
def uint64_residue_elements(
    source: Any, parent: Any, element_type: Any
) -> list[Any]: ...
def uint64_pack_le(source: Any, width: int) -> Any: ...
def uint64_residue_buffer(source: Any, modulus: int) -> Any: ...
def uint64_unpack_le(source: Any, width: int, length: int) -> Any: ...
