// Copyright (C) Sage.js contributors.
// GPL-2.0-or-later, without warranty.

//! Recover rank-one or rank-two lattices generated by compact cubic units.

use crate::hnf::{BigIntMatrix, ExactNormalFormWorkspace, NormalFormError, NormalFormLimits};
use rug::{Complete, Float, Integer, Rational};

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum UnitLatticeError {
    WrongRank,
    ZeroDenominatorBound,
    NonFiniteLogarithm,
    RationalReconstructionFailed,
    Exact(NormalFormError),
}

impl From<NormalFormError> for UnitLatticeError {
    fn from(value: NormalFormError) -> Self {
        Self::Exact(value)
    }
}

#[derive(Clone, Debug)]
pub struct ReconstructedUnitLattice {
    pub coordinate_basis_indices: [usize; 2],
    /// Two rational coordinates for each supplied compact unit.
    pub rational_coordinates: Vec<[Rational; 2]>,
    /// Common denominator of the integer coordinate model.
    pub common_denominator: Integer,
    /// Index of the selected two-unit lattice in the full reconstructed one.
    pub selected_basis_index: Integer,
    /// Two rows expressing a basis of the reconstructed lattice in terms of
    /// the supplied compact units.
    pub generator_combinations: [Vec<Integer>; 2],
    pub regulator_approximation: Float,
}

#[derive(Clone, Debug)]
pub struct ReconstructedRankOneUnitLattice {
    pub coordinate_basis_index: usize,
    /// One rational coordinate for each supplied compact unit.
    pub rational_coordinates: Vec<Rational>,
    pub common_denominator: Integer,
    /// Index of the selected unit lattice in the reconstructed rank-one one.
    pub selected_basis_index: Integer,
    /// A generator of the reconstructed lattice in terms of supplied units.
    pub generator_combination: Vec<Integer>,
    pub regulator_approximation: Float,
}

fn determinant(left: &[Float; 3], right: &[Float; 3], precision: u32) -> Float {
    let mut value = Float::with_val(precision, &left[0]);
    value *= &right[1];
    let mut cross = Float::with_val(precision, &left[1]);
    cross *= &right[0];
    value -= cross;
    value
}

fn lcm(left: &Integer, right: &Integer) -> Integer {
    if left == &0 || right == &0 {
        return Integer::from(0);
    }
    let gcd = left.gcd_ref(right).complete();
    let quotient = Integer::from(left / &gcd);
    Integer::from(&quotient * right)
}

/// Closest rational with denominator at most `maximum_denominator`.
fn limit_denominator(
    value: &Rational,
    maximum_denominator: &Integer,
) -> Result<Rational, UnitLatticeError> {
    if maximum_denominator <= &0 {
        return Err(UnitLatticeError::ZeroDenominatorBound);
    }
    let negative = value < &0;
    let mut numerator = value.numer().clone().abs();
    let mut denominator = value.denom().clone();
    if denominator <= *maximum_denominator {
        return Ok(value.clone());
    }
    let mut p0 = Integer::from(0);
    let mut q0 = Integer::from(1);
    let mut p1 = Integer::from(1);
    let mut q1 = Integer::from(0);
    loop {
        let quotient = Integer::from(&numerator / &denominator);
        let q2 = Integer::from(&q0 + &quotient * &q1);
        if q2 > *maximum_denominator {
            break;
        }
        let p2 = Integer::from(&p0 + &quotient * &p1);
        p0 = p1;
        q0 = q1;
        p1 = p2;
        q1 = q2;
        let remainder = Integer::from(&numerator - &quotient * &denominator);
        numerator = denominator;
        denominator = remainder;
        if denominator == 0 {
            break;
        }
    }
    let remaining = Integer::from(maximum_denominator - &q0);
    let k = Integer::from(&remaining / &q1);
    let bound_one = Rational::from((Integer::from(&p0 + &k * &p1), Integer::from(&q0 + &k * &q1)));
    let bound_two = Rational::from((p1, q1));
    let absolute = Rational::from((value.numer().clone().abs(), value.denom().clone()));
    let mut distance_one = Rational::from(&bound_one - &absolute);
    distance_one.abs_mut();
    let mut distance_two = Rational::from(&bound_two - &absolute);
    distance_two.abs_mut();
    let mut answer = if distance_two <= distance_one {
        bound_two
    } else {
        bound_one
    };
    if negative {
        answer = -answer;
    }
    Ok(answer)
}

pub fn reconstruct_rank_two_unit_lattice(
    logarithms: &[[Float; 3]],
    maximum_denominator: &Integer,
) -> Result<ReconstructedUnitLattice, UnitLatticeError> {
    if logarithms.len() < 2 {
        return Err(UnitLatticeError::WrongRank);
    }
    let precision = logarithms
        .iter()
        .flat_map(|row| row.iter())
        .map(Float::prec)
        .min()
        .ok_or(UnitLatticeError::WrongRank)?;
    if logarithms.iter().flatten().any(|value| !value.is_finite()) {
        return Err(UnitLatticeError::NonFiniteLogarithm);
    }
    let mut selected = None;
    let mut selected_determinant = Float::with_val(precision, 0);
    for left in 0..logarithms.len() {
        for right in left + 1..logarithms.len() {
            let candidate = determinant(&logarithms[left], &logarithms[right], precision);
            let mut magnitude = candidate.clone();
            magnitude.abs_mut();
            if selected.is_none() || magnitude > selected_determinant {
                selected = Some([left, right]);
                selected_determinant = magnitude;
            }
        }
    }
    let selected = selected.ok_or(UnitLatticeError::WrongRank)?;
    if selected_determinant == 0 {
        return Err(UnitLatticeError::WrongRank);
    }
    let signed_determinant = determinant(
        &logarithms[selected[0]],
        &logarithms[selected[1]],
        precision,
    );
    let mut rational_coordinates = Vec::with_capacity(logarithms.len());
    for logarithm in logarithms {
        let mut first = determinant(logarithm, &logarithms[selected[1]], precision);
        first /= &signed_determinant;
        let mut second = determinant(&logarithms[selected[0]], logarithm, precision);
        second /= &signed_determinant;
        rational_coordinates.push([
            limit_denominator(
                &first
                    .to_rational()
                    .ok_or(UnitLatticeError::RationalReconstructionFailed)?,
                maximum_denominator,
            )?,
            limit_denominator(
                &second
                    .to_rational()
                    .ok_or(UnitLatticeError::RationalReconstructionFailed)?,
                maximum_denominator,
            )?,
        ]);
    }
    let common_denominator = rational_coordinates
        .iter()
        .flatten()
        .fold(Integer::from(1), |denominator, value| {
            lcm(&denominator, value.denom())
        });
    let integer_coordinates = rational_coordinates
        .iter()
        .flat_map(|coordinate| {
            coordinate.iter().map(|value| {
                Integer::from(value.numer() * Integer::from(&common_denominator / value.denom()))
            })
        })
        .collect::<Vec<_>>();
    let coordinate_matrix = BigIntMatrix::try_new(logarithms.len(), 2, integer_coordinates)?;
    let mut workspace = ExactNormalFormWorkspace::new(NormalFormLimits {
        max_entries: logarithms.len() * logarithms.len(),
        max_operations: 1_000_000,
    });
    let hnf = workspace.row_hnf(&coordinate_matrix)?;
    if hnf.rank() != 2 {
        return Err(UnitLatticeError::WrongRank);
    }
    let nonzero_rows = (0..hnf.hnf.rows())
        .filter(|row| (0..2).any(|column| hnf.hnf.get(*row, column).unwrap() != &0))
        .collect::<Vec<_>>();
    if nonzero_rows.len() != 2 {
        return Err(UnitLatticeError::WrongRank);
    }
    let generator_combinations = std::array::from_fn(|basis| {
        (0..logarithms.len())
            .map(|unit| {
                hnf.left_transform
                    .get(nonzero_rows[basis], unit)
                    .unwrap()
                    .clone()
            })
            .collect::<Vec<_>>()
    });
    let mut lattice_determinant = Integer::from(
        hnf.hnf.get(nonzero_rows[0], 0).unwrap() * hnf.hnf.get(nonzero_rows[1], 1).unwrap(),
    );
    lattice_determinant -= Integer::from(
        hnf.hnf.get(nonzero_rows[0], 1).unwrap() * hnf.hnf.get(nonzero_rows[1], 0).unwrap(),
    );
    lattice_determinant.abs_mut();
    let denominator_square = Integer::from(&common_denominator * &common_denominator);
    let selected_basis_index = Integer::from(&denominator_square / &lattice_determinant);
    let mut regulator_approximation = selected_determinant;
    regulator_approximation *= &lattice_determinant;
    regulator_approximation /= &denominator_square;
    Ok(ReconstructedUnitLattice {
        coordinate_basis_indices: selected,
        rational_coordinates,
        common_denominator,
        selected_basis_index,
        generator_combinations,
        regulator_approximation,
    })
}

/// Recover a rank-one unit lattice from Dirichlet logarithms.
///
/// The first coordinate is used because signature `(1, 1)` stores
/// `[log|sigma_real|, 2 log|sigma_complex|, 0]`; the two nonzero coordinates
/// are negatives of one another for units.
pub fn reconstruct_rank_one_unit_lattice(
    logarithms: &[[Float; 3]],
    maximum_denominator: &Integer,
) -> Result<ReconstructedRankOneUnitLattice, UnitLatticeError> {
    if logarithms.is_empty() {
        return Err(UnitLatticeError::WrongRank);
    }
    let precision = logarithms
        .iter()
        .flat_map(|row| row.iter())
        .map(Float::prec)
        .min()
        .ok_or(UnitLatticeError::WrongRank)?;
    if logarithms.iter().flatten().any(|value| !value.is_finite()) {
        return Err(UnitLatticeError::NonFiniteLogarithm);
    }
    let selected = logarithms
        .iter()
        .enumerate()
        .max_by(|(_, left), (_, right)| {
            let mut left = left[0].clone();
            left.abs_mut();
            let mut right = right[0].clone();
            right.abs_mut();
            left.partial_cmp(&right)
                .unwrap_or(std::cmp::Ordering::Equal)
        })
        .map(|(index, _)| index)
        .ok_or(UnitLatticeError::WrongRank)?;
    if logarithms[selected][0] == 0 {
        return Err(UnitLatticeError::WrongRank);
    }
    let mut rational_coordinates = Vec::with_capacity(logarithms.len());
    for logarithm in logarithms {
        let mut coordinate = Float::with_val(precision, &logarithm[0]);
        coordinate /= &logarithms[selected][0];
        rational_coordinates.push(limit_denominator(
            &coordinate
                .to_rational()
                .ok_or(UnitLatticeError::RationalReconstructionFailed)?,
            maximum_denominator,
        )?);
    }
    let common_denominator = rational_coordinates
        .iter()
        .fold(Integer::from(1), |denominator, value| {
            lcm(&denominator, value.denom())
        });
    let integer_coordinates = rational_coordinates
        .iter()
        .map(|value| {
            Integer::from(value.numer() * Integer::from(&common_denominator / value.denom()))
        })
        .collect::<Vec<_>>();
    let coordinate_matrix = BigIntMatrix::try_new(logarithms.len(), 1, integer_coordinates)?;
    let mut workspace = ExactNormalFormWorkspace::new(NormalFormLimits {
        max_entries: logarithms.len() * logarithms.len(),
        max_operations: 1_000_000,
    });
    let hnf = workspace.row_hnf(&coordinate_matrix)?;
    if hnf.rank() != 1 {
        return Err(UnitLatticeError::WrongRank);
    }
    let nonzero_row = (0..hnf.hnf.rows())
        .find(|row| hnf.hnf.get(*row, 0).unwrap() != &0)
        .ok_or(UnitLatticeError::WrongRank)?;
    let lattice_step = hnf.hnf.get(nonzero_row, 0).unwrap().clone().abs();
    if lattice_step == 0 || Integer::from(&common_denominator % &lattice_step) != 0 {
        return Err(UnitLatticeError::RationalReconstructionFailed);
    }
    let generator_combination = (0..logarithms.len())
        .map(|unit| hnf.left_transform.get(nonzero_row, unit).unwrap().clone())
        .collect::<Vec<_>>();
    let selected_basis_index = Integer::from(&common_denominator / &lattice_step);
    let mut regulator_approximation = logarithms[selected][0].clone();
    regulator_approximation.abs_mut();
    regulator_approximation *= &lattice_step;
    regulator_approximation /= &common_denominator;
    Ok(ReconstructedRankOneUnitLattice {
        coordinate_basis_index: selected,
        rational_coordinates,
        common_denominator,
        selected_basis_index,
        generator_combination,
        regulator_approximation,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reconstructs_a_rational_superlattice() {
        let precision = 256;
        let logs = [
            [
                Float::with_val(precision, 2),
                Float::with_val(precision, 0),
                Float::with_val(precision, -2),
            ],
            [
                Float::with_val(precision, 0),
                Float::with_val(precision, 3),
                Float::with_val(precision, -3),
            ],
            [
                Float::with_val(precision, 1),
                Float::with_val(precision, 1.5),
                Float::with_val(precision, -2.5),
            ],
        ];
        let answer = reconstruct_rank_two_unit_lattice(&logs, &Integer::from(16)).unwrap();
        assert_eq!(answer.selected_basis_index, 2);
        assert_eq!(answer.common_denominator, 2);
        assert_eq!(answer.regulator_approximation, 3);
    }

    #[test]
    fn reconstructs_a_rank_one_superlattice() {
        let precision = 256;
        let logs = [
            [
                Float::with_val(precision, 2),
                Float::with_val(precision, -2),
                Float::with_val(precision, 0),
            ],
            [
                Float::with_val(precision, 3),
                Float::with_val(precision, -3),
                Float::with_val(precision, 0),
            ],
        ];
        let answer = reconstruct_rank_one_unit_lattice(&logs, &Integer::from(16)).unwrap();
        assert_eq!(answer.selected_basis_index, 3);
        assert_eq!(answer.common_denominator, 3);
        assert_eq!(answer.regulator_approximation, 1);
    }
}
