"""Connect PARI analytic inverse-hR preparation to one class-group attempt.

Copyright (C) The PARI group. GPL-2.0-or-later, without warranty.
Raw field data and prime degree patterns remain prepared; inverse hR is not an
answer input. Candidate acceptance is not a completeness certificate.
"""

from sagejs.native import Float64Buffer, Int64Buffer, IntegerBuffer, native
from .analytic_inverse_hr import pari_analytic_inverse_hr
from .discriminant_log import pari_discriminant_log
from .prepared_class_group_attempt import pari_prepared_class_group_attempt


@native
def pari_analytic_class_group_attempt(
    matrix: IntegerBuffer,
    ideal: IntegerBuffer,
    n: int,
    precision: int,
    scale: float,
    track_small: int,
    reduction: IntegerBuffer,
    vectors: IntegerBuffer,
    betas: IntegerBuffer,
    norms: IntegerBuffer,
    column: IntegerBuffer,
    float_q: Float64Buffer,
    float_v: Float64Buffer,
    bound: Float64Buffer,
    cache: IntegerBuffer,
    a: IntegerBuffer,
    b: IntegerBuffer,
    p: IntegerBuffer,
    q: IntegerBuffer,
    stack: IntegerBuffer,
    x: Int64Buffer,
    y: Float64Buffer,
    z: Float64Buffer,
    inc: Int64Buffer,
    state: Int64Buffer,
    cursor_output: Int64Buffer,
    element: IntegerBuffer,
    counters: Int64Buffer,
    admission_matrix_m: IntegerBuffer,
    admission_matrix_p: IntegerBuffer,
    admission_matrix_e: IntegerBuffer,
    admission_embedding_m: IntegerBuffer,
    admission_embedding_p: IntegerBuffer,
    admission_embedding_e: IntegerBuffer,
    admission_real_count: int,
    admission_ideal: IntegerBuffer,
    admission_mode: int,
    admission_factor_product: int,
    admission_primes: IntegerBuffer,
    admission_products: IntegerBuffer,
    admission_factorlimit: int,
    admission_prime_limit: int,
    admission_rational_factors: IntegerBuffer,
    admission_rational_exponents: IntegerBuffer,
    admission_prime_offsets: IntegerBuffer,
    admission_prime_counts: IntegerBuffer,
    admission_group_tau: IntegerBuffer,
    admission_group_e: IntegerBuffer,
    admission_group_f: IntegerBuffer,
    admission_group_inert: IntegerBuffer,
    admission_tau: IntegerBuffer,
    admission_x: IntegerBuffer,
    admission_y: IntegerBuffer,
    admission_spare: IntegerBuffer,
    admission_stack: IntegerBuffer,
    admission_primitive: IntegerBuffer,
    admission_columns: IntegerBuffer,
    admission_values: IntegerBuffer,
    admission_temporary: IntegerBuffer,
    admission_indices: IntegerBuffer,
    admission_exponents: IntegerBuffer,
    diagnostic: IntegerBuffer,
    nrelid: int,
    track_fact: int,
    jid0: int,
    e0: int,
    subfactor: IntegerBuffer,
    extra: IntegerBuffer,
    extra_count: int,
    relation_primes: IntegerBuffer,
    ramification: IntegerBuffer,
    relation: IntegerBuffer,
    relation_state: IntegerBuffer,
    relation_basis: IntegerBuffer,
    relation_records: IntegerBuffer,
    relation_hashes: IntegerBuffer,
    relation_metadata: IntegerBuffer,
    relation_scratch: IntegerBuffer,
    generators: IntegerBuffer,
    progress: Int64Buffer,
    preparation_rounded_embedding: IntegerBuffer,
    preparation_embedding: IntegerBuffer,
    preparation_original: IntegerBuffer,
    preparation_basis: IntegerBuffer,
    preparation_transform: IntegerBuffer,
    preparation_flags: IntegerBuffer,
    preparation_rank_diagnostic: IntegerBuffer,
    preparation_selection: IntegerBuffer,
    preparation_stages: IntegerBuffer,
    preparation_flatter_input: IntegerBuffer,
    preparation_current: IntegerBuffer,
    preparation_flatter_transform: IntegerBuffer,
    preparation_total_work: IntegerBuffer,
    preparation_step_t: IntegerBuffer,
    preparation_step_s: IntegerBuffer,
    preparation_product: IntegerBuffer,
    preparation_next_basis: IntegerBuffer,
    preparation_y: IntegerBuffer,
    preparation_diagnostic: IntegerBuffer,
    preparation_r1: IntegerBuffer,
    preparation_r2: IntegerBuffer,
    preparation_r3: IntegerBuffer,
    preparation_t1: IntegerBuffer,
    preparation_t2: IntegerBuffer,
    preparation_t3: IntegerBuffer,
    preparation_integers: IntegerBuffer,
    preparation_inverse: IntegerBuffer,
    preparation_first: IntegerBuffer,
    preparation_second: IntegerBuffer,
    preparation_final: IntegerBuffer,
    preparation_rounded: IntegerBuffer,
    preparation_mu: Float64Buffer,
    preparation_r: Float64Buffer,
    preparation_s: Float64Buffer,
    preparation_approximate: Float64Buffer,
    preparation_exponents: IntegerBuffer,
    preparation_float_gram: Float64Buffer,
    preparation_gram: IntegerBuffer,
    preparation_mu_exponents: IntegerBuffer,
    preparation_r_exponents: IntegerBuffer,
    preparation_s_exponents: IntegerBuffer,
    preparation_alpha: IntegerBuffer,
    preparation_column_exponents: IntegerBuffer,
    preparation_float_scratch: Float64Buffer,
    preparation_temporary: Float64Buffer,
    preparation_state: Int64Buffer,
    search_ideals: IntegerBuffer,
    search_count: int,
    packet_ids: IntegerBuffer,
    packet_ideals: IntegerBuffer,
    packet_norms: IntegerBuffer,
    schedule: Int64Buffer,
    construct_primes: int,
    basis_table: IntegerBuffer,
    packet_primes: IntegerBuffer,
    packet_generators: IntegerBuffer,
    packet_inert: IntegerBuffer,
    hnf_generator: IntegerBuffer,
    hnf_matrix: IntegerBuffer,
    hnf_work: IntegerBuffer,
    hnf_pivots: IntegerBuffer,
    power_ideal: IntegerBuffer,
    power_alpha: IntegerBuffer,
    power_metadata: IntegerBuffer,
    power_primitive: IntegerBuffer,
    power_temporary: IntegerBuffer,
    power_diagnostic: IntegerBuffer,
    power_multiplication: IntegerBuffer,
    power_work: IntegerBuffer,
    power_triangular: IntegerBuffer,
    power_moduli: IntegerBuffer,
    product_primitive: IntegerBuffer,
    product_matrix: IntegerBuffer,
    outer_mode: int,
    outer_ru: int,
    outer_state: Int64Buffer,
    outer_minidx: IntegerBuffer,
    outer_present: IntegerBuffer,
    outer_live: IntegerBuffer,
    outer_perm: IntegerBuffer,
    outer_multiplier: IntegerBuffer,
    log_precision: int,
    log_completed: IntegerBuffer,
    log_embeddings: IntegerBuffer,
    log_coordinates: IntegerBuffer,
    log_column: IntegerBuffer,
    log_cache: IntegerBuffer,
    log_pi_cache: IntegerBuffer,
    log_a: IntegerBuffer,
    log_b: IntegerBuffer,
    log_p: IntegerBuffer,
    log_q: IntegerBuffer,
    log_stack: IntegerBuffer,
    initial_additional: int,
    initial_target: int,
    initial_primes: IntegerBuffer,
    initial_offsets: IntegerBuffer,
    initial_counts: IntegerBuffer,
    initial_complete: IntegerBuffer,
    hnf_k0: int,
    hnf_original: Int64Buffer,
    hnf_perm: Int64Buffer,
    hnf_mat: Int64Buffer,
    hnf_dense: IntegerBuffer,
    hnf_transform: IntegerBuffer,
    hnf_vmax: Int64Buffer,
    hnf_found: Int64Buffer,
    hnf_sparse_state: Int64Buffer,
    hnf_bottom: IntegerBuffer,
    hnf_updated_dense: IntegerBuffer,
    hnf_extra: IntegerBuffer,
    hnf_cleanup_state: Int64Buffer,
    hnf_rank_matrix: IntegerBuffer,
    hnf_occupied: IntegerBuffer,
    hnf_rank_pivots: IntegerBuffer,
    hnf_best: IntegerBuffer,
    hnf_profile: IntegerBuffer,
    hnf_rank_state: IntegerBuffer,
    hnf_perm_work: Int64Buffer,
    hnf_matbnew: IntegerBuffer,
    hnf_dep: IntegerBuffer,
    hnf_b: IntegerBuffer,
    hnf_assembly_state: Int64Buffer,
    hnf_transformed_logs: IntegerBuffer,
    hnf_full_h: IntegerBuffer,
    hnf_hnf_transform: IntegerBuffer,
    hnf_lam: IntegerBuffer,
    hnf_d: IntegerBuffer,
    hnf_hnf_state: Int64Buffer,
    hnf_full_dep: IntegerBuffer,
    hnf_work_b: IntegerBuffer,
    hnf_work_c: IntegerBuffer,
    hnf_diagonal: Int64Buffer,
    hnf_result_h: IntegerBuffer,
    hnf_result_dep: IntegerBuffer,
    hnf_result_b: IntegerBuffer,
    hnf_result_c: IntegerBuffer,
    hnf_final_state: Int64Buffer,
    hnf_state: Int64Buffer,
    chain_state: Int64Buffer,
    accept_inverse_hr: IntegerBuffer,
    accept_logs: IntegerBuffer,
    accept_class_number: IntegerBuffer,
    accept_zeta_factor: IntegerBuffer,
    accept_post_hnf_state: Int64Buffer,
    accept_prepared: IntegerBuffer,
    accept_selected: Int64Buffer,
    accept_prep_state: Int64Buffer,
    accept_rank_work: IntegerBuffer,
    accept_rank_occupied: Int64Buffer,
    accept_rank_pivots: Int64Buffer,
    accept_rank_state: Int64Buffer,
    accept_integer_input: IntegerBuffer,
    accept_integer_work: IntegerBuffer,
    accept_integer_occupied: IntegerBuffer,
    accept_integer_pivots: IntegerBuffer,
    accept_integer_best: IntegerBuffer,
    accept_integer_state: IntegerBuffer,
    accept_basis: IntegerBuffer,
    accept_minor: IntegerBuffer,
    accept_det_work: IntegerBuffer,
    accept_det_result: IntegerBuffer,
    accept_det_pivots: Int64Buffer,
    accept_det_state: Int64Buffer,
    accept_inverse_work: IntegerBuffer,
    accept_inverse_rhs: IntegerBuffer,
    accept_inverse: IntegerBuffer,
    accept_inverse_pivots: Int64Buffer,
    accept_inverse_state: Int64Buffer,
    accept_product: IntegerBuffer,
    accept_inverse_slice: IntegerBuffer,
    accept_multiple: IntegerBuffer,
    accept_coordinates: IntegerBuffer,
    accept_multiple_state: Int64Buffer,
    accept_rational_work: IntegerBuffer,
    accept_lattice: IntegerBuffer,
    accept_hnf_work: IntegerBuffer,
    accept_hnf_column: IntegerBuffer,
    accept_hnf_output: IntegerBuffer,
    accept_hnf_state: Int64Buffer,
    accept_regulator: IntegerBuffer,
    accept_relations: IntegerBuffer,
    accept_denominator: IntegerBuffer,
    accept_reconstruction_state: Int64Buffer,
    accept_hnf_row_pivots: Int64Buffer,
    accept_hnf_heights: Int64Buffer,
    accept_cache_changed: bool,
    accept_acceptance_state: Int64Buffer,
    smith_work: IntegerBuffer,
    smith_column: IntegerBuffer,
    smith_invariants: IntegerBuffer,
    smith_class_number: IntegerBuffer,
    smith_state: Int64Buffer,
    class_invariants: IntegerBuffer,
    class_number: IntegerBuffer,
    attempt_state: Int64Buffer,
    hnf_cup_arena: IntegerBuffer,
    hnf_cup_frames: IntegerBuffer,
    hnf_cup_solve_state: Int64Buffer,
    hnf_cup_state: Int64Buffer,
    analytic_discriminant: int,
    analytic_roots_of_unity: int,
    analytic_log_discriminant: Float64Buffer,
    analytic_primes: IntegerBuffer,
    analytic_offsets: IntegerBuffer,
    analytic_counts: IntegerBuffer,
    analytic_degrees: IntegerBuffer,
    analytic_multiplicities: IntegerBuffer,
    analytic_coefficients: Float64Buffer,
    analytic_table: Float64Buffer,
    analytic_tail: Float64Buffer,
    analytic_logarithms: Float64Buffer,
    analytic_log_inverse_residue: Float64Buffer,
    analytic_inverse_residue: IntegerBuffer,
    analytic_exp_cache: IntegerBuffer,
    analytic_pi_cache: IntegerBuffer,
    analytic_a: IntegerBuffer,
    analytic_b: IntegerBuffer,
    analytic_p: IntegerBuffer,
    analytic_q: IntegerBuffer,
    analytic_stack: IntegerBuffer,
    analytic_state: Int64Buffer,
) -> int:
    """Compute inverse hR before invoking the existing prepared attempt.

    `accept_inverse_hr` is output-only scratch; its initial values are ignored.
    `analytic_log_discriminant` is also output-only scratch, derived from the
    exact signed discriminant using the translated PARI conversion.
    `analytic_state` receives the selected residue bound and processed count.
    All owners must be disjoint and satisfy their component capacity contracts.
    The analytic discriminant and prime patterns must describe the same field
    as the prepared nf/ideal data; signature checks alone cannot prove this.
    Terminal repeats are mutation-free, including all analytic scratch.
    Analytic failure can mutate analytic scratch, but publishes no class result.
    This is an initial attempt only, with no retry or honesty-policy extension.
    """
    if len(attempt_state) < 4:
        raise ValueError("short prepared class attempt state")
    if attempt_state[0] == 4:
        return int(attempt_state[1])
    if attempt_state[0] != 0:
        raise ValueError("cannot reuse a partial class group attempt")
    if len(class_invariants) < len(relation) or len(class_number) < 1:
        raise ValueError("short prepared class result owners")
    if len(chain_state) < 4 or chain_state[0] != 0:
        raise ValueError("class attempt requires a fresh relation stage")
    if (
        len(accept_inverse_hr) < 3
        or len(analytic_state) < 2
        or len(analytic_log_discriminant) < 1
    ):
        raise ValueError("short analytic class attempt output owners")
    if admission_real_count < 0 or admission_real_count > n:
        raise ValueError("invalid analytic field signature")
    if (n - admission_real_count) % 2 != 0:
        raise ValueError("invalid analytic field signature")
    attempt_state[0] = 1
    attempt_state[1] = -1
    attempt_state[2] = 0
    attempt_state[3] = 0
    analytic_log_discriminant[0] = pari_discriminant_log(analytic_discriminant)
    residue_bound, processed, hm, hp, he = pari_analytic_inverse_hr(
        analytic_discriminant,
        admission_real_count,
        (n - admission_real_count) // 2,
        analytic_roots_of_unity,
        analytic_log_discriminant,
        analytic_primes,
        analytic_offsets,
        analytic_counts,
        analytic_degrees,
        analytic_multiplicities,
        analytic_coefficients,
        analytic_table,
        analytic_tail,
        analytic_logarithms,
        analytic_log_inverse_residue,
        analytic_inverse_residue,
        analytic_exp_cache,
        analytic_pi_cache,
        analytic_a,
        analytic_b,
        analytic_p,
        analytic_q,
        analytic_stack,
    )
    analytic_state[0] = residue_bound
    analytic_state[1] = processed
    accept_inverse_hr[0] = hm
    accept_inverse_hr[1] = hp
    accept_inverse_hr[2] = he
    attempt_state[0] = 0
    return pari_prepared_class_group_attempt(
        matrix,
        ideal,
        n,
        precision,
        scale,
        track_small,
        reduction,
        vectors,
        betas,
        norms,
        column,
        float_q,
        float_v,
        bound,
        cache,
        a,
        b,
        p,
        q,
        stack,
        x,
        y,
        z,
        inc,
        state,
        cursor_output,
        element,
        counters,
        admission_matrix_m,
        admission_matrix_p,
        admission_matrix_e,
        admission_embedding_m,
        admission_embedding_p,
        admission_embedding_e,
        admission_real_count,
        admission_ideal,
        admission_mode,
        admission_factor_product,
        admission_primes,
        admission_products,
        admission_factorlimit,
        admission_prime_limit,
        admission_rational_factors,
        admission_rational_exponents,
        admission_prime_offsets,
        admission_prime_counts,
        admission_group_tau,
        admission_group_e,
        admission_group_f,
        admission_group_inert,
        admission_tau,
        admission_x,
        admission_y,
        admission_spare,
        admission_stack,
        admission_primitive,
        admission_columns,
        admission_values,
        admission_temporary,
        admission_indices,
        admission_exponents,
        diagnostic,
        nrelid,
        track_fact,
        jid0,
        e0,
        subfactor,
        extra,
        extra_count,
        relation_primes,
        ramification,
        relation,
        relation_state,
        relation_basis,
        relation_records,
        relation_hashes,
        relation_metadata,
        relation_scratch,
        generators,
        progress,
        preparation_rounded_embedding,
        preparation_embedding,
        preparation_original,
        preparation_basis,
        preparation_transform,
        preparation_flags,
        preparation_rank_diagnostic,
        preparation_selection,
        preparation_stages,
        preparation_flatter_input,
        preparation_current,
        preparation_flatter_transform,
        preparation_total_work,
        preparation_step_t,
        preparation_step_s,
        preparation_product,
        preparation_next_basis,
        preparation_y,
        preparation_diagnostic,
        preparation_r1,
        preparation_r2,
        preparation_r3,
        preparation_t1,
        preparation_t2,
        preparation_t3,
        preparation_integers,
        preparation_inverse,
        preparation_first,
        preparation_second,
        preparation_final,
        preparation_rounded,
        preparation_mu,
        preparation_r,
        preparation_s,
        preparation_approximate,
        preparation_exponents,
        preparation_float_gram,
        preparation_gram,
        preparation_mu_exponents,
        preparation_r_exponents,
        preparation_s_exponents,
        preparation_alpha,
        preparation_column_exponents,
        preparation_float_scratch,
        preparation_temporary,
        preparation_state,
        search_ideals,
        search_count,
        packet_ids,
        packet_ideals,
        packet_norms,
        schedule,
        construct_primes,
        basis_table,
        packet_primes,
        packet_generators,
        packet_inert,
        hnf_generator,
        hnf_matrix,
        hnf_work,
        hnf_pivots,
        power_ideal,
        power_alpha,
        power_metadata,
        power_primitive,
        power_temporary,
        power_diagnostic,
        power_multiplication,
        power_work,
        power_triangular,
        power_moduli,
        product_primitive,
        product_matrix,
        outer_mode,
        outer_ru,
        outer_state,
        outer_minidx,
        outer_present,
        outer_live,
        outer_perm,
        outer_multiplier,
        log_precision,
        log_completed,
        log_embeddings,
        log_coordinates,
        log_column,
        log_cache,
        log_pi_cache,
        log_a,
        log_b,
        log_p,
        log_q,
        log_stack,
        initial_additional,
        initial_target,
        initial_primes,
        initial_offsets,
        initial_counts,
        initial_complete,
        hnf_k0,
        hnf_original,
        hnf_perm,
        hnf_mat,
        hnf_dense,
        hnf_transform,
        hnf_vmax,
        hnf_found,
        hnf_sparse_state,
        hnf_bottom,
        hnf_updated_dense,
        hnf_extra,
        hnf_cleanup_state,
        hnf_rank_matrix,
        hnf_occupied,
        hnf_rank_pivots,
        hnf_best,
        hnf_profile,
        hnf_rank_state,
        hnf_perm_work,
        hnf_matbnew,
        hnf_dep,
        hnf_b,
        hnf_assembly_state,
        hnf_transformed_logs,
        hnf_full_h,
        hnf_hnf_transform,
        hnf_lam,
        hnf_d,
        hnf_hnf_state,
        hnf_full_dep,
        hnf_work_b,
        hnf_work_c,
        hnf_diagonal,
        hnf_result_h,
        hnf_result_dep,
        hnf_result_b,
        hnf_result_c,
        hnf_final_state,
        hnf_state,
        chain_state,
        accept_inverse_hr,
        accept_logs,
        accept_class_number,
        accept_zeta_factor,
        accept_post_hnf_state,
        accept_prepared,
        accept_selected,
        accept_prep_state,
        accept_rank_work,
        accept_rank_occupied,
        accept_rank_pivots,
        accept_rank_state,
        accept_integer_input,
        accept_integer_work,
        accept_integer_occupied,
        accept_integer_pivots,
        accept_integer_best,
        accept_integer_state,
        accept_basis,
        accept_minor,
        accept_det_work,
        accept_det_result,
        accept_det_pivots,
        accept_det_state,
        accept_inverse_work,
        accept_inverse_rhs,
        accept_inverse,
        accept_inverse_pivots,
        accept_inverse_state,
        accept_product,
        accept_inverse_slice,
        accept_multiple,
        accept_coordinates,
        accept_multiple_state,
        accept_rational_work,
        accept_lattice,
        accept_hnf_work,
        accept_hnf_column,
        accept_hnf_output,
        accept_hnf_state,
        accept_regulator,
        accept_relations,
        accept_denominator,
        accept_reconstruction_state,
        accept_hnf_row_pivots,
        accept_hnf_heights,
        accept_cache_changed,
        accept_acceptance_state,
        smith_work,
        smith_column,
        smith_invariants,
        smith_class_number,
        smith_state,
        class_invariants,
        class_number,
        attempt_state,
        hnf_cup_arena,
        hnf_cup_frames,
        hnf_cup_solve_state,
        hnf_cup_state,
    )
