"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {spawnSync}=require("node:child_process"),{compileKernel}=require("../../tools/native-kernel/compiler.cjs");
const ARCHIVE_SHA256="02651d99c391007d384b3fadbc20abc6916b77036f9e496c99e9ce8688ca4b53";
const hash=x=>crypto.createHash("sha256").update(x).digest("hex");
function run(c,a,o={}){const r=spawnSync(c,a,{encoding:"utf8",timeout:900000,maxBuffer:64*1024*1024,...o});assert.equal(r.status,0,r.stderr||String(r.error));return r.stdout;}
function oracle(pari,archive){
 assert.equal(hash(fs.readFileSync(archive)),ARCHIVE_SHA256);const lib=path.join(pari,"Olinux-x86_64"),dir=fs.mkdtempSync(path.join(os.tmpdir(),"sagejs-quartic-cxlog-")),src=path.join(dir,"oracle.c"),exe=path.join(dir,"oracle");
 fs.writeFileSync(src,`#include "pari.h"
#include "paripriv.h"
static void s(GEN x){long e;if(typ(x)==t_INT){pari_printf("%Ps -1 0 ",x);return;}pari_printf("%Ps %ld %ld ",signe(x)?mantissa_real(x,&e):gen_0,signe(x)?bit_prec(x):0,expo(x));}
static void z(GEN x){if(typ(x)==t_COMPLEX){printf("2 ");s(gel(x,1));s(gel(x,2));}else{printf("1 ");s(x);printf("0 -1 0 ");}}
static void im(GEN x){for(long j=1;j<lg(x);j++)for(long i=1;i<lg(gel(x,j));i++)pari_printf("%Ps ",gcoeff(x,i,j));}
static void lm(GEN x,long c){for(long j=1;j<=c;j++)for(long i=1;i<=3;i++)z(gcoeff(x,i,j));}
static GEN add0(GEN a,GEN t){return a?RgC_add(a,t):t;}
static GEN act0(GEN A,GEN x){GEN a;long i,l=lg(A),t=typ(A);if(t==t_MAT){a=cgetg(l,t_MAT);for(i=1;i<l;i++)gel(a,i)=act0(gel(A,i),x);return a;}if(l==1)return cgetg(1,t_COL);a=NULL;for(i=1;i<l;i++){GEN c=gel(A,i);if(signe(c))a=add0(a,gmul(c,gel(x,i)));}return a?a:zerocol(lgcols(x)-1);}
static GEN diag0(GEN v,GEN x){long i,l=lg(v);GEN a=cgetg(l,t_MAT);for(i=1;i<l;i++)gel(a,i)=gmul(gel(x,i),gel(v,i));return a;}
static void fac(GEN F){long n=lg(gel(F,1))-1;printf("%ld ",n);for(long i=1;i<=n;i++){GEN x=gcoeff(F,i,1);if(typ(x)==t_COL){printf("1 ");for(long k=1;k<=4;k++)pari_printf("%Ps ",gel(x,k));printf("1 ");}else{GEN a=x,d=gen_1;if(typ(x)==t_FRAC){a=gel(x,1);d=gel(x,2);}printf("0 ");pari_printf("%Ps 0 0 0 %Ps ",a,d);}pari_printf("%Ps ",gcoeff(F,i,2));}}
int main(){pari_init(1200000000,10000);long bits=192;GEN b=bnfinit0(gp_read_str("x^4-200000002*x-200000002"),1,NULL,nbits2prec(bits)),nf=bnf_get_nf(b),M=nf_get_M(nf),W=gel(b,1),C=gel(b,4),Ge=gmael(b,9,4),U,V,Y,X;GEN D=ZM_snfall(W,&U,&V),D0=gcopy(D),V0=gcopy(V),Ui=ZM_inv(U,NULL),Ur=ZM_hnfdivrem(U,D,&Y),Uir=ZM_hnfdivrem(Ui,W,&X),M2=ZM_add(ZM_mul(X,Ur),ZM_mul(V,Y));long n=lg(W)-1,j,l;for(j=1;j<lg(D);j++)if(is_pm1(gcoeff(D,j,j)))break;l=j;GEN cyc=cgetg(l,t_VEC);for(j=1;j<l;j++)gel(cyc,j)=gcoeff(D,j,j);setlg(V,l);setlg(D,l);GEN M1=ZM_add(V,ZM_mul(X,D)),Ga=nfV_cxlog(nf,Ge,nbits2prec(bits)),GD=gsub(act0(M1,C),diag0(cyc,Ga)),ga=gsub(act0(M2,C),act0(Ur,Ga));printf("%ld %ld %ld ",n,l-1,bits);for(long r=1;r<=4;r++)for(long c=1;c<=4;c++){GEN q=gcoeff(M,3,c),x;if(r<=2)x=gcoeff(M,r,c);else if(typ(q)==t_COMPLEX)x=gel(q,r-2);else x=r==3?q:gen_0;s(x);}im(W);lm(C,n);im(D0);im(U);im(Ui);im(V0);im(Ur);im(Y);im(Uir);im(X);im(M1);im(M2);for(j=1;j<l;j++)pari_printf("%Ps ",gel(cyc,j));pari_printf("%Ps ",bnf_get_no(b));for(j=1;j<l;j++)fac(gel(Ge,j));lm(Ga,l-1);lm(GD,l-1);lm(ga,n);putchar('\\n');pari_close();}`);
 run("cc",["-O2",`-I${path.join(pari,"src/headers")}`,`-I${lib}`,src,`-L${lib}`,`-Wl,-rpath,${lib}`,"-lpari","-lm","-o",exe]);
 const w=run(exe,[]).trim().split(/\s+/),take=n=>{const a=w.slice(take.at,take.at+n).map(BigInt);take.at+=n;return a;};take.at=0;const n=Number(take(1)[0]),active=Number(take(1)[0]),precision=Number(take(1)[0]),t=take(48),matrix=[0,1,2].map(k=>t.filter((_,i)=>i%3===k)),W=take(n*n),C=take(21*n),square=["D","U","Ui","V","Ur","Y","Uir","X"],expected=Object.fromEntries(square.map(k=>[k,take(n*n)]));expected.M1=take(n*active).concat(Array(n*(n-active)).fill(0n));expected.M2=take(n*n);expected.invariants=take(active);expected.classNumber=take(1);const offsets=[0n],kinds=[],values=[],exponents=[];for(let g=0;g<active;g++){const count=Number(take(1)[0]);for(let i=0;i<count;i++){kinds.push(...take(1));values.push(...take(5));exponents.push(...take(1));}offsets.push(BigInt(kinds.length));}expected.Ga=take(21*active);expected.GD=take(21*active);expected.ga=take(21*n);assert.equal(take.at,w.length);return{n,active,precision,matrix,W,C,offsets,kinds,values,exponents,expected,dir};
}
const vals=x=>Array.isArray(x)?x:x.toArray();
function alloc(fn,backend,f){const exact=(a,b=1536)=>backend==="javascript"?a.slice():fn.createIntegerBuffer(a.length,b,a),z=(n,b=1536)=>exact(Array(n).fill(0n),b),i64=n=>Array(n).fill(0n),input=a=>exact(a),n=f.n,a=f.active,m=Array.from({length:10},()=>z(n*n)),inv=z(n),h=z(1),Ga=exact(Array(21*a).fill(77n)),GD=exact(Array(21*a).fill(77n)),ga=exact(Array(21*n).fill(77n));const args=[...f.matrix.map(input),input(f.W),input(f.C),input(f.offsets),input(f.kinds),input(f.values),input(f.exponents),BigInt(n),BigInt(a),BigInt(f.precision),...m,inv,h,Ga,GD,ga,z(n),z(n*n),z(2*n*n),...Array.from({length:4},()=>i64(7)),i64(9),z(9),z(4),z(21),z(21),...Array.from({length:6},()=>z(64)),z(128),z(21*n),z(21*a),z(21*a),z(21*n),z(21*n),z(21*a),z(21*n),i64(8)];return{args,m,inv,h,Ga,GD,ga};}
function check(c,f,label){for(const[i,k]of["D","U","Ui","V","Ur","Y","Uir","X","M1","M2"].entries())assert.deepEqual(vals(c.m[i]),f.expected[k],`${label}:${k}`);assert.deepEqual(vals(c.inv).slice(0,f.active),f.expected.invariants,`${label}:invariants`);assert.deepEqual(vals(c.h),f.expected.classNumber,`${label}:number`);assert.deepEqual(vals(c.Ga),f.expected.Ga,`${label}:Ga`);assert.deepEqual(vals(c.GD),f.expected.GD,`${label}:GD`);assert.deepEqual(vals(c.ga),f.expected.ga,`${label}:ga`);}
(async()=>{const pari=path.resolve(process.argv[2]||"/scratch/pari-class-group-port-C7hzCV2b/pari-2.17.4"),archive=path.resolve(process.argv[3]||"/scratch/pari-class-group-port-C7hzCV2b/pari-2.17.4.tar.gz"),f=oracle(pari,archive);assert.equal(f.n,3);assert.equal(f.active,2);assert.deepEqual(f.offsets,[0n,0n,7n]);
 const payload=JSON.stringify(f,(_,v)=>typeof v==="bigint"?v.toString():v),py=`import importlib,json,sys\nsys.path[:0]=sys.argv[1:3]\nr=json.load(sys.stdin);cv=lambda a:list(map(int,a));z=lambda n:[0]*n\nf=importlib.import_module('bench.pari-class-group-port.quartic_nf_cxlog').pari_mixed_quartic_class_group_log_assembly\nn=r['n'];a=r['active'];m=[z(n*n) for _ in range(10)];inv=z(n);h=z(1);Ga=[77]*(21*a);GD=[77]*(21*a);ga=[77]*(21*n)\nargs=[*map(cv,r['matrix']),cv(r['W']),cv(r['C']),cv(r['offsets']),cv(r['kinds']),cv(r['values']),cv(r['exponents']),n,a,r['precision'],*m,inv,h,Ga,GD,ga,z(n),z(n*n),z(2*n*n),*[z(7) for _ in range(4)],z(9),z(9),z(4),z(21),z(21),*[z(64) for _ in range(6)],z(128),z(21*n),z(21*a),z(21*a),z(21*n),z(21*n),z(21*a),z(21*n),z(8)]\nassert f(*args)==0\ndef enc(x):\n return [enc(v) for v in x] if isinstance(x,list) else str(x)\nprint(json.dumps(enc([m,inv,h,Ga,GD,ga])))`;
 const d=JSON.parse(run("python3",["-c",py,path.resolve(__dirname,"../.."),path.resolve(__dirname,"../../src/lib")],{input:payload}),(_,v)=>typeof v==="string"&&/^-?\d+$/.test(v)?BigInt(v):v),names=["D","U","Ui","V","Ur","Y","Uir","X","M1","M2"];for(let i=0;i<10;i++)assert.deepEqual(d[0][i],f.expected[names[i]],`CPython:${names[i]}`);assert.deepEqual(d.slice(1),[f.expected.invariants.concat([0n]),f.expected.classNumber,f.expected.Ga,f.expected.GD,f.expected.ga]);
 const built=await compileKernel({sourcePath:path.join(__dirname,"quartic_nf_cxlog.py")}),fn=require(built.modulePath).pari_mixed_quartic_class_group_log_assembly;assert.equal(fn.nativeAvailable,true);for(const backend of["javascript","gmp","tagged"]){const c=alloc(fn,backend,f);assert.equal(fn[backend](...c.args),0n,backend);check(c,f,backend);}console.log(JSON.stringify({polynomial:"x^4-200000002*x-200000002",factors:7,embeddingPrecisionBits:[448,384,448,384],backends:["pristine PARI 2.17.4","CPython","javascript","gmp","tagged"],coreSha256:hash(fs.readFileSync(built.coreSourcePath)),qualifiedTiming:false,directory:f.dir}));
})().catch(e=>{console.error(e);process.exitCode=1;});
