"""Compile the Phase-0 class-group suffixes as one native dependency graph.

This module deliberately adds no mathematical glue.  Its wrappers preserve the
public ABI of each independently qualified stage while forcing their complete
source-transparent dependency closures through one compiler invocation.
"""

from sagejs.native import Float64Buffer, IntegerBuffer, Int64Buffer, native

from .class_group_smith_transform import pari_class_group_smith_transform
from .honesty_branch import pari_honesty_retry_ideal
from .nf_cxlog import pari_prepared_famat_cxlog
from .signed_prime_ideal_reduction import pari_cubic_idealred_candidate
from .unit_lattice_reduction import (
    pari_cleanarchunit_real_cubic,
    pari_unit_compose_rank_two,
    pari_unit_integer_lattice_rank_two,
    pari_unit_real_lattice_rank_two,
)
from .unit_reconstruction_cubic import pari_getfu_real_cubic


@native
def composed_smith_transform(
    original: IntegerBuffer,
    dimension: int,
    smith: IntegerBuffer,
    left: IntegerBuffer,
    left_inverse: IntegerBuffer,
    right: IntegerBuffer,
    ur: IntegerBuffer,
    y: IntegerBuffer,
    uir: IntegerBuffer,
    x: IntegerBuffer,
    m1: IntegerBuffer,
    m2: IntegerBuffer,
    invariants: IntegerBuffer,
    class_number: IntegerBuffer,
    column: IntegerBuffer,
    product: IntegerBuffer,
    augmented: IntegerBuffer,
    left_inverse_state: Int64Buffer,
    right_inverse_state: Int64Buffer,
    first_division_state: Int64Buffer,
    second_division_state: Int64Buffer,
    state: Int64Buffer,
) -> int:
    return pari_class_group_smith_transform(
        original,
        dimension,
        smith,
        left,
        left_inverse,
        right,
        ur,
        y,
        uir,
        x,
        m1,
        m2,
        invariants,
        class_number,
        column,
        product,
        augmented,
        left_inverse_state,
        right_inverse_state,
        first_division_state,
        second_division_state,
        state,
    )


@native
def composed_ideal_reduction(
    ideal: IntegerBuffer,
    multiplication_table: IntegerBuffer,
    candidate: IntegerBuffer,
    content: IntegerBuffer,
    kinds: IntegerBuffer,
    values: IntegerBuffer,
    exponents: IntegerBuffer,
    metadata: IntegerBuffer,
    multiplication_matrix: IntegerBuffer,
    product: IntegerBuffer,
    inverse_numerator: IntegerBuffer,
    inverse_denominator: IntegerBuffer,
    hnf_work: IntegerBuffer,
    hnf_triangular: IntegerBuffer,
    hnf_moduli: IntegerBuffer,
    output: IntegerBuffer,
) -> int:
    return pari_cubic_idealred_candidate(
        ideal,
        multiplication_table,
        candidate,
        content,
        kinds,
        values,
        exponents,
        metadata,
        multiplication_matrix,
        product,
        inverse_numerator,
        inverse_denominator,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        output,
    )


@native
def composed_honesty_retry(
    basis_table: IntegerBuffer,
    initial_ideal: IntegerBuffer,
    subfactor_generator: IntegerBuffer,
    n: int,
    prime: int,
    ramification: int,
    residue_degree: int,
    exponent: int,
    power_primitive: IntegerBuffer,
    power_temporary: IntegerBuffer,
    power_alpha: IntegerBuffer,
    power_metadata: IntegerBuffer,
    power_diagnostic: IntegerBuffer,
    alpha_table: IntegerBuffer,
    ideal_primitive: IntegerBuffer,
    product: IntegerBuffer,
    work: IntegerBuffer,
    triangular: IntegerBuffer,
    moduli: IntegerBuffer,
    output: IntegerBuffer,
) -> int:
    return pari_honesty_retry_ideal(
        basis_table,
        initial_ideal,
        subfactor_generator,
        n,
        prime,
        ramification,
        residue_degree,
        exponent,
        power_primitive,
        power_temporary,
        power_alpha,
        power_metadata,
        power_diagnostic,
        alpha_table,
        ideal_primitive,
        product,
        work,
        triangular,
        moduli,
        output,
    )


@native
def composed_famat_cxlog(
    matrix_m: IntegerBuffer,
    matrix_p: IntegerBuffer,
    matrix_e: IntegerBuffer,
    factor_offsets: IntegerBuffer,
    factor_kinds: IntegerBuffer,
    factor_numerators: IntegerBuffer,
    factor_denominators: IntegerBuffer,
    factor_coordinates: IntegerBuffer,
    factor_exponents: IntegerBuffer,
    generator_count: int,
    precision: int,
    ga: IntegerBuffer,
    state: IntegerBuffer,
    coordinates: IntegerBuffer,
    column: IntegerBuffer,
    accumulator: IntegerBuffer,
    log_cache: IntegerBuffer,
    pi_cache: IntegerBuffer,
    a: IntegerBuffer,
    b: IntegerBuffer,
    p: IntegerBuffer,
    q: IntegerBuffer,
    stack: IntegerBuffer,
) -> int:
    return pari_prepared_famat_cxlog(
        matrix_m,
        matrix_p,
        matrix_e,
        factor_offsets,
        factor_kinds,
        factor_numerators,
        factor_denominators,
        factor_coordinates,
        factor_exponents,
        generator_count,
        precision,
        ga,
        state,
        coordinates,
        column,
        accumulator,
        log_cache,
        pi_cache,
        a,
        b,
        p,
        q,
        stack,
    )


@native
def composed_getfu_real_cubic(
    clean_logs: IntegerBuffer,
    embedding_matrix: IntegerBuffer,
    multiplication_basis: IntegerBuffer,
    precision: int,
    matep: IntegerBuffer,
    lll_basis: IntegerBuffer,
    transform: IntegerBuffer,
    transformed_logs: IntegerBuffer,
    exponential_values: IntegerBuffer,
    solve_work: IntegerBuffer,
    solve_rhs: IntegerBuffer,
    solved: IntegerBuffer,
    rounded: IntegerBuffer,
    multiplication: IntegerBuffer,
    inverse: IntegerBuffer,
    candidate_units: IntegerBuffer,
    output_units: IntegerBuffer,
    output_logs: IntegerBuffer,
    state: Int64Buffer,
    pivots: Int64Buffer,
    mu: Float64Buffer,
    r: Float64Buffer,
    s: Float64Buffer,
    approximate: Float64Buffer,
    exponents: IntegerBuffer,
    float_gram: Float64Buffer,
    alpha: IntegerBuffer,
    column: IntegerBuffer,
    column_exponents: IntegerBuffer,
    normalized: Float64Buffer,
    temporary: Float64Buffer,
    exact_gram: IntegerBuffer,
    mu_exponents: IntegerBuffer,
    r_exponents: IntegerBuffer,
    s_exponents: IntegerBuffer,
    exp_cache: IntegerBuffer,
    exp_a: IntegerBuffer,
    exp_b: IntegerBuffer,
    exp_p: IntegerBuffer,
    exp_q: IntegerBuffer,
    exp_stack: IntegerBuffer,
) -> int:
    return pari_getfu_real_cubic(
        clean_logs,
        embedding_matrix,
        multiplication_basis,
        precision,
        matep,
        lll_basis,
        transform,
        transformed_logs,
        exponential_values,
        solve_work,
        solve_rhs,
        solved,
        rounded,
        multiplication,
        inverse,
        candidate_units,
        output_units,
        output_logs,
        state,
        pivots,
        mu,
        r,
        s,
        approximate,
        exponents,
        float_gram,
        alpha,
        column,
        column_exponents,
        normalized,
        temporary,
        exact_gram,
        mu_exponents,
        r_exponents,
        s_exponents,
        exp_cache,
        exp_a,
        exp_b,
        exp_p,
        exp_q,
        exp_stack,
    )


@native
def composed_unit_integer_lattice(
    original: IntegerBuffer,
    columns: int,
    u1: IntegerBuffer,
    state: IntegerBuffer,
    basis: IntegerBuffer,
    transform: IntegerBuffer,
    gram: IntegerBuffer,
    mu: Float64Buffer,
    mu_exponents: IntegerBuffer,
    r: Float64Buffer,
    r_exponents: IntegerBuffer,
    s: Float64Buffer,
    s_exponents: IntegerBuffer,
    approximate: Float64Buffer,
    float_gram: Float64Buffer,
    alpha: IntegerBuffer,
    column: IntegerBuffer,
    column_exponents: IntegerBuffer,
    normalized: Float64Buffer,
    temporary: Float64Buffer,
    dpe_float_scratch: Float64Buffer,
    integer_scratch: IntegerBuffer,
) -> int:
    return pari_unit_integer_lattice_rank_two(
        original,
        columns,
        u1,
        state,
        basis,
        transform,
        gram,
        mu,
        mu_exponents,
        r,
        r_exponents,
        s,
        s_exponents,
        approximate,
        float_gram,
        alpha,
        column,
        column_exponents,
        normalized,
        temporary,
        dpe_float_scratch,
        integer_scratch,
    )


@native
def composed_unit_real_lattice(
    matrix_triples: IntegerBuffer,
    rows: int,
    integers: IntegerBuffer,
    u2: IntegerBuffer,
    form: IntegerBuffer,
    basis: IntegerBuffer,
    transform: IntegerBuffer,
    gram: IntegerBuffer,
    mu: Float64Buffer,
    mu_exponents: IntegerBuffer,
    r: Float64Buffer,
    r_exponents: IntegerBuffer,
    s: Float64Buffer,
    s_exponents: IntegerBuffer,
    approximate: Float64Buffer,
    float_gram: Float64Buffer,
    alpha: IntegerBuffer,
    column: IntegerBuffer,
    column_exponents: IntegerBuffer,
    normalized: Float64Buffer,
    temporary: Float64Buffer,
    dpe_float_scratch: Float64Buffer,
    integer_scratch: IntegerBuffer,
    state: IntegerBuffer,
) -> int:
    return pari_unit_real_lattice_rank_two(
        matrix_triples,
        rows,
        integers,
        u2,
        form,
        basis,
        transform,
        gram,
        mu,
        mu_exponents,
        r,
        r_exponents,
        s,
        s_exponents,
        approximate,
        float_gram,
        alpha,
        column,
        column_exponents,
        normalized,
        temporary,
        dpe_float_scratch,
        integer_scratch,
        state,
    )


@native
def composed_unit_product(
    u1: IntegerBuffer,
    rows: int,
    u2: IntegerBuffer,
    output: IntegerBuffer,
) -> int:
    return pari_unit_compose_rank_two(u1, rows, u2, output)


@native
def composed_cleanarchunit(
    arch: Float64Buffer,
    columns: int,
    expected_regulator: float,
    clean: Float64Buffer,
    trace: Float64Buffer,
) -> int:
    return pari_cleanarchunit_real_cubic(
        arch, columns, expected_regulator, clean, trace
    )
