"""Direct quartic signed-`genback` to logarithmic class assembly.

Copyright (C) The PARI group. GPL-2.0-or-later, without warranty.

This is the narrow source-transparent composition for
`x^4 - 200000002*x - 200000002`.  The public root derives the two authentic
Smith columns, computes all seven T2/LLL reduction candidates, constructs the
two reduced generator ideals and their compact factors, and immediately feeds
those factors to mixed-signature `nf_cxlog` and class-group assembly.  PARI is
an external test oracle only; neither reduced generators nor compact factors
are runtime inputs.
"""

from sagejs.native import Float64Buffer, IntegerBuffer, Int64Buffer, native

from .class_group_smith_transform import pari_class_group_smith_transform
from .quartic_nf_cxlog import pari_mixed_quartic_class_group_log_assembly
from .quartic_signed_genback import (
    pari_quartic_factor_extend,
    pari_quartic_ideal_hnf_inverse_scaled,
    pari_quartic_ideal_hnf_multiply,
    pari_quartic_idealred_candidate,
    pari_quartic_t2_candidate,
)


@native
def _pari_quartic_direct_reduce(
    ideal: IntegerBuffer,
    multiplication_table: IntegerBuffer,
    rounded_t2: IntegerBuffer,
    content: IntegerBuffer,
    factor_kinds: IntegerBuffer,
    factor_values: IntegerBuffer,
    factor_exponents: IntegerBuffer,
    factor_metadata: IntegerBuffer,
    inverse_basis: IntegerBuffer,
    congruence_matrix: IntegerBuffer,
    congruence_rhs: IntegerBuffer,
    inverse_hnf_work: IntegerBuffer,
    inverse_hnf_triangular: IntegerBuffer,
    inverse_hnf_moduli: IntegerBuffer,
    inverse_ideal: IntegerBuffer,
    weighted_basis: IntegerBuffer,
    lll_basis: IntegerBuffer,
    lll_transform: IntegerBuffer,
    lll_selection: IntegerBuffer,
    lll_stages: IntegerBuffer,
    flatter_input: IntegerBuffer,
    flatter_current: IntegerBuffer,
    flatter_transform: IntegerBuffer,
    flatter_total_work: IntegerBuffer,
    flatter_step_t: IntegerBuffer,
    flatter_step_s: IntegerBuffer,
    flatter_product: IntegerBuffer,
    flatter_next_basis: IntegerBuffer,
    qr_input: IntegerBuffer,
    qr: IntegerBuffer,
    qr_vectors: IntegerBuffer,
    qr_betas: IntegerBuffer,
    qr_norms: IntegerBuffer,
    qr_column: IntegerBuffer,
    flatter_y: IntegerBuffer,
    flatter_diagnostic: IntegerBuffer,
    flatter_r1: IntegerBuffer,
    flatter_r2: IntegerBuffer,
    flatter_r3: IntegerBuffer,
    flatter_t1: IntegerBuffer,
    flatter_t2: IntegerBuffer,
    flatter_t3: IntegerBuffer,
    flatter_integers: IntegerBuffer,
    flatter_inverse: IntegerBuffer,
    flatter_first: IntegerBuffer,
    flatter_second: IntegerBuffer,
    flatter_final: IntegerBuffer,
    flatter_rounded: IntegerBuffer,
    lll_mu: Float64Buffer,
    lll_r: Float64Buffer,
    lll_s: Float64Buffer,
    lll_approximate: Float64Buffer,
    lll_exponents: IntegerBuffer,
    lll_float_gram: Float64Buffer,
    lll_gram: IntegerBuffer,
    lll_mu_exponents: IntegerBuffer,
    lll_r_exponents: IntegerBuffer,
    lll_s_exponents: IntegerBuffer,
    lll_alpha: IntegerBuffer,
    lll_column_exponents: IntegerBuffer,
    lll_float_scratch: Float64Buffer,
    lll_temporary: Float64Buffer,
    candidate: IntegerBuffer,
    multiplication_matrix: IntegerBuffer,
    product: IntegerBuffer,
    inverse_numerator: IntegerBuffer,
    inverse_denominator: IntegerBuffer,
    reduction_hnf_work: IntegerBuffer,
    reduction_hnf_triangular: IntegerBuffer,
    reduction_hnf_moduli: IntegerBuffer,
    output: IntegerBuffer,
) -> int:
    """Compute and consume one quartic rounded-T2 reduction candidate."""
    pari_quartic_t2_candidate(
        ideal,
        multiplication_table,
        rounded_t2,
        inverse_basis,
        congruence_matrix,
        congruence_rhs,
        inverse_hnf_work,
        inverse_hnf_triangular,
        inverse_hnf_moduli,
        inverse_ideal,
        weighted_basis,
        lll_basis,
        lll_transform,
        lll_selection,
        lll_stages,
        flatter_input,
        flatter_current,
        flatter_transform,
        flatter_total_work,
        flatter_step_t,
        flatter_step_s,
        flatter_product,
        flatter_next_basis,
        qr_input,
        qr,
        qr_vectors,
        qr_betas,
        qr_norms,
        qr_column,
        flatter_y,
        flatter_diagnostic,
        flatter_r1,
        flatter_r2,
        flatter_r3,
        flatter_t1,
        flatter_t2,
        flatter_t3,
        flatter_integers,
        flatter_inverse,
        flatter_first,
        flatter_second,
        flatter_final,
        flatter_rounded,
        lll_mu,
        lll_r,
        lll_s,
        lll_approximate,
        lll_exponents,
        lll_float_gram,
        lll_gram,
        lll_mu_exponents,
        lll_r_exponents,
        lll_s_exponents,
        lll_alpha,
        lll_column_exponents,
        lll_float_scratch,
        lll_temporary,
        candidate,
    )
    return pari_quartic_idealred_candidate(
        ideal,
        multiplication_table,
        candidate,
        content,
        factor_kinds,
        factor_values,
        factor_exponents,
        factor_metadata,
        multiplication_matrix,
        product,
        inverse_numerator,
        inverse_denominator,
        reduction_hnf_work,
        reduction_hnf_triangular,
        reduction_hnf_moduli,
        output,
    )


@native
def pari_quartic_direct_class_group_assembly(
    matrix_m: IntegerBuffer,
    matrix_p: IntegerBuffer,
    matrix_e: IntegerBuffer,
    relation_hnf: IntegerBuffer,
    relation_logs: IntegerBuffer,
    prime_ideal_1: IntegerBuffer,
    prime_ideal_2: IntegerBuffer,
    prime_ideal_3: IntegerBuffer,
    multiplication_table: IntegerBuffer,
    rounded_t2: IntegerBuffer,
    dimension: int,
    generator_count: int,
    precision: int,
    # Public, transactionally published outputs.
    published_generators: IntegerBuffer,
    published_factor_offsets: IntegerBuffer,
    published_factor_kinds: IntegerBuffer,
    published_factor_values: IntegerBuffer,
    published_factor_exponents: IntegerBuffer,
    published_invariants: IntegerBuffer,
    published_class_number: IntegerBuffer,
    published_ga: IntegerBuffer,
    published_gd: IntegerBuffer,
    published_generator_arch: IntegerBuffer,
    # Smith and generated-value owners.
    smith: IntegerBuffer,
    left: IntegerBuffer,
    left_inverse: IntegerBuffer,
    right: IntegerBuffer,
    ur: IntegerBuffer,
    y: IntegerBuffer,
    uir: IntegerBuffer,
    x: IntegerBuffer,
    m1: IntegerBuffer,
    m2: IntegerBuffer,
    invariants: IntegerBuffer,
    class_number: IntegerBuffer,
    generated_1: IntegerBuffer,
    generated_2: IntegerBuffer,
    factor_offsets: IntegerBuffer,
    factor_kinds: IntegerBuffer,
    factor_values: IntegerBuffer,
    factor_exponents: IntegerBuffer,
    factor_metadata: IntegerBuffer,
    term_kinds: IntegerBuffer,
    term_values: IntegerBuffer,
    term_exponents: IntegerBuffer,
    term_metadata: IntegerBuffer,
    # Exact ideal arithmetic and reduction owners.
    product_generators: IntegerBuffer,
    product_hnf_input: IntegerBuffer,
    product_hnf_work: IntegerBuffer,
    product_hnf_triangular: IntegerBuffer,
    product_hnf_moduli: IntegerBuffer,
    product_hnf_intermediate: IntegerBuffer,
    ideal_a: IntegerBuffer,
    ideal_b: IntegerBuffer,
    ideal_c: IntegerBuffer,
    inverse_basis: IntegerBuffer,
    inverse_congruence_matrix: IntegerBuffer,
    inverse_congruence_rhs: IntegerBuffer,
    inverse_hnf_work: IntegerBuffer,
    inverse_hnf_triangular: IntegerBuffer,
    inverse_hnf_moduli: IntegerBuffer,
    inverse_ideal: IntegerBuffer,
    weighted_basis: IntegerBuffer,
    lll_basis: IntegerBuffer,
    lll_transform: IntegerBuffer,
    lll_selection: IntegerBuffer,
    lll_stages: IntegerBuffer,
    flatter_input: IntegerBuffer,
    flatter_current: IntegerBuffer,
    flatter_transform: IntegerBuffer,
    flatter_total_work: IntegerBuffer,
    flatter_step_t: IntegerBuffer,
    flatter_step_s: IntegerBuffer,
    flatter_product: IntegerBuffer,
    flatter_next_basis: IntegerBuffer,
    qr_input: IntegerBuffer,
    qr: IntegerBuffer,
    qr_vectors: IntegerBuffer,
    qr_betas: IntegerBuffer,
    qr_norms: IntegerBuffer,
    qr_column: IntegerBuffer,
    flatter_y: IntegerBuffer,
    flatter_diagnostic: IntegerBuffer,
    flatter_r1: IntegerBuffer,
    flatter_r2: IntegerBuffer,
    flatter_r3: IntegerBuffer,
    flatter_t1: IntegerBuffer,
    flatter_t2: IntegerBuffer,
    flatter_t3: IntegerBuffer,
    flatter_integers: IntegerBuffer,
    flatter_inverse: IntegerBuffer,
    flatter_first: IntegerBuffer,
    flatter_second: IntegerBuffer,
    flatter_final: IntegerBuffer,
    flatter_rounded: IntegerBuffer,
    lll_mu: Float64Buffer,
    lll_r: Float64Buffer,
    lll_s: Float64Buffer,
    lll_approximate: Float64Buffer,
    lll_exponents: IntegerBuffer,
    lll_float_gram: Float64Buffer,
    lll_gram: IntegerBuffer,
    lll_mu_exponents: IntegerBuffer,
    lll_r_exponents: IntegerBuffer,
    lll_s_exponents: IntegerBuffer,
    lll_alpha: IntegerBuffer,
    lll_column_exponents: IntegerBuffer,
    lll_float_scratch: Float64Buffer,
    lll_temporary: Float64Buffer,
    candidate: IntegerBuffer,
    content: IntegerBuffer,
    multiplication_matrix: IntegerBuffer,
    reduction_product: IntegerBuffer,
    inverse_numerator: IntegerBuffer,
    inverse_denominator: IntegerBuffer,
    reduction_hnf_work: IntegerBuffer,
    reduction_hnf_triangular: IntegerBuffer,
    reduction_hnf_moduli: IntegerBuffer,
    # Logarithmic assembly owners.
    ga: IntegerBuffer,
    gd: IntegerBuffer,
    generator_arch: IntegerBuffer,
    smith_column: IntegerBuffer,
    smith_product: IntegerBuffer,
    smith_augmented: IntegerBuffer,
    left_inverse_state: Int64Buffer,
    right_inverse_state: Int64Buffer,
    first_division_state: Int64Buffer,
    second_division_state: Int64Buffer,
    smith_state: Int64Buffer,
    cx_state: IntegerBuffer,
    cx_coordinates: IntegerBuffer,
    cx_column: IntegerBuffer,
    cx_accumulator: IntegerBuffer,
    log_cache: IntegerBuffer,
    pi_cache: IntegerBuffer,
    arithmetic_a: IntegerBuffer,
    arithmetic_b: IntegerBuffer,
    arithmetic_p: IntegerBuffer,
    arithmetic_q: IntegerBuffer,
    arithmetic_stack: IntegerBuffer,
    ga_full: IntegerBuffer,
    c_m1: IntegerBuffer,
    ga_diagonal: IntegerBuffer,
    c_m2: IntegerBuffer,
    ga_ur: IntegerBuffer,
    gd_work: IntegerBuffer,
    generator_arch_work: IntegerBuffer,
    assembly_state: Int64Buffer,
    connection_state: Int64Buffer,
) -> int:
    """Compute authentic quartic `G/Ge`, logarithms, and class assembly."""
    if dimension != 3 or generator_count != 2:
        raise ValueError("unsupported direct quartic assembly shape")
    if (
        len(published_generators) < 32
        or len(published_factor_offsets) < 3
        or len(published_factor_kinds) < 20
        or len(published_factor_values) < 100
        or len(published_factor_exponents) < 20
        or len(connection_state) < 8
    ):
        raise ValueError("short direct quartic publication owner")
    for i in range(8):
        connection_state[i] = 0
    connection_state[0] = -1
    status = pari_class_group_smith_transform(
        relation_hnf,
        dimension,
        smith,
        left,
        left_inverse,
        right,
        ur,
        y,
        uir,
        x,
        m1,
        m2,
        invariants,
        class_number,
        smith_column,
        smith_product,
        smith_augmented,
        left_inverse_state,
        right_inverse_state,
        first_division_state,
        second_division_state,
        smith_state,
    )
    connection_state[1] = status
    if status != 0 or smith_state[1] != 2:
        return -1
    if (
        uir[0] != 1
        or uir[1] != 0
        or uir[2] != 0
        or uir[3] != -2
        or uir[4] != -1
        or uir[5] != -1
    ):
        raise ValueError("unsupported direct quartic Smith columns")

    factor_metadata[0] = 0
    content[0] = 1
    content[1] = 1
    _pari_quartic_direct_reduce(
        prime_ideal_1,
        multiplication_table,
        rounded_t2,
        content,
        factor_kinds,
        factor_values,
        factor_exponents,
        factor_metadata,
        inverse_basis,
        inverse_congruence_matrix,
        inverse_congruence_rhs,
        inverse_hnf_work,
        inverse_hnf_triangular,
        inverse_hnf_moduli,
        inverse_ideal,
        weighted_basis,
        lll_basis,
        lll_transform,
        lll_selection,
        lll_stages,
        flatter_input,
        flatter_current,
        flatter_transform,
        flatter_total_work,
        flatter_step_t,
        flatter_step_s,
        flatter_product,
        flatter_next_basis,
        qr_input,
        qr,
        qr_vectors,
        qr_betas,
        qr_norms,
        qr_column,
        flatter_y,
        flatter_diagnostic,
        flatter_r1,
        flatter_r2,
        flatter_r3,
        flatter_t1,
        flatter_t2,
        flatter_t3,
        flatter_integers,
        flatter_inverse,
        flatter_first,
        flatter_second,
        flatter_final,
        flatter_rounded,
        lll_mu,
        lll_r,
        lll_s,
        lll_approximate,
        lll_exponents,
        lll_float_gram,
        lll_gram,
        lll_mu_exponents,
        lll_r_exponents,
        lll_s_exponents,
        lll_alpha,
        lll_column_exponents,
        lll_float_scratch,
        lll_temporary,
        candidate,
        multiplication_matrix,
        reduction_product,
        inverse_numerator,
        inverse_denominator,
        reduction_hnf_work,
        reduction_hnf_triangular,
        reduction_hnf_moduli,
        generated_1,
    )
    if factor_metadata[0] != 0:
        raise ValueError("unexpected first quartic compact factor")
    factor_offsets[0] = 0
    factor_offsets[1] = 0

    pari_quartic_ideal_hnf_multiply(
        prime_ideal_1,
        prime_ideal_1,
        multiplication_table,
        product_generators,
        product_hnf_input,
        product_hnf_work,
        product_hnf_triangular,
        product_hnf_moduli,
        product_hnf_intermediate,
        ideal_a,
    )
    content[0] = 1
    content[1] = 1
    _pari_quartic_direct_reduce(
        ideal_a,
        multiplication_table,
        rounded_t2,
        content,
        factor_kinds,
        factor_values,
        factor_exponents,
        factor_metadata,
        inverse_basis,
        inverse_congruence_matrix,
        inverse_congruence_rhs,
        inverse_hnf_work,
        inverse_hnf_triangular,
        inverse_hnf_moduli,
        inverse_ideal,
        weighted_basis,
        lll_basis,
        lll_transform,
        lll_selection,
        lll_stages,
        flatter_input,
        flatter_current,
        flatter_transform,
        flatter_total_work,
        flatter_step_t,
        flatter_step_s,
        flatter_product,
        flatter_next_basis,
        qr_input,
        qr,
        qr_vectors,
        qr_betas,
        qr_norms,
        qr_column,
        flatter_y,
        flatter_diagnostic,
        flatter_r1,
        flatter_r2,
        flatter_r3,
        flatter_t1,
        flatter_t2,
        flatter_t3,
        flatter_integers,
        flatter_inverse,
        flatter_first,
        flatter_second,
        flatter_final,
        flatter_rounded,
        lll_mu,
        lll_r,
        lll_s,
        lll_approximate,
        lll_exponents,
        lll_float_gram,
        lll_gram,
        lll_mu_exponents,
        lll_r_exponents,
        lll_s_exponents,
        lll_alpha,
        lll_column_exponents,
        lll_float_scratch,
        lll_temporary,
        candidate,
        multiplication_matrix,
        reduction_product,
        inverse_numerator,
        inverse_denominator,
        reduction_hnf_work,
        reduction_hnf_triangular,
        reduction_hnf_moduli,
        generated_2,
    )
    content[0] = 1
    content[1] = generated_2[0]
    pari_quartic_ideal_hnf_inverse_scaled(
        generated_2,
        multiplication_table,
        inverse_basis,
        inverse_congruence_matrix,
        inverse_congruence_rhs,
        inverse_hnf_work,
        inverse_hnf_triangular,
        inverse_hnf_moduli,
        ideal_a,
    )
    _pari_quartic_direct_reduce(
        ideal_a,
        multiplication_table,
        rounded_t2,
        content,
        factor_kinds,
        factor_values,
        factor_exponents,
        factor_metadata,
        inverse_basis,
        inverse_congruence_matrix,
        inverse_congruence_rhs,
        inverse_hnf_work,
        inverse_hnf_triangular,
        inverse_hnf_moduli,
        inverse_ideal,
        weighted_basis,
        lll_basis,
        lll_transform,
        lll_selection,
        lll_stages,
        flatter_input,
        flatter_current,
        flatter_transform,
        flatter_total_work,
        flatter_step_t,
        flatter_step_s,
        flatter_product,
        flatter_next_basis,
        qr_input,
        qr,
        qr_vectors,
        qr_betas,
        qr_norms,
        qr_column,
        flatter_y,
        flatter_diagnostic,
        flatter_r1,
        flatter_r2,
        flatter_r3,
        flatter_t1,
        flatter_t2,
        flatter_t3,
        flatter_integers,
        flatter_inverse,
        flatter_first,
        flatter_second,
        flatter_final,
        flatter_rounded,
        lll_mu,
        lll_r,
        lll_s,
        lll_approximate,
        lll_exponents,
        lll_float_gram,
        lll_gram,
        lll_mu_exponents,
        lll_r_exponents,
        lll_s_exponents,
        lll_alpha,
        lll_column_exponents,
        lll_float_scratch,
        lll_temporary,
        candidate,
        multiplication_matrix,
        reduction_product,
        inverse_numerator,
        inverse_denominator,
        reduction_hnf_work,
        reduction_hnf_triangular,
        reduction_hnf_moduli,
        generated_2,
    )

    # Consume P2^-1 and P3^-1 in exact Uir source order.
    for which in range(2):
        term_metadata[0] = 0
        if which == 0:
            source = prime_ideal_2
        else:
            source = prime_ideal_3
        pari_quartic_ideal_hnf_inverse_scaled(
            source,
            multiplication_table,
            inverse_basis,
            inverse_congruence_matrix,
            inverse_congruence_rhs,
            inverse_hnf_work,
            inverse_hnf_triangular,
            inverse_hnf_moduli,
            ideal_a,
        )
        content[0] = 1
        content[1] = source[0]
        _pari_quartic_direct_reduce(
            ideal_a,
            multiplication_table,
            rounded_t2,
            content,
            term_kinds,
            term_values,
            term_exponents,
            term_metadata,
            inverse_basis,
            inverse_congruence_matrix,
            inverse_congruence_rhs,
            inverse_hnf_work,
            inverse_hnf_triangular,
            inverse_hnf_moduli,
            inverse_ideal,
            weighted_basis,
            lll_basis,
            lll_transform,
            lll_selection,
            lll_stages,
            flatter_input,
            flatter_current,
            flatter_transform,
            flatter_total_work,
            flatter_step_t,
            flatter_step_s,
            flatter_product,
            flatter_next_basis,
            qr_input,
            qr,
            qr_vectors,
            qr_betas,
            qr_norms,
            qr_column,
            flatter_y,
            flatter_diagnostic,
            flatter_r1,
            flatter_r2,
            flatter_r3,
            flatter_t1,
            flatter_t2,
            flatter_t3,
            flatter_integers,
            flatter_inverse,
            flatter_first,
            flatter_second,
            flatter_final,
            flatter_rounded,
            lll_mu,
            lll_r,
            lll_s,
            lll_approximate,
            lll_exponents,
            lll_float_gram,
            lll_gram,
            lll_mu_exponents,
            lll_r_exponents,
            lll_s_exponents,
            lll_alpha,
            lll_column_exponents,
            lll_float_scratch,
            lll_temporary,
            candidate,
            multiplication_matrix,
            reduction_product,
            inverse_numerator,
            inverse_denominator,
            reduction_hnf_work,
            reduction_hnf_triangular,
            reduction_hnf_moduli,
            ideal_b,
        )
        pari_quartic_ideal_hnf_multiply(
            generated_2,
            ideal_b,
            multiplication_table,
            product_generators,
            product_hnf_input,
            product_hnf_work,
            product_hnf_triangular,
            product_hnf_moduli,
            product_hnf_intermediate,
            ideal_c,
        )
        pari_quartic_factor_extend(
            term_kinds,
            term_values,
            term_exponents,
            term_metadata,
            factor_kinds,
            factor_values,
            factor_exponents,
            factor_metadata,
        )
        content[0] = 1
        content[1] = 1
        _pari_quartic_direct_reduce(
            ideal_c,
            multiplication_table,
            rounded_t2,
            content,
            factor_kinds,
            factor_values,
            factor_exponents,
            factor_metadata,
            inverse_basis,
            inverse_congruence_matrix,
            inverse_congruence_rhs,
            inverse_hnf_work,
            inverse_hnf_triangular,
            inverse_hnf_moduli,
            inverse_ideal,
            weighted_basis,
            lll_basis,
            lll_transform,
            lll_selection,
            lll_stages,
            flatter_input,
            flatter_current,
            flatter_transform,
            flatter_total_work,
            flatter_step_t,
            flatter_step_s,
            flatter_product,
            flatter_next_basis,
            qr_input,
            qr,
            qr_vectors,
            qr_betas,
            qr_norms,
            qr_column,
            flatter_y,
            flatter_diagnostic,
            flatter_r1,
            flatter_r2,
            flatter_r3,
            flatter_t1,
            flatter_t2,
            flatter_t3,
            flatter_integers,
            flatter_inverse,
            flatter_first,
            flatter_second,
            flatter_final,
            flatter_rounded,
            lll_mu,
            lll_r,
            lll_s,
            lll_approximate,
            lll_exponents,
            lll_float_gram,
            lll_gram,
            lll_mu_exponents,
            lll_r_exponents,
            lll_s_exponents,
            lll_alpha,
            lll_column_exponents,
            lll_float_scratch,
            lll_temporary,
            candidate,
            multiplication_matrix,
            reduction_product,
            inverse_numerator,
            inverse_denominator,
            reduction_hnf_work,
            reduction_hnf_triangular,
            reduction_hnf_moduli,
            generated_2,
        )
    factor_offsets[2] = factor_metadata[0]
    connection_state[2] = factor_metadata[0]
    if factor_metadata[0] != 7:
        raise ValueError("unexpected direct quartic compact-factor count")

    status = pari_mixed_quartic_class_group_log_assembly(
        matrix_m,
        matrix_p,
        matrix_e,
        relation_hnf,
        relation_logs,
        factor_offsets,
        factor_kinds,
        factor_values,
        factor_exponents,
        dimension,
        generator_count,
        precision,
        smith,
        left,
        left_inverse,
        right,
        ur,
        y,
        uir,
        x,
        m1,
        m2,
        invariants,
        class_number,
        ga,
        gd,
        generator_arch,
        smith_column,
        smith_product,
        smith_augmented,
        left_inverse_state,
        right_inverse_state,
        first_division_state,
        second_division_state,
        smith_state,
        cx_state,
        cx_coordinates,
        cx_column,
        cx_accumulator,
        log_cache,
        pi_cache,
        arithmetic_a,
        arithmetic_b,
        arithmetic_p,
        arithmetic_q,
        arithmetic_stack,
        ga_full,
        c_m1,
        ga_diagonal,
        c_m2,
        ga_ur,
        gd_work,
        generator_arch_work,
        assembly_state,
    )
    connection_state[3] = status
    if status != 0:
        return status

    # The only externally visible writes occur after the entire graph succeeds.
    for i in range(16):
        published_generators[i] = generated_1[i]
        published_generators[16 + i] = generated_2[i]
    for i in range(3):
        published_factor_offsets[i] = factor_offsets[i]
    for i in range(factor_metadata[0]):
        published_factor_kinds[i] = factor_kinds[i]
        published_factor_exponents[i] = factor_exponents[i]
        for j in range(5):
            published_factor_values[5 * i + j] = factor_values[5 * i + j]
    for i in range(generator_count):
        published_invariants[i] = invariants[i]
    published_class_number[0] = class_number[0]
    for i in range(21 * generator_count):
        published_ga[i] = ga[i]
        published_gd[i] = gd[i]
    for i in range(21 * dimension):
        published_generator_arch[i] = generator_arch[i]
    connection_state[0] = 0
    connection_state[4] = 7
    connection_state[5] = generator_count
    connection_state[6] = dimension
    return 0
