"""Exact signed-generator and principal-order replay for row 14.

This is the missing bridge between the retained Smith quotient
``(-2, -1, -1)`` and the second published class-generator ideal.  It consumes
only the immutable row-14 result owners and prepared-field metadata.  In
particular, no published reduction candidate or PARI ``G``/``Ge`` value is an
input.

The output principal witness is deliberately factored.  Expanding the 806 raw
principal generators with 62-bit exponents would be both unnecessary and
enormous.  Instead we replay every raw principal ideal equation, reconstruct
the signed ``genback`` reduction and its principal scaling, and prove the
following exact ideal identity for each generator::

    (G * Ge)^order = product(P_i, order * quotient_i)
                    = product((alpha_j), relation_coefficient_j)

Consequently ``G**order`` is generated by the stated raw-principal product
times ``Ge**(-order)``.  Every equality above is checked with exact HNF ideal
arithmetic; no floating-point comparison is used.
"""

from __future__ import annotations

import importlib
import hashlib
import json
import math
from collections.abc import Mapping, Sequence
from typing import Any


class Row14SignedGeneratorWitnessFailure(ValueError):
    """The row-14 signed generator or its principal witness failed replay."""


_ROWS = 799
_RELATIONS = 806
_DEGREE = 4
_IDEAL_SIZE = 16
_IDENTITY = (1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1)
_FIELD_ID = (
    "generated-sha256-e1d4643ab62bde9546d63340545e5302c2cef517222d569e634fb5e2093f6413"
)
_PARI_SOURCE_SHA256 = "02651d99c391007d384b3fadbc20abc6916b77036f9e496c99e9ce8688ca4b53"
_METADATA_RECEIPT_SHA256 = (
    "c6c58eeeb1367fd6cfc7d8313f88076aa471bbf1882e2b24da5d8a28af4b1c1c"
)
_METADATA_CORE_SHA256 = (
    "ec691ce6d73051d78053db99611ff238f8db1c3a5f9a969aed33a523caee5d80"
)
_METADATA_CANONICAL_SHA256 = (
    "08ed0e2f5202fbe049c653603b2a0f9f31ac9db621ffa477451e74539aa28d9b"
)


def _digest(value: Any, *, sort_keys: bool = True) -> str:
    encoded = json.dumps(value, separators=(",", ":"), sort_keys=sort_keys).encode()
    return hashlib.sha256(encoded).hexdigest()


def _authenticate(
    correspondence: Mapping[str, Any], metadata_receipt: Mapping[str, Any]
) -> tuple[Mapping[str, Any], Mapping[str, Any]]:
    if (
        correspondence.get("schema")
        != "sagejs.pari-class-group/class-unit-correspondence-envelope-v1"
        or correspondence.get("payloadSha256") != _digest(correspondence.get("payload"))
    ):
        raise Row14SignedGeneratorWitnessFailure(
            "correspondence envelope authentication failed"
        )
    payload = correspondence.get("payload")
    if not isinstance(payload, Mapping):
        raise Row14SignedGeneratorWitnessFailure("correspondence payload is absent")
    field = payload.get("field")
    source = payload.get("source")
    if (
        payload.get("schema")
        != "sagejs.pari-class-group/class-unit-correspondence-result-v1"
        or not isinstance(field, Mapping)
        or field.get("id") != _FIELD_ID
        or field.get("definingPolynomialAscending")
        != ["-200000002", "-200000002", "0", "0", "1"]
        or not isinstance(source, Mapping)
        or source.get("pariVersion") != "2.17.4"
        or source.get("pariSourceSha256") != _PARI_SOURCE_SHA256
    ):
        raise Row14SignedGeneratorWitnessFailure(
            "correspondence source authority changed"
        )

    metadata = metadata_receipt.get("metadata")
    if (
        not isinstance(metadata, Mapping)
        or metadata_receipt.get("metadataSha256") != _METADATA_RECEIPT_SHA256
        or metadata_receipt.get("coreSha256") != _METADATA_CORE_SHA256
        or _digest(metadata, sort_keys=False) != _METADATA_CANONICAL_SHA256
        or metadata.get("schema")
        != "sagejs.pari-class-group/row14-connected-factor-metadata-v1"
        or metadata.get("authority")
        != {
            "capsuleSha256": (
                "33d2606a151ecf0ba5a73c247ecf3f219ff84a2341048ebbbe374ecd9c7939b1"
            ),
            "preparedAuthoritySha256": (
                "6c8ac1e7e6a47a486de92cd180f9524a1be132d8fe1f7ccbd822166e77d4da92"
            ),
            "tauAuthority": "authenticated-initial-factor-descriptor",
        }
    ):
        raise Row14SignedGeneratorWitnessFailure(
            "factor-metadata receipt authentication failed"
        )
    return payload, metadata


def _integers(value: Any, length: int, label: str) -> list[int]:
    if not isinstance(value, list) or len(value) != length:
        raise Row14SignedGeneratorWitnessFailure(label + " changed shape")
    answer: list[int] = []
    for entry in value:
        if isinstance(entry, bool) or not isinstance(entry, (str, int)):
            raise Row14SignedGeneratorWitnessFailure(label + " is not integer data")
        number = int(entry)
        if str(number) != str(entry):
            raise Row14SignedGeneratorWitnessFailure(label + " is not canonical")
        answer.append(number)
    return answer


def _owners(payload: Mapping[str, Any]) -> dict[str, list[int]]:
    storage = payload.get("storage")
    if not isinstance(storage, list):
        raise Row14SignedGeneratorWitnessFailure("storage owners are absent")
    answer: dict[str, list[int]] = {}
    for owner in storage:
        if not isinstance(owner, Mapping) or not isinstance(owner.get("name"), str):
            raise Row14SignedGeneratorWitnessFailure("a storage owner is malformed")
        name = owner["name"]
        if name in answer:
            raise Row14SignedGeneratorWitnessFailure("duplicate owner " + name)
        entries = owner.get("entries")
        if not isinstance(entries, list):
            raise Row14SignedGeneratorWitnessFailure(name + " has no entries")
        answer[name] = _integers(entries, len(entries), name)
    return answer


def _workspace() -> list[list[int] | list[float]]:
    def z(count: int) -> list[int]:
        return [0] * count

    def f(count: int) -> list[float]:
        return [0.0] * count

    return [
        z(16),
        z(4),
        z(4),
        z(52),
        z(20),
        z(4),
        z(16),
        z(16),
        z(16),
        z(16),
        z(5),
        z(4),
        z(16),
        z(16),
        z(16),
        z(16),
        z(16),
        z(16),
        z(16),
        z(16),
        z(48),
        z(48),
        z(48),
        z(12),
        z(12),
        z(12),
        z(4),
        z(7),
        z(12),
        z(12),
        z(12),
        z(4),
        z(4),
        z(4),
        z(4),
        z(12),
        z(12),
        z(12),
        z(12),
        z(4),
        f(16),
        f(16),
        f(4),
        f(16),
        z(4),
        f(16),
        z(16),
        z(16),
        z(16),
        z(4),
        z(4),
        z(4),
        f(4),
        f(1),
        z(4),
    ]


def _transpose4(matrix: Sequence[int]) -> tuple[int, ...]:
    return tuple(matrix[(index % 4) * 4 + index // 4] for index in range(16))


def _factor_store() -> list[list[int]]:
    return [[0] * 20, [0] * 100, [0] * 20, [0]]


def _unpack_factors(store: Sequence[Sequence[int]]) -> list[dict[str, Any]]:
    count = store[3][0]
    return [
        {
            "kind": store[0][index],
            "values": list(store[1][5 * index : 5 * index + 4]),
            "denominator": store[1][5 * index + 4],
            "exponent": store[2][index],
        }
        for index in range(count)
    ]


def _signed_genback(
    primes: Sequence[Sequence[int]], table: list[int], rounded: list[int]
) -> tuple[list[tuple[int, ...]], list[list[dict[str, Any]]], list[list[int]]]:
    quartic = importlib.import_module(
        "bench.pari-class-group-port.quartic_signed_genback"
    )

    candidates: list[list[int]] = []

    def candidate(ideal: Sequence[int]) -> list[int]:
        work = _workspace()
        quartic.pari_quartic_t2_candidate(list(ideal), table, rounded, *work)
        value = list(work[-1])
        candidates.append(value)
        return value

    def multiply(left: Sequence[int], right: Sequence[int]) -> list[int]:
        output = [0] * 16
        quartic.pari_quartic_ideal_hnf_multiply(
            list(left),
            list(right),
            table,
            [0] * 64,
            [0] * 32,
            [0] * 52,
            [0] * 20,
            [0] * 4,
            [0] * 16,
            output,
        )
        return output

    def inverse(ideal: Sequence[int]) -> list[int]:
        output = [0] * 16
        quartic.pari_quartic_ideal_hnf_inverse_scaled(
            list(ideal),
            table,
            [0] * 16,
            [0] * 4,
            [0] * 4,
            [0] * 52,
            [0] * 20,
            [0] * 4,
            output,
        )
        return output

    def reduce(
        ideal: Sequence[int], content: list[int], factors: list[list[int]]
    ) -> list[int]:
        output = [0] * 16
        quartic.pari_quartic_idealred_candidate(
            list(ideal),
            table,
            candidate(ideal),
            content,
            *factors,
            [0] * 16,
            [0] * 16,
            [0] * 4,
            [0],
            [0] * 52,
            [0] * 20,
            [0] * 4,
            output,
        )
        return output

    first_factors = _factor_store()
    first = reduce(primes[0], [1, 1], first_factors)

    second_factors = _factor_store()
    second = reduce(multiply(primes[0], primes[0]), [1, 1], second_factors)
    denominator = second[0]
    for index in range(second_factors[3][0]):
        second_factors[2][index] = -second_factors[2][index]
    second = reduce(inverse(second), [1, denominator], second_factors)
    for prime in primes[1:]:
        factors = _factor_store()
        term = reduce(inverse(prime), [1, prime[0]], factors)
        second = multiply(second, term)
        quartic.pari_quartic_factor_extend(*factors, *second_factors)
        second = reduce(second, [1, 1], second_factors)

    return (
        [tuple(first), tuple(second)],
        [_unpack_factors(first_factors), _unpack_factors(second_factors)],
        candidates,
    )


FractionalIdeal = tuple[tuple[int, ...], int]


def _normalize(ideal: Sequence[int], denominator: int) -> FractionalIdeal:
    if denominator <= 0:
        raise Row14SignedGeneratorWitnessFailure("invalid ideal denominator")
    common = denominator
    for value in ideal:
        common = math.gcd(common, abs(value))
    return tuple(value // common for value in ideal), denominator // common


def _fractional_arithmetic(table: list[int]):
    quartic = importlib.import_module(
        "bench.pari-class-group-port.quartic_signed_genback"
    )
    replay = importlib.import_module(
        "bench.pari-class-group-port.field3_relation_replay_map"
    )

    def multiply(left: FractionalIdeal, right: FractionalIdeal) -> FractionalIdeal:
        return _normalize(
            replay._quartic_product(left[0], right[0], table),
            left[1] * right[1],
        )

    def inverse(value: FractionalIdeal) -> FractionalIdeal:
        ideal, denominator = value
        scaled = [0] * 16
        quartic.pari_quartic_ideal_hnf_inverse_scaled(
            list(ideal),
            table,
            [0] * 16,
            [0] * 4,
            [0] * 4,
            [0] * 52,
            [0] * 20,
            [0] * 4,
            scaled,
        )
        return _normalize([denominator * entry for entry in scaled], ideal[0])

    def power(value: FractionalIdeal, exponent: int) -> FractionalIdeal:
        if exponent < 0:
            return power(inverse(value), -exponent)
        answer: FractionalIdeal = (_IDENTITY, 1)
        base = value
        while exponent:
            if exponent & 1:
                answer = multiply(answer, base)
            exponent >>= 1
            if exponent:
                base = multiply(base, base)
        return answer

    def principal(values: Sequence[int], denominator: int) -> FractionalIdeal:
        return _normalize(replay._principal_hnf(values, table), denominator)

    return multiply, power, principal


def replay_row14_signed_generator_witness(
    correspondence: Mapping[str, Any], metadata_receipt: Mapping[str, Any]
) -> dict[str, Any]:
    """Replay both row-14 class generators and their principal order witnesses."""
    payload, metadata = _authenticate(correspondence, metadata_receipt)
    owners = _owners(payload)
    required = {
        "class-generator-ideals",
        "class-order-principal-coefficients",
        "factor-base-ideals",
        "factor-map",
        "factor-base-norms",
        "factor-base-primes",
        "field-multiplication-table",
        "raw-relation-records",
    }
    if required - owners.keys():
        raise Row14SignedGeneratorWitnessFailure("a required exact owner is absent")
    prepared = metadata.get("prepared")
    if not isinstance(prepared, Mapping):
        raise Row14SignedGeneratorWitnessFailure("prepared metadata is absent")
    rounded = _integers(
        prepared.get("preparation_rounded_embedding"), 16, "rounded T2 matrix"
    )
    table = _integers(owners["field-multiplication-table"], 64, "basis table")
    if (
        prepared.get("n") != "4"
        or _integers(prepared.get("prep_polynomial"), 5, "prepared polynomial")
        != [-200000002, -200000002, 0, 0, 1]
        or _integers(prepared.get("basis_table"), 64, "prepared basis table") != table
    ):
        raise Row14SignedGeneratorWitnessFailure("prepared-field identity changed")
    factor_map = _integers(owners["factor-map"], 3 * _ROWS, "factor map")
    factor_base = _integers(
        owners["factor-base-ideals"], _ROWS * 16, "factor-base ideals"
    )
    pivots: list[int] = []
    for column in range(3):
        vector = factor_map[column * _ROWS : (column + 1) * _ROWS]
        support = [index for index, value in enumerate(vector) if value]
        if len(support) != 1 or vector[support[0]] != 1:
            raise Row14SignedGeneratorWitnessFailure("factor map is not a unit map")
        pivots.append(support[0])
    if len(set(pivots)) != 3:
        raise Row14SignedGeneratorWitnessFailure("factor-map pivots are not distinct")
    primes = [factor_base[16 * index : 16 * (index + 1)] for index in pivots]
    prime_numbers = _integers(owners["factor-base-primes"], _ROWS, "factor-base primes")
    norms = _integers(owners["factor-base-norms"], _ROWS, "factor-base norms")
    if [prime_numbers[index] for index in pivots] != [5099, 5659, 5939] or [
        norms[index] for index in pivots
    ] != [5099, 5659, 5939]:
        raise Row14SignedGeneratorWitnessFailure("signed source ideals changed")
    generators, factors, candidates = _signed_genback(primes, table, rounded)

    published = _integers(
        owners["class-generator-ideals"], 32, "published class generators"
    )
    published_generators = [
        tuple(published[16 * index : 16 * (index + 1)]) for index in range(2)
    ]
    if [_transpose4(value) for value in generators] != published_generators:
        raise Row14SignedGeneratorWitnessFailure(
            "signed reduction does not reproduce the published generators"
        )

    independent = importlib.import_module(
        "bench.pari-class-group-port.independent_rich_quartic_class_replay"
    )
    class_replay = independent.replay_rich_quartic_class(payload)
    quotients = class_replay["presentationCoordinates"]
    orders = class_replay["sourceGeneratorOrders"]
    if quotients != [[1, 0, 0], [-2, -1, -1]] or orders != [24, 8]:
        raise Row14SignedGeneratorWitnessFailure("Smith quotient changed")

    multiply, power, principal = _fractional_arithmetic(table)
    exact_reductions = 0
    opposite_corrections_rejected = 0
    source_witnesses: list[dict[str, Any]] = []
    for generator in range(2):
        source: FractionalIdeal = (_IDENTITY, 1)
        for prime, exponent in zip(primes, quotients[generator], strict=True):
            source = multiply(source, power((tuple(prime), 1), exponent))
        scaling: FractionalIdeal = (_IDENTITY, 1)
        for factor in factors[generator]:
            scaling = multiply(
                scaling,
                power(
                    principal(factor["values"], factor["denominator"]),
                    factor["exponent"],
                ),
            )
        if multiply((generators[generator], 1), scaling) != source:
            raise Row14SignedGeneratorWitnessFailure(
                f"signed reduction equation failed for generator {generator}"
            )
        exact_reductions += 1
        order = orders[generator]
        # `independent_rich_quartic_class_replay` has already authenticated all
        # 806 raw principal equations and this generator's exact linear
        # combination.  The correction below is therefore the exact stated
        # generator of G**order, kept factored to avoid exponential expansion.
        correction = [
            {
                **factor,
                "exponent": -order * factor["exponent"],
            }
            for factor in factors[generator]
        ]
        correction_ideal: FractionalIdeal = (_IDENTITY, 1)
        for factor in correction:
            correction_ideal = multiply(
                correction_ideal,
                power(
                    principal(factor["values"], factor["denominator"]),
                    factor["exponent"],
                ),
            )
        if power((generators[generator], 1), order) != multiply(
            power(source, order), correction_ideal
        ):
            raise Row14SignedGeneratorWitnessFailure(
                f"principal order witness failed for generator {generator}"
            )
        if factors[generator]:
            opposite: FractionalIdeal = (_IDENTITY, 1)
            for factor in factors[generator]:
                opposite = multiply(
                    opposite,
                    power(
                        principal(factor["values"], factor["denominator"]),
                        order * factor["exponent"],
                    ),
                )
            if power((generators[generator], 1), order) == multiply(
                power(source, order), opposite
            ):
                raise Row14SignedGeneratorWitnessFailure(
                    "principal correction sign is not discriminated"
                )
            opposite_corrections_rejected += 1
        source_witnesses.append(
            {
                "sourceIndex": generator,
                "publishedIndex": 1 - generator,
                "order": order,
                "smithQuotient": quotients[generator],
                "rawPrincipalCoefficientOffset": generator * _RELATIONS,
                "rawPrincipalCoefficientCount": _RELATIONS,
                "reductionFactors": factors[generator],
                "principalCorrectionFactors": correction,
                "equation": (
                    "G^order = principal(raw-principal-product "
                    "* reduction-scaling^(-order))"
                ),
            }
        )

    # The admitted public boundary is normalized as [8, 24].  Move the entire
    # tuple (ideal identity, order, raw witness range, and reduction scaling)
    # atomically; never sort the invariant integer without its witnesses.
    witnesses = [source_witnesses[1], source_witnesses[0]]

    return {
        "schema": "sagejs.pari-class-group/row14-signed-generator-witness-v1",
        "factorMapPivots": pivots,
        "publishedInvariantFactors": [8, 24],
        "sourceSmithQuotients": quotients,
        "signedSmithQuotients": [quotients[1], quotients[0]],
        "candidateCount": len(candidates),
        "candidates": candidates,
        "signedGeneratorIdealReductionsReplayed": exact_reductions,
        "principalOrderWitnessesReplayed": len(witnesses),
        "oppositePrincipalCorrectionsRejected": opposite_corrections_rejected,
        "rawPrincipalRelationsReplayed": class_replay["principalRelationsReplayed"],
        "principalIdealMultiplications": class_replay["principalIdealMultiplications"],
        "generatorWitnesses": witnesses,
        "missingOwners": [],
        "qualifiedTiming": False,
    }


__all__ = [
    "Row14SignedGeneratorWitnessFailure",
    "replay_row14_signed_generator_witness",
]
