"""Generated private row-19 prepared-input class-and-unit aggregate."""

from typing import TypedDict

from sagejs.native import (
    Float64Buffer,
    Int64Buffer,
    IntegerBuffer,
    integer_buffer_view,
    native,
    uint64,
)
from .row19_phase6_prepared_factor_root import pari_row19_phase6_prepared_factor_root
from .collected_log_embeddings import pari_collect_and_log_relations
from .hnfspec_complete import pari_hnfspec_complete
from .row14_next_pass import pari_row14_prepare_next_pass
from .row14_post806_terminal import pari_row14_analytic_inverse_hr
from .connected_hnfadd_acceptance import pari_connected_hnfadd_acceptance
from .row19_hnfadd_cup_suffix import pari_row19_hnfadd_cup_suffix
from .post_hnf_acceptance import pari_post_hnf_acceptance
from .row19_phase6_resident_class_private import (
    pari_row19_phase6_resident_class_private,
)
from .row19_phase6_resident_kernel_private import (
    pari_row19_phase6_resident_kernel_private,
)
from .row19_phase6_resident_unit_private import pari_row19_phase6_resident_unit_private
from .row19_phase6_resident_witness_private import (
    pari_row19_phase6_resident_witness_private,
)


class Row19ClassManifest(TypedDict):
    factor_count: uint64
    relation_count: uint64
    class_dimension: uint64


class Row19KernelManifest(TypedDict):
    factor_count: uint64
    first_columns: uint64
    relation_count: uint64
    kernel_rank: uint64


class Row19UnitManifest(TypedDict):
    relation_count: uint64
    kernel_rank: uint64
    log_stride: uint64
    degree: uint64


class Row19WitnessManifest(TypedDict):
    factor_count: uint64
    relation_count: uint64
    class_dimension: uint64


@native
def pari_row19_phase6_prepared_aggregate_root(
    factor_polynomial: IntegerBuffer,
    factor_discriminant: int,
    factor_real_places: int,
    factor_complex_pairs: int,
    factor_precision: int,
    factor_equation_index: int,
    factor_roots_of_unity: int,
    factor_zkden: int,
    factor_invzk: IntegerBuffer,
    factor_zk: IntegerBuffer,
    factor_zk_degrees: IntegerBuffer,
    factor_basis_table: IntegerBuffer,
    factor_embedding_m: IntegerBuffer,
    factor_embedding_p: IntegerBuffer,
    factor_embedding_e: IntegerBuffer,
    factor_runtime_primes: IntegerBuffer,
    factor_runtime_products: IntegerBuffer,
    factor_preparation_rounded_embedding: IntegerBuffer,
    factor_preparation_embedding: IntegerBuffer,
    factor_factor_limit: int,
    factor_prime_limit: int,
    factor_index_workspace: IntegerBuffer,
    factor_index_descriptors: IntegerBuffer,
    factor_index_ranks: IntegerBuffer,
    factor_index_states: IntegerBuffer,
    factor_degree_workspace: IntegerBuffer,
    factor_factor_degrees: IntegerBuffer,
    factor_factor_exponents: IntegerBuffer,
    factor_group_degrees: IntegerBuffer,
    factor_group_counts: IntegerBuffer,
    factor_local_state: IntegerBuffer,
    factor_pattern_offsets: IntegerBuffer,
    factor_pattern_counts: IntegerBuffer,
    factor_pattern_degrees: IntegerBuffer,
    factor_pattern_multiplicities: IntegerBuffer,
    factor_full_offsets: IntegerBuffer,
    factor_full_counts: IntegerBuffer,
    factor_full_degrees: IntegerBuffer,
    factor_degree_state: IntegerBuffer,
    factor_base_norms: IntegerBuffer,
    factor_base_configuration: Float64Buffer,
    factor_base_constants_logs: Float64Buffer,
    factor_base_sums: Float64Buffer,
    factor_base_factor_logs: Float64Buffer,
    factor_selected_primes: IntegerBuffer,
    factor_prime_offsets: IntegerBuffer,
    factor_prime_counts: IntegerBuffer,
    factor_complete_groups: IntegerBuffer,
    factor_selected_indices: IntegerBuffer,
    factor_factor_product: IntegerBuffer,
    factor_random_state: IntegerBuffer,
    factor_kummer_factorwork: IntegerBuffer,
    factor_kummer_factor: IntegerBuffer,
    factor_kummer_diagnostic: IntegerBuffer,
    factor_kummer_minpoly_diagnostic: IntegerBuffer,
    factor_kummer_polywork: IntegerBuffer,
    factor_kummer_u: IntegerBuffer,
    factor_kummer_t: IntegerBuffer,
    factor_kummer_rational: IntegerBuffer,
    factor_kummer_primitive: IntegerBuffer,
    factor_kummer_column: IntegerBuffer,
    factor_kummer_resultant_work: IntegerBuffer,
    factor_kummer_resultant_trace: IntegerBuffer,
    factor_kummer_u_output: IntegerBuffer,
    factor_kummer_tau_output: IntegerBuffer,
    factor_kummer_descriptor_state: IntegerBuffer,
    factor_kummer_unsorted: IntegerBuffer,
    factor_kummer_generators: IntegerBuffer,
    factor_kummer_residue_degrees: IntegerBuffer,
    factor_kummer_order: IntegerBuffer,
    factor_kummer_sort_diagnostic: IntegerBuffer,
    factor_kummer_decomposition_output: IntegerBuffer,
    factor_kummer_decomposition_state: IntegerBuffer,
    factor_catalog_primes: IntegerBuffer,
    factor_catalog_e: IntegerBuffer,
    factor_catalog_f: IntegerBuffer,
    factor_catalog_inert: IntegerBuffer,
    factor_catalog_generators: IntegerBuffer,
    factor_catalog_tau: IntegerBuffer,
    factor_requested_counts: IntegerBuffer,
    factor_kummer_state: IntegerBuffer,
    factor_packet_generator: IntegerBuffer,
    factor_packet_multiplication: IntegerBuffer,
    factor_packet_work: IntegerBuffer,
    factor_packet_pivots: IntegerBuffer,
    factor_packet_ideal: IntegerBuffer,
    factor_packet_ideals: IntegerBuffer,
    factor_packet_norms: IntegerBuffer,
    factor_relation_primes: IntegerBuffer,
    factor_ramification: IntegerBuffer,
    factor_residue_degrees: IntegerBuffer,
    factor_inert_flags: IntegerBuffer,
    factor_selected_tau: IntegerBuffer,
    factor_rational_primes: IntegerBuffer,
    factor_rational_offsets: IntegerBuffer,
    factor_rational_counts: IntegerBuffer,
    factor_rational_complete: IntegerBuffer,
    factor_bad_flags: IntegerBuffer,
    factor_sub_configuration: Float64Buffer,
    factor_sub_order: IntegerBuffer,
    factor_sub_scratch: IntegerBuffer,
    factor_sub_stack: IntegerBuffer,
    factor_sub_chosen: IntegerBuffer,
    factor_sub_rejected: IntegerBuffer,
    factor_permutation: IntegerBuffer,
    factor_subfactor: IntegerBuffer,
    factor_relation_state: IntegerBuffer,
    factor_relation_basis: IntegerBuffer,
    factor_relation_records: IntegerBuffer,
    factor_relation_hashes: IntegerBuffer,
    factor_relation_metadata: IntegerBuffer,
    factor_relation_scratch: IntegerBuffer,
    factor_relation_generators: IntegerBuffer,
    factor_analytic_primes: IntegerBuffer,
    factor_analytic_workspace: IntegerBuffer,
    factor_analytic_factor_degrees: IntegerBuffer,
    factor_analytic_factor_exponents: IntegerBuffer,
    factor_analytic_group_degrees: IntegerBuffer,
    factor_analytic_group_counts: IntegerBuffer,
    factor_analytic_local_state: IntegerBuffer,
    factor_analytic_offsets: IntegerBuffer,
    factor_analytic_counts: IntegerBuffer,
    factor_analytic_degrees: IntegerBuffer,
    factor_analytic_multiplicities: IntegerBuffer,
    factor_analytic_full_offsets: IntegerBuffer,
    factor_analytic_full_counts: IntegerBuffer,
    factor_analytic_full_degrees: IntegerBuffer,
    factor_analytic_state: IntegerBuffer,
    factor_root_state: IntegerBuffer,
    collector_matrix: IntegerBuffer,
    collector_ideal: IntegerBuffer,
    collector_reduction: IntegerBuffer,
    collector_vectors: IntegerBuffer,
    collector_betas: IntegerBuffer,
    collector_norms: IntegerBuffer,
    collector_column: IntegerBuffer,
    collector_float_q: Float64Buffer,
    collector_float_v: Float64Buffer,
    collector_bound: Float64Buffer,
    collector_cache: IntegerBuffer,
    collector_a: IntegerBuffer,
    collector_b: IntegerBuffer,
    collector_p: IntegerBuffer,
    collector_q: IntegerBuffer,
    collector_stack: IntegerBuffer,
    collector_x: Int64Buffer,
    collector_y: Float64Buffer,
    collector_z: Float64Buffer,
    collector_inc: Int64Buffer,
    collector_state: Int64Buffer,
    collector_cursor_output: Int64Buffer,
    collector_element: IntegerBuffer,
    collector_counters: Int64Buffer,
    collector_admission_embedding_m: IntegerBuffer,
    collector_admission_embedding_p: IntegerBuffer,
    collector_admission_embedding_e: IntegerBuffer,
    collector_admission_ideal: IntegerBuffer,
    collector_admission_rational_factors: IntegerBuffer,
    collector_admission_rational_exponents: IntegerBuffer,
    collector_admission_tau: IntegerBuffer,
    collector_admission_x: IntegerBuffer,
    collector_admission_y: IntegerBuffer,
    collector_admission_spare: IntegerBuffer,
    collector_admission_stack: IntegerBuffer,
    collector_admission_primitive: IntegerBuffer,
    collector_admission_columns: IntegerBuffer,
    collector_admission_values: IntegerBuffer,
    collector_admission_temporary: IntegerBuffer,
    collector_admission_indices: IntegerBuffer,
    collector_admission_exponents: IntegerBuffer,
    collector_diagnostic: IntegerBuffer,
    collector_extra: IntegerBuffer,
    collector_relation: IntegerBuffer,
    collector_relation_scratch: IntegerBuffer,
    collector_progress: Int64Buffer,
    collector_preparation_original: IntegerBuffer,
    collector_preparation_basis: IntegerBuffer,
    collector_preparation_transform: IntegerBuffer,
    collector_preparation_flags: IntegerBuffer,
    collector_preparation_rank_diagnostic: IntegerBuffer,
    collector_preparation_selection: IntegerBuffer,
    collector_preparation_stages: IntegerBuffer,
    collector_preparation_flatter_input: IntegerBuffer,
    collector_preparation_current: IntegerBuffer,
    collector_preparation_flatter_transform: IntegerBuffer,
    collector_preparation_total_work: IntegerBuffer,
    collector_preparation_step_t: IntegerBuffer,
    collector_preparation_step_s: IntegerBuffer,
    collector_preparation_product: IntegerBuffer,
    collector_preparation_next_basis: IntegerBuffer,
    collector_preparation_y: IntegerBuffer,
    collector_preparation_diagnostic: IntegerBuffer,
    collector_preparation_r1: IntegerBuffer,
    collector_preparation_r2: IntegerBuffer,
    collector_preparation_r3: IntegerBuffer,
    collector_preparation_t1: IntegerBuffer,
    collector_preparation_t2: IntegerBuffer,
    collector_preparation_t3: IntegerBuffer,
    collector_preparation_integers: IntegerBuffer,
    collector_preparation_inverse: IntegerBuffer,
    collector_preparation_first: IntegerBuffer,
    collector_preparation_second: IntegerBuffer,
    collector_preparation_final: IntegerBuffer,
    collector_preparation_rounded: IntegerBuffer,
    collector_preparation_mu: Float64Buffer,
    collector_preparation_r: Float64Buffer,
    collector_preparation_s: Float64Buffer,
    collector_preparation_approximate: Float64Buffer,
    collector_preparation_exponents: IntegerBuffer,
    collector_preparation_float_gram: Float64Buffer,
    collector_preparation_gram: IntegerBuffer,
    collector_preparation_mu_exponents: IntegerBuffer,
    collector_preparation_r_exponents: IntegerBuffer,
    collector_preparation_s_exponents: IntegerBuffer,
    collector_preparation_alpha: IntegerBuffer,
    collector_preparation_column_exponents: IntegerBuffer,
    collector_preparation_float_scratch: Float64Buffer,
    collector_preparation_temporary: Float64Buffer,
    collector_preparation_state: Int64Buffer,
    collector_packet_ids: IntegerBuffer,
    collector_schedule: Int64Buffer,
    collector_packet_generators: IntegerBuffer,
    collector_hnf_generator: IntegerBuffer,
    collector_hnf_matrix: IntegerBuffer,
    collector_hnf_work: IntegerBuffer,
    collector_hnf_pivots: IntegerBuffer,
    collector_power_ideal: IntegerBuffer,
    collector_power_alpha: IntegerBuffer,
    collector_power_metadata: IntegerBuffer,
    collector_power_primitive: IntegerBuffer,
    collector_power_temporary: IntegerBuffer,
    collector_power_diagnostic: IntegerBuffer,
    collector_power_multiplication: IntegerBuffer,
    collector_power_work: IntegerBuffer,
    collector_power_triangular: IntegerBuffer,
    collector_power_moduli: IntegerBuffer,
    collector_product_primitive: IntegerBuffer,
    collector_product_matrix: IntegerBuffer,
    collector_outer_state: Int64Buffer,
    collector_outer_minidx: IntegerBuffer,
    collector_outer_present: IntegerBuffer,
    collector_outer_live: IntegerBuffer,
    collector_outer_perm: IntegerBuffer,
    collector_outer_multiplier: IntegerBuffer,
    collector_log_completed: IntegerBuffer,
    collector_log_embeddings: IntegerBuffer,
    collector_log_coordinates: IntegerBuffer,
    collector_log_column: IntegerBuffer,
    collector_log_cache: IntegerBuffer,
    collector_log_pi_cache: IntegerBuffer,
    collector_log_a: IntegerBuffer,
    collector_log_b: IntegerBuffer,
    collector_log_p: IntegerBuffer,
    collector_log_q: IntegerBuffer,
    collector_log_stack: IntegerBuffer,
    hnf_original: Int64Buffer,
    hnf_perm: Int64Buffer,
    hnf_logs: IntegerBuffer,
    hnf_mat: Int64Buffer,
    hnf_dense: IntegerBuffer,
    hnf_transform: IntegerBuffer,
    hnf_vmax: Int64Buffer,
    hnf_found: Int64Buffer,
    hnf_sparse_state: Int64Buffer,
    hnf_bottom: IntegerBuffer,
    hnf_updated_dense: IntegerBuffer,
    hnf_extra: IntegerBuffer,
    hnf_cleanup_state: Int64Buffer,
    hnf_rank_matrix: IntegerBuffer,
    hnf_occupied: IntegerBuffer,
    hnf_pivots: IntegerBuffer,
    hnf_best: IntegerBuffer,
    hnf_profile: IntegerBuffer,
    hnf_rank_state: IntegerBuffer,
    hnf_perm_work: Int64Buffer,
    hnf_matbnew: IntegerBuffer,
    hnf_dep: IntegerBuffer,
    hnf_b: IntegerBuffer,
    hnf_assembly_state: Int64Buffer,
    hnf_transformed_logs: IntegerBuffer,
    hnf_full_h: IntegerBuffer,
    hnf_hnf_transform: IntegerBuffer,
    hnf_lam: IntegerBuffer,
    hnf_d: IntegerBuffer,
    hnf_hnf_state: Int64Buffer,
    hnf_full_dep: IntegerBuffer,
    hnf_work_b: IntegerBuffer,
    hnf_work_c: IntegerBuffer,
    hnf_diagonal: Int64Buffer,
    hnf_result_h: IntegerBuffer,
    hnf_result_dep: IntegerBuffer,
    hnf_result_b: IntegerBuffer,
    hnf_result_c: IntegerBuffer,
    hnf_final_state: Int64Buffer,
    hnf_state: Int64Buffer,
    hnf_cup_arena: IntegerBuffer,
    hnf_cup_frames: IntegerBuffer,
    hnf_cup_solve_state: Int64Buffer,
    hnf_cup_state: Int64Buffer,
    next_control: Int64Buffer,
    analytic_log_discriminant: Float64Buffer,
    analytic_coefficients: Float64Buffer,
    analytic_table: Float64Buffer,
    analytic_tail: Float64Buffer,
    analytic_logarithms: Float64Buffer,
    analytic_log_inverse_residue: Float64Buffer,
    analytic_inverse_residue: IntegerBuffer,
    analytic_exp_cache: IntegerBuffer,
    analytic_pi_cache: IntegerBuffer,
    analytic_a: IntegerBuffer,
    analytic_b: IntegerBuffer,
    analytic_p: IntegerBuffer,
    analytic_q: IntegerBuffer,
    analytic_stack: IntegerBuffer,
    analytic_inverse_hr: IntegerBuffer,
    analytic_state: Int64Buffer,
    terminal_new_relations: Int64Buffer,
    terminal_top: IntegerBuffer,
    terminal_exact_product: IntegerBuffer,
    terminal_log_product: IntegerBuffer,
    terminal_adjusted_logs: IntegerBuffer,
    terminal_joined: IntegerBuffer,
    terminal_joined_logs: IntegerBuffer,
    terminal_rank_matrix: IntegerBuffer,
    terminal_occupied: IntegerBuffer,
    terminal_pivots: IntegerBuffer,
    terminal_best: IntegerBuffer,
    terminal_profile: IntegerBuffer,
    terminal_rank_state: IntegerBuffer,
    terminal_perm_work: Int64Buffer,
    terminal_matb: IntegerBuffer,
    terminal_new_dep: IntegerBuffer,
    terminal_permuted_b: IntegerBuffer,
    terminal_full_h: IntegerBuffer,
    terminal_transform: IntegerBuffer,
    terminal_lam: IntegerBuffer,
    terminal_d: IntegerBuffer,
    terminal_hnf_state: Int64Buffer,
    terminal_full_dep: IntegerBuffer,
    terminal_work_b: IntegerBuffer,
    terminal_work_c: IntegerBuffer,
    terminal_diagonal: Int64Buffer,
    terminal_final_c: IntegerBuffer,
    terminal_result_h: IntegerBuffer,
    terminal_result_dep: IntegerBuffer,
    terminal_result_b: IntegerBuffer,
    terminal_result_c: IntegerBuffer,
    terminal_final_state: Int64Buffer,
    terminal_state: Int64Buffer,
    terminal_accept_logs: IntegerBuffer,
    terminal_accept_class_number: IntegerBuffer,
    terminal_accept_zeta_factor: IntegerBuffer,
    terminal_accept_post_hnf_state: Int64Buffer,
    terminal_accept_prepared: IntegerBuffer,
    terminal_accept_selected: Int64Buffer,
    terminal_accept_prep_state: Int64Buffer,
    terminal_accept_rank_work: IntegerBuffer,
    terminal_accept_rank_occupied: Int64Buffer,
    terminal_accept_rank_pivots: Int64Buffer,
    terminal_accept_rank_state: Int64Buffer,
    terminal_accept_integer_input: IntegerBuffer,
    terminal_accept_integer_work: IntegerBuffer,
    terminal_accept_integer_occupied: IntegerBuffer,
    terminal_accept_integer_pivots: IntegerBuffer,
    terminal_accept_integer_best: IntegerBuffer,
    terminal_accept_integer_state: IntegerBuffer,
    terminal_accept_basis: IntegerBuffer,
    terminal_accept_minor: IntegerBuffer,
    terminal_accept_det_work: IntegerBuffer,
    terminal_accept_det_result: IntegerBuffer,
    terminal_accept_det_pivots: Int64Buffer,
    terminal_accept_det_state: Int64Buffer,
    terminal_accept_inverse_work: IntegerBuffer,
    terminal_accept_inverse_rhs: IntegerBuffer,
    terminal_accept_inverse: IntegerBuffer,
    terminal_accept_inverse_pivots: Int64Buffer,
    terminal_accept_inverse_state: Int64Buffer,
    terminal_accept_product: IntegerBuffer,
    terminal_accept_inverse_slice: IntegerBuffer,
    terminal_accept_multiple: IntegerBuffer,
    terminal_accept_coordinates: IntegerBuffer,
    terminal_accept_multiple_state: Int64Buffer,
    terminal_accept_rational_work: IntegerBuffer,
    terminal_accept_lattice: IntegerBuffer,
    terminal_accept_hnf_work: IntegerBuffer,
    terminal_accept_hnf_column: IntegerBuffer,
    terminal_accept_hnf_output: IntegerBuffer,
    terminal_accept_hnf_state: Int64Buffer,
    terminal_accept_regulator: IntegerBuffer,
    terminal_accept_relations: IntegerBuffer,
    terminal_accept_denominator: IntegerBuffer,
    terminal_accept_reconstruction_state: Int64Buffer,
    terminal_accept_hnf_row_pivots: Int64Buffer,
    terminal_accept_hnf_heights: Int64Buffer,
    terminal_accept_acceptance_state: Int64Buffer,
    terminal_attempt_state: Int64Buffer,
    cup_cup_arena: IntegerBuffer,
    cup_cup_frames: IntegerBuffer,
    cup_cup_solve_state: Int64Buffer,
    cup_cup_state: Int64Buffer,
    class_manifest: Row19ClassManifest,
    class_invariants_output: IntegerBuffer,
    class_class_number_output: IntegerBuffer,
    class_m1_output: IntegerBuffer,
    class_uir_output: IntegerBuffer,
    class_class_state_output: Int64Buffer,
    kernel_manifest: Row19KernelManifest,
    kernel_workspace: IntegerBuffer,
    kernel_kernel_output: IntegerBuffer,
    kernel_presentation_output: IntegerBuffer,
    kernel_state_output: Int64Buffer,
    unit_manifest: Row19UnitManifest,
    unit_dependency_output: IntegerBuffer,
    unit_inverse_output: IntegerBuffer,
    unit_multiples_output: Int64Buffer,
    unit_state_output: Int64Buffer,
    witness_manifest: Row19WitnessManifest,
    witness_coefficients_output: IntegerBuffer,
    witness_valuations_output: IntegerBuffer,
    witness_support_output: Int64Buffer,
    witness_state_output: Int64Buffer,
) -> int:
    """Compute the complete retained row-19 factored result in one call."""
    count = pari_row19_phase6_prepared_factor_root(
        factor_polynomial,
        factor_discriminant,
        factor_real_places,
        factor_complex_pairs,
        factor_precision,
        factor_equation_index,
        factor_roots_of_unity,
        factor_zkden,
        factor_invzk,
        factor_zk,
        factor_zk_degrees,
        factor_basis_table,
        factor_embedding_m,
        factor_embedding_p,
        factor_embedding_e,
        factor_runtime_primes,
        factor_runtime_products,
        factor_preparation_rounded_embedding,
        factor_preparation_embedding,
        factor_factor_limit,
        factor_prime_limit,
        factor_index_workspace,
        factor_index_descriptors,
        factor_index_ranks,
        factor_index_states,
        factor_degree_workspace,
        factor_factor_degrees,
        factor_factor_exponents,
        factor_group_degrees,
        factor_group_counts,
        factor_local_state,
        factor_pattern_offsets,
        factor_pattern_counts,
        factor_pattern_degrees,
        factor_pattern_multiplicities,
        factor_full_offsets,
        factor_full_counts,
        factor_full_degrees,
        factor_degree_state,
        factor_base_norms,
        factor_base_configuration,
        factor_base_constants_logs,
        factor_base_sums,
        factor_base_factor_logs,
        factor_selected_primes,
        factor_prime_offsets,
        factor_prime_counts,
        factor_complete_groups,
        factor_selected_indices,
        factor_factor_product,
        factor_random_state,
        factor_kummer_factorwork,
        factor_kummer_factor,
        factor_kummer_diagnostic,
        factor_kummer_minpoly_diagnostic,
        factor_kummer_polywork,
        factor_kummer_u,
        factor_kummer_t,
        factor_kummer_rational,
        factor_kummer_primitive,
        factor_kummer_column,
        factor_kummer_resultant_work,
        factor_kummer_resultant_trace,
        factor_kummer_u_output,
        factor_kummer_tau_output,
        factor_kummer_descriptor_state,
        factor_kummer_unsorted,
        factor_kummer_generators,
        factor_kummer_residue_degrees,
        factor_kummer_order,
        factor_kummer_sort_diagnostic,
        factor_kummer_decomposition_output,
        factor_kummer_decomposition_state,
        factor_catalog_primes,
        factor_catalog_e,
        factor_catalog_f,
        factor_catalog_inert,
        factor_catalog_generators,
        factor_catalog_tau,
        factor_requested_counts,
        factor_kummer_state,
        factor_packet_generator,
        factor_packet_multiplication,
        factor_packet_work,
        factor_packet_pivots,
        factor_packet_ideal,
        factor_packet_ideals,
        factor_packet_norms,
        factor_relation_primes,
        factor_ramification,
        factor_residue_degrees,
        factor_inert_flags,
        factor_selected_tau,
        factor_rational_primes,
        factor_rational_offsets,
        factor_rational_counts,
        factor_rational_complete,
        factor_bad_flags,
        factor_sub_configuration,
        factor_sub_order,
        factor_sub_scratch,
        factor_sub_stack,
        factor_sub_chosen,
        factor_sub_rejected,
        factor_permutation,
        factor_subfactor,
        factor_relation_state,
        factor_relation_basis,
        factor_relation_records,
        factor_relation_hashes,
        factor_relation_metadata,
        factor_relation_scratch,
        factor_relation_generators,
        factor_analytic_primes,
        factor_analytic_workspace,
        factor_analytic_factor_degrees,
        factor_analytic_factor_exponents,
        factor_analytic_group_degrees,
        factor_analytic_group_counts,
        factor_analytic_local_state,
        factor_analytic_offsets,
        factor_analytic_counts,
        factor_analytic_degrees,
        factor_analytic_multiplicities,
        factor_analytic_full_offsets,
        factor_analytic_full_counts,
        factor_analytic_full_degrees,
        factor_analytic_state,
        factor_root_state,
    )
    if count != 424:
        return 11
    for i in range(20):
        collector_outer_state[i] = 0
    collector_outer_state[0] = 359
    collector_outer_state[1] = 4
    collector_outer_state[4] = 425
    for i in range(4):
        collector_schedule[i] = 0
    collector_log_completed[0] = 0
    for i in range(424):
        collector_packet_ids[i] = i + 1
        collector_outer_minidx[i] = i + 1
        collector_outer_perm[i] = factor_permutation[i]
        selected = factor_selected_indices[i]
        for coordinate in range(3):
            collector_packet_generators[3 * i + coordinate] = factor_catalog_generators[
                3 * selected + coordinate
            ]
    status = pari_collect_and_log_relations(
        collector_matrix,
        collector_ideal,
        3,
        factor_precision,
        477.46482927568604,
        1,
        collector_reduction,
        collector_vectors,
        collector_betas,
        collector_norms,
        collector_column,
        collector_float_q,
        collector_float_v,
        collector_bound,
        collector_cache,
        collector_a,
        collector_b,
        collector_p,
        collector_q,
        collector_stack,
        collector_x,
        collector_y,
        collector_z,
        collector_inc,
        collector_state,
        collector_cursor_output,
        collector_element,
        collector_counters,
        factor_embedding_m,
        factor_embedding_p,
        factor_embedding_e,
        collector_admission_embedding_m,
        collector_admission_embedding_p,
        collector_admission_embedding_e,
        1,
        collector_admission_ideal,
        2,
        factor_factor_product[0],
        factor_runtime_primes,
        factor_runtime_products,
        factor_factor_limit,
        factor_prime_limit,
        collector_admission_rational_factors,
        collector_admission_rational_exponents,
        factor_prime_offsets,
        factor_prime_counts,
        factor_selected_tau,
        factor_ramification,
        factor_residue_degrees,
        factor_inert_flags,
        collector_admission_tau,
        collector_admission_x,
        collector_admission_y,
        collector_admission_spare,
        collector_admission_stack,
        collector_admission_primitive,
        collector_admission_columns,
        collector_admission_values,
        collector_admission_temporary,
        collector_admission_indices,
        collector_admission_exponents,
        collector_diagnostic,
        4,
        1,
        0,
        0,
        integer_buffer_view(factor_subfactor, 0, 3),
        collector_extra,
        -1,
        factor_relation_primes,
        factor_ramification,
        collector_relation,
        factor_relation_state,
        factor_relation_basis,
        factor_relation_records,
        factor_relation_hashes,
        factor_relation_metadata,
        collector_relation_scratch,
        factor_relation_generators,
        collector_progress,
        factor_preparation_rounded_embedding,
        factor_preparation_embedding,
        collector_preparation_original,
        collector_preparation_basis,
        collector_preparation_transform,
        collector_preparation_flags,
        collector_preparation_rank_diagnostic,
        collector_preparation_selection,
        collector_preparation_stages,
        collector_preparation_flatter_input,
        collector_preparation_current,
        collector_preparation_flatter_transform,
        collector_preparation_total_work,
        collector_preparation_step_t,
        collector_preparation_step_s,
        collector_preparation_product,
        collector_preparation_next_basis,
        collector_preparation_y,
        collector_preparation_diagnostic,
        collector_preparation_r1,
        collector_preparation_r2,
        collector_preparation_r3,
        collector_preparation_t1,
        collector_preparation_t2,
        collector_preparation_t3,
        collector_preparation_integers,
        collector_preparation_inverse,
        collector_preparation_first,
        collector_preparation_second,
        collector_preparation_final,
        collector_preparation_rounded,
        collector_preparation_mu,
        collector_preparation_r,
        collector_preparation_s,
        collector_preparation_approximate,
        collector_preparation_exponents,
        collector_preparation_float_gram,
        collector_preparation_gram,
        collector_preparation_mu_exponents,
        collector_preparation_r_exponents,
        collector_preparation_s_exponents,
        collector_preparation_alpha,
        collector_preparation_column_exponents,
        collector_preparation_float_scratch,
        collector_preparation_temporary,
        collector_preparation_state,
        factor_permutation,
        424,
        collector_packet_ids,
        factor_packet_ideals,
        factor_packet_norms,
        collector_schedule,
        0,
        factor_basis_table,
        factor_relation_primes,
        collector_packet_generators,
        factor_inert_flags,
        collector_hnf_generator,
        collector_hnf_matrix,
        collector_hnf_work,
        collector_hnf_pivots,
        collector_power_ideal,
        collector_power_alpha,
        collector_power_metadata,
        collector_power_primitive,
        collector_power_temporary,
        collector_power_diagnostic,
        collector_power_multiplication,
        collector_power_work,
        collector_power_triangular,
        collector_power_moduli,
        collector_product_primitive,
        collector_product_matrix,
        1,
        2,
        collector_outer_state,
        collector_outer_minidx,
        collector_outer_present,
        collector_outer_live,
        collector_outer_perm,
        collector_outer_multiplier,
        192,
        collector_log_completed,
        collector_log_embeddings,
        collector_log_coordinates,
        collector_log_column,
        collector_log_cache,
        collector_log_pi_cache,
        collector_log_a,
        collector_log_b,
        collector_log_p,
        collector_log_q,
        collector_log_stack,
        71,
    )
    if status != 0 and status != 1:
        return 20 + status
    if factor_relation_state[0] != 423 or collector_log_completed[0] != 423:
        return 30
    for i in range(424 * 423):
        hnf_original[i] = factor_relation_records[i]
    for i in range(424):
        hnf_perm[i] = collector_outer_perm[i]
    for i in range(14 * 423):
        hnf_logs[i] = collector_log_embeddings[i]
    status = pari_hnfspec_complete(
        hnf_original,
        424,
        423,
        hnf_perm,
        3,
        hnf_logs,
        2,
        hnf_mat,
        hnf_dense,
        hnf_transform,
        hnf_vmax,
        hnf_found,
        hnf_sparse_state,
        hnf_bottom,
        hnf_updated_dense,
        hnf_extra,
        hnf_cleanup_state,
        hnf_rank_matrix,
        hnf_occupied,
        hnf_pivots,
        hnf_best,
        hnf_profile,
        hnf_rank_state,
        hnf_perm_work,
        hnf_matbnew,
        hnf_dep,
        hnf_b,
        hnf_assembly_state,
        hnf_transformed_logs,
        hnf_full_h,
        hnf_hnf_transform,
        hnf_lam,
        hnf_d,
        hnf_hnf_state,
        hnf_full_dep,
        hnf_work_b,
        hnf_work_c,
        hnf_diagonal,
        hnf_result_h,
        hnf_result_dep,
        hnf_result_b,
        hnf_result_c,
        hnf_final_state,
        hnf_state,
        hnf_cup_arena,
        hnf_cup_frames,
        hnf_cup_solve_state,
        hnf_cup_state,
    )
    if status != 0 or hnf_state[0] != 9 or hnf_state[2] != 408:
        return 40 + status
    status = pari_row14_prepare_next_pass(
        hnf_perm,
        424,
        9,
        7,
        0,
        factor_permutation,
        collector_outer_perm,
        1,
        collector_outer_state,
        factor_relation_state,
        collector_schedule,
        collector_log_completed,
        next_control,
    )
    if status != 0:
        return 50 + status
    status = pari_collect_and_log_relations(
        collector_matrix,
        collector_ideal,
        3,
        factor_precision,
        477.46482927568604,
        1,
        collector_reduction,
        collector_vectors,
        collector_betas,
        collector_norms,
        collector_column,
        collector_float_q,
        collector_float_v,
        collector_bound,
        collector_cache,
        collector_a,
        collector_b,
        collector_p,
        collector_q,
        collector_stack,
        collector_x,
        collector_y,
        collector_z,
        collector_inc,
        collector_state,
        collector_cursor_output,
        collector_element,
        collector_counters,
        factor_embedding_m,
        factor_embedding_p,
        factor_embedding_e,
        collector_admission_embedding_m,
        collector_admission_embedding_p,
        collector_admission_embedding_e,
        1,
        collector_admission_ideal,
        2,
        factor_factor_product[0],
        factor_runtime_primes,
        factor_runtime_products,
        factor_factor_limit,
        factor_prime_limit,
        collector_admission_rational_factors,
        collector_admission_rational_exponents,
        factor_prime_offsets,
        factor_prime_counts,
        factor_selected_tau,
        factor_ramification,
        factor_residue_degrees,
        factor_inert_flags,
        collector_admission_tau,
        collector_admission_x,
        collector_admission_y,
        collector_admission_spare,
        collector_admission_stack,
        collector_admission_primitive,
        collector_admission_columns,
        collector_admission_values,
        collector_admission_temporary,
        collector_admission_indices,
        collector_admission_exponents,
        collector_diagnostic,
        4,
        1,
        0,
        0,
        integer_buffer_view(factor_subfactor, 0, 3),
        collector_extra,
        -1,
        factor_relation_primes,
        factor_ramification,
        collector_relation,
        factor_relation_state,
        factor_relation_basis,
        factor_relation_records,
        factor_relation_hashes,
        factor_relation_metadata,
        collector_relation_scratch,
        factor_relation_generators,
        collector_progress,
        factor_preparation_rounded_embedding,
        factor_preparation_embedding,
        collector_preparation_original,
        collector_preparation_basis,
        collector_preparation_transform,
        collector_preparation_flags,
        collector_preparation_rank_diagnostic,
        collector_preparation_selection,
        collector_preparation_stages,
        collector_preparation_flatter_input,
        collector_preparation_current,
        collector_preparation_flatter_transform,
        collector_preparation_total_work,
        collector_preparation_step_t,
        collector_preparation_step_s,
        collector_preparation_product,
        collector_preparation_next_basis,
        collector_preparation_y,
        collector_preparation_diagnostic,
        collector_preparation_r1,
        collector_preparation_r2,
        collector_preparation_r3,
        collector_preparation_t1,
        collector_preparation_t2,
        collector_preparation_t3,
        collector_preparation_integers,
        collector_preparation_inverse,
        collector_preparation_first,
        collector_preparation_second,
        collector_preparation_final,
        collector_preparation_rounded,
        collector_preparation_mu,
        collector_preparation_r,
        collector_preparation_s,
        collector_preparation_approximate,
        collector_preparation_exponents,
        collector_preparation_float_gram,
        collector_preparation_gram,
        collector_preparation_mu_exponents,
        collector_preparation_r_exponents,
        collector_preparation_s_exponents,
        collector_preparation_alpha,
        collector_preparation_column_exponents,
        collector_preparation_float_scratch,
        collector_preparation_temporary,
        collector_preparation_state,
        factor_permutation,
        int(next_control[0]),
        collector_packet_ids,
        factor_packet_ideals,
        factor_packet_norms,
        collector_schedule,
        0,
        factor_basis_table,
        factor_relation_primes,
        collector_packet_generators,
        factor_inert_flags,
        collector_hnf_generator,
        collector_hnf_matrix,
        collector_hnf_work,
        collector_hnf_pivots,
        collector_power_ideal,
        collector_power_alpha,
        collector_power_metadata,
        collector_power_primitive,
        collector_power_temporary,
        collector_power_diagnostic,
        collector_power_multiplication,
        collector_power_work,
        collector_power_triangular,
        collector_power_moduli,
        collector_product_primitive,
        collector_product_matrix,
        1,
        2,
        collector_outer_state,
        collector_outer_minidx,
        collector_outer_present,
        collector_outer_live,
        collector_outer_perm,
        collector_outer_multiplier,
        192,
        collector_log_completed,
        collector_log_embeddings,
        collector_log_coordinates,
        collector_log_column,
        collector_log_cache,
        collector_log_pi_cache,
        collector_log_a,
        collector_log_b,
        collector_log_p,
        collector_log_q,
        collector_log_stack,
        71,
    )
    if status != 0 and status != 1:
        return 60 + status
    if factor_relation_state[0] != 430 or collector_log_completed[0] != 430:
        return 70
    status = pari_row14_analytic_inverse_hr(
        factor_discriminant,
        1,
        1,
        factor_roots_of_unity,
        analytic_log_discriminant,
        factor_analytic_primes,
        factor_analytic_offsets,
        factor_analytic_counts,
        factor_analytic_degrees,
        factor_analytic_multiplicities,
        analytic_coefficients,
        analytic_table,
        analytic_tail,
        analytic_logarithms,
        analytic_log_inverse_residue,
        analytic_inverse_residue,
        analytic_exp_cache,
        analytic_pi_cache,
        analytic_a,
        analytic_b,
        analytic_p,
        analytic_q,
        analytic_stack,
        analytic_inverse_hr,
        analytic_state,
    )
    if status != 0:
        return 80 + status
    for i in range(424 * 7):
        terminal_new_relations[i] = factor_relation_records[424 * 423 + i]
    status = pari_connected_hnfadd_acceptance(
        hnf_result_h,
        9,
        hnf_result_dep,
        hnf_result_b,
        408,
        hnf_result_c,
        423,
        2,
        hnf_perm,
        424,
        terminal_new_relations,
        7,
        integer_buffer_view(collector_log_embeddings, 14 * 423, 14 * 7),
        terminal_top,
        terminal_exact_product,
        terminal_log_product,
        terminal_adjusted_logs,
        terminal_joined,
        terminal_joined_logs,
        terminal_rank_matrix,
        terminal_occupied,
        terminal_pivots,
        terminal_best,
        terminal_profile,
        terminal_rank_state,
        terminal_perm_work,
        terminal_matb,
        terminal_new_dep,
        terminal_permuted_b,
        terminal_full_h,
        terminal_transform,
        terminal_lam,
        terminal_d,
        terminal_hnf_state,
        terminal_full_dep,
        terminal_work_b,
        terminal_work_c,
        terminal_diagonal,
        terminal_final_c,
        terminal_result_h,
        terminal_result_dep,
        terminal_result_b,
        terminal_result_c,
        terminal_final_state,
        terminal_state,
        3,
        analytic_inverse_hr,
        terminal_accept_logs,
        terminal_accept_class_number,
        terminal_accept_zeta_factor,
        terminal_accept_post_hnf_state,
        terminal_accept_prepared,
        terminal_accept_selected,
        terminal_accept_prep_state,
        terminal_accept_rank_work,
        terminal_accept_rank_occupied,
        terminal_accept_rank_pivots,
        terminal_accept_rank_state,
        terminal_accept_integer_input,
        terminal_accept_integer_work,
        terminal_accept_integer_occupied,
        terminal_accept_integer_pivots,
        terminal_accept_integer_best,
        terminal_accept_integer_state,
        terminal_accept_basis,
        terminal_accept_minor,
        terminal_accept_det_work,
        terminal_accept_det_result,
        terminal_accept_det_pivots,
        terminal_accept_det_state,
        terminal_accept_inverse_work,
        terminal_accept_inverse_rhs,
        terminal_accept_inverse,
        terminal_accept_inverse_pivots,
        terminal_accept_inverse_state,
        terminal_accept_product,
        terminal_accept_inverse_slice,
        terminal_accept_multiple,
        terminal_accept_coordinates,
        terminal_accept_multiple_state,
        terminal_accept_rational_work,
        terminal_accept_lattice,
        terminal_accept_hnf_work,
        terminal_accept_hnf_column,
        terminal_accept_hnf_output,
        terminal_accept_hnf_state,
        terminal_accept_regulator,
        terminal_accept_relations,
        terminal_accept_denominator,
        terminal_accept_reconstruction_state,
        terminal_accept_hnf_row_pivots,
        terminal_accept_hnf_heights,
        True,
        terminal_accept_acceptance_state,
        terminal_attempt_state,
    )
    if status != -2 or terminal_attempt_state[1] != -2:
        return 90 + status
    status = pari_row19_hnfadd_cup_suffix(
        terminal_joined,
        16,
        16,
        terminal_joined_logs,
        hnf_result_c,
        2,
        terminal_permuted_b,
        408,
        hnf_perm,
        423,
        7,
        terminal_rank_matrix,
        terminal_occupied,
        terminal_pivots,
        terminal_best,
        terminal_profile,
        terminal_rank_state,
        cup_cup_arena,
        cup_cup_frames,
        cup_cup_solve_state,
        cup_cup_state,
        terminal_perm_work,
        terminal_matb,
        terminal_new_dep,
        terminal_permuted_b,
        terminal_full_h,
        terminal_transform,
        terminal_lam,
        terminal_d,
        terminal_hnf_state,
        terminal_full_dep,
        terminal_work_b,
        terminal_work_c,
        terminal_diagonal,
        terminal_final_c,
        terminal_result_h,
        terminal_result_dep,
        terminal_result_b,
        terminal_result_c,
        terminal_final_state,
        terminal_state,
    )
    if status != 0:
        return 100 + status
    status = pari_post_hnf_acceptance(
        424,
        9,
        415,
        430,
        2,
        3,
        terminal_result_h,
        terminal_result_c,
        analytic_inverse_hr,
        terminal_accept_logs,
        terminal_accept_class_number,
        terminal_accept_zeta_factor,
        terminal_accept_post_hnf_state,
        terminal_accept_prepared,
        terminal_accept_selected,
        terminal_accept_prep_state,
        terminal_accept_rank_work,
        terminal_accept_rank_occupied,
        terminal_accept_rank_pivots,
        terminal_accept_rank_state,
        terminal_accept_integer_input,
        terminal_accept_integer_work,
        terminal_accept_integer_occupied,
        terminal_accept_integer_pivots,
        terminal_accept_integer_best,
        terminal_accept_integer_state,
        terminal_accept_basis,
        terminal_accept_minor,
        terminal_accept_det_work,
        terminal_accept_det_result,
        terminal_accept_det_pivots,
        terminal_accept_det_state,
        terminal_accept_inverse_work,
        terminal_accept_inverse_rhs,
        terminal_accept_inverse,
        terminal_accept_inverse_pivots,
        terminal_accept_inverse_state,
        terminal_accept_product,
        terminal_accept_inverse_slice,
        terminal_accept_multiple,
        terminal_accept_coordinates,
        terminal_accept_multiple_state,
        terminal_accept_rational_work,
        terminal_accept_lattice,
        terminal_accept_hnf_work,
        terminal_accept_hnf_column,
        terminal_accept_hnf_output,
        terminal_accept_hnf_state,
        terminal_accept_regulator,
        terminal_accept_relations,
        terminal_accept_denominator,
        terminal_accept_reconstruction_state,
        terminal_accept_hnf_row_pivots,
        terminal_accept_hnf_heights,
        True,
        terminal_accept_acceptance_state,
    )
    if status != 0:
        return 110 + status
    terminal_attempt_state[0] = 3
    terminal_attempt_state[1] = status
    terminal_attempt_state[2] = terminal_accept_multiple_state[1]
    factor_relation_state[4] = 430
    status = pari_row19_phase6_resident_class_private(
        class_manifest,
        terminal_result_h,
        class_invariants_output,
        class_class_number_output,
        class_m1_output,
        class_uir_output,
        class_class_state_output,
    )
    if status != 0:
        return 120 + status
    status = pari_row19_phase6_resident_kernel_private(
        kernel_manifest,
        factor_relation_records,
        hnf_transform,
        hnf_hnf_transform,
        hnf_full_h,
        hnf_full_dep,
        hnf_b,
        hnf_diagonal,
        terminal_transform,
        terminal_full_h,
        terminal_full_dep,
        terminal_permuted_b,
        terminal_diagonal,
        hnf_perm,
        terminal_result_h,
        kernel_workspace,
        kernel_kernel_output,
        kernel_presentation_output,
        kernel_state_output,
    )
    if status != 0:
        return 130 + status
    status = pari_row19_phase6_resident_unit_private(
        unit_manifest,
        kernel_kernel_output,
        collector_log_embeddings,
        terminal_accept_regulator,
        factor_relation_generators,
        unit_dependency_output,
        unit_inverse_output,
        unit_multiples_output,
        unit_state_output,
    )
    if status != 0:
        return 140 + status
    status = pari_row19_phase6_resident_witness_private(
        witness_manifest,
        kernel_presentation_output,
        class_m1_output,
        class_uir_output,
        class_invariants_output,
        factor_relation_records,
        factor_relation_generators,
        hnf_perm,
        witness_coefficients_output,
        witness_valuations_output,
        witness_support_output,
        witness_state_output,
    )
    if status != 0:
        return 150 + status
    return 0


__all__ = ["pari_row19_phase6_prepared_aggregate_root"]
