#!/usr/bin/env node
"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),zlib=require("node:zlib");
const {spawnSync}=require("node:child_process"),{compileKernel}=require("../../tools/native-kernel/compiler.cjs"),{authenticatePackedLogCheckpoint,embedHnfInputColumn,reverseHnfFinal,reverseSchedule}=require("./relation_column_ancestry.cjs");
const ROOT=path.resolve(__dirname,"../.."),ROWS=799,COLUMNS=806,PLACES=3;
const PYTHON=fs.realpathSync("/usr/bin/python3");
const STARTED=Date.now();
const OWNER_SHA="9a24358fc2846778c7940df1be206a18048780375a60f6e9edf039b36c770b65",METADATA_SHA="cca3c14630fc91a407a052bbc7fb2799b5e95bce79f1948fc422ca39cda07684";
const sha=x=>crypto.createHash("sha256").update(x).digest("hex"),view=x=>x.toArray?x.toArray():Array.from(x);
function signature(source,name){const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),match=fs.readFileSync(source,"utf8").match(new RegExp(`def ${escaped}\\(([\\s\\S]*?)\\n\\)`));assert(match,`missing ${name}`);return match[1].trim().split("\n").map(line=>line.trim().replace(/,$/,"").split(": "));}
async function compiled(file,name){const source=path.join(__dirname,file),built=await compileKernel({sourcePath:source}),fn=require(built.modulePath)[name];assert(fn?.nativeAvailable);return{fn,names:signature(source,name)};}
function words(values,minimum=1){return values.reduce((a,x)=>{let v=BigInt(x);if(v<0n)v=-v;return Math.max(a,Math.ceil(Math.max(1,v.toString(2).length)/64));},minimum);}
function allocate(kernel,names,lengths,explicit={},capacity=16){const out={};for(const[name,kind]of names){if(!kind.endsWith("Buffer")){out[name]=typeof explicit[name]==="boolean"?explicit[name]:BigInt(explicit[name]);continue;}const supplied=explicit[name],length=supplied===undefined?lengths[name]:supplied.length;assert.notEqual(length,undefined,`missing length ${name}`);if(kind==="Int64Buffer")out[name]=kernel.createInt64Buffer(supplied===undefined?length:supplied.map(BigInt));else out[name]=kernel.createIntegerBuffer(length,supplied===undefined?capacity:words(supplied,capacity),supplied===undefined?undefined:supplied.map(BigInt));}return out;}
function hnfStep(v,rows,depRows,columns,tail,trailingName,transformName,fullHName,fullDepName,diagonalName){return{rows,depRows,columns,tail,trailing:view(v[trailingName]).slice(0,(rows+depRows)*tail),transform:view(v[transformName]).slice(0,columns*columns),fullH:view(v[fullHName]).slice(0,rows*columns),fullDep:view(v[fullDepName]).slice(0,depRows*columns),diagonal:view(v[diagonalName]).slice(0,rows)};}
function relationProduct(records,columns,coefficients){const output=Array(ROWS).fill(0n);for(let source=0;source<columns;source++){const coefficient=coefficients[source];if(!coefficient)continue;for(let row=0;row<ROWS;row++)output[row]+=coefficient*records[source*ROWS+row];}return output;}
function expectedPublishedColumn(perm,dep,h,depRows,hRows,column){const output=Array(ROWS).fill(0n);for(let row=0;row<depRows;row++)output[Number(perm[row])-1]=dep[column*depRows+row];for(let row=0;row<hRows;row++)output[Number(perm[depRows+row])-1]=h[column*hRows+row];return output;}
function initialAssemblyProduct(iv,coefficients){return embedHnfInputColumn(coefficients,{totalRows:ROWS,genuineRows:108,dependentRows:4,width:115,tail:687,dependent:view(iv.dep).slice(0,460),active:view(iv.matbnew).slice(0,12420),trailing:view(iv.b).slice(0,76944),preHnfPermutation:Array.from(iv.perm_work).slice(0,112),postHnfPermutation:Array.from(iv.perm).slice(112)});}
function appendAssemblyProduct(av,coefficients,genuine,redundant,width,tailColumns){const lig=genuine+redundant;return embedHnfInputColumn(coefficients,{totalRows:ROWS,genuineRows:genuine,dependentRows:redundant,width,tail:tailColumns,dependent:view(av.new_dep).slice(0,width*redundant),active:view(av.matb).slice(0,width*genuine),trailing:view(av.permuted_b).slice(0,lig*tailColumns),preHnfPermutation:Array.from(av.perm_work).slice(0,lig),postHnfPermutation:Array.from(av.perm).slice(lig)});}
function logCheckpoint(owner,columns,state,values){const checkpoint=owner.schedule.checkpoints.find(entry=>entry.columns===columns);assert(checkpoint,`missing accepted ${columns} checkpoint`);assert.deepEqual(state,checkpoint.state);const strings=values.map(String),digest=authenticatePackedLogCheckpoint(strings,checkpoint.hashes.c),mutated=strings.slice();mutated[0]=(BigInt(mutated[0])+1n).toString();assert.throws(()=>authenticatePackedLogCheckpoint(mutated,checkpoint.hashes.c),/hash changed/);return{columns,cells:strings.length,sha256:digest,sourceOrderPreserved:true,mutationRejected:true};}
async function sourceAncestry(owner,metadata){
 const records=owner.final.records.map(BigInt),logs=owner.final.logs.map(BigInt),initialColumns=802;
 const initial=await compiled("hnfspec_complete.py","pari_hnfspec_complete"),k0=Number(metadata.policy.hnfK0),size=ROWS*initialColumns;
 const lengths={mat:size,dense:k0*initialColumns,transform:initialColumns**2,vmax:initialColumns,found:1,sparse_state:13,bottom:(ROWS-k0)*initialColumns,updated_dense:k0*initialColumns,extra:size,cleanup_state:10,rank_matrix:size,occupied:initialColumns,pivots:ROWS,best:ROWS,profile:ROWS+1,rank_state:10,perm_work:ROWS,matbnew:size,dep:size,b:size,assembly_state:6,transformed_logs:21*initialColumns,full_h:size,hnf_transform:initialColumns**2,lam:initialColumns**2,d:initialColumns+1,hnf_state:11,full_dep:size,work_b:size,work_c:21*initialColumns,diagonal:ROWS,result_h:size,result_dep:size,result_b:ROWS*(initialColumns+ROWS),result_c:21*initialColumns,final_state:7,state:9,cup_arena:2881440,cup_frames:64,cup_solve_state:8,cup_state:8};
 const explicit={original:records.slice(0,size),rows:ROWS,columns:initialColumns,perm:metadata.factor.permutation,k0,logs:logs.slice(0,21*initialColumns),log_rows:PLACES};
 const iv=allocate(initial.fn,initial.names,lengths,explicit);assert.equal(initial.fn.gmp(...initial.names.map(([n])=>iv[n])),0n);
 const initialState=Array.from(iv.state,Number);assert.deepEqual(initialState,[3,10,792,4,7,105,0,802,0]);
 let resident={state:initialState,perm:view(iv.perm),h:view(iv.result_h).slice(0,9),dep:view(iv.result_dep).slice(0,12),b:view(iv.result_b).slice(0,7*792),c:view(iv.result_c).slice(0,21*802)};
 const logProvenance=[logCheckpoint(owner,802,resident.state,resident.c)];
 const initialStep={columns:initialColumns,cleanupTransform:view(iv.transform).slice(0,initialColumns**2),hnf:hnfStep(iv,108,4,115,687,"b","hnf_transform","full_h","full_dep","diagonal")};
 const assembly=Array.from(iv.assembly_state,Number);assert.deepEqual(assembly,[108,4,115,112,687,0]);
 if(process.argv.includes("--audit-initial")){
  const checks=[];
  for(let column=0;column<3;column++){
   const selected=Array(initialColumns).fill(0n);selected[7+column]=1n;
   const cleaned=reverseHnfFinal(selected,initialStep.hnf),raw=Array(initialColumns).fill(0n);
   for(let source=0;source<initialColumns;source++)for(let target=0;target<initialColumns;target++)raw[source]+=initialStep.cleanupTransform[target*initialColumns+source]*cleaned[target];
   const expected=expectedPublishedColumn(resident.perm,resident.dep,resident.h,4,3,column);
   assert.deepEqual(initialAssemblyProduct(iv,cleaned),expected,`initial hnffinal capture column ${column}`);
   assert.deepEqual(relationProduct(records,initialColumns,raw),expected,`initial cleanup capture column ${column}`);
   checks.push({column,cleanedNonzero:cleaned.filter(Boolean).length,rawNonzero:raw.filter(Boolean).length});
  }
  return{schema:"sagejs.pari-class-group/row14-column-ancestry-initial-audit-v1",assembly,hnfShape:[108,4,115,687],checks,state:initialState};
 }
 const append=await compiled("hnfadd.py","pari_hnfadd"),appendSteps=[];
 for(const nextTotal of[804,805,806]){const oldTotal=resident.state[7],newColumns=nextTotal-oldTotal,hRows=resident.state[0],bColumns=resident.state[2],lig=ROWS-bColumns,width=hRows+newColumns,cWidth=width+bColumns,depRows=lig-hRows,newRelations=records.slice(oldTotal*ROWS,nextTotal*ROWS);
  const al={top:lig*newColumns,exact_product:lig*newColumns,log_product:21*newColumns,adjusted_logs:21*newColumns,joined:lig*width,joined_logs:21*cWidth,rank_matrix:lig*width,occupied:width,pivots:lig,best:lig,profile:lig,rank_state:10,perm_work:ROWS,matb:lig*width,new_dep:lig*width,permuted_b:lig*bColumns,full_h:lig*width,transform:width*width,lam:width*width,d:width+1,hnf_state:11,full_dep:lig*width,work_b:lig*bColumns,work_c:21*cWidth,diagonal:lig,final_c:21*cWidth,result_h:lig*lig,result_dep:lig*lig,result_b:lig*(bColumns+lig),result_c:21*nextTotal,final_state:7,state:9};
  const ae={h:resident.h,h_rows:hRows,dep:resident.dep,b:resident.b,b_columns:bColumns,logs:resident.c,total_columns:oldTotal,log_rows:PLACES,perm:resident.perm,rows:ROWS,new_relations:newRelations,new_columns:newColumns,new_logs:logs.slice(oldTotal*21,nextTotal*21)};
  const av=allocate(append.fn,append.names,al,ae),beforePerm=resident.perm.slice();assert.equal(append.fn.gmp(...append.names.map(([n])=>av[n])),0n);
  const rankState=view(av.rank_state).map(Number),redundant=rankState[7];assert.equal(rankState[2],redundant);assert.equal(rankState[8],lig);assert(Number.isSafeInteger(redundant)&&redundant>=0&&redundant<=lig);const genuine=lig-redundant,appendStep={oldTotal,newColumns,zeroPrefix:oldTotal-bColumns-hRows,hRows,bColumns,perm:beforePerm,newRelations,rows:ROWS,hnf:hnfStep(av,genuine,redundant,width,bColumns,"permuted_b","transform","full_h","full_dep","diagonal")};appendSteps.push(appendStep);
  const state=Array.from(av.state,Number),newH=state[0],newB=state[2],newDep=ROWS-newB-newH;resident={state,perm:Array.from(av.perm),h:view(av.result_h).slice(0,newH*newH),dep:view(av.result_dep).slice(0,newDep*newH),b:view(av.result_b).slice(0,(ROWS-newB)*newB),c:view(av.result_c).slice(0,21*nextTotal)};
  logProvenance.push(logCheckpoint(owner,nextTotal,resident.state,resident.c));
  const auditTarget=process.argv.includes("--audit-append-804")?804:process.argv.includes("--audit-append-805")?805:process.argv.includes("--audit-append-806")?806:0;if(auditTarget===nextTotal){const checks=[];for(let column=0;column<newH;column++){const selectedColumn=state[4]+column,selected=Array(nextTotal).fill(0n);selected[selectedColumn]=1n;const localOutput=selected.slice(appendStep.zeroPrefix),localInput=reverseHnfFinal(localOutput,appendStep.hnf),expected=expectedPublishedColumn(resident.perm,resident.dep,resident.h,newDep,newH,column);assert.deepEqual(appendAssemblyProduct(av,localInput,genuine,redundant,width,bColumns),expected,`${nextTotal} hnffinal capture column ${column}`);const raw=reverseSchedule(nextTotal,[selectedColumn],initialStep,appendSteps)[0];assert.deepEqual(relationProduct(records,nextTotal,raw),expected,`${nextTotal} composed ancestry column ${column}`);checks.push({column,localNonzero:localInput.filter(Boolean).length,rawNonzero:raw.filter(Boolean).length});}return{schema:`sagejs.pari-class-group/row14-column-ancestry-${nextTotal}-audit-v1`,rankState,preHnfShape:[genuine,redundant,width,bColumns],state,checks};}
 }
 assert.deepEqual(resident.state,[3,10,796,0,7,0,0,806,0]);assert.deepEqual(resident.h.map(String),owner.final.h);assert.deepEqual(resident.c.map(String),owner.final.c);assert.deepEqual(resident.perm.map(String),owner.final.perm);
 const transforms=reverseSchedule(COLUMNS,Array.from({length:10},(_,i)=>i),initialStep,appendSteps),unit=transforms.slice(0,7),klass=transforms.slice(7);
 for(const vector of unit)for(let row=0;row<ROWS;row++)assert.equal(vector.reduce((s,v,c)=>s+v*records[c*ROWS+row],0n),0n);
 const active=owner.final.perm.slice(0,3).map(x=>Number(x)-1);for(let col=0;col<3;col++)for(let row=0;row<ROWS;row++){const actual=klass[col].reduce((s,v,k)=>s+v*records[k*ROWS+row],0n),i=active.indexOf(row),expected=i<0?0n:BigInt(owner.final.h[col*3+i]);assert.equal(actual,expected);}
 assert.deepEqual(resident.c.map(String),owner.final.c);
 return{schema:"sagejs.pari-class-group/row14-column-ancestry-v1",rawToUnitKernel:unit.flat().map(String),rawToPresentation:klass.flat().map(String),state:{backend:"source-hnfspec-hnfadd-reverse-replay",selectedColumns:10,kernelColumns:7,classColumns:3,relationReplayCells:ROWS*10,packedLogProvenance:{arithmetic:"source-stage-order",pathDependent:true,oneShotRawTransformAuthoritative:false,rawToUnitKernelAuthority:"integer relation kernel R*T=0",terminalPackedEquality:true,checkpoints:logProvenance,mutationsRejected:logProvenance.length},relationCollectionRerun:false,frozenW0UsedAsInput:false}};
}
(async()=>{const auditInitial=process.argv.includes("--audit-initial"),auditAppend=[804,805,806].some(stage=>process.argv.includes(`--audit-append-${stage}`)),audit=auditInitial||auditAppend;if(process.argv.length!==(audit?6:5))throw new Error("usage: coordinator ACCEPTED METADATA OUTPUT_DIR [--audit-initial|--audit-append-804|--audit-append-805|--audit-append-806]");const[acceptedPath,metadataPath,outputDir]=process.argv.slice(2),plain=zlib.gunzipSync(fs.readFileSync(acceptedPath));assert.equal(sha(plain),OWNER_SHA);const owner=JSON.parse(plain),receipt=JSON.parse(fs.readFileSync(metadataPath));assert.equal(receipt.metadataSha256,METADATA_SHA);const ancestry=await sourceAncestry(owner,receipt.metadata);if(audit){process.stdout.write(`${JSON.stringify({...ancestry,coordinatorElapsedMs:Date.now()-STARTED,coordinatorMaxRssKiB:process.resourceUsage().maxRSS})}\n`);return;}const temporary=fs.mkdtempSync(path.join(os.tmpdir(),"sagejs-row14-ancestry-")),transformPath=path.join(temporary,"transform.json");fs.writeFileSync(transformPath,JSON.stringify(ancestry));fs.mkdirSync(outputDir,{recursive:true});assert.deepEqual(fs.readdirSync(outputDir),[],"terminal class output directory is not empty");const child=spawnSync("timeout",["600","prlimit","--as=4294967296","--rss=4294967296","--cpu=600","--",PYTHON,path.join(__dirname,"row14_terminal_class_owner.py"),acceptedPath,metadataPath,transformPath,outputDir],{cwd:ROOT,encoding:"utf8",timeout:610000,maxBuffer:256*1024*1024});fs.rmSync(temporary,{recursive:true,force:true});if(child.status!==0)throw new Error(child.stderr||child.stdout||String(child.error));const publication=JSON.parse(child.stdout.trim().split(/\r?\n/).at(-1));process.stdout.write(`${JSON.stringify({...publication,childLauncher:PYTHON,coordinatorElapsedMs:Date.now()-STARTED,coordinatorMaxRssKiB:process.resourceUsage().maxRSS,limits:{timeoutSeconds:600,addressSpaceGiB:4,rssGiB:4,cpuSeconds:600}})}\n`);})().catch(error=>{console.error(error.stack||error);process.exitCode=1;});
