"""Generated resident row-21 prepared input through exact units.

Copyright (C) The PARI group. GPL-2.0-or-later, without warranty.
Generated mechanically by row21_phase6_unit_source.cjs.
"""

from sagejs.native import IntegerBuffer, Int64Buffer, integer_buffer_view, native

from .log_matrix_transform import pari_log_matrix_transform
from .row20_successful_c6 import pari_getfu_quintic_unit_inverse
from .row21_native_supported_ideal_maps import _row21_bareiss_determinant
from .row21_phase6_acceptance_root_generated import pari_row21_phase6_acceptance_root
from .row21_rank3_getfu import pari_getfu_rank3_mixed_quintic
from .row21_rank3_unit_lattice import (
    pari_cleanarchunit_31_quintic,
    pari_prepare_getfu_31_quintic,
    pari_unit_compose_rank_three,
    pari_unit_integer_lattice_rank_three,
    pari_unit_real_lattice_rank_three,
)


@native
def pari_row21_phase6_unit_root(
    fb_polynomial: IntegerBuffer,
    fb_basis_table: IntegerBuffer,
    fb_matrix_m: IntegerBuffer,
    fb_matrix_p: IntegerBuffer,
    fb_matrix_e: IntegerBuffer,
    fb_discriminant: int,
    fb_equation_index: int,
    fb_primes: IntegerBuffer,
    fb_prime_count: int,
    fb_descriptor_workspace: IntegerBuffer,
    fb_descriptor_scratch: IntegerBuffer,
    fb_descriptor_ranks: IntegerBuffer,
    fb_descriptor_state: IntegerBuffer,
    fb_degree_scratch: IntegerBuffer,
    fb_exponent_scratch: IntegerBuffer,
    fb_factor_workspace: IntegerBuffer,
    fb_factor_state: IntegerBuffer,
    fb_pattern_offsets: IntegerBuffer,
    fb_pattern_counts: IntegerBuffer,
    fb_pattern_degrees: IntegerBuffer,
    fb_pattern_multiplicities: IntegerBuffer,
    fb_full_offsets: IntegerBuffer,
    fb_full_counts: IntegerBuffer,
    fb_full_degrees: IntegerBuffer,
    fb_configuration: Float64Buffer,
    fb_bound_norms: IntegerBuffer,
    fb_constants_logs: Float64Buffer,
    fb_sums: Float64Buffer,
    fb_factor_logs: Float64Buffer,
    fb_selected_primes: IntegerBuffer,
    fb_prime_offsets: IntegerBuffer,
    fb_prime_counts: IntegerBuffer,
    fb_complete_groups: IntegerBuffer,
    fb_selected_indices: IntegerBuffer,
    fb_base_state: IntegerBuffer,
    fb_selected_descriptors: IntegerBuffer,
    fb_selected_ideals: IntegerBuffer,
    fb_selected_norms: IntegerBuffer,
    fb_group_offsets: IntegerBuffer,
    fb_group_sizes: IntegerBuffer,
    fb_group_complete: IntegerBuffer,
    fb_hnf_multiplication: IntegerBuffer,
    fb_hnf_work: IntegerBuffer,
    fb_hnf_pivots: IntegerBuffer,
    fb_subfactor_bad: IntegerBuffer,
    fb_subfactor_configuration: Float64Buffer,
    fb_subfactor_order: IntegerBuffer,
    fb_subfactor_scratch: IntegerBuffer,
    fb_subfactor_stack: IntegerBuffer,
    fb_subfactor_chosen: IntegerBuffer,
    fb_subfactor_rejected: IntegerBuffer,
    fb_permutation: IntegerBuffer,
    fb_subfactor_state: IntegerBuffer,
    fb_relation_ramification: IntegerBuffer,
    fb_relation_state: IntegerBuffer,
    fb_relation_basis: IntegerBuffer,
    fb_relation_records: IntegerBuffer,
    fb_relation_hashes: IntegerBuffer,
    fb_relation_metadata: IntegerBuffer,
    fb_relation: IntegerBuffer,
    fb_relation_scratch: IntegerBuffer,
    fb_relation_generators: IntegerBuffer,
    fb_frontier_state: IntegerBuffer,
    fb_resident_state: IntegerBuffer,
    h_matrix: IntegerBuffer,
    h_ideal: IntegerBuffer,
    h_n: int,
    h_precision: int,
    h_scale: float,
    h_track_small: int,
    h_reduction: IntegerBuffer,
    h_vectors: IntegerBuffer,
    h_betas: IntegerBuffer,
    h_norms: IntegerBuffer,
    h_column: IntegerBuffer,
    h_float_q: Float64Buffer,
    h_float_v: Float64Buffer,
    h_bound: Float64Buffer,
    h_cache: IntegerBuffer,
    h_a: IntegerBuffer,
    h_b: IntegerBuffer,
    h_p: IntegerBuffer,
    h_q: IntegerBuffer,
    h_stack: IntegerBuffer,
    h_x: Int64Buffer,
    h_y: Float64Buffer,
    h_z: Float64Buffer,
    h_inc: Int64Buffer,
    h_state: Int64Buffer,
    h_cursor_output: Int64Buffer,
    h_element: IntegerBuffer,
    h_counters: Int64Buffer,
    h_admission_embedding_m: IntegerBuffer,
    h_admission_embedding_p: IntegerBuffer,
    h_admission_embedding_e: IntegerBuffer,
    h_admission_real_count: int,
    h_admission_ideal: IntegerBuffer,
    h_admission_mode: int,
    h_admission_primes: IntegerBuffer,
    h_admission_products: IntegerBuffer,
    h_admission_factorlimit: int,
    h_admission_prime_limit: int,
    h_admission_rational_factors: IntegerBuffer,
    h_admission_rational_exponents: IntegerBuffer,
    h_admission_group_tau: IntegerBuffer,
    h_admission_group_e: IntegerBuffer,
    h_admission_group_f: IntegerBuffer,
    h_admission_group_inert: IntegerBuffer,
    h_admission_tau: IntegerBuffer,
    h_admission_x: IntegerBuffer,
    h_admission_y: IntegerBuffer,
    h_admission_spare: IntegerBuffer,
    h_admission_stack: IntegerBuffer,
    h_admission_primitive: IntegerBuffer,
    h_admission_columns: IntegerBuffer,
    h_admission_values: IntegerBuffer,
    h_admission_temporary: IntegerBuffer,
    h_admission_indices: IntegerBuffer,
    h_admission_exponents: IntegerBuffer,
    h_diagnostic: IntegerBuffer,
    h_nrelid: int,
    h_track_fact: int,
    h_jid0: int,
    h_e0: int,
    h_subfactor: IntegerBuffer,
    h_extra: IntegerBuffer,
    h_extra_count: int,
    h_relation_primes: IntegerBuffer,
    h_ramification: IntegerBuffer,
    h_relation: IntegerBuffer,
    h_relation_state: IntegerBuffer,
    h_relation_basis: IntegerBuffer,
    h_relation_records: IntegerBuffer,
    h_relation_hashes: IntegerBuffer,
    h_relation_metadata: IntegerBuffer,
    h_relation_scratch: IntegerBuffer,
    h_generators: IntegerBuffer,
    h_progress: Int64Buffer,
    h_preparation_rounded_embedding: IntegerBuffer,
    h_preparation_embedding: IntegerBuffer,
    h_preparation_original: IntegerBuffer,
    h_preparation_basis: IntegerBuffer,
    h_preparation_transform: IntegerBuffer,
    h_preparation_flags: IntegerBuffer,
    h_preparation_rank_diagnostic: IntegerBuffer,
    h_preparation_selection: IntegerBuffer,
    h_preparation_stages: IntegerBuffer,
    h_preparation_flatter_input: IntegerBuffer,
    h_preparation_current: IntegerBuffer,
    h_preparation_flatter_transform: IntegerBuffer,
    h_preparation_total_work: IntegerBuffer,
    h_preparation_step_t: IntegerBuffer,
    h_preparation_step_s: IntegerBuffer,
    h_preparation_product: IntegerBuffer,
    h_preparation_next_basis: IntegerBuffer,
    h_preparation_y: IntegerBuffer,
    h_preparation_diagnostic: IntegerBuffer,
    h_preparation_r1: IntegerBuffer,
    h_preparation_r2: IntegerBuffer,
    h_preparation_r3: IntegerBuffer,
    h_preparation_t1: IntegerBuffer,
    h_preparation_t2: IntegerBuffer,
    h_preparation_t3: IntegerBuffer,
    h_preparation_integers: IntegerBuffer,
    h_preparation_inverse: IntegerBuffer,
    h_preparation_first: IntegerBuffer,
    h_preparation_second: IntegerBuffer,
    h_preparation_final: IntegerBuffer,
    h_preparation_rounded: IntegerBuffer,
    h_preparation_mu: Float64Buffer,
    h_preparation_r: Float64Buffer,
    h_preparation_s: Float64Buffer,
    h_preparation_approximate: Float64Buffer,
    h_preparation_exponents: IntegerBuffer,
    h_preparation_float_gram: Float64Buffer,
    h_preparation_gram: IntegerBuffer,
    h_preparation_mu_exponents: IntegerBuffer,
    h_preparation_r_exponents: IntegerBuffer,
    h_preparation_s_exponents: IntegerBuffer,
    h_preparation_alpha: IntegerBuffer,
    h_preparation_column_exponents: IntegerBuffer,
    h_preparation_float_scratch: Float64Buffer,
    h_preparation_temporary: Float64Buffer,
    h_preparation_state: Int64Buffer,
    h_search_ideals: IntegerBuffer,
    h_search_count: int,
    h_packet_ids: IntegerBuffer,
    h_schedule: Int64Buffer,
    h_construct_primes: int,
    h_packet_primes: IntegerBuffer,
    h_packet_generators: IntegerBuffer,
    h_packet_inert: IntegerBuffer,
    h_hnf_generator: IntegerBuffer,
    h_hnf_matrix: IntegerBuffer,
    h_hnf_work: IntegerBuffer,
    h_hnf_pivots: IntegerBuffer,
    h_power_ideal: IntegerBuffer,
    h_power_alpha: IntegerBuffer,
    h_power_metadata: IntegerBuffer,
    h_power_primitive: IntegerBuffer,
    h_power_temporary: IntegerBuffer,
    h_power_diagnostic: IntegerBuffer,
    h_power_multiplication: IntegerBuffer,
    h_power_work: IntegerBuffer,
    h_power_triangular: IntegerBuffer,
    h_power_moduli: IntegerBuffer,
    h_product_primitive: IntegerBuffer,
    h_product_matrix: IntegerBuffer,
    h_outer_mode: int,
    h_outer_ru: int,
    h_outer_state: Int64Buffer,
    h_outer_minidx: IntegerBuffer,
    h_outer_present: IntegerBuffer,
    h_outer_live: IntegerBuffer,
    h_outer_perm: IntegerBuffer,
    h_outer_multiplier: IntegerBuffer,
    h_log_precision: int,
    h_log_completed: IntegerBuffer,
    h_log_embeddings: IntegerBuffer,
    h_log_coordinates: IntegerBuffer,
    h_log_column: IntegerBuffer,
    h_log_cache: IntegerBuffer,
    h_log_pi_cache: IntegerBuffer,
    h_log_a: IntegerBuffer,
    h_log_b: IntegerBuffer,
    h_log_p: IntegerBuffer,
    h_log_q: IntegerBuffer,
    h_log_stack: IntegerBuffer,
    h_initial_additional: int,
    h_initial_target: int,
    h_hnf_k0: int,
    h_hnf_original: Int64Buffer,
    h_hnf_perm: Int64Buffer,
    h_hnf_mat: Int64Buffer,
    h_hnf_dense: IntegerBuffer,
    h_hnf_transform: IntegerBuffer,
    h_hnf_vmax: Int64Buffer,
    h_hnf_found: Int64Buffer,
    h_hnf_sparse_state: Int64Buffer,
    h_hnf_bottom: IntegerBuffer,
    h_hnf_updated_dense: IntegerBuffer,
    h_hnf_extra: IntegerBuffer,
    h_hnf_cleanup_state: Int64Buffer,
    h_hnf_rank_matrix: IntegerBuffer,
    h_hnf_occupied: IntegerBuffer,
    h_hnf_rank_pivots: IntegerBuffer,
    h_hnf_best: IntegerBuffer,
    h_hnf_profile: IntegerBuffer,
    h_hnf_rank_state: IntegerBuffer,
    h_hnf_perm_work: Int64Buffer,
    h_hnf_matbnew: IntegerBuffer,
    h_hnf_dep: IntegerBuffer,
    h_hnf_b: IntegerBuffer,
    h_hnf_assembly_state: Int64Buffer,
    h_hnf_transformed_logs: IntegerBuffer,
    h_hnf_full_h: IntegerBuffer,
    h_hnf_hnf_transform: IntegerBuffer,
    h_hnf_lam: IntegerBuffer,
    h_hnf_d: IntegerBuffer,
    h_hnf_hnf_state: Int64Buffer,
    h_hnf_full_dep: IntegerBuffer,
    h_hnf_work_b: IntegerBuffer,
    h_hnf_work_c: IntegerBuffer,
    h_hnf_diagonal: Int64Buffer,
    h_hnf_result_h: IntegerBuffer,
    h_hnf_result_dep: IntegerBuffer,
    h_hnf_result_b: IntegerBuffer,
    h_hnf_result_c: IntegerBuffer,
    h_hnf_final_state: Int64Buffer,
    h_hnf_state: Int64Buffer,
    h_chain_state: Int64Buffer,
    h_hnf_cup_arena: IntegerBuffer,
    h_hnf_cup_frames: IntegerBuffer,
    h_hnf_cup_solve_state: Int64Buffer,
    h_hnf_cup_state: Int64Buffer,
    connected_state: IntegerBuffer,
    t_primes: IntegerBuffer,
    t_prime_count: int,
    t_workspace: IntegerBuffer,
    t_pattern_offsets: IntegerBuffer,
    t_pattern_counts: IntegerBuffer,
    t_pattern_degrees: IntegerBuffer,
    t_pattern_multiplicities: IntegerBuffer,
    t_state: IntegerBuffer,
    t_roots_of_unity: int,
    t_log_discriminant: Float64Buffer,
    t_coefficients: Float64Buffer,
    t_table: Float64Buffer,
    t_tail: Float64Buffer,
    t_logarithms: Float64Buffer,
    t_log_inverse_residue: Float64Buffer,
    t_inverse_residue: IntegerBuffer,
    t_exp_cache: IntegerBuffer,
    t_pi_cache: IntegerBuffer,
    t_a: IntegerBuffer,
    t_b: IntegerBuffer,
    t_p: IntegerBuffer,
    t_q: IntegerBuffer,
    t_stack: IntegerBuffer,
    t_inverse_hr: IntegerBuffer,
    t_analytic_state: Int64Buffer,
    t_accept_h: IntegerBuffer,
    t_accept_logs: IntegerBuffer,
    t_accept_class_number: IntegerBuffer,
    t_accept_zeta_factor: IntegerBuffer,
    t_accept_post_hnf_state: Int64Buffer,
    t_accept_prepared: IntegerBuffer,
    t_accept_selected: Int64Buffer,
    t_accept_prep_state: Int64Buffer,
    t_accept_rank_work: IntegerBuffer,
    t_accept_rank_occupied: Int64Buffer,
    t_accept_rank_pivots: Int64Buffer,
    t_accept_rank_state: Int64Buffer,
    t_accept_integer_input: IntegerBuffer,
    t_accept_integer_work: IntegerBuffer,
    t_accept_integer_occupied: IntegerBuffer,
    t_accept_integer_pivots: IntegerBuffer,
    t_accept_integer_best: IntegerBuffer,
    t_accept_integer_state: IntegerBuffer,
    t_accept_basis: IntegerBuffer,
    t_accept_minor: IntegerBuffer,
    t_accept_det_work: IntegerBuffer,
    t_accept_det_result: IntegerBuffer,
    t_accept_det_pivots: Int64Buffer,
    t_accept_det_state: Int64Buffer,
    t_accept_inverse_work: IntegerBuffer,
    t_accept_inverse_rhs: IntegerBuffer,
    t_accept_inverse: IntegerBuffer,
    t_accept_inverse_pivots: Int64Buffer,
    t_accept_inverse_state: Int64Buffer,
    t_accept_product: IntegerBuffer,
    t_accept_inverse_slice: IntegerBuffer,
    t_accept_multiple: IntegerBuffer,
    t_accept_coordinates: IntegerBuffer,
    t_accept_multiple_state: Int64Buffer,
    t_accept_rational_work: IntegerBuffer,
    t_accept_lattice: IntegerBuffer,
    t_accept_hnf_work: IntegerBuffer,
    t_accept_hnf_column: IntegerBuffer,
    t_accept_hnf_output: IntegerBuffer,
    t_accept_hnf_state: Int64Buffer,
    t_accept_regulator: IntegerBuffer,
    t_accept_relations: IntegerBuffer,
    t_accept_denominator: IntegerBuffer,
    t_accept_reconstruction_state: Int64Buffer,
    t_accept_hnf_row_pivots: Int64Buffer,
    t_accept_hnf_heights: Int64Buffer,
    t_accept_cache_changed: bool,
    t_accept_acceptance_state: Int64Buffer,
    terminal_state: IntegerBuffer,
    u_integer_basis: IntegerBuffer,
    u_integer_transform: IntegerBuffer,
    u_integer_gram: IntegerBuffer,
    u_integer_mu: Float64Buffer,
    u_integer_mu_exponents: IntegerBuffer,
    u_integer_r: Float64Buffer,
    u_integer_r_exponents: IntegerBuffer,
    u_integer_s: Float64Buffer,
    u_integer_s_exponents: IntegerBuffer,
    u_integer_approximate: Float64Buffer,
    u_integer_float_gram: Float64Buffer,
    u_integer_alpha: IntegerBuffer,
    u_integer_column: IntegerBuffer,
    u_integer_column_exponents: IntegerBuffer,
    u_integer_normalized: Float64Buffer,
    u_integer_temporary: Float64Buffer,
    u_integer_dpe_float_scratch: Float64Buffer,
    u_integer_integer_scratch: IntegerBuffer,
    u_u1: IntegerBuffer,
    u_integer_state: IntegerBuffer,
    u_first_logs: IntegerBuffer,
    u_first_triples: IntegerBuffer,
    u_real_integers: IntegerBuffer,
    u_real_basis: IntegerBuffer,
    u_real_transform: IntegerBuffer,
    u_real_gram: IntegerBuffer,
    u_real_mu: Float64Buffer,
    u_real_mu_exponents: IntegerBuffer,
    u_real_r: Float64Buffer,
    u_real_r_exponents: IntegerBuffer,
    u_real_s: Float64Buffer,
    u_real_s_exponents: IntegerBuffer,
    u_real_approximate: Float64Buffer,
    u_real_float_gram: Float64Buffer,
    u_real_alpha: IntegerBuffer,
    u_real_column: IntegerBuffer,
    u_real_column_exponents: IntegerBuffer,
    u_real_normalized: Float64Buffer,
    u_real_temporary: Float64Buffer,
    u_real_dpe_float_scratch: Float64Buffer,
    u_real_integer_scratch: IntegerBuffer,
    u_u2: IntegerBuffer,
    u_real_state: IntegerBuffer,
    u_unit_transform: IntegerBuffer,
    u_unit_logs: IntegerBuffer,
    u_clean_pi_cache: IntegerBuffer,
    u_clean_a: IntegerBuffer,
    u_clean_b: IntegerBuffer,
    u_clean_p: IntegerBuffer,
    u_clean_q: IntegerBuffer,
    u_clean_stack: IntegerBuffer,
    u_clean_scratch: IntegerBuffer,
    u_cleaned: IntegerBuffer,
    u_clean_state: IntegerBuffer,
    u_identity: IntegerBuffer,
    u_first_matep: IntegerBuffer,
    u_first_arch: IntegerBuffer,
    u_first_factored_clean: IntegerBuffer,
    u_first_arch_real: IntegerBuffer,
    u_first_arch_imag: IntegerBuffer,
    u_first_clean_real: IntegerBuffer,
    u_first_clean_imag: IntegerBuffer,
    u_getfu_triples: IntegerBuffer,
    u_getfu_real_integers: IntegerBuffer,
    u_getfu_real_basis: IntegerBuffer,
    u_getfu_real_transform: IntegerBuffer,
    u_getfu_real_gram: IntegerBuffer,
    u_getfu_real_mu: Float64Buffer,
    u_getfu_real_mu_exponents: IntegerBuffer,
    u_getfu_real_r: Float64Buffer,
    u_getfu_real_r_exponents: IntegerBuffer,
    u_getfu_real_s: Float64Buffer,
    u_getfu_real_s_exponents: IntegerBuffer,
    u_getfu_real_approximate: Float64Buffer,
    u_getfu_real_float_gram: Float64Buffer,
    u_getfu_real_alpha: IntegerBuffer,
    u_getfu_real_column: IntegerBuffer,
    u_getfu_real_column_exponents: IntegerBuffer,
    u_getfu_real_normalized: Float64Buffer,
    u_getfu_real_temporary: Float64Buffer,
    u_getfu_real_dpe_float_scratch: Float64Buffer,
    u_getfu_real_integer_scratch: IntegerBuffer,
    u_getfu_u2: IntegerBuffer,
    u_getfu_real_state: IntegerBuffer,
    u_factor: IntegerBuffer,
    u_final_matep: IntegerBuffer,
    u_final_arch: IntegerBuffer,
    u_final_factored_clean: IntegerBuffer,
    u_final_arch_real: IntegerBuffer,
    u_final_arch_imag: IntegerBuffer,
    u_final_clean_real: IntegerBuffer,
    u_final_clean_imag: IntegerBuffer,
    u_embedding_real: IntegerBuffer,
    u_embedding_imag: IntegerBuffer,
    u_getfu_exponential_real: IntegerBuffer,
    u_getfu_exponential_imag: IntegerBuffer,
    u_getfu_split_matrix: IntegerBuffer,
    u_getfu_split_rhs: IntegerBuffer,
    u_getfu_solve_work: IntegerBuffer,
    u_getfu_solve_rhs: IntegerBuffer,
    u_getfu_solved: IntegerBuffer,
    u_getfu_rounded: IntegerBuffer,
    u_getfu_multiplication: IntegerBuffer,
    u_getfu_inverse: IntegerBuffer,
    u_getfu_candidate_units: IntegerBuffer,
    u_getfu_exp_cache: IntegerBuffer,
    u_getfu_pi_cache: IntegerBuffer,
    u_getfu_a: IntegerBuffer,
    u_getfu_b: IntegerBuffer,
    u_getfu_p: IntegerBuffer,
    u_getfu_q: IntegerBuffer,
    u_getfu_stack: IntegerBuffer,
    u_output_units: IntegerBuffer,
    u_output_logs_real: IntegerBuffer,
    u_output_logs_imag: IntegerBuffer,
    u_getfu_state: Int64Buffer,
    u_getfu_pivots: Int64Buffer,
    u_inverse_multiplication: IntegerBuffer,
    u_output_inverses: IntegerBuffer,
    unit_terminal_state: Int64Buffer,
    u_norm_matrix: IntegerBuffer,
    u_norm_work: IntegerBuffer,
    u_output_norms: IntegerBuffer,
    u_output_real_signs: Int64Buffer,
) -> int:
    if len(unit_terminal_state) < 14:
        raise ValueError("short row21 unit resident state")
    for index in range(14):
        unit_terminal_state[index] = 0
    unit_terminal_state[0] = -1
    status = pari_row21_phase6_acceptance_root(
        fb_polynomial,
        fb_basis_table,
        fb_matrix_m,
        fb_matrix_p,
        fb_matrix_e,
        fb_discriminant,
        fb_equation_index,
        fb_primes,
        fb_prime_count,
        fb_descriptor_workspace,
        fb_descriptor_scratch,
        fb_descriptor_ranks,
        fb_descriptor_state,
        fb_degree_scratch,
        fb_exponent_scratch,
        fb_factor_workspace,
        fb_factor_state,
        fb_pattern_offsets,
        fb_pattern_counts,
        fb_pattern_degrees,
        fb_pattern_multiplicities,
        fb_full_offsets,
        fb_full_counts,
        fb_full_degrees,
        fb_configuration,
        fb_bound_norms,
        fb_constants_logs,
        fb_sums,
        fb_factor_logs,
        fb_selected_primes,
        fb_prime_offsets,
        fb_prime_counts,
        fb_complete_groups,
        fb_selected_indices,
        fb_base_state,
        fb_selected_descriptors,
        fb_selected_ideals,
        fb_selected_norms,
        fb_group_offsets,
        fb_group_sizes,
        fb_group_complete,
        fb_hnf_multiplication,
        fb_hnf_work,
        fb_hnf_pivots,
        fb_subfactor_bad,
        fb_subfactor_configuration,
        fb_subfactor_order,
        fb_subfactor_scratch,
        fb_subfactor_stack,
        fb_subfactor_chosen,
        fb_subfactor_rejected,
        fb_permutation,
        fb_subfactor_state,
        fb_relation_ramification,
        fb_relation_state,
        fb_relation_basis,
        fb_relation_records,
        fb_relation_hashes,
        fb_relation_metadata,
        fb_relation,
        fb_relation_scratch,
        fb_relation_generators,
        fb_frontier_state,
        fb_resident_state,
        h_matrix,
        h_ideal,
        h_n,
        h_precision,
        h_scale,
        h_track_small,
        h_reduction,
        h_vectors,
        h_betas,
        h_norms,
        h_column,
        h_float_q,
        h_float_v,
        h_bound,
        h_cache,
        h_a,
        h_b,
        h_p,
        h_q,
        h_stack,
        h_x,
        h_y,
        h_z,
        h_inc,
        h_state,
        h_cursor_output,
        h_element,
        h_counters,
        h_admission_embedding_m,
        h_admission_embedding_p,
        h_admission_embedding_e,
        h_admission_real_count,
        h_admission_ideal,
        h_admission_mode,
        h_admission_primes,
        h_admission_products,
        h_admission_factorlimit,
        h_admission_prime_limit,
        h_admission_rational_factors,
        h_admission_rational_exponents,
        h_admission_group_tau,
        h_admission_group_e,
        h_admission_group_f,
        h_admission_group_inert,
        h_admission_tau,
        h_admission_x,
        h_admission_y,
        h_admission_spare,
        h_admission_stack,
        h_admission_primitive,
        h_admission_columns,
        h_admission_values,
        h_admission_temporary,
        h_admission_indices,
        h_admission_exponents,
        h_diagnostic,
        h_nrelid,
        h_track_fact,
        h_jid0,
        h_e0,
        h_subfactor,
        h_extra,
        h_extra_count,
        h_relation_primes,
        h_ramification,
        h_relation,
        h_relation_state,
        h_relation_basis,
        h_relation_records,
        h_relation_hashes,
        h_relation_metadata,
        h_relation_scratch,
        h_generators,
        h_progress,
        h_preparation_rounded_embedding,
        h_preparation_embedding,
        h_preparation_original,
        h_preparation_basis,
        h_preparation_transform,
        h_preparation_flags,
        h_preparation_rank_diagnostic,
        h_preparation_selection,
        h_preparation_stages,
        h_preparation_flatter_input,
        h_preparation_current,
        h_preparation_flatter_transform,
        h_preparation_total_work,
        h_preparation_step_t,
        h_preparation_step_s,
        h_preparation_product,
        h_preparation_next_basis,
        h_preparation_y,
        h_preparation_diagnostic,
        h_preparation_r1,
        h_preparation_r2,
        h_preparation_r3,
        h_preparation_t1,
        h_preparation_t2,
        h_preparation_t3,
        h_preparation_integers,
        h_preparation_inverse,
        h_preparation_first,
        h_preparation_second,
        h_preparation_final,
        h_preparation_rounded,
        h_preparation_mu,
        h_preparation_r,
        h_preparation_s,
        h_preparation_approximate,
        h_preparation_exponents,
        h_preparation_float_gram,
        h_preparation_gram,
        h_preparation_mu_exponents,
        h_preparation_r_exponents,
        h_preparation_s_exponents,
        h_preparation_alpha,
        h_preparation_column_exponents,
        h_preparation_float_scratch,
        h_preparation_temporary,
        h_preparation_state,
        h_search_ideals,
        h_search_count,
        h_packet_ids,
        h_schedule,
        h_construct_primes,
        h_packet_primes,
        h_packet_generators,
        h_packet_inert,
        h_hnf_generator,
        h_hnf_matrix,
        h_hnf_work,
        h_hnf_pivots,
        h_power_ideal,
        h_power_alpha,
        h_power_metadata,
        h_power_primitive,
        h_power_temporary,
        h_power_diagnostic,
        h_power_multiplication,
        h_power_work,
        h_power_triangular,
        h_power_moduli,
        h_product_primitive,
        h_product_matrix,
        h_outer_mode,
        h_outer_ru,
        h_outer_state,
        h_outer_minidx,
        h_outer_present,
        h_outer_live,
        h_outer_perm,
        h_outer_multiplier,
        h_log_precision,
        h_log_completed,
        h_log_embeddings,
        h_log_coordinates,
        h_log_column,
        h_log_cache,
        h_log_pi_cache,
        h_log_a,
        h_log_b,
        h_log_p,
        h_log_q,
        h_log_stack,
        h_initial_additional,
        h_initial_target,
        h_hnf_k0,
        h_hnf_original,
        h_hnf_perm,
        h_hnf_mat,
        h_hnf_dense,
        h_hnf_transform,
        h_hnf_vmax,
        h_hnf_found,
        h_hnf_sparse_state,
        h_hnf_bottom,
        h_hnf_updated_dense,
        h_hnf_extra,
        h_hnf_cleanup_state,
        h_hnf_rank_matrix,
        h_hnf_occupied,
        h_hnf_rank_pivots,
        h_hnf_best,
        h_hnf_profile,
        h_hnf_rank_state,
        h_hnf_perm_work,
        h_hnf_matbnew,
        h_hnf_dep,
        h_hnf_b,
        h_hnf_assembly_state,
        h_hnf_transformed_logs,
        h_hnf_full_h,
        h_hnf_hnf_transform,
        h_hnf_lam,
        h_hnf_d,
        h_hnf_hnf_state,
        h_hnf_full_dep,
        h_hnf_work_b,
        h_hnf_work_c,
        h_hnf_diagonal,
        h_hnf_result_h,
        h_hnf_result_dep,
        h_hnf_result_b,
        h_hnf_result_c,
        h_hnf_final_state,
        h_hnf_state,
        h_chain_state,
        h_hnf_cup_arena,
        h_hnf_cup_frames,
        h_hnf_cup_solve_state,
        h_hnf_cup_state,
        connected_state,
        t_primes,
        t_prime_count,
        t_workspace,
        t_pattern_offsets,
        t_pattern_counts,
        t_pattern_degrees,
        t_pattern_multiplicities,
        t_state,
        t_roots_of_unity,
        t_log_discriminant,
        t_coefficients,
        t_table,
        t_tail,
        t_logarithms,
        t_log_inverse_residue,
        t_inverse_residue,
        t_exp_cache,
        t_pi_cache,
        t_a,
        t_b,
        t_p,
        t_q,
        t_stack,
        t_inverse_hr,
        t_analytic_state,
        t_accept_h,
        t_accept_logs,
        t_accept_class_number,
        t_accept_zeta_factor,
        t_accept_post_hnf_state,
        t_accept_prepared,
        t_accept_selected,
        t_accept_prep_state,
        t_accept_rank_work,
        t_accept_rank_occupied,
        t_accept_rank_pivots,
        t_accept_rank_state,
        t_accept_integer_input,
        t_accept_integer_work,
        t_accept_integer_occupied,
        t_accept_integer_pivots,
        t_accept_integer_best,
        t_accept_integer_state,
        t_accept_basis,
        t_accept_minor,
        t_accept_det_work,
        t_accept_det_result,
        t_accept_det_pivots,
        t_accept_det_state,
        t_accept_inverse_work,
        t_accept_inverse_rhs,
        t_accept_inverse,
        t_accept_inverse_pivots,
        t_accept_inverse_state,
        t_accept_product,
        t_accept_inverse_slice,
        t_accept_multiple,
        t_accept_coordinates,
        t_accept_multiple_state,
        t_accept_rational_work,
        t_accept_lattice,
        t_accept_hnf_work,
        t_accept_hnf_column,
        t_accept_hnf_output,
        t_accept_hnf_state,
        t_accept_regulator,
        t_accept_relations,
        t_accept_denominator,
        t_accept_reconstruction_state,
        t_accept_hnf_row_pivots,
        t_accept_hnf_heights,
        t_accept_cache_changed,
        t_accept_acceptance_state,
        terminal_state,
    )
    unit_terminal_state[1] = status
    if status != 0:
        unit_terminal_state[0] = status
        return status
    status = pari_unit_integer_lattice_rank_three(
        t_accept_relations,
        8,
        u_u1,
        u_integer_state,
        u_integer_basis,
        u_integer_transform,
        u_integer_gram,
        u_integer_mu,
        u_integer_mu_exponents,
        u_integer_r,
        u_integer_r_exponents,
        u_integer_s,
        u_integer_s_exponents,
        u_integer_approximate,
        u_integer_float_gram,
        u_integer_alpha,
        u_integer_column,
        u_integer_column_exponents,
        u_integer_normalized,
        u_integer_temporary,
        u_integer_dpe_float_scratch,
        u_integer_integer_scratch,
    )
    unit_terminal_state[2] = status
    if status != 0:
        unit_terminal_state[0] = status
        return status
    status = pari_log_matrix_transform(
        h_hnf_result_c,
        u_u1,
        4,
        8,
        3,
        False,
        u_first_logs,
    )
    unit_terminal_state[3] = status
    if status != 0:
        unit_terminal_state[0] = status
        return status
    for row in range(4):
        for column in range(3):
            source = 7 * (column * 4 + row) + 1
            target = 3 * (row * 3 + column)
            u_first_triples[target] = u_first_logs[source]
            u_first_triples[target + 1] = u_first_logs[source + 1]
            u_first_triples[target + 2] = u_first_logs[source + 2]
    status = pari_unit_real_lattice_rank_three(
        u_first_triples,
        4,
        u_real_integers,
        u_u2,
        u_real_basis,
        u_real_transform,
        u_real_gram,
        u_real_mu,
        u_real_mu_exponents,
        u_real_r,
        u_real_r_exponents,
        u_real_s,
        u_real_s_exponents,
        u_real_approximate,
        u_real_float_gram,
        u_real_alpha,
        u_real_column,
        u_real_column_exponents,
        u_real_normalized,
        u_real_temporary,
        u_real_dpe_float_scratch,
        u_real_integer_scratch,
        u_real_state,
    )
    unit_terminal_state[4] = status
    if status != 0:
        unit_terminal_state[0] = status
        return status
    status = pari_unit_compose_rank_three(u_u1, 8, u_u2, u_unit_transform)
    unit_terminal_state[5] = status
    if status != 0:
        unit_terminal_state[0] = status
        return status
    status = pari_log_matrix_transform(
        h_hnf_result_c,
        u_unit_transform,
        4,
        8,
        3,
        False,
        u_unit_logs,
    )
    unit_terminal_state[6] = status
    if status != 0:
        unit_terminal_state[0] = status
        return status
    status = pari_cleanarchunit_31_quintic(
        u_unit_logs,
        t_accept_regulator,
        192,
        u_clean_pi_cache,
        u_clean_a,
        u_clean_b,
        u_clean_p,
        u_clean_q,
        u_clean_stack,
        u_clean_scratch,
        u_cleaned,
        u_clean_state,
    )
    unit_terminal_state[7] = status
    if status != 0:
        unit_terminal_state[0] = status
        return status
    for column in range(3):
        for row in range(3):
            if row == column:
                u_identity[column * 3 + row] = 1
            else:
                u_identity[column * 3 + row] = 0
    status = pari_prepare_getfu_31_quintic(
        u_cleaned,
        u_identity,
        u_first_matep,
        u_first_arch,
        u_first_factored_clean,
        u_first_arch_real,
        u_first_arch_imag,
        u_first_clean_real,
        u_first_clean_imag,
    )
    unit_terminal_state[8] = status
    if status != 0:
        unit_terminal_state[0] = status
        return status
    for row in range(4):
        for column in range(3):
            source = 7 * (column * 4 + row) + 1
            target = 3 * (row * 3 + column)
            u_getfu_triples[target] = u_first_matep[source]
            u_getfu_triples[target + 1] = u_first_matep[source + 1]
            u_getfu_triples[target + 2] = u_first_matep[source + 2]
    status = pari_unit_real_lattice_rank_three(
        u_getfu_triples,
        4,
        u_getfu_real_integers,
        u_getfu_u2,
        u_getfu_real_basis,
        u_getfu_real_transform,
        u_getfu_real_gram,
        u_getfu_real_mu,
        u_getfu_real_mu_exponents,
        u_getfu_real_r,
        u_getfu_real_r_exponents,
        u_getfu_real_s,
        u_getfu_real_s_exponents,
        u_getfu_real_approximate,
        u_getfu_real_float_gram,
        u_getfu_real_alpha,
        u_getfu_real_column,
        u_getfu_real_column_exponents,
        u_getfu_real_normalized,
        u_getfu_real_temporary,
        u_getfu_real_dpe_float_scratch,
        u_getfu_real_integer_scratch,
        u_getfu_real_state,
    )
    unit_terminal_state[9] = status
    if status != 0:
        unit_terminal_state[0] = status
        return status
    for index in range(9):
        u_factor[index] = u_getfu_u2[3 * (index % 3) + index // 3]
    status = pari_prepare_getfu_31_quintic(
        u_cleaned,
        u_factor,
        u_final_matep,
        u_final_arch,
        u_final_factored_clean,
        u_final_arch_real,
        u_final_arch_imag,
        u_final_clean_real,
        u_final_clean_imag,
    )
    unit_terminal_state[10] = status
    if status != 0:
        unit_terminal_state[0] = status
        return status
    for column in range(5):
        for row in range(4):
            source = 5 * row + column
            target = 3 * (4 * column + row)
            u_embedding_real[target] = fb_matrix_m[source]
            u_embedding_real[target + 1] = fb_matrix_p[source]
            u_embedding_real[target + 2] = fb_matrix_e[source]
            if row < 3:
                u_embedding_imag[target] = 0
                u_embedding_imag[target + 1] = -1
                u_embedding_imag[target + 2] = 0
            else:
                u_embedding_imag[target] = fb_matrix_m[20 + column]
                u_embedding_imag[target + 1] = fb_matrix_p[20 + column]
                u_embedding_imag[target + 2] = fb_matrix_e[20 + column]
    status = pari_getfu_rank3_mixed_quintic(
        u_final_arch_real,
        u_final_arch_imag,
        u_final_clean_real,
        u_final_clean_imag,
        u_factor,
        u_embedding_real,
        u_embedding_imag,
        fb_basis_table,
        192,
        u_getfu_exponential_real,
        u_getfu_exponential_imag,
        u_getfu_split_matrix,
        u_getfu_split_rhs,
        u_getfu_solve_work,
        u_getfu_solve_rhs,
        u_getfu_solved,
        u_getfu_rounded,
        u_getfu_multiplication,
        u_getfu_inverse,
        u_getfu_candidate_units,
        u_output_units,
        u_output_logs_real,
        u_output_logs_imag,
        u_getfu_state,
        u_getfu_pivots,
        u_getfu_exp_cache,
        u_getfu_pi_cache,
        u_getfu_a,
        u_getfu_b,
        u_getfu_p,
        u_getfu_q,
        u_getfu_stack,
    )
    unit_terminal_state[11] = status
    if status != 0:
        unit_terminal_state[0] = status
        return status
    for column in range(3):
        status = pari_getfu_quintic_unit_inverse(
            u_output_units,
            5 * column,
            fb_basis_table,
            u_inverse_multiplication,
            integer_buffer_view(u_output_inverses, 5 * column, 5),
        )
        if status != 1:
            unit_terminal_state[0] = status
            return 12
        for index in range(25):
            value = 0
            for basis in range(5):
                value += (
                    u_output_units[5 * column + basis]
                    * fb_basis_table[25 * basis + index]
                )
            u_norm_matrix[index] = value
        u_output_norms[column] = _row21_bareiss_determinant(u_norm_matrix, u_norm_work)
        for row in range(3):
            least = 0
            for basis in range(5):
                at = 5 * row + basis
                exponent = 0
                if fb_matrix_p[at] != -1:
                    exponent = fb_matrix_e[at] + 1 - fb_matrix_p[at]
                if basis == 0 or exponent < least:
                    least = exponent
            numerator = 0
            for basis in range(5):
                at = 5 * row + basis
                exponent = 0
                if fb_matrix_p[at] != -1:
                    exponent = fb_matrix_e[at] + 1 - fb_matrix_p[at]
                numerator += u_output_units[5 * column + basis] * fb_matrix_m[at] << (
                    exponent - least
                )
            if numerator == 0:
                raise ValueError("zero exact row21 unit real embedding")
            if numerator < 0:
                u_output_real_signs[3 * column + row] = -1
            else:
                u_output_real_signs[3 * column + row] = 1
    unit_terminal_state[12] = 1
    unit_terminal_state[13] = u_getfu_state[7]
    unit_terminal_state[0] = 0
    return 0


__all__ = ["pari_row21_phase6_unit_root"]
