"""Generated private row-20 aggregate resident root."""

from sagejs.native import Float64Buffer, Int64Buffer, IntegerBuffer, native
from .row20_phase6_factor_base_root import pari_row20_phase6_factor_base_root
from .row20_connected_relation_hnf import pari_connected_relation_hnf
from .row21_analytic_catalog import pari_row21_analytic_degree_catalog
from .row14_post806_terminal import pari_row14_analytic_inverse_hr
from .post_hnf_acceptance import pari_post_hnf_acceptance
from .row20_phase6_resident_unit_root import pari_row20_phase6_resident_unit_root


@native
def pari_row20_phase6_aggregate_root(
    factor_polynomial: IntegerBuffer,
    factor_basis_table: IntegerBuffer,
    factor_matrix_m: IntegerBuffer,
    factor_matrix_p: IntegerBuffer,
    factor_matrix_e: IntegerBuffer,
    factor_discriminant: int,
    factor_equation_index: int,
    factor_primes: IntegerBuffer,
    factor_prime_count: int,
    factor_descriptor_workspace: IntegerBuffer,
    factor_descriptor_scratch: IntegerBuffer,
    factor_descriptor_ranks: IntegerBuffer,
    factor_descriptor_state: IntegerBuffer,
    factor_degree_scratch: IntegerBuffer,
    factor_exponent_scratch: IntegerBuffer,
    factor_factor_workspace: IntegerBuffer,
    factor_factor_state: IntegerBuffer,
    factor_pattern_offsets: IntegerBuffer,
    factor_pattern_counts: IntegerBuffer,
    factor_pattern_degrees: IntegerBuffer,
    factor_pattern_multiplicities: IntegerBuffer,
    factor_full_offsets: IntegerBuffer,
    factor_full_counts: IntegerBuffer,
    factor_full_degrees: IntegerBuffer,
    factor_configuration: Float64Buffer,
    factor_bound_norms: IntegerBuffer,
    factor_constants_logs: Float64Buffer,
    factor_sums: Float64Buffer,
    factor_factor_logs: Float64Buffer,
    factor_selected_primes: IntegerBuffer,
    factor_prime_offsets: IntegerBuffer,
    factor_prime_counts: IntegerBuffer,
    factor_complete_groups: IntegerBuffer,
    factor_selected_indices: IntegerBuffer,
    factor_base_state: IntegerBuffer,
    factor_selected_descriptors: IntegerBuffer,
    factor_selected_ideals: IntegerBuffer,
    factor_selected_norms: IntegerBuffer,
    factor_group_offsets: IntegerBuffer,
    factor_group_sizes: IntegerBuffer,
    factor_group_complete: IntegerBuffer,
    factor_hnf_multiplication: IntegerBuffer,
    factor_hnf_work: IntegerBuffer,
    factor_hnf_pivots: IntegerBuffer,
    factor_subfactor_bad: IntegerBuffer,
    factor_subfactor_configuration: Float64Buffer,
    factor_subfactor_order: IntegerBuffer,
    factor_subfactor_scratch: IntegerBuffer,
    factor_subfactor_stack: IntegerBuffer,
    factor_subfactor_chosen: IntegerBuffer,
    factor_subfactor_rejected: IntegerBuffer,
    factor_permutation: IntegerBuffer,
    factor_subfactor_state: IntegerBuffer,
    factor_relation_primes: IntegerBuffer,
    factor_ramification: IntegerBuffer,
    factor_residue_degrees: IntegerBuffer,
    factor_packet_generators: IntegerBuffer,
    factor_admission_group_tau: IntegerBuffer,
    factor_packet_inert: IntegerBuffer,
    factor_packet_primes: IntegerBuffer,
    factor_hnf_perm: IntegerBuffer,
    factor_outer_perm: IntegerBuffer,
    factor_hnf_subfactor: IntegerBuffer,
    factor_resident_state: IntegerBuffer,
    hnf_matrix: IntegerBuffer,
    hnf_ideal: IntegerBuffer,
    hnf_n: int,
    hnf_precision: int,
    hnf_scale: float,
    hnf_track_small: int,
    hnf_reduction: IntegerBuffer,
    hnf_vectors: IntegerBuffer,
    hnf_betas: IntegerBuffer,
    hnf_norms: IntegerBuffer,
    hnf_column: IntegerBuffer,
    hnf_float_q: Float64Buffer,
    hnf_float_v: Float64Buffer,
    hnf_bound: Float64Buffer,
    hnf_cache: IntegerBuffer,
    hnf_a: IntegerBuffer,
    hnf_b: IntegerBuffer,
    hnf_p: IntegerBuffer,
    hnf_q: IntegerBuffer,
    hnf_stack: IntegerBuffer,
    hnf_x: Int64Buffer,
    hnf_y: Float64Buffer,
    hnf_z: Float64Buffer,
    hnf_inc: Int64Buffer,
    hnf_state: Int64Buffer,
    hnf_cursor_output: Int64Buffer,
    hnf_element: IntegerBuffer,
    hnf_counters: Int64Buffer,
    hnf_admission_matrix_m: IntegerBuffer,
    hnf_admission_matrix_p: IntegerBuffer,
    hnf_admission_matrix_e: IntegerBuffer,
    hnf_admission_embedding_m: IntegerBuffer,
    hnf_admission_embedding_p: IntegerBuffer,
    hnf_admission_embedding_e: IntegerBuffer,
    hnf_admission_real_count: int,
    hnf_admission_ideal: IntegerBuffer,
    hnf_admission_mode: int,
    hnf_admission_factor_product: int,
    hnf_admission_primes: IntegerBuffer,
    hnf_admission_products: IntegerBuffer,
    hnf_admission_factorlimit: int,
    hnf_admission_prime_limit: int,
    hnf_admission_rational_factors: IntegerBuffer,
    hnf_admission_rational_exponents: IntegerBuffer,
    hnf_admission_prime_offsets: IntegerBuffer,
    hnf_admission_prime_counts: IntegerBuffer,
    hnf_admission_group_tau: IntegerBuffer,
    hnf_admission_group_e: IntegerBuffer,
    hnf_admission_group_f: IntegerBuffer,
    hnf_admission_group_inert: IntegerBuffer,
    hnf_admission_tau: IntegerBuffer,
    hnf_admission_x: IntegerBuffer,
    hnf_admission_y: IntegerBuffer,
    hnf_admission_spare: IntegerBuffer,
    hnf_admission_stack: IntegerBuffer,
    hnf_admission_primitive: IntegerBuffer,
    hnf_admission_columns: IntegerBuffer,
    hnf_admission_values: IntegerBuffer,
    hnf_admission_temporary: IntegerBuffer,
    hnf_admission_indices: IntegerBuffer,
    hnf_admission_exponents: IntegerBuffer,
    hnf_diagnostic: IntegerBuffer,
    hnf_nrelid: int,
    hnf_track_fact: int,
    hnf_jid0: int,
    hnf_e0: int,
    hnf_subfactor: IntegerBuffer,
    hnf_extra: IntegerBuffer,
    hnf_extra_count: int,
    hnf_relation_primes: IntegerBuffer,
    hnf_ramification: IntegerBuffer,
    hnf_relation: IntegerBuffer,
    hnf_relation_state: IntegerBuffer,
    hnf_relation_basis: IntegerBuffer,
    hnf_relation_records: IntegerBuffer,
    hnf_relation_hashes: IntegerBuffer,
    hnf_relation_metadata: IntegerBuffer,
    hnf_relation_scratch: IntegerBuffer,
    hnf_generators: IntegerBuffer,
    hnf_progress: Int64Buffer,
    hnf_preparation_rounded_embedding: IntegerBuffer,
    hnf_preparation_embedding: IntegerBuffer,
    hnf_preparation_original: IntegerBuffer,
    hnf_preparation_basis: IntegerBuffer,
    hnf_preparation_transform: IntegerBuffer,
    hnf_preparation_flags: IntegerBuffer,
    hnf_preparation_rank_diagnostic: IntegerBuffer,
    hnf_preparation_selection: IntegerBuffer,
    hnf_preparation_stages: IntegerBuffer,
    hnf_preparation_flatter_input: IntegerBuffer,
    hnf_preparation_current: IntegerBuffer,
    hnf_preparation_flatter_transform: IntegerBuffer,
    hnf_preparation_total_work: IntegerBuffer,
    hnf_preparation_step_t: IntegerBuffer,
    hnf_preparation_step_s: IntegerBuffer,
    hnf_preparation_product: IntegerBuffer,
    hnf_preparation_next_basis: IntegerBuffer,
    hnf_preparation_y: IntegerBuffer,
    hnf_preparation_diagnostic: IntegerBuffer,
    hnf_preparation_r1: IntegerBuffer,
    hnf_preparation_r2: IntegerBuffer,
    hnf_preparation_r3: IntegerBuffer,
    hnf_preparation_t1: IntegerBuffer,
    hnf_preparation_t2: IntegerBuffer,
    hnf_preparation_t3: IntegerBuffer,
    hnf_preparation_integers: IntegerBuffer,
    hnf_preparation_inverse: IntegerBuffer,
    hnf_preparation_first: IntegerBuffer,
    hnf_preparation_second: IntegerBuffer,
    hnf_preparation_final: IntegerBuffer,
    hnf_preparation_rounded: IntegerBuffer,
    hnf_preparation_mu: Float64Buffer,
    hnf_preparation_r: Float64Buffer,
    hnf_preparation_s: Float64Buffer,
    hnf_preparation_approximate: Float64Buffer,
    hnf_preparation_exponents: IntegerBuffer,
    hnf_preparation_float_gram: Float64Buffer,
    hnf_preparation_gram: IntegerBuffer,
    hnf_preparation_mu_exponents: IntegerBuffer,
    hnf_preparation_r_exponents: IntegerBuffer,
    hnf_preparation_s_exponents: IntegerBuffer,
    hnf_preparation_alpha: IntegerBuffer,
    hnf_preparation_column_exponents: IntegerBuffer,
    hnf_preparation_float_scratch: Float64Buffer,
    hnf_preparation_temporary: Float64Buffer,
    hnf_preparation_state: Int64Buffer,
    hnf_search_ideals: IntegerBuffer,
    hnf_search_count: int,
    hnf_packet_ids: IntegerBuffer,
    hnf_packet_ideals: IntegerBuffer,
    hnf_packet_norms: IntegerBuffer,
    hnf_schedule: Int64Buffer,
    hnf_construct_primes: int,
    hnf_basis_table: IntegerBuffer,
    hnf_packet_primes: IntegerBuffer,
    hnf_packet_generators: IntegerBuffer,
    hnf_packet_inert: IntegerBuffer,
    hnf_hnf_generator: IntegerBuffer,
    hnf_hnf_matrix: IntegerBuffer,
    hnf_hnf_work: IntegerBuffer,
    hnf_hnf_pivots: IntegerBuffer,
    hnf_power_ideal: IntegerBuffer,
    hnf_power_alpha: IntegerBuffer,
    hnf_power_metadata: IntegerBuffer,
    hnf_power_primitive: IntegerBuffer,
    hnf_power_temporary: IntegerBuffer,
    hnf_power_diagnostic: IntegerBuffer,
    hnf_power_multiplication: IntegerBuffer,
    hnf_power_work: IntegerBuffer,
    hnf_power_triangular: IntegerBuffer,
    hnf_power_moduli: IntegerBuffer,
    hnf_product_primitive: IntegerBuffer,
    hnf_product_matrix: IntegerBuffer,
    hnf_outer_mode: int,
    hnf_outer_ru: int,
    hnf_outer_state: Int64Buffer,
    hnf_outer_minidx: IntegerBuffer,
    hnf_outer_present: IntegerBuffer,
    hnf_outer_live: IntegerBuffer,
    hnf_outer_perm: IntegerBuffer,
    hnf_outer_multiplier: IntegerBuffer,
    hnf_log_precision: int,
    hnf_log_completed: IntegerBuffer,
    hnf_log_embeddings: IntegerBuffer,
    hnf_log_coordinates: IntegerBuffer,
    hnf_log_column: IntegerBuffer,
    hnf_log_cache: IntegerBuffer,
    hnf_log_pi_cache: IntegerBuffer,
    hnf_log_a: IntegerBuffer,
    hnf_log_b: IntegerBuffer,
    hnf_log_p: IntegerBuffer,
    hnf_log_q: IntegerBuffer,
    hnf_log_stack: IntegerBuffer,
    hnf_initial_additional: int,
    hnf_initial_target: int,
    hnf_initial_primes: IntegerBuffer,
    hnf_initial_offsets: IntegerBuffer,
    hnf_initial_counts: IntegerBuffer,
    hnf_initial_complete: IntegerBuffer,
    hnf_hnf_k0: int,
    hnf_hnf_original: Int64Buffer,
    hnf_hnf_perm: Int64Buffer,
    hnf_hnf_mat: Int64Buffer,
    hnf_hnf_dense: IntegerBuffer,
    hnf_hnf_transform: IntegerBuffer,
    hnf_hnf_vmax: Int64Buffer,
    hnf_hnf_found: Int64Buffer,
    hnf_hnf_sparse_state: Int64Buffer,
    hnf_hnf_bottom: IntegerBuffer,
    hnf_hnf_updated_dense: IntegerBuffer,
    hnf_hnf_extra: IntegerBuffer,
    hnf_hnf_cleanup_state: Int64Buffer,
    hnf_hnf_rank_matrix: IntegerBuffer,
    hnf_hnf_occupied: IntegerBuffer,
    hnf_hnf_rank_pivots: IntegerBuffer,
    hnf_hnf_best: IntegerBuffer,
    hnf_hnf_profile: IntegerBuffer,
    hnf_hnf_rank_state: IntegerBuffer,
    hnf_hnf_perm_work: Int64Buffer,
    hnf_hnf_matbnew: IntegerBuffer,
    hnf_hnf_dep: IntegerBuffer,
    hnf_hnf_b: IntegerBuffer,
    hnf_hnf_assembly_state: Int64Buffer,
    hnf_hnf_transformed_logs: IntegerBuffer,
    hnf_hnf_full_h: IntegerBuffer,
    hnf_hnf_hnf_transform: IntegerBuffer,
    hnf_hnf_lam: IntegerBuffer,
    hnf_hnf_d: IntegerBuffer,
    hnf_hnf_hnf_state: Int64Buffer,
    hnf_hnf_full_dep: IntegerBuffer,
    hnf_hnf_work_b: IntegerBuffer,
    hnf_hnf_work_c: IntegerBuffer,
    hnf_hnf_diagonal: Int64Buffer,
    hnf_hnf_result_h: IntegerBuffer,
    hnf_hnf_result_dep: IntegerBuffer,
    hnf_hnf_result_b: IntegerBuffer,
    hnf_hnf_result_c: IntegerBuffer,
    hnf_hnf_final_state: Int64Buffer,
    hnf_hnf_state: Int64Buffer,
    hnf_chain_state: Int64Buffer,
    hnf_hnf_cup_arena: IntegerBuffer,
    hnf_hnf_cup_frames: IntegerBuffer,
    hnf_hnf_cup_solve_state: Int64Buffer,
    hnf_hnf_cup_state: Int64Buffer,
    catalog_polynomial: IntegerBuffer,
    catalog_table: IntegerBuffer,
    catalog_primes: IntegerBuffer,
    catalog_prime_count: int,
    catalog_workspace: IntegerBuffer,
    catalog_pattern_offsets: IntegerBuffer,
    catalog_pattern_counts: IntegerBuffer,
    catalog_pattern_degrees: IntegerBuffer,
    catalog_pattern_multiplicities: IntegerBuffer,
    catalog_state: IntegerBuffer,
    analytic_discriminant: int,
    analytic_real_places: int,
    analytic_complex_places: int,
    analytic_roots_of_unity: int,
    analytic_log_discriminant: Float64Buffer,
    analytic_primes: IntegerBuffer,
    analytic_offsets: IntegerBuffer,
    analytic_counts: IntegerBuffer,
    analytic_degrees: IntegerBuffer,
    analytic_multiplicities: IntegerBuffer,
    analytic_coefficients: Float64Buffer,
    analytic_table: Float64Buffer,
    analytic_tail: Float64Buffer,
    analytic_logarithms: Float64Buffer,
    analytic_log_inverse_residue: Float64Buffer,
    analytic_inverse_residue: IntegerBuffer,
    analytic_exp_cache: IntegerBuffer,
    analytic_pi_cache: IntegerBuffer,
    analytic_a: IntegerBuffer,
    analytic_b: IntegerBuffer,
    analytic_p: IntegerBuffer,
    analytic_q: IntegerBuffer,
    analytic_stack: IntegerBuffer,
    analytic_inverse_hr: IntegerBuffer,
    analytic_state: Int64Buffer,
    acceptance_factor_count: int,
    acceptance_h_rows: int,
    acceptance_b_columns: int,
    acceptance_c_columns: int,
    acceptance_places: int,
    acceptance_degree: int,
    acceptance_h: IntegerBuffer,
    acceptance_c: IntegerBuffer,
    acceptance_inverse_hr: IntegerBuffer,
    acceptance_logs: IntegerBuffer,
    acceptance_class_number: IntegerBuffer,
    acceptance_zeta_factor: IntegerBuffer,
    acceptance_post_hnf_state: Int64Buffer,
    acceptance_prepared: IntegerBuffer,
    acceptance_selected: Int64Buffer,
    acceptance_prep_state: Int64Buffer,
    acceptance_rank_work: IntegerBuffer,
    acceptance_rank_occupied: Int64Buffer,
    acceptance_rank_pivots: Int64Buffer,
    acceptance_rank_state: Int64Buffer,
    acceptance_integer_input: IntegerBuffer,
    acceptance_integer_work: IntegerBuffer,
    acceptance_integer_occupied: IntegerBuffer,
    acceptance_integer_pivots: IntegerBuffer,
    acceptance_integer_best: IntegerBuffer,
    acceptance_integer_state: IntegerBuffer,
    acceptance_basis: IntegerBuffer,
    acceptance_minor: IntegerBuffer,
    acceptance_det_work: IntegerBuffer,
    acceptance_det_result: IntegerBuffer,
    acceptance_det_pivots: Int64Buffer,
    acceptance_det_state: Int64Buffer,
    acceptance_inverse_work: IntegerBuffer,
    acceptance_inverse_rhs: IntegerBuffer,
    acceptance_inverse: IntegerBuffer,
    acceptance_inverse_pivots: Int64Buffer,
    acceptance_inverse_state: Int64Buffer,
    acceptance_product: IntegerBuffer,
    acceptance_inverse_slice: IntegerBuffer,
    acceptance_multiple: IntegerBuffer,
    acceptance_coordinates: IntegerBuffer,
    acceptance_multiple_state: Int64Buffer,
    acceptance_rational_work: IntegerBuffer,
    acceptance_lattice: IntegerBuffer,
    acceptance_hnf_work: IntegerBuffer,
    acceptance_hnf_column: IntegerBuffer,
    acceptance_hnf_output: IntegerBuffer,
    acceptance_hnf_state: Int64Buffer,
    acceptance_regulator: IntegerBuffer,
    acceptance_relations: IntegerBuffer,
    acceptance_denominator: IntegerBuffer,
    acceptance_reconstruction_state: Int64Buffer,
    acceptance_hnf_row_pivots: Int64Buffer,
    acceptance_hnf_heights: Int64Buffer,
    acceptance_cache_changed: bool,
    acceptance_acceptance_state: Int64Buffer,
    unit_exact_logs: IntegerBuffer,
    unit_relation_lattice: IntegerBuffer,
    unit_regulator: IntegerBuffer,
    unit_embedding_m: IntegerBuffer,
    unit_embedding_p: IntegerBuffer,
    unit_embedding_e: IntegerBuffer,
    unit_multiplication_tensor: IntegerBuffer,
    unit_u1: IntegerBuffer,
    unit_integer_state: IntegerBuffer,
    unit_lll_basis: IntegerBuffer,
    unit_lll_transform: IntegerBuffer,
    unit_lll_gram: IntegerBuffer,
    unit_lll_mu: Float64Buffer,
    unit_lll_mu_exponents: IntegerBuffer,
    unit_lll_r: Float64Buffer,
    unit_lll_r_exponents: IntegerBuffer,
    unit_lll_s: Float64Buffer,
    unit_lll_s_exponents: IntegerBuffer,
    unit_lll_approximate: Float64Buffer,
    unit_lll_float_gram: Float64Buffer,
    unit_lll_alpha: IntegerBuffer,
    unit_lll_column: IntegerBuffer,
    unit_lll_column_exponents: IntegerBuffer,
    unit_lll_normalized: Float64Buffer,
    unit_lll_temporary: Float64Buffer,
    unit_lll_dpe_scratch: Float64Buffer,
    unit_lll_integer_scratch: IntegerBuffer,
    unit_first_logs: IntegerBuffer,
    unit_triples: IntegerBuffer,
    unit_factor: IntegerBuffer,
    unit_real_integers: IntegerBuffer,
    unit_real_form: IntegerBuffer,
    unit_real_state: IntegerBuffer,
    unit_composed: IntegerBuffer,
    unit_transformed_logs: IntegerBuffer,
    unit_clean_scratch: IntegerBuffer,
    unit_clean: IntegerBuffer,
    unit_clean_state: Int64Buffer,
    unit_matep: IntegerBuffer,
    unit_arch: IntegerBuffer,
    unit_candidate_a: IntegerBuffer,
    unit_arch_real: IntegerBuffer,
    unit_arch_imag: IntegerBuffer,
    unit_clean_real: IntegerBuffer,
    unit_clean_imag: IntegerBuffer,
    unit_embedding_real: IntegerBuffer,
    unit_embedding_imag: IntegerBuffer,
    unit_exponential_real: IntegerBuffer,
    unit_exponential_imag: IntegerBuffer,
    unit_split_matrix: IntegerBuffer,
    unit_split_rhs: IntegerBuffer,
    unit_solve_work: IntegerBuffer,
    unit_solve_rhs: IntegerBuffer,
    unit_solved: IntegerBuffer,
    unit_rounded: IntegerBuffer,
    unit_multiplication: IntegerBuffer,
    unit_inverse: IntegerBuffer,
    unit_candidate_units: IntegerBuffer,
    unit_output_units: IntegerBuffer,
    unit_output_logs_real: IntegerBuffer,
    unit_output_logs_imag: IntegerBuffer,
    unit_getfu_state: Int64Buffer,
    unit_pivots: Int64Buffer,
    unit_exp_cache: IntegerBuffer,
    unit_pi_cache: IntegerBuffer,
    unit_arithmetic_a: IntegerBuffer,
    unit_arithmetic_b: IntegerBuffer,
    unit_arithmetic_p: IntegerBuffer,
    unit_arithmetic_q: IntegerBuffer,
    unit_arithmetic_stack: IntegerBuffer,
    unit_resident_state: Int64Buffer,
) -> int:
    """Run the retained row-20 graph through one native ABI entry."""
    status = pari_row20_phase6_factor_base_root(
        factor_polynomial,
        factor_basis_table,
        factor_matrix_m,
        factor_matrix_p,
        factor_matrix_e,
        factor_discriminant,
        factor_equation_index,
        factor_primes,
        factor_prime_count,
        factor_descriptor_workspace,
        factor_descriptor_scratch,
        factor_descriptor_ranks,
        factor_descriptor_state,
        factor_degree_scratch,
        factor_exponent_scratch,
        factor_factor_workspace,
        factor_factor_state,
        factor_pattern_offsets,
        factor_pattern_counts,
        factor_pattern_degrees,
        factor_pattern_multiplicities,
        factor_full_offsets,
        factor_full_counts,
        factor_full_degrees,
        factor_configuration,
        factor_bound_norms,
        factor_constants_logs,
        factor_sums,
        factor_factor_logs,
        factor_selected_primes,
        factor_prime_offsets,
        factor_prime_counts,
        factor_complete_groups,
        factor_selected_indices,
        factor_base_state,
        factor_selected_descriptors,
        factor_selected_ideals,
        factor_selected_norms,
        factor_group_offsets,
        factor_group_sizes,
        factor_group_complete,
        factor_hnf_multiplication,
        factor_hnf_work,
        factor_hnf_pivots,
        factor_subfactor_bad,
        factor_subfactor_configuration,
        factor_subfactor_order,
        factor_subfactor_scratch,
        factor_subfactor_stack,
        factor_subfactor_chosen,
        factor_subfactor_rejected,
        factor_permutation,
        factor_subfactor_state,
        factor_relation_primes,
        factor_ramification,
        factor_residue_degrees,
        factor_packet_generators,
        factor_admission_group_tau,
        factor_packet_inert,
        factor_packet_primes,
        factor_hnf_perm,
        factor_outer_perm,
        factor_hnf_subfactor,
        factor_resident_state,
    )
    if status != 0:
        return 10 + status
    status = pari_connected_relation_hnf(
        hnf_matrix,
        hnf_ideal,
        hnf_n,
        hnf_precision,
        hnf_scale,
        hnf_track_small,
        hnf_reduction,
        hnf_vectors,
        hnf_betas,
        hnf_norms,
        hnf_column,
        hnf_float_q,
        hnf_float_v,
        hnf_bound,
        hnf_cache,
        hnf_a,
        hnf_b,
        hnf_p,
        hnf_q,
        hnf_stack,
        hnf_x,
        hnf_y,
        hnf_z,
        hnf_inc,
        hnf_state,
        hnf_cursor_output,
        hnf_element,
        hnf_counters,
        hnf_admission_matrix_m,
        hnf_admission_matrix_p,
        hnf_admission_matrix_e,
        hnf_admission_embedding_m,
        hnf_admission_embedding_p,
        hnf_admission_embedding_e,
        hnf_admission_real_count,
        hnf_admission_ideal,
        hnf_admission_mode,
        hnf_admission_factor_product,
        hnf_admission_primes,
        hnf_admission_products,
        hnf_admission_factorlimit,
        hnf_admission_prime_limit,
        hnf_admission_rational_factors,
        hnf_admission_rational_exponents,
        hnf_admission_prime_offsets,
        hnf_admission_prime_counts,
        hnf_admission_group_tau,
        hnf_admission_group_e,
        hnf_admission_group_f,
        hnf_admission_group_inert,
        hnf_admission_tau,
        hnf_admission_x,
        hnf_admission_y,
        hnf_admission_spare,
        hnf_admission_stack,
        hnf_admission_primitive,
        hnf_admission_columns,
        hnf_admission_values,
        hnf_admission_temporary,
        hnf_admission_indices,
        hnf_admission_exponents,
        hnf_diagnostic,
        hnf_nrelid,
        hnf_track_fact,
        hnf_jid0,
        hnf_e0,
        hnf_subfactor,
        hnf_extra,
        hnf_extra_count,
        hnf_relation_primes,
        hnf_ramification,
        hnf_relation,
        hnf_relation_state,
        hnf_relation_basis,
        hnf_relation_records,
        hnf_relation_hashes,
        hnf_relation_metadata,
        hnf_relation_scratch,
        hnf_generators,
        hnf_progress,
        hnf_preparation_rounded_embedding,
        hnf_preparation_embedding,
        hnf_preparation_original,
        hnf_preparation_basis,
        hnf_preparation_transform,
        hnf_preparation_flags,
        hnf_preparation_rank_diagnostic,
        hnf_preparation_selection,
        hnf_preparation_stages,
        hnf_preparation_flatter_input,
        hnf_preparation_current,
        hnf_preparation_flatter_transform,
        hnf_preparation_total_work,
        hnf_preparation_step_t,
        hnf_preparation_step_s,
        hnf_preparation_product,
        hnf_preparation_next_basis,
        hnf_preparation_y,
        hnf_preparation_diagnostic,
        hnf_preparation_r1,
        hnf_preparation_r2,
        hnf_preparation_r3,
        hnf_preparation_t1,
        hnf_preparation_t2,
        hnf_preparation_t3,
        hnf_preparation_integers,
        hnf_preparation_inverse,
        hnf_preparation_first,
        hnf_preparation_second,
        hnf_preparation_final,
        hnf_preparation_rounded,
        hnf_preparation_mu,
        hnf_preparation_r,
        hnf_preparation_s,
        hnf_preparation_approximate,
        hnf_preparation_exponents,
        hnf_preparation_float_gram,
        hnf_preparation_gram,
        hnf_preparation_mu_exponents,
        hnf_preparation_r_exponents,
        hnf_preparation_s_exponents,
        hnf_preparation_alpha,
        hnf_preparation_column_exponents,
        hnf_preparation_float_scratch,
        hnf_preparation_temporary,
        hnf_preparation_state,
        hnf_search_ideals,
        hnf_search_count,
        hnf_packet_ids,
        hnf_packet_ideals,
        hnf_packet_norms,
        hnf_schedule,
        hnf_construct_primes,
        hnf_basis_table,
        hnf_packet_primes,
        hnf_packet_generators,
        hnf_packet_inert,
        hnf_hnf_generator,
        hnf_hnf_matrix,
        hnf_hnf_work,
        hnf_hnf_pivots,
        hnf_power_ideal,
        hnf_power_alpha,
        hnf_power_metadata,
        hnf_power_primitive,
        hnf_power_temporary,
        hnf_power_diagnostic,
        hnf_power_multiplication,
        hnf_power_work,
        hnf_power_triangular,
        hnf_power_moduli,
        hnf_product_primitive,
        hnf_product_matrix,
        hnf_outer_mode,
        hnf_outer_ru,
        hnf_outer_state,
        hnf_outer_minidx,
        hnf_outer_present,
        hnf_outer_live,
        hnf_outer_perm,
        hnf_outer_multiplier,
        hnf_log_precision,
        hnf_log_completed,
        hnf_log_embeddings,
        hnf_log_coordinates,
        hnf_log_column,
        hnf_log_cache,
        hnf_log_pi_cache,
        hnf_log_a,
        hnf_log_b,
        hnf_log_p,
        hnf_log_q,
        hnf_log_stack,
        hnf_initial_additional,
        hnf_initial_target,
        hnf_initial_primes,
        hnf_initial_offsets,
        hnf_initial_counts,
        hnf_initial_complete,
        hnf_hnf_k0,
        hnf_hnf_original,
        hnf_hnf_perm,
        hnf_hnf_mat,
        hnf_hnf_dense,
        hnf_hnf_transform,
        hnf_hnf_vmax,
        hnf_hnf_found,
        hnf_hnf_sparse_state,
        hnf_hnf_bottom,
        hnf_hnf_updated_dense,
        hnf_hnf_extra,
        hnf_hnf_cleanup_state,
        hnf_hnf_rank_matrix,
        hnf_hnf_occupied,
        hnf_hnf_rank_pivots,
        hnf_hnf_best,
        hnf_hnf_profile,
        hnf_hnf_rank_state,
        hnf_hnf_perm_work,
        hnf_hnf_matbnew,
        hnf_hnf_dep,
        hnf_hnf_b,
        hnf_hnf_assembly_state,
        hnf_hnf_transformed_logs,
        hnf_hnf_full_h,
        hnf_hnf_hnf_transform,
        hnf_hnf_lam,
        hnf_hnf_d,
        hnf_hnf_hnf_state,
        hnf_hnf_full_dep,
        hnf_hnf_work_b,
        hnf_hnf_work_c,
        hnf_hnf_diagonal,
        hnf_hnf_result_h,
        hnf_hnf_result_dep,
        hnf_hnf_result_b,
        hnf_hnf_result_c,
        hnf_hnf_final_state,
        hnf_hnf_state,
        hnf_chain_state,
        hnf_hnf_cup_arena,
        hnf_hnf_cup_frames,
        hnf_hnf_cup_solve_state,
        hnf_hnf_cup_state,
    )
    if status != 0:
        return 20 + status
    status = pari_row21_analytic_degree_catalog(
        catalog_polynomial,
        catalog_table,
        catalog_primes,
        catalog_prime_count,
        catalog_workspace,
        catalog_pattern_offsets,
        catalog_pattern_counts,
        catalog_pattern_degrees,
        catalog_pattern_multiplicities,
        catalog_state,
    )
    if status != 0:
        return 30 + status
    status = pari_row14_analytic_inverse_hr(
        analytic_discriminant,
        analytic_real_places,
        analytic_complex_places,
        analytic_roots_of_unity,
        analytic_log_discriminant,
        analytic_primes,
        analytic_offsets,
        analytic_counts,
        analytic_degrees,
        analytic_multiplicities,
        analytic_coefficients,
        analytic_table,
        analytic_tail,
        analytic_logarithms,
        analytic_log_inverse_residue,
        analytic_inverse_residue,
        analytic_exp_cache,
        analytic_pi_cache,
        analytic_a,
        analytic_b,
        analytic_p,
        analytic_q,
        analytic_stack,
        analytic_inverse_hr,
        analytic_state,
    )
    if status != 0:
        return 40 + status
    status = pari_post_hnf_acceptance(
        acceptance_factor_count,
        acceptance_h_rows,
        acceptance_b_columns,
        acceptance_c_columns,
        acceptance_places,
        acceptance_degree,
        acceptance_h,
        acceptance_c,
        acceptance_inverse_hr,
        acceptance_logs,
        acceptance_class_number,
        acceptance_zeta_factor,
        acceptance_post_hnf_state,
        acceptance_prepared,
        acceptance_selected,
        acceptance_prep_state,
        acceptance_rank_work,
        acceptance_rank_occupied,
        acceptance_rank_pivots,
        acceptance_rank_state,
        acceptance_integer_input,
        acceptance_integer_work,
        acceptance_integer_occupied,
        acceptance_integer_pivots,
        acceptance_integer_best,
        acceptance_integer_state,
        acceptance_basis,
        acceptance_minor,
        acceptance_det_work,
        acceptance_det_result,
        acceptance_det_pivots,
        acceptance_det_state,
        acceptance_inverse_work,
        acceptance_inverse_rhs,
        acceptance_inverse,
        acceptance_inverse_pivots,
        acceptance_inverse_state,
        acceptance_product,
        acceptance_inverse_slice,
        acceptance_multiple,
        acceptance_coordinates,
        acceptance_multiple_state,
        acceptance_rational_work,
        acceptance_lattice,
        acceptance_hnf_work,
        acceptance_hnf_column,
        acceptance_hnf_output,
        acceptance_hnf_state,
        acceptance_regulator,
        acceptance_relations,
        acceptance_denominator,
        acceptance_reconstruction_state,
        acceptance_hnf_row_pivots,
        acceptance_hnf_heights,
        acceptance_cache_changed,
        acceptance_acceptance_state,
    )
    if status != 0:
        return 50 + status
    status = pari_row20_phase6_resident_unit_root(
        unit_exact_logs,
        unit_relation_lattice,
        unit_regulator,
        unit_embedding_m,
        unit_embedding_p,
        unit_embedding_e,
        unit_multiplication_tensor,
        unit_u1,
        unit_integer_state,
        unit_lll_basis,
        unit_lll_transform,
        unit_lll_gram,
        unit_lll_mu,
        unit_lll_mu_exponents,
        unit_lll_r,
        unit_lll_r_exponents,
        unit_lll_s,
        unit_lll_s_exponents,
        unit_lll_approximate,
        unit_lll_float_gram,
        unit_lll_alpha,
        unit_lll_column,
        unit_lll_column_exponents,
        unit_lll_normalized,
        unit_lll_temporary,
        unit_lll_dpe_scratch,
        unit_lll_integer_scratch,
        unit_first_logs,
        unit_triples,
        unit_factor,
        unit_real_integers,
        unit_real_form,
        unit_real_state,
        unit_composed,
        unit_transformed_logs,
        unit_clean_scratch,
        unit_clean,
        unit_clean_state,
        unit_matep,
        unit_arch,
        unit_candidate_a,
        unit_arch_real,
        unit_arch_imag,
        unit_clean_real,
        unit_clean_imag,
        unit_embedding_real,
        unit_embedding_imag,
        unit_exponential_real,
        unit_exponential_imag,
        unit_split_matrix,
        unit_split_rhs,
        unit_solve_work,
        unit_solve_rhs,
        unit_solved,
        unit_rounded,
        unit_multiplication,
        unit_inverse,
        unit_candidate_units,
        unit_output_units,
        unit_output_logs_real,
        unit_output_logs_imag,
        unit_getfu_state,
        unit_pivots,
        unit_exp_cache,
        unit_pi_cache,
        unit_arithmetic_a,
        unit_arithmetic_b,
        unit_arithmetic_p,
        unit_arithmetic_q,
        unit_arithmetic_stack,
        unit_resident_state,
    )
    if status != 0:
        return 60 + status
    return 0


__all__ = ["pari_row20_phase6_aggregate_root"]
