"""Generated one-call row-23 relation/HNF/class/unit root."""

from sagejs.native import Float64Buffer, Int64Buffer, IntegerBuffer, native
from .row23_connected_relation_hnf import pari_connected_relation_hnf
from .row23_phase6_suffix_root import pari_row23_phase6_suffix_root


@native
def pari_row23_phase6_aggregate_root(
    matrix: IntegerBuffer,
    ideal: IntegerBuffer,
    n: int,
    precision: int,
    scale: float,
    track_small: int,
    reduction: IntegerBuffer,
    vectors: IntegerBuffer,
    betas: IntegerBuffer,
    norms: IntegerBuffer,
    column: IntegerBuffer,
    float_q: Float64Buffer,
    float_v: Float64Buffer,
    bound: Float64Buffer,
    cache: IntegerBuffer,
    a: IntegerBuffer,
    b: IntegerBuffer,
    p: IntegerBuffer,
    q: IntegerBuffer,
    stack: IntegerBuffer,
    x: Int64Buffer,
    y: Float64Buffer,
    z: Float64Buffer,
    inc: Int64Buffer,
    state: Int64Buffer,
    cursor_output: Int64Buffer,
    element: IntegerBuffer,
    counters: Int64Buffer,
    admission_matrix_m: IntegerBuffer,
    admission_matrix_p: IntegerBuffer,
    admission_matrix_e: IntegerBuffer,
    admission_embedding_m: IntegerBuffer,
    admission_embedding_p: IntegerBuffer,
    admission_embedding_e: IntegerBuffer,
    admission_real_count: int,
    admission_ideal: IntegerBuffer,
    admission_mode: int,
    admission_factor_product: int,
    admission_primes: IntegerBuffer,
    admission_products: IntegerBuffer,
    admission_factorlimit: int,
    admission_prime_limit: int,
    admission_rational_factors: IntegerBuffer,
    admission_rational_exponents: IntegerBuffer,
    admission_prime_offsets: IntegerBuffer,
    admission_prime_counts: IntegerBuffer,
    admission_group_tau: IntegerBuffer,
    admission_group_e: IntegerBuffer,
    admission_group_f: IntegerBuffer,
    admission_group_inert: IntegerBuffer,
    admission_tau: IntegerBuffer,
    admission_x: IntegerBuffer,
    admission_y: IntegerBuffer,
    admission_spare: IntegerBuffer,
    admission_stack: IntegerBuffer,
    admission_primitive: IntegerBuffer,
    admission_columns: IntegerBuffer,
    admission_values: IntegerBuffer,
    admission_temporary: IntegerBuffer,
    admission_indices: IntegerBuffer,
    admission_exponents: IntegerBuffer,
    diagnostic: IntegerBuffer,
    nrelid: int,
    track_fact: int,
    jid0: int,
    e0: int,
    subfactor: IntegerBuffer,
    extra: IntegerBuffer,
    extra_count: int,
    relation_primes: IntegerBuffer,
    ramification: IntegerBuffer,
    relation: IntegerBuffer,
    relation_state: IntegerBuffer,
    relation_basis: IntegerBuffer,
    relation_records: IntegerBuffer,
    relation_hashes: IntegerBuffer,
    relation_metadata: IntegerBuffer,
    relation_scratch: IntegerBuffer,
    generators: IntegerBuffer,
    progress: Int64Buffer,
    preparation_rounded_embedding: IntegerBuffer,
    preparation_embedding: IntegerBuffer,
    preparation_original: IntegerBuffer,
    preparation_basis: IntegerBuffer,
    preparation_transform: IntegerBuffer,
    preparation_flags: IntegerBuffer,
    preparation_rank_diagnostic: IntegerBuffer,
    preparation_selection: IntegerBuffer,
    preparation_stages: IntegerBuffer,
    preparation_flatter_input: IntegerBuffer,
    preparation_current: IntegerBuffer,
    preparation_flatter_transform: IntegerBuffer,
    preparation_total_work: IntegerBuffer,
    preparation_step_t: IntegerBuffer,
    preparation_step_s: IntegerBuffer,
    preparation_product: IntegerBuffer,
    preparation_next_basis: IntegerBuffer,
    preparation_y: IntegerBuffer,
    preparation_diagnostic: IntegerBuffer,
    preparation_r1: IntegerBuffer,
    preparation_r2: IntegerBuffer,
    preparation_r3: IntegerBuffer,
    preparation_t1: IntegerBuffer,
    preparation_t2: IntegerBuffer,
    preparation_t3: IntegerBuffer,
    preparation_integers: IntegerBuffer,
    preparation_inverse: IntegerBuffer,
    preparation_first: IntegerBuffer,
    preparation_second: IntegerBuffer,
    preparation_final: IntegerBuffer,
    preparation_rounded: IntegerBuffer,
    preparation_mu: Float64Buffer,
    preparation_r: Float64Buffer,
    preparation_s: Float64Buffer,
    preparation_approximate: Float64Buffer,
    preparation_exponents: IntegerBuffer,
    preparation_float_gram: Float64Buffer,
    preparation_gram: IntegerBuffer,
    preparation_mu_exponents: IntegerBuffer,
    preparation_r_exponents: IntegerBuffer,
    preparation_s_exponents: IntegerBuffer,
    preparation_alpha: IntegerBuffer,
    preparation_column_exponents: IntegerBuffer,
    preparation_float_scratch: Float64Buffer,
    preparation_temporary: Float64Buffer,
    preparation_state: Int64Buffer,
    search_ideals: IntegerBuffer,
    search_count: int,
    packet_ids: IntegerBuffer,
    packet_ideals: IntegerBuffer,
    packet_norms: IntegerBuffer,
    schedule: Int64Buffer,
    construct_primes: int,
    basis_table: IntegerBuffer,
    packet_primes: IntegerBuffer,
    packet_generators: IntegerBuffer,
    packet_inert: IntegerBuffer,
    hnf_generator: IntegerBuffer,
    hnf_matrix: IntegerBuffer,
    hnf_work: IntegerBuffer,
    hnf_pivots: IntegerBuffer,
    power_ideal: IntegerBuffer,
    power_alpha: IntegerBuffer,
    power_metadata: IntegerBuffer,
    power_primitive: IntegerBuffer,
    power_temporary: IntegerBuffer,
    power_diagnostic: IntegerBuffer,
    power_multiplication: IntegerBuffer,
    power_work: IntegerBuffer,
    power_triangular: IntegerBuffer,
    power_moduli: IntegerBuffer,
    product_primitive: IntegerBuffer,
    product_matrix: IntegerBuffer,
    outer_mode: int,
    outer_ru: int,
    outer_state: Int64Buffer,
    outer_minidx: IntegerBuffer,
    outer_present: IntegerBuffer,
    outer_live: IntegerBuffer,
    outer_perm: IntegerBuffer,
    outer_multiplier: IntegerBuffer,
    log_precision: int,
    log_completed: IntegerBuffer,
    log_embeddings: IntegerBuffer,
    log_coordinates: IntegerBuffer,
    log_column: IntegerBuffer,
    log_cache: IntegerBuffer,
    log_pi_cache: IntegerBuffer,
    log_a: IntegerBuffer,
    log_b: IntegerBuffer,
    log_p: IntegerBuffer,
    log_q: IntegerBuffer,
    log_stack: IntegerBuffer,
    initial_additional: int,
    initial_target: int,
    initial_primes: IntegerBuffer,
    initial_offsets: IntegerBuffer,
    initial_counts: IntegerBuffer,
    initial_complete: IntegerBuffer,
    hnf_k0: int,
    hnf_original: Int64Buffer,
    hnf_perm: Int64Buffer,
    hnf_mat: Int64Buffer,
    hnf_dense: IntegerBuffer,
    hnf_transform: IntegerBuffer,
    hnf_vmax: Int64Buffer,
    hnf_found: Int64Buffer,
    hnf_sparse_state: Int64Buffer,
    hnf_bottom: IntegerBuffer,
    hnf_updated_dense: IntegerBuffer,
    hnf_extra: IntegerBuffer,
    hnf_cleanup_state: Int64Buffer,
    hnf_rank_matrix: IntegerBuffer,
    hnf_occupied: IntegerBuffer,
    hnf_rank_pivots: IntegerBuffer,
    hnf_best: IntegerBuffer,
    hnf_profile: IntegerBuffer,
    hnf_rank_state: IntegerBuffer,
    hnf_perm_work: Int64Buffer,
    hnf_matbnew: IntegerBuffer,
    hnf_dep: IntegerBuffer,
    hnf_b: IntegerBuffer,
    hnf_assembly_state: Int64Buffer,
    hnf_transformed_logs: IntegerBuffer,
    hnf_full_h: IntegerBuffer,
    hnf_hnf_transform: IntegerBuffer,
    hnf_lam: IntegerBuffer,
    hnf_d: IntegerBuffer,
    hnf_hnf_state: Int64Buffer,
    hnf_full_dep: IntegerBuffer,
    hnf_work_b: IntegerBuffer,
    hnf_work_c: IntegerBuffer,
    hnf_diagonal: Int64Buffer,
    hnf_result_h: IntegerBuffer,
    hnf_result_dep: IntegerBuffer,
    hnf_result_b: IntegerBuffer,
    hnf_result_c: IntegerBuffer,
    hnf_final_state: Int64Buffer,
    hnf_state: Int64Buffer,
    chain_state: Int64Buffer,
    hnf_cup_arena: IntegerBuffer,
    hnf_cup_frames: IntegerBuffer,
    hnf_cup_solve_state: Int64Buffer,
    hnf_cup_state: Int64Buffer,
    analytic_polynomial: IntegerBuffer,
    analytic_primes: IntegerBuffer,
    analytic_prime_count: int,
    analytic_discriminant: int,
    analytic_roots_of_unity: int,
    catalog_workspace: IntegerBuffer,
    pattern_offsets: IntegerBuffer,
    pattern_counts: IntegerBuffer,
    pattern_degrees: IntegerBuffer,
    pattern_multiplicities: IntegerBuffer,
    suffix_embedding_matrix: IntegerBuffer,
    suffix_work_arena: IntegerBuffer,
    suffix_exact_arena: IntegerBuffer,
    output_units: IntegerBuffer,
    output_norms: IntegerBuffer,
    output_class_number: IntegerBuffer,
    output_invariants: IntegerBuffer,
    suffix_state: Int64Buffer,
    aggregate_state: Int64Buffer,
) -> int:
    if len(aggregate_state) < 4:
        raise ValueError("short row-23 aggregate state")
    for i in range(4):
        aggregate_state[i] = 0
    aggregate_state[0] = -1
    status = pari_connected_relation_hnf(
        matrix,
        ideal,
        n,
        precision,
        scale,
        track_small,
        reduction,
        vectors,
        betas,
        norms,
        column,
        float_q,
        float_v,
        bound,
        cache,
        a,
        b,
        p,
        q,
        stack,
        x,
        y,
        z,
        inc,
        state,
        cursor_output,
        element,
        counters,
        admission_matrix_m,
        admission_matrix_p,
        admission_matrix_e,
        admission_embedding_m,
        admission_embedding_p,
        admission_embedding_e,
        admission_real_count,
        admission_ideal,
        admission_mode,
        admission_factor_product,
        admission_primes,
        admission_products,
        admission_factorlimit,
        admission_prime_limit,
        admission_rational_factors,
        admission_rational_exponents,
        admission_prime_offsets,
        admission_prime_counts,
        admission_group_tau,
        admission_group_e,
        admission_group_f,
        admission_group_inert,
        admission_tau,
        admission_x,
        admission_y,
        admission_spare,
        admission_stack,
        admission_primitive,
        admission_columns,
        admission_values,
        admission_temporary,
        admission_indices,
        admission_exponents,
        diagnostic,
        nrelid,
        track_fact,
        jid0,
        e0,
        subfactor,
        extra,
        extra_count,
        relation_primes,
        ramification,
        relation,
        relation_state,
        relation_basis,
        relation_records,
        relation_hashes,
        relation_metadata,
        relation_scratch,
        generators,
        progress,
        preparation_rounded_embedding,
        preparation_embedding,
        preparation_original,
        preparation_basis,
        preparation_transform,
        preparation_flags,
        preparation_rank_diagnostic,
        preparation_selection,
        preparation_stages,
        preparation_flatter_input,
        preparation_current,
        preparation_flatter_transform,
        preparation_total_work,
        preparation_step_t,
        preparation_step_s,
        preparation_product,
        preparation_next_basis,
        preparation_y,
        preparation_diagnostic,
        preparation_r1,
        preparation_r2,
        preparation_r3,
        preparation_t1,
        preparation_t2,
        preparation_t3,
        preparation_integers,
        preparation_inverse,
        preparation_first,
        preparation_second,
        preparation_final,
        preparation_rounded,
        preparation_mu,
        preparation_r,
        preparation_s,
        preparation_approximate,
        preparation_exponents,
        preparation_float_gram,
        preparation_gram,
        preparation_mu_exponents,
        preparation_r_exponents,
        preparation_s_exponents,
        preparation_alpha,
        preparation_column_exponents,
        preparation_float_scratch,
        preparation_temporary,
        preparation_state,
        search_ideals,
        search_count,
        packet_ids,
        packet_ideals,
        packet_norms,
        schedule,
        construct_primes,
        basis_table,
        packet_primes,
        packet_generators,
        packet_inert,
        hnf_generator,
        hnf_matrix,
        hnf_work,
        hnf_pivots,
        power_ideal,
        power_alpha,
        power_metadata,
        power_primitive,
        power_temporary,
        power_diagnostic,
        power_multiplication,
        power_work,
        power_triangular,
        power_moduli,
        product_primitive,
        product_matrix,
        outer_mode,
        outer_ru,
        outer_state,
        outer_minidx,
        outer_present,
        outer_live,
        outer_perm,
        outer_multiplier,
        log_precision,
        log_completed,
        log_embeddings,
        log_coordinates,
        log_column,
        log_cache,
        log_pi_cache,
        log_a,
        log_b,
        log_p,
        log_q,
        log_stack,
        initial_additional,
        initial_target,
        initial_primes,
        initial_offsets,
        initial_counts,
        initial_complete,
        hnf_k0,
        hnf_original,
        hnf_perm,
        hnf_mat,
        hnf_dense,
        hnf_transform,
        hnf_vmax,
        hnf_found,
        hnf_sparse_state,
        hnf_bottom,
        hnf_updated_dense,
        hnf_extra,
        hnf_cleanup_state,
        hnf_rank_matrix,
        hnf_occupied,
        hnf_rank_pivots,
        hnf_best,
        hnf_profile,
        hnf_rank_state,
        hnf_perm_work,
        hnf_matbnew,
        hnf_dep,
        hnf_b,
        hnf_assembly_state,
        hnf_transformed_logs,
        hnf_full_h,
        hnf_hnf_transform,
        hnf_lam,
        hnf_d,
        hnf_hnf_state,
        hnf_full_dep,
        hnf_work_b,
        hnf_work_c,
        hnf_diagonal,
        hnf_result_h,
        hnf_result_dep,
        hnf_result_b,
        hnf_result_c,
        hnf_final_state,
        hnf_state,
        chain_state,
        hnf_cup_arena,
        hnf_cup_frames,
        hnf_cup_solve_state,
        hnf_cup_state,
    )
    aggregate_state[1] = status
    if status != 0:
        return 1
    status = pari_row23_phase6_suffix_root(
        analytic_polynomial,
        basis_table,
        analytic_primes,
        analytic_prime_count,
        analytic_discriminant,
        analytic_roots_of_unity,
        catalog_workspace,
        pattern_offsets,
        pattern_counts,
        pattern_degrees,
        pattern_multiplicities,
        hnf_result_h,
        hnf_result_c,
        suffix_embedding_matrix,
        suffix_work_arena,
        suffix_exact_arena,
        output_units,
        output_norms,
        output_class_number,
        output_invariants,
        suffix_state,
    )
    aggregate_state[2] = status
    if status != 0:
        return 2
    aggregate_state[0] = 0
    aggregate_state[3] = 1
    return 0


__all__ = ["pari_row23_phase6_aggregate_root"]
