"""Generated resident row-21 factor-base through connected HNF root.

Copyright (C) The PARI group. GPL-2.0-or-later, without warranty.
Generated mechanically by row21_phase6_connected_source.cjs.
"""

from sagejs.native import IntegerBuffer, integer_buffer_view, native

from .connected_relation_hnf import pari_connected_relation_hnf
from .row21_phase6_factor_base_root import pari_row21_phase6_factor_base_root


@native
def pari_row21_phase6_connected_hnf_root(
    fb_polynomial: IntegerBuffer,
    fb_basis_table: IntegerBuffer,
    fb_matrix_m: IntegerBuffer,
    fb_matrix_p: IntegerBuffer,
    fb_matrix_e: IntegerBuffer,
    fb_discriminant: int,
    fb_equation_index: int,
    fb_primes: IntegerBuffer,
    fb_prime_count: int,
    fb_descriptor_workspace: IntegerBuffer,
    fb_descriptor_scratch: IntegerBuffer,
    fb_descriptor_ranks: IntegerBuffer,
    fb_descriptor_state: IntegerBuffer,
    fb_degree_scratch: IntegerBuffer,
    fb_exponent_scratch: IntegerBuffer,
    fb_factor_workspace: IntegerBuffer,
    fb_factor_state: IntegerBuffer,
    fb_pattern_offsets: IntegerBuffer,
    fb_pattern_counts: IntegerBuffer,
    fb_pattern_degrees: IntegerBuffer,
    fb_pattern_multiplicities: IntegerBuffer,
    fb_full_offsets: IntegerBuffer,
    fb_full_counts: IntegerBuffer,
    fb_full_degrees: IntegerBuffer,
    fb_configuration: Float64Buffer,
    fb_bound_norms: IntegerBuffer,
    fb_constants_logs: Float64Buffer,
    fb_sums: Float64Buffer,
    fb_factor_logs: Float64Buffer,
    fb_selected_primes: IntegerBuffer,
    fb_prime_offsets: IntegerBuffer,
    fb_prime_counts: IntegerBuffer,
    fb_complete_groups: IntegerBuffer,
    fb_selected_indices: IntegerBuffer,
    fb_base_state: IntegerBuffer,
    fb_selected_descriptors: IntegerBuffer,
    fb_selected_ideals: IntegerBuffer,
    fb_selected_norms: IntegerBuffer,
    fb_group_offsets: IntegerBuffer,
    fb_group_sizes: IntegerBuffer,
    fb_group_complete: IntegerBuffer,
    fb_hnf_multiplication: IntegerBuffer,
    fb_hnf_work: IntegerBuffer,
    fb_hnf_pivots: IntegerBuffer,
    fb_subfactor_bad: IntegerBuffer,
    fb_subfactor_configuration: Float64Buffer,
    fb_subfactor_order: IntegerBuffer,
    fb_subfactor_scratch: IntegerBuffer,
    fb_subfactor_stack: IntegerBuffer,
    fb_subfactor_chosen: IntegerBuffer,
    fb_subfactor_rejected: IntegerBuffer,
    fb_permutation: IntegerBuffer,
    fb_subfactor_state: IntegerBuffer,
    fb_relation_ramification: IntegerBuffer,
    fb_relation_state: IntegerBuffer,
    fb_relation_basis: IntegerBuffer,
    fb_relation_records: IntegerBuffer,
    fb_relation_hashes: IntegerBuffer,
    fb_relation_metadata: IntegerBuffer,
    fb_relation: IntegerBuffer,
    fb_relation_scratch: IntegerBuffer,
    fb_relation_generators: IntegerBuffer,
    fb_frontier_state: IntegerBuffer,
    fb_resident_state: IntegerBuffer,
    h_matrix: IntegerBuffer,
    h_ideal: IntegerBuffer,
    h_n: int,
    h_precision: int,
    h_scale: float,
    h_track_small: int,
    h_reduction: IntegerBuffer,
    h_vectors: IntegerBuffer,
    h_betas: IntegerBuffer,
    h_norms: IntegerBuffer,
    h_column: IntegerBuffer,
    h_float_q: Float64Buffer,
    h_float_v: Float64Buffer,
    h_bound: Float64Buffer,
    h_cache: IntegerBuffer,
    h_a: IntegerBuffer,
    h_b: IntegerBuffer,
    h_p: IntegerBuffer,
    h_q: IntegerBuffer,
    h_stack: IntegerBuffer,
    h_x: Int64Buffer,
    h_y: Float64Buffer,
    h_z: Float64Buffer,
    h_inc: Int64Buffer,
    h_state: Int64Buffer,
    h_cursor_output: Int64Buffer,
    h_element: IntegerBuffer,
    h_counters: Int64Buffer,
    h_admission_embedding_m: IntegerBuffer,
    h_admission_embedding_p: IntegerBuffer,
    h_admission_embedding_e: IntegerBuffer,
    h_admission_real_count: int,
    h_admission_ideal: IntegerBuffer,
    h_admission_mode: int,
    h_admission_primes: IntegerBuffer,
    h_admission_products: IntegerBuffer,
    h_admission_factorlimit: int,
    h_admission_prime_limit: int,
    h_admission_rational_factors: IntegerBuffer,
    h_admission_rational_exponents: IntegerBuffer,
    h_admission_group_tau: IntegerBuffer,
    h_admission_group_e: IntegerBuffer,
    h_admission_group_f: IntegerBuffer,
    h_admission_group_inert: IntegerBuffer,
    h_admission_tau: IntegerBuffer,
    h_admission_x: IntegerBuffer,
    h_admission_y: IntegerBuffer,
    h_admission_spare: IntegerBuffer,
    h_admission_stack: IntegerBuffer,
    h_admission_primitive: IntegerBuffer,
    h_admission_columns: IntegerBuffer,
    h_admission_values: IntegerBuffer,
    h_admission_temporary: IntegerBuffer,
    h_admission_indices: IntegerBuffer,
    h_admission_exponents: IntegerBuffer,
    h_diagnostic: IntegerBuffer,
    h_nrelid: int,
    h_track_fact: int,
    h_jid0: int,
    h_e0: int,
    h_subfactor: IntegerBuffer,
    h_extra: IntegerBuffer,
    h_extra_count: int,
    h_relation_primes: IntegerBuffer,
    h_ramification: IntegerBuffer,
    h_relation: IntegerBuffer,
    h_relation_state: IntegerBuffer,
    h_relation_basis: IntegerBuffer,
    h_relation_records: IntegerBuffer,
    h_relation_hashes: IntegerBuffer,
    h_relation_metadata: IntegerBuffer,
    h_relation_scratch: IntegerBuffer,
    h_generators: IntegerBuffer,
    h_progress: Int64Buffer,
    h_preparation_rounded_embedding: IntegerBuffer,
    h_preparation_embedding: IntegerBuffer,
    h_preparation_original: IntegerBuffer,
    h_preparation_basis: IntegerBuffer,
    h_preparation_transform: IntegerBuffer,
    h_preparation_flags: IntegerBuffer,
    h_preparation_rank_diagnostic: IntegerBuffer,
    h_preparation_selection: IntegerBuffer,
    h_preparation_stages: IntegerBuffer,
    h_preparation_flatter_input: IntegerBuffer,
    h_preparation_current: IntegerBuffer,
    h_preparation_flatter_transform: IntegerBuffer,
    h_preparation_total_work: IntegerBuffer,
    h_preparation_step_t: IntegerBuffer,
    h_preparation_step_s: IntegerBuffer,
    h_preparation_product: IntegerBuffer,
    h_preparation_next_basis: IntegerBuffer,
    h_preparation_y: IntegerBuffer,
    h_preparation_diagnostic: IntegerBuffer,
    h_preparation_r1: IntegerBuffer,
    h_preparation_r2: IntegerBuffer,
    h_preparation_r3: IntegerBuffer,
    h_preparation_t1: IntegerBuffer,
    h_preparation_t2: IntegerBuffer,
    h_preparation_t3: IntegerBuffer,
    h_preparation_integers: IntegerBuffer,
    h_preparation_inverse: IntegerBuffer,
    h_preparation_first: IntegerBuffer,
    h_preparation_second: IntegerBuffer,
    h_preparation_final: IntegerBuffer,
    h_preparation_rounded: IntegerBuffer,
    h_preparation_mu: Float64Buffer,
    h_preparation_r: Float64Buffer,
    h_preparation_s: Float64Buffer,
    h_preparation_approximate: Float64Buffer,
    h_preparation_exponents: IntegerBuffer,
    h_preparation_float_gram: Float64Buffer,
    h_preparation_gram: IntegerBuffer,
    h_preparation_mu_exponents: IntegerBuffer,
    h_preparation_r_exponents: IntegerBuffer,
    h_preparation_s_exponents: IntegerBuffer,
    h_preparation_alpha: IntegerBuffer,
    h_preparation_column_exponents: IntegerBuffer,
    h_preparation_float_scratch: Float64Buffer,
    h_preparation_temporary: Float64Buffer,
    h_preparation_state: Int64Buffer,
    h_search_ideals: IntegerBuffer,
    h_search_count: int,
    h_packet_ids: IntegerBuffer,
    h_schedule: Int64Buffer,
    h_construct_primes: int,
    h_packet_primes: IntegerBuffer,
    h_packet_generators: IntegerBuffer,
    h_packet_inert: IntegerBuffer,
    h_hnf_generator: IntegerBuffer,
    h_hnf_matrix: IntegerBuffer,
    h_hnf_work: IntegerBuffer,
    h_hnf_pivots: IntegerBuffer,
    h_power_ideal: IntegerBuffer,
    h_power_alpha: IntegerBuffer,
    h_power_metadata: IntegerBuffer,
    h_power_primitive: IntegerBuffer,
    h_power_temporary: IntegerBuffer,
    h_power_diagnostic: IntegerBuffer,
    h_power_multiplication: IntegerBuffer,
    h_power_work: IntegerBuffer,
    h_power_triangular: IntegerBuffer,
    h_power_moduli: IntegerBuffer,
    h_product_primitive: IntegerBuffer,
    h_product_matrix: IntegerBuffer,
    h_outer_mode: int,
    h_outer_ru: int,
    h_outer_state: Int64Buffer,
    h_outer_minidx: IntegerBuffer,
    h_outer_present: IntegerBuffer,
    h_outer_live: IntegerBuffer,
    h_outer_perm: IntegerBuffer,
    h_outer_multiplier: IntegerBuffer,
    h_log_precision: int,
    h_log_completed: IntegerBuffer,
    h_log_embeddings: IntegerBuffer,
    h_log_coordinates: IntegerBuffer,
    h_log_column: IntegerBuffer,
    h_log_cache: IntegerBuffer,
    h_log_pi_cache: IntegerBuffer,
    h_log_a: IntegerBuffer,
    h_log_b: IntegerBuffer,
    h_log_p: IntegerBuffer,
    h_log_q: IntegerBuffer,
    h_log_stack: IntegerBuffer,
    h_initial_additional: int,
    h_initial_target: int,
    h_hnf_k0: int,
    h_hnf_original: Int64Buffer,
    h_hnf_perm: Int64Buffer,
    h_hnf_mat: Int64Buffer,
    h_hnf_dense: IntegerBuffer,
    h_hnf_transform: IntegerBuffer,
    h_hnf_vmax: Int64Buffer,
    h_hnf_found: Int64Buffer,
    h_hnf_sparse_state: Int64Buffer,
    h_hnf_bottom: IntegerBuffer,
    h_hnf_updated_dense: IntegerBuffer,
    h_hnf_extra: IntegerBuffer,
    h_hnf_cleanup_state: Int64Buffer,
    h_hnf_rank_matrix: IntegerBuffer,
    h_hnf_occupied: IntegerBuffer,
    h_hnf_rank_pivots: IntegerBuffer,
    h_hnf_best: IntegerBuffer,
    h_hnf_profile: IntegerBuffer,
    h_hnf_rank_state: IntegerBuffer,
    h_hnf_perm_work: Int64Buffer,
    h_hnf_matbnew: IntegerBuffer,
    h_hnf_dep: IntegerBuffer,
    h_hnf_b: IntegerBuffer,
    h_hnf_assembly_state: Int64Buffer,
    h_hnf_transformed_logs: IntegerBuffer,
    h_hnf_full_h: IntegerBuffer,
    h_hnf_hnf_transform: IntegerBuffer,
    h_hnf_lam: IntegerBuffer,
    h_hnf_d: IntegerBuffer,
    h_hnf_hnf_state: Int64Buffer,
    h_hnf_full_dep: IntegerBuffer,
    h_hnf_work_b: IntegerBuffer,
    h_hnf_work_c: IntegerBuffer,
    h_hnf_diagonal: Int64Buffer,
    h_hnf_result_h: IntegerBuffer,
    h_hnf_result_dep: IntegerBuffer,
    h_hnf_result_b: IntegerBuffer,
    h_hnf_result_c: IntegerBuffer,
    h_hnf_final_state: Int64Buffer,
    h_hnf_state: Int64Buffer,
    h_chain_state: Int64Buffer,
    h_hnf_cup_arena: IntegerBuffer,
    h_hnf_cup_frames: IntegerBuffer,
    h_hnf_cup_solve_state: Int64Buffer,
    h_hnf_cup_state: Int64Buffer,
    connected_state: IntegerBuffer,
) -> int:
    if len(connected_state) < 5:
        raise ValueError("short row21 connected resident state")
    for i in range(5):
        connected_state[i] = 0
    connected_state[0] = -1
    status = pari_row21_phase6_factor_base_root(
        fb_polynomial,
        fb_basis_table,
        fb_matrix_m,
        fb_matrix_p,
        fb_matrix_e,
        fb_discriminant,
        fb_equation_index,
        fb_primes,
        fb_prime_count,
        fb_descriptor_workspace,
        fb_descriptor_scratch,
        fb_descriptor_ranks,
        fb_descriptor_state,
        fb_degree_scratch,
        fb_exponent_scratch,
        fb_factor_workspace,
        fb_factor_state,
        fb_pattern_offsets,
        fb_pattern_counts,
        fb_pattern_degrees,
        fb_pattern_multiplicities,
        fb_full_offsets,
        fb_full_counts,
        fb_full_degrees,
        fb_configuration,
        fb_bound_norms,
        fb_constants_logs,
        fb_sums,
        fb_factor_logs,
        fb_selected_primes,
        fb_prime_offsets,
        fb_prime_counts,
        fb_complete_groups,
        fb_selected_indices,
        fb_base_state,
        fb_selected_descriptors,
        fb_selected_ideals,
        fb_selected_norms,
        fb_group_offsets,
        fb_group_sizes,
        fb_group_complete,
        fb_hnf_multiplication,
        fb_hnf_work,
        fb_hnf_pivots,
        fb_subfactor_bad,
        fb_subfactor_configuration,
        fb_subfactor_order,
        fb_subfactor_scratch,
        fb_subfactor_stack,
        fb_subfactor_chosen,
        fb_subfactor_rejected,
        fb_permutation,
        fb_subfactor_state,
        fb_relation_ramification,
        fb_relation_state,
        fb_relation_basis,
        fb_relation_records,
        fb_relation_hashes,
        fb_relation_metadata,
        fb_relation,
        fb_relation_scratch,
        fb_relation_generators,
        fb_frontier_state,
        fb_resident_state,
    )
    connected_state[1] = status
    if status != 0:
        connected_state[0] = status
        return status

    stride = 33
    rows = fb_resident_state[2]
    groups = fb_resident_state[3]
    subcount = fb_subfactor_state[0]
    for i in range(rows):
        h_admission_group_e[i] = fb_selected_descriptors[i * stride + 1]
        h_admission_group_f[i] = fb_selected_descriptors[i * stride + 2]
        h_relation_primes[i] = fb_selected_descriptors[i * stride]
        h_ramification[i] = fb_selected_descriptors[i * stride + 1]
        h_packet_primes[i] = fb_selected_descriptors[i * stride]
        inert = 1
        for j in range(5):
            generator = fb_selected_descriptors[i * stride + 3 + j]
            h_packet_generators[i * 5 + j] = generator
            if generator != 0:
                inert = 0
        h_admission_group_inert[i] = inert
        h_packet_inert[i] = inert
        h_search_ideals[i] = fb_permutation[i]
        h_packet_ids[i] = i + 1
        h_outer_perm[i] = fb_permutation[i]
        h_hnf_perm[i] = fb_permutation[i]
    for i in range(rows):
        for row in range(5):
            for column in range(5):
                h_admission_group_tau[i * 25 + row * 5 + column] = (
                    fb_selected_descriptors[i * stride + 8 + column * 5 + row]
                )
    for i in range(subcount):
        h_subfactor[i] = fb_permutation[i]

    status = pari_connected_relation_hnf(
        h_matrix,
        h_ideal,
        h_n,
        h_precision,
        h_scale,
        h_track_small,
        h_reduction,
        h_vectors,
        h_betas,
        h_norms,
        h_column,
        h_float_q,
        h_float_v,
        h_bound,
        h_cache,
        h_a,
        h_b,
        h_p,
        h_q,
        h_stack,
        h_x,
        h_y,
        h_z,
        h_inc,
        h_state,
        h_cursor_output,
        h_element,
        h_counters,
        fb_matrix_m,
        fb_matrix_p,
        fb_matrix_e,
        h_admission_embedding_m,
        h_admission_embedding_p,
        h_admission_embedding_e,
        h_admission_real_count,
        h_admission_ideal,
        h_admission_mode,
        fb_base_state[6],
        h_admission_primes,
        h_admission_products,
        h_admission_factorlimit,
        h_admission_prime_limit,
        h_admission_rational_factors,
        h_admission_rational_exponents,
        fb_prime_offsets,
        fb_prime_counts,
        h_admission_group_tau,
        h_admission_group_e,
        h_admission_group_f,
        h_admission_group_inert,
        h_admission_tau,
        h_admission_x,
        h_admission_y,
        h_admission_spare,
        h_admission_stack,
        h_admission_primitive,
        h_admission_columns,
        h_admission_values,
        h_admission_temporary,
        h_admission_indices,
        h_admission_exponents,
        h_diagnostic,
        h_nrelid,
        h_track_fact,
        h_jid0,
        h_e0,
        h_subfactor,
        h_extra,
        h_extra_count,
        h_relation_primes,
        h_ramification,
        h_relation,
        h_relation_state,
        h_relation_basis,
        h_relation_records,
        h_relation_hashes,
        h_relation_metadata,
        h_relation_scratch,
        h_generators,
        h_progress,
        h_preparation_rounded_embedding,
        h_preparation_embedding,
        h_preparation_original,
        h_preparation_basis,
        h_preparation_transform,
        h_preparation_flags,
        h_preparation_rank_diagnostic,
        h_preparation_selection,
        h_preparation_stages,
        h_preparation_flatter_input,
        h_preparation_current,
        h_preparation_flatter_transform,
        h_preparation_total_work,
        h_preparation_step_t,
        h_preparation_step_s,
        h_preparation_product,
        h_preparation_next_basis,
        h_preparation_y,
        h_preparation_diagnostic,
        h_preparation_r1,
        h_preparation_r2,
        h_preparation_r3,
        h_preparation_t1,
        h_preparation_t2,
        h_preparation_t3,
        h_preparation_integers,
        h_preparation_inverse,
        h_preparation_first,
        h_preparation_second,
        h_preparation_final,
        h_preparation_rounded,
        h_preparation_mu,
        h_preparation_r,
        h_preparation_s,
        h_preparation_approximate,
        h_preparation_exponents,
        h_preparation_float_gram,
        h_preparation_gram,
        h_preparation_mu_exponents,
        h_preparation_r_exponents,
        h_preparation_s_exponents,
        h_preparation_alpha,
        h_preparation_column_exponents,
        h_preparation_float_scratch,
        h_preparation_temporary,
        h_preparation_state,
        h_search_ideals,
        h_search_count,
        h_packet_ids,
        fb_selected_ideals,
        fb_selected_norms,
        h_schedule,
        h_construct_primes,
        fb_basis_table,
        h_packet_primes,
        h_packet_generators,
        h_packet_inert,
        h_hnf_generator,
        h_hnf_matrix,
        h_hnf_work,
        h_hnf_pivots,
        h_power_ideal,
        h_power_alpha,
        h_power_metadata,
        h_power_primitive,
        h_power_temporary,
        h_power_diagnostic,
        h_power_multiplication,
        h_power_work,
        h_power_triangular,
        h_power_moduli,
        h_product_primitive,
        h_product_matrix,
        h_outer_mode,
        h_outer_ru,
        h_outer_state,
        h_outer_minidx,
        h_outer_present,
        h_outer_live,
        h_outer_perm,
        h_outer_multiplier,
        h_log_precision,
        h_log_completed,
        h_log_embeddings,
        h_log_coordinates,
        h_log_column,
        h_log_cache,
        h_log_pi_cache,
        h_log_a,
        h_log_b,
        h_log_p,
        h_log_q,
        h_log_stack,
        h_initial_additional,
        h_initial_target,
        integer_buffer_view(fb_selected_primes, 0, fb_base_state[4]),
        fb_group_offsets,
        fb_group_sizes,
        fb_group_complete,
        h_hnf_k0,
        h_hnf_original,
        h_hnf_perm,
        h_hnf_mat,
        h_hnf_dense,
        h_hnf_transform,
        h_hnf_vmax,
        h_hnf_found,
        h_hnf_sparse_state,
        h_hnf_bottom,
        h_hnf_updated_dense,
        h_hnf_extra,
        h_hnf_cleanup_state,
        h_hnf_rank_matrix,
        h_hnf_occupied,
        h_hnf_rank_pivots,
        h_hnf_best,
        h_hnf_profile,
        h_hnf_rank_state,
        h_hnf_perm_work,
        h_hnf_matbnew,
        h_hnf_dep,
        h_hnf_b,
        h_hnf_assembly_state,
        h_hnf_transformed_logs,
        h_hnf_full_h,
        h_hnf_hnf_transform,
        h_hnf_lam,
        h_hnf_d,
        h_hnf_hnf_state,
        h_hnf_full_dep,
        h_hnf_work_b,
        h_hnf_work_c,
        h_hnf_diagonal,
        h_hnf_result_h,
        h_hnf_result_dep,
        h_hnf_result_b,
        h_hnf_result_c,
        h_hnf_final_state,
        h_hnf_state,
        h_chain_state,
        h_hnf_cup_arena,
        h_hnf_cup_frames,
        h_hnf_cup_solve_state,
        h_hnf_cup_state,
    )
    connected_state[0] = status
    connected_state[2] = h_chain_state[0]
    connected_state[3] = h_hnf_state[1]
    connected_state[4] = h_relation_state[0]
    return status


__all__ = ["pari_row21_phase6_connected_hnf_root"]
