"""Generated connected row-6 prepared factor/initial prefix."""

from sagejs.native import Float64Buffer, IntegerBuffer, integer_buffer_view, native
from .row6_prepared_factor_base_root import pari_row6_prepared_factor_base_root
from .row6_prepared_initial_relations import pari_row6_prepared_initial_relations


@native
def pari_row6_phase6_prepared_prefix_root(
    factor_polynomial: IntegerBuffer,
    factor_discriminant: int,
    factor_real_places: int,
    factor_complex_pairs: int,
    factor_precision: int,
    factor_equation_index: int,
    factor_roots_of_unity: int,
    factor_zkden: int,
    factor_invzk: IntegerBuffer,
    factor_zk: IntegerBuffer,
    factor_zk_degrees: IntegerBuffer,
    factor_basis_table: IntegerBuffer,
    factor_embedding_m: IntegerBuffer,
    factor_embedding_p: IntegerBuffer,
    factor_embedding_e: IntegerBuffer,
    factor_runtime_primes: IntegerBuffer,
    factor_runtime_products: IntegerBuffer,
    factor_factor_limit: int,
    factor_prime_limit: int,
    factor_index_work: IntegerBuffer,
    factor_degree_workspace: IntegerBuffer,
    factor_factor_degrees: IntegerBuffer,
    factor_factor_exponents: IntegerBuffer,
    factor_group_degrees: IntegerBuffer,
    factor_group_counts: IntegerBuffer,
    factor_local_state: IntegerBuffer,
    factor_pattern_offsets: IntegerBuffer,
    factor_pattern_counts: IntegerBuffer,
    factor_pattern_degrees: IntegerBuffer,
    factor_pattern_multiplicities: IntegerBuffer,
    factor_full_offsets: IntegerBuffer,
    factor_full_counts: IntegerBuffer,
    factor_full_degrees: IntegerBuffer,
    factor_degree_state: IntegerBuffer,
    factor_base_norms: IntegerBuffer,
    factor_base_configuration: Float64Buffer,
    factor_base_constants_logs: Float64Buffer,
    factor_base_sums: Float64Buffer,
    factor_base_factor_logs: Float64Buffer,
    factor_selected_primes: IntegerBuffer,
    factor_prime_offsets: IntegerBuffer,
    factor_prime_counts: IntegerBuffer,
    factor_complete_groups: IntegerBuffer,
    factor_selected_indices: IntegerBuffer,
    factor_base_state: IntegerBuffer,
    factor_random_state: IntegerBuffer,
    factor_kummer_factorwork: IntegerBuffer,
    factor_kummer_factor: IntegerBuffer,
    factor_kummer_diagnostic: IntegerBuffer,
    factor_kummer_minpoly_diagnostic: IntegerBuffer,
    factor_kummer_polywork: IntegerBuffer,
    factor_kummer_u: IntegerBuffer,
    factor_kummer_t: IntegerBuffer,
    factor_kummer_rational: IntegerBuffer,
    factor_kummer_primitive: IntegerBuffer,
    factor_kummer_column: IntegerBuffer,
    factor_kummer_resultant_work: IntegerBuffer,
    factor_kummer_resultant_trace: IntegerBuffer,
    factor_kummer_u_output: IntegerBuffer,
    factor_kummer_tau_output: IntegerBuffer,
    factor_kummer_descriptor_state: IntegerBuffer,
    factor_kummer_unsorted: IntegerBuffer,
    factor_kummer_generators: IntegerBuffer,
    factor_kummer_residue_degrees: IntegerBuffer,
    factor_kummer_order: IntegerBuffer,
    factor_kummer_sort_diagnostic: IntegerBuffer,
    factor_kummer_decomposition_output: IntegerBuffer,
    factor_kummer_decomposition_state: IntegerBuffer,
    factor_catalog_primes: IntegerBuffer,
    factor_catalog_e: IntegerBuffer,
    factor_catalog_f: IntegerBuffer,
    factor_catalog_inert: IntegerBuffer,
    factor_catalog_generators: IntegerBuffer,
    factor_catalog_tau: IntegerBuffer,
    factor_requested_counts: IntegerBuffer,
    factor_kummer_state: IntegerBuffer,
    factor_packet_generator: IntegerBuffer,
    factor_packet_multiplication: IntegerBuffer,
    factor_packet_work: IntegerBuffer,
    factor_packet_pivots: IntegerBuffer,
    factor_packet_ideal: IntegerBuffer,
    factor_packet_ideals: IntegerBuffer,
    factor_packet_norms: IntegerBuffer,
    factor_relation_primes: IntegerBuffer,
    factor_ramification: IntegerBuffer,
    factor_residue_degrees: IntegerBuffer,
    factor_inert_flags: IntegerBuffer,
    factor_selected_tau: IntegerBuffer,
    factor_initial_primes: IntegerBuffer,
    factor_initial_offsets: IntegerBuffer,
    factor_initial_counts: IntegerBuffer,
    factor_initial_complete: IntegerBuffer,
    factor_bad_flags: IntegerBuffer,
    factor_sub_configuration: Float64Buffer,
    factor_sub_order: IntegerBuffer,
    factor_sub_scratch: IntegerBuffer,
    factor_sub_stack: IntegerBuffer,
    factor_sub_chosen: IntegerBuffer,
    factor_sub_rejected: IntegerBuffer,
    factor_permutation: IntegerBuffer,
    factor_subfactor: IntegerBuffer,
    factor_minidx: IntegerBuffer,
    factor_root_state: IntegerBuffer,
    initial_relation_state: IntegerBuffer,
    initial_relation_basis: IntegerBuffer,
    initial_relation_records: IntegerBuffer,
    initial_relation_hashes: IntegerBuffer,
    initial_relation_metadata: IntegerBuffer,
    initial_relation: IntegerBuffer,
    initial_relation_scratch: IntegerBuffer,
    initial_relation_generators: IntegerBuffer,
    initial_root_state: IntegerBuffer,
) -> int:
    """Run factor selection and initial relations without a host owner boundary."""
    count = pari_row6_prepared_factor_base_root(
        factor_polynomial,
        factor_discriminant,
        factor_real_places,
        factor_complex_pairs,
        factor_precision,
        factor_equation_index,
        factor_roots_of_unity,
        factor_zkden,
        factor_invzk,
        factor_zk,
        factor_zk_degrees,
        factor_basis_table,
        factor_embedding_m,
        factor_embedding_p,
        factor_embedding_e,
        factor_runtime_primes,
        factor_runtime_products,
        factor_factor_limit,
        factor_prime_limit,
        factor_index_work,
        factor_degree_workspace,
        factor_factor_degrees,
        factor_factor_exponents,
        factor_group_degrees,
        factor_group_counts,
        factor_local_state,
        factor_pattern_offsets,
        factor_pattern_counts,
        factor_pattern_degrees,
        factor_pattern_multiplicities,
        factor_full_offsets,
        factor_full_counts,
        factor_full_degrees,
        factor_degree_state,
        factor_base_norms,
        factor_base_configuration,
        factor_base_constants_logs,
        factor_base_sums,
        factor_base_factor_logs,
        factor_selected_primes,
        factor_prime_offsets,
        factor_prime_counts,
        factor_complete_groups,
        factor_selected_indices,
        factor_base_state,
        factor_random_state,
        factor_kummer_factorwork,
        factor_kummer_factor,
        factor_kummer_diagnostic,
        factor_kummer_minpoly_diagnostic,
        factor_kummer_polywork,
        factor_kummer_u,
        factor_kummer_t,
        factor_kummer_rational,
        factor_kummer_primitive,
        factor_kummer_column,
        factor_kummer_resultant_work,
        factor_kummer_resultant_trace,
        factor_kummer_u_output,
        factor_kummer_tau_output,
        factor_kummer_descriptor_state,
        factor_kummer_unsorted,
        factor_kummer_generators,
        factor_kummer_residue_degrees,
        factor_kummer_order,
        factor_kummer_sort_diagnostic,
        factor_kummer_decomposition_output,
        factor_kummer_decomposition_state,
        factor_catalog_primes,
        factor_catalog_e,
        factor_catalog_f,
        factor_catalog_inert,
        factor_catalog_generators,
        factor_catalog_tau,
        factor_requested_counts,
        factor_kummer_state,
        factor_packet_generator,
        factor_packet_multiplication,
        factor_packet_work,
        factor_packet_pivots,
        factor_packet_ideal,
        factor_packet_ideals,
        factor_packet_norms,
        factor_relation_primes,
        factor_ramification,
        factor_residue_degrees,
        factor_inert_flags,
        factor_selected_tau,
        factor_initial_primes,
        factor_initial_offsets,
        factor_initial_counts,
        factor_initial_complete,
        factor_bad_flags,
        factor_sub_configuration,
        factor_sub_order,
        factor_sub_scratch,
        factor_sub_stack,
        factor_sub_chosen,
        factor_sub_rejected,
        factor_permutation,
        factor_subfactor,
        factor_minidx,
        factor_root_state,
    )
    if count != 1130:
        return 1
    initial_count = pari_row6_prepared_initial_relations(
        factor_polynomial,
        factor_discriminant,
        factor_real_places,
        factor_complex_pairs,
        factor_precision,
        factor_equation_index,
        factor_root_state,
        factor_random_state,
        integer_buffer_view(factor_initial_primes, 0, 740),
        integer_buffer_view(factor_initial_offsets, 0, 740),
        integer_buffer_view(factor_initial_counts, 0, 740),
        integer_buffer_view(factor_initial_complete, 0, 740),
        integer_buffer_view(factor_ramification, 0, 1130),
        initial_relation_state,
        initial_relation_basis,
        initial_relation_records,
        initial_relation_hashes,
        initial_relation_metadata,
        initial_relation,
        initial_relation_scratch,
        initial_relation_generators,
        initial_root_state,
    )
    if initial_count != 203:
        return 2
    return 0


__all__ = ["pari_row6_phase6_prepared_prefix_root"]
