"""Computed PARI 2.17.4 cubic T2 candidates for signed `genback`.

Copyright (C) The PARI group. GPL-2.0-or-later, without warranty.

This is the narrow `x^3 - 200*x + 7` composition cut.  It replaces the
previously authenticated five-vector candidate tape with the actual
`idealHNF_inv_Z`, rounded-T2 multiplication, and `ZM_lll(..., LLL_IM)` path.
The frozen relation is still obtained from the real Smith transform; PARI's
trace is an oracle only and is never a runtime input.
"""

from sagejs.native import Float64Buffer, IntegerBuffer, Int64Buffer, native

from .class_group_smith_transform import pari_class_group_smith_transform
from .lll_ranked_basis import pari_lll_ranked_basis
from .signed_genback_assembly import pari_signed_genback_class_group_assembly
from .signed_prime_ideal_reduction import (
    pari_cubic_genback_tape,
    pari_cubic_ideal_hnf_inverse_scaled,
    pari_cubic_ideal_hnf_multiply,
    pari_cubic_idealred_candidate,
)


@native
def pari_cubic_t2_candidate(
    ideal: IntegerBuffer,
    multiplication_table: IntegerBuffer,
    rounded_t2: IntegerBuffer,
    inverse_basis: IntegerBuffer,
    congruence_row: IntegerBuffer,
    hnf_work: IntegerBuffer,
    hnf_triangular: IntegerBuffer,
    hnf_moduli: IntegerBuffer,
    inverse_ideal: IntegerBuffer,
    weighted_basis: IntegerBuffer,
    lll_basis: IntegerBuffer,
    lll_transform: IntegerBuffer,
    lll_selection: IntegerBuffer,
    lll_stages: IntegerBuffer,
    flatter_input: IntegerBuffer,
    flatter_current: IntegerBuffer,
    flatter_transform: IntegerBuffer,
    flatter_total_work: IntegerBuffer,
    flatter_step_t: IntegerBuffer,
    flatter_step_s: IntegerBuffer,
    flatter_product: IntegerBuffer,
    flatter_next_basis: IntegerBuffer,
    qr_input: IntegerBuffer,
    qr: IntegerBuffer,
    qr_vectors: IntegerBuffer,
    qr_betas: IntegerBuffer,
    qr_norms: IntegerBuffer,
    qr_column: IntegerBuffer,
    flatter_y: IntegerBuffer,
    flatter_diagnostic: IntegerBuffer,
    flatter_r1: IntegerBuffer,
    flatter_r2: IntegerBuffer,
    flatter_r3: IntegerBuffer,
    flatter_t1: IntegerBuffer,
    flatter_t2: IntegerBuffer,
    flatter_t3: IntegerBuffer,
    flatter_integers: IntegerBuffer,
    flatter_inverse: IntegerBuffer,
    flatter_first: IntegerBuffer,
    flatter_second: IntegerBuffer,
    flatter_final: IntegerBuffer,
    flatter_rounded: IntegerBuffer,
    lll_mu: Float64Buffer,
    lll_r: Float64Buffer,
    lll_s: Float64Buffer,
    lll_approximate: Float64Buffer,
    lll_exponents: IntegerBuffer,
    lll_float_gram: Float64Buffer,
    lll_gram: IntegerBuffer,
    lll_mu_exponents: IntegerBuffer,
    lll_r_exponents: IntegerBuffer,
    lll_s_exponents: IntegerBuffer,
    lll_alpha: IntegerBuffer,
    lll_column_exponents: IntegerBuffer,
    lll_float_scratch: Float64Buffer,
    lll_temporary: Float64Buffer,
    output: IntegerBuffer,
) -> int:
    """Return `J * first_column(ZM_lll(rounded_t2 * J, .99, LLL_IM))`.

    Here `J = (I intersect Z) * I^-1`.  Every matrix argument is row-major
    except the LLL basis and transformation outputs, which retain the
    connected LLL module's column-major contract.
    """
    if (
        len(ideal) < 9
        or len(multiplication_table) < 27
        or len(rounded_t2) < 9
        or len(inverse_ideal) < 9
        or len(weighted_basis) < 9
        or len(output) < 3
    ):
        raise ValueError("short cubic T2 candidate storage")
    pari_cubic_ideal_hnf_inverse_scaled(
        ideal,
        multiplication_table,
        inverse_basis,
        congruence_row,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        inverse_ideal,
    )
    for row in range(3):
        for column in range(3):
            value = 0
            for inner in range(3):
                value += rounded_t2[row * 3 + inner] * inverse_ideal[inner * 3 + column]
            weighted_basis[row * 3 + column] = value
    status = pari_lll_ranked_basis(
        weighted_basis,
        3,
        3,
        lll_basis,
        lll_transform,
        lll_selection,
        lll_stages,
        flatter_input,
        flatter_current,
        flatter_transform,
        flatter_total_work,
        flatter_step_t,
        flatter_step_s,
        flatter_product,
        flatter_next_basis,
        qr_input,
        qr,
        qr_vectors,
        qr_betas,
        qr_norms,
        qr_column,
        flatter_y,
        flatter_diagnostic,
        flatter_r1,
        flatter_r2,
        flatter_r3,
        flatter_t1,
        flatter_t2,
        flatter_t3,
        flatter_integers,
        flatter_inverse,
        flatter_first,
        flatter_second,
        flatter_final,
        flatter_rounded,
        lll_mu,
        lll_r,
        lll_s,
        lll_approximate,
        lll_exponents,
        lll_float_gram,
        lll_gram,
        lll_mu_exponents,
        lll_r_exponents,
        lll_s_exponents,
        lll_alpha,
        lll_column_exponents,
        lll_float_scratch,
        lll_temporary,
    )
    if status != 0 or lll_stages[3] != 0:
        raise ValueError("cubic T2 candidate requires an unresolved LLL fallback")
    for row in range(3):
        value = 0
        for inner in range(3):
            value += inverse_ideal[row * 3 + inner] * lll_transform[inner]
        output[row] = value
    return 0


@native
def _pari_cubic_computed_t2_reduce(
    ideal: IntegerBuffer,
    multiplication_table: IntegerBuffer,
    rounded_t2: IntegerBuffer,
    candidate_trace: IntegerBuffer,
    inverse_trace: IntegerBuffer,
    weighted_trace: IntegerBuffer,
    transform_trace: IntegerBuffer,
    candidate_cursor: IntegerBuffer,
    kinds: IntegerBuffer,
    values: IntegerBuffer,
    exponents: IntegerBuffer,
    metadata: IntegerBuffer,
    candidate: IntegerBuffer,
    content: IntegerBuffer,
    multiplication_matrix: IntegerBuffer,
    product: IntegerBuffer,
    inverse_numerator: IntegerBuffer,
    inverse_denominator: IntegerBuffer,
    hnf_work: IntegerBuffer,
    hnf_triangular: IntegerBuffer,
    hnf_moduli: IntegerBuffer,
    inverse_basis: IntegerBuffer,
    congruence_row: IntegerBuffer,
    inverse_ideal: IntegerBuffer,
    weighted_basis: IntegerBuffer,
    lll_basis: IntegerBuffer,
    lll_transform: IntegerBuffer,
    lll_selection: IntegerBuffer,
    lll_stages: IntegerBuffer,
    flatter_input: IntegerBuffer,
    flatter_current: IntegerBuffer,
    flatter_transform: IntegerBuffer,
    flatter_total_work: IntegerBuffer,
    flatter_step_t: IntegerBuffer,
    flatter_step_s: IntegerBuffer,
    flatter_product: IntegerBuffer,
    flatter_next_basis: IntegerBuffer,
    qr_input: IntegerBuffer,
    qr: IntegerBuffer,
    qr_vectors: IntegerBuffer,
    qr_betas: IntegerBuffer,
    qr_norms: IntegerBuffer,
    qr_column: IntegerBuffer,
    flatter_y: IntegerBuffer,
    flatter_diagnostic: IntegerBuffer,
    flatter_r1: IntegerBuffer,
    flatter_r2: IntegerBuffer,
    flatter_r3: IntegerBuffer,
    flatter_t1: IntegerBuffer,
    flatter_t2: IntegerBuffer,
    flatter_t3: IntegerBuffer,
    flatter_integers: IntegerBuffer,
    flatter_inverse: IntegerBuffer,
    flatter_first: IntegerBuffer,
    flatter_second: IntegerBuffer,
    flatter_final: IntegerBuffer,
    flatter_rounded: IntegerBuffer,
    lll_mu: Float64Buffer,
    lll_r: Float64Buffer,
    lll_s: Float64Buffer,
    lll_approximate: Float64Buffer,
    lll_exponents: IntegerBuffer,
    lll_float_gram: Float64Buffer,
    lll_gram: IntegerBuffer,
    lll_mu_exponents: IntegerBuffer,
    lll_r_exponents: IntegerBuffer,
    lll_s_exponents: IntegerBuffer,
    lll_alpha: IntegerBuffer,
    lll_column_exponents: IntegerBuffer,
    lll_float_scratch: Float64Buffer,
    lll_temporary: Float64Buffer,
    output: IntegerBuffer,
) -> int:
    """Compute, record, and consume one exact cubic T2/LLL candidate."""
    if len(candidate_cursor) < 1:
        raise ValueError("missing computed T2 candidate cursor")
    cursor = candidate_cursor[0]
    if (
        cursor < 0
        or 3 * (cursor + 1) > len(candidate_trace)
        or 9 * (cursor + 1) > len(inverse_trace)
        or 9 * (cursor + 1) > len(weighted_trace)
        or 9 * (cursor + 1) > len(transform_trace)
    ):
        raise ValueError("computed T2 witness capacity exhausted")
    pari_cubic_t2_candidate(
        ideal,
        multiplication_table,
        rounded_t2,
        inverse_basis,
        congruence_row,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        inverse_ideal,
        weighted_basis,
        lll_basis,
        lll_transform,
        lll_selection,
        lll_stages,
        flatter_input,
        flatter_current,
        flatter_transform,
        flatter_total_work,
        flatter_step_t,
        flatter_step_s,
        flatter_product,
        flatter_next_basis,
        qr_input,
        qr,
        qr_vectors,
        qr_betas,
        qr_norms,
        qr_column,
        flatter_y,
        flatter_diagnostic,
        flatter_r1,
        flatter_r2,
        flatter_r3,
        flatter_t1,
        flatter_t2,
        flatter_t3,
        flatter_integers,
        flatter_inverse,
        flatter_first,
        flatter_second,
        flatter_final,
        flatter_rounded,
        lll_mu,
        lll_r,
        lll_s,
        lll_approximate,
        lll_exponents,
        lll_float_gram,
        lll_gram,
        lll_mu_exponents,
        lll_r_exponents,
        lll_s_exponents,
        lll_alpha,
        lll_column_exponents,
        lll_float_scratch,
        lll_temporary,
        candidate,
    )
    for i in range(3):
        candidate_trace[3 * cursor + i] = candidate[i]
    for i in range(9):
        inverse_trace[9 * cursor + i] = inverse_ideal[i]
        weighted_trace[9 * cursor + i] = weighted_basis[i]
        transform_trace[9 * cursor + i] = lll_transform[i]
    candidate_cursor[0] = cursor + 1
    return pari_cubic_idealred_candidate(
        ideal,
        multiplication_table,
        candidate,
        content,
        kinds,
        values,
        exponents,
        metadata,
        multiplication_matrix,
        product,
        inverse_numerator,
        inverse_denominator,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        output,
    )


@native
def pari_cubic_genback_computed_t2_frozen(
    prime_ideals: IntegerBuffer,
    relation_exponents: IntegerBuffer,
    prime_count: int,
    multiplication_table: IntegerBuffer,
    rounded_t2: IntegerBuffer,
    candidate_trace: IntegerBuffer,
    inverse_trace: IntegerBuffer,
    weighted_trace: IntegerBuffer,
    transform_trace: IntegerBuffer,
    candidate_cursor: IntegerBuffer,
    output_kinds: IntegerBuffer,
    output_values: IntegerBuffer,
    output_exponents: IntegerBuffer,
    output_metadata: IntegerBuffer,
    term_kinds: IntegerBuffer,
    term_values: IntegerBuffer,
    term_exponents: IntegerBuffer,
    term_metadata: IntegerBuffer,
    base: IntegerBuffer,
    term: IntegerBuffer,
    current: IntegerBuffer,
    matrix_scratch: IntegerBuffer,
    generators: IntegerBuffer,
    hnf_input: IntegerBuffer,
    hnf_work: IntegerBuffer,
    hnf_triangular: IntegerBuffer,
    hnf_moduli: IntegerBuffer,
    hnf_intermediate: IntegerBuffer,
    inverse_basis: IntegerBuffer,
    congruence_row: IntegerBuffer,
    candidate: IntegerBuffer,
    content: IntegerBuffer,
    multiplication_matrix: IntegerBuffer,
    product: IntegerBuffer,
    inverse_numerator: IntegerBuffer,
    inverse_denominator: IntegerBuffer,
    inverse_ideal: IntegerBuffer,
    weighted_basis: IntegerBuffer,
    lll_basis: IntegerBuffer,
    lll_transform: IntegerBuffer,
    lll_selection: IntegerBuffer,
    lll_stages: IntegerBuffer,
    flatter_input: IntegerBuffer,
    flatter_current: IntegerBuffer,
    flatter_transform: IntegerBuffer,
    flatter_total_work: IntegerBuffer,
    flatter_step_t: IntegerBuffer,
    flatter_step_s: IntegerBuffer,
    flatter_product: IntegerBuffer,
    flatter_next_basis: IntegerBuffer,
    qr_input: IntegerBuffer,
    qr: IntegerBuffer,
    qr_vectors: IntegerBuffer,
    qr_betas: IntegerBuffer,
    qr_norms: IntegerBuffer,
    qr_column: IntegerBuffer,
    flatter_y: IntegerBuffer,
    flatter_diagnostic: IntegerBuffer,
    flatter_r1: IntegerBuffer,
    flatter_r2: IntegerBuffer,
    flatter_r3: IntegerBuffer,
    flatter_t1: IntegerBuffer,
    flatter_t2: IntegerBuffer,
    flatter_t3: IntegerBuffer,
    flatter_integers: IntegerBuffer,
    flatter_inverse: IntegerBuffer,
    flatter_first: IntegerBuffer,
    flatter_second: IntegerBuffer,
    flatter_final: IntegerBuffer,
    flatter_rounded: IntegerBuffer,
    lll_mu: Float64Buffer,
    lll_r: Float64Buffer,
    lll_s: Float64Buffer,
    lll_approximate: Float64Buffer,
    lll_exponents: IntegerBuffer,
    lll_float_gram: Float64Buffer,
    lll_gram: IntegerBuffer,
    lll_mu_exponents: IntegerBuffer,
    lll_r_exponents: IntegerBuffer,
    lll_s_exponents: IntegerBuffer,
    lll_alpha: IntegerBuffer,
    lll_column_exponents: IntegerBuffer,
    lll_float_scratch: Float64Buffer,
    lll_temporary: Float64Buffer,
    output: IntegerBuffer,
) -> int:
    """Compute the five candidates, then replay the existing signed genback.

    This boundary deliberately admits only the authenticated two-prime Smith
    relation `[-3,-1]`.  The first pass follows its exact square, multiply,
    invert, and final multiply schedule to obtain each candidate from the
    actual intermediate ideal.  The second pass reuses the established
    factored-principal implementation with that Sage.js-produced tape.
    """
    if (
        prime_count != 2
        or len(relation_exponents) < 2
        or relation_exponents[0] != -3
        or relation_exponents[1] != -1
    ):
        raise ValueError("unsupported computed-T2 cubic relation")
    if (
        len(prime_ideals) < 18
        or len(candidate_trace) < 15
        or len(inverse_trace) < 45
        or len(weighted_trace) < 45
        or len(transform_trace) < 45
        or len(candidate_cursor) < 1
        or len(base) < 9
        or len(term) < 9
        or len(current) < 9
        or len(matrix_scratch) < 9
    ):
        raise ValueError("short frozen computed-T2 genback storage")
    candidate_cursor[0] = 0

    # P_2^(-3): reduce P_2^2, P_2^3, then the scaled inverse.
    for i in range(9):
        base[i] = prime_ideals[i]
        current[i] = base[i]
    pari_cubic_ideal_hnf_multiply(
        current,
        current,
        multiplication_table,
        generators,
        hnf_input,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        hnf_intermediate,
        matrix_scratch,
    )
    term_metadata[0] = 0
    content[0] = 1
    content[1] = 1
    _pari_cubic_computed_t2_reduce(
        matrix_scratch,
        multiplication_table,
        rounded_t2,
        candidate_trace,
        inverse_trace,
        weighted_trace,
        transform_trace,
        candidate_cursor,
        term_kinds,
        term_values,
        term_exponents,
        term_metadata,
        candidate,
        content,
        multiplication_matrix,
        product,
        inverse_numerator,
        inverse_denominator,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        inverse_basis,
        congruence_row,
        inverse_ideal,
        weighted_basis,
        lll_basis,
        lll_transform,
        lll_selection,
        lll_stages,
        flatter_input,
        flatter_current,
        flatter_transform,
        flatter_total_work,
        flatter_step_t,
        flatter_step_s,
        flatter_product,
        flatter_next_basis,
        qr_input,
        qr,
        qr_vectors,
        qr_betas,
        qr_norms,
        qr_column,
        flatter_y,
        flatter_diagnostic,
        flatter_r1,
        flatter_r2,
        flatter_r3,
        flatter_t1,
        flatter_t2,
        flatter_t3,
        flatter_integers,
        flatter_inverse,
        flatter_first,
        flatter_second,
        flatter_final,
        flatter_rounded,
        lll_mu,
        lll_r,
        lll_s,
        lll_approximate,
        lll_exponents,
        lll_float_gram,
        lll_gram,
        lll_mu_exponents,
        lll_r_exponents,
        lll_s_exponents,
        lll_alpha,
        lll_column_exponents,
        lll_float_scratch,
        lll_temporary,
        current,
    )
    pari_cubic_ideal_hnf_multiply(
        current,
        base,
        multiplication_table,
        generators,
        hnf_input,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        hnf_intermediate,
        matrix_scratch,
    )
    term_metadata[0] = 0
    content[0] = 1
    content[1] = 1
    _pari_cubic_computed_t2_reduce(
        matrix_scratch,
        multiplication_table,
        rounded_t2,
        candidate_trace,
        inverse_trace,
        weighted_trace,
        transform_trace,
        candidate_cursor,
        term_kinds,
        term_values,
        term_exponents,
        term_metadata,
        candidate,
        content,
        multiplication_matrix,
        product,
        inverse_numerator,
        inverse_denominator,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        inverse_basis,
        congruence_row,
        inverse_ideal,
        weighted_basis,
        lll_basis,
        lll_transform,
        lll_selection,
        lll_stages,
        flatter_input,
        flatter_current,
        flatter_transform,
        flatter_total_work,
        flatter_step_t,
        flatter_step_s,
        flatter_product,
        flatter_next_basis,
        qr_input,
        qr,
        qr_vectors,
        qr_betas,
        qr_norms,
        qr_column,
        flatter_y,
        flatter_diagnostic,
        flatter_r1,
        flatter_r2,
        flatter_r3,
        flatter_t1,
        flatter_t2,
        flatter_t3,
        flatter_integers,
        flatter_inverse,
        flatter_first,
        flatter_second,
        flatter_final,
        flatter_rounded,
        lll_mu,
        lll_r,
        lll_s,
        lll_approximate,
        lll_exponents,
        lll_float_gram,
        lll_gram,
        lll_mu_exponents,
        lll_r_exponents,
        lll_s_exponents,
        lll_alpha,
        lll_column_exponents,
        lll_float_scratch,
        lll_temporary,
        current,
    )
    denominator = current[0]
    pari_cubic_ideal_hnf_inverse_scaled(
        current,
        multiplication_table,
        inverse_basis,
        congruence_row,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        matrix_scratch,
    )
    term_metadata[0] = 0
    content[0] = 1
    content[1] = denominator
    _pari_cubic_computed_t2_reduce(
        matrix_scratch,
        multiplication_table,
        rounded_t2,
        candidate_trace,
        inverse_trace,
        weighted_trace,
        transform_trace,
        candidate_cursor,
        term_kinds,
        term_values,
        term_exponents,
        term_metadata,
        candidate,
        content,
        multiplication_matrix,
        product,
        inverse_numerator,
        inverse_denominator,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        inverse_basis,
        congruence_row,
        inverse_ideal,
        weighted_basis,
        lll_basis,
        lll_transform,
        lll_selection,
        lll_stages,
        flatter_input,
        flatter_current,
        flatter_transform,
        flatter_total_work,
        flatter_step_t,
        flatter_step_s,
        flatter_product,
        flatter_next_basis,
        qr_input,
        qr,
        qr_vectors,
        qr_betas,
        qr_norms,
        qr_column,
        flatter_y,
        flatter_diagnostic,
        flatter_r1,
        flatter_r2,
        flatter_r3,
        flatter_t1,
        flatter_t2,
        flatter_t3,
        flatter_integers,
        flatter_inverse,
        flatter_first,
        flatter_second,
        flatter_final,
        flatter_rounded,
        lll_mu,
        lll_r,
        lll_s,
        lll_approximate,
        lll_exponents,
        lll_float_gram,
        lll_gram,
        lll_mu_exponents,
        lll_r_exponents,
        lll_s_exponents,
        lll_alpha,
        lll_column_exponents,
        lll_float_scratch,
        lll_temporary,
        current,
    )
    for i in range(9):
        term[i] = current[i]

    # P_5^(-1): scaled inverse followed by reduction.
    for i in range(9):
        current[i] = prime_ideals[9 + i]
    denominator = current[0]
    pari_cubic_ideal_hnf_inverse_scaled(
        current,
        multiplication_table,
        inverse_basis,
        congruence_row,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        matrix_scratch,
    )
    term_metadata[0] = 0
    content[0] = 1
    content[1] = denominator
    _pari_cubic_computed_t2_reduce(
        matrix_scratch,
        multiplication_table,
        rounded_t2,
        candidate_trace,
        inverse_trace,
        weighted_trace,
        transform_trace,
        candidate_cursor,
        term_kinds,
        term_values,
        term_exponents,
        term_metadata,
        candidate,
        content,
        multiplication_matrix,
        product,
        inverse_numerator,
        inverse_denominator,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        inverse_basis,
        congruence_row,
        inverse_ideal,
        weighted_basis,
        lll_basis,
        lll_transform,
        lll_selection,
        lll_stages,
        flatter_input,
        flatter_current,
        flatter_transform,
        flatter_total_work,
        flatter_step_t,
        flatter_step_s,
        flatter_product,
        flatter_next_basis,
        qr_input,
        qr,
        qr_vectors,
        qr_betas,
        qr_norms,
        qr_column,
        flatter_y,
        flatter_diagnostic,
        flatter_r1,
        flatter_r2,
        flatter_r3,
        flatter_t1,
        flatter_t2,
        flatter_t3,
        flatter_integers,
        flatter_inverse,
        flatter_first,
        flatter_second,
        flatter_final,
        flatter_rounded,
        lll_mu,
        lll_r,
        lll_s,
        lll_approximate,
        lll_exponents,
        lll_float_gram,
        lll_gram,
        lll_mu_exponents,
        lll_r_exponents,
        lll_s_exponents,
        lll_alpha,
        lll_column_exponents,
        lll_float_scratch,
        lll_temporary,
        current,
    )

    # Final reduced product of the two signed prime powers.
    pari_cubic_ideal_hnf_multiply(
        term,
        current,
        multiplication_table,
        generators,
        hnf_input,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        hnf_intermediate,
        matrix_scratch,
    )
    term_metadata[0] = 0
    content[0] = 1
    content[1] = 1
    _pari_cubic_computed_t2_reduce(
        matrix_scratch,
        multiplication_table,
        rounded_t2,
        candidate_trace,
        inverse_trace,
        weighted_trace,
        transform_trace,
        candidate_cursor,
        term_kinds,
        term_values,
        term_exponents,
        term_metadata,
        candidate,
        content,
        multiplication_matrix,
        product,
        inverse_numerator,
        inverse_denominator,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        inverse_basis,
        congruence_row,
        inverse_ideal,
        weighted_basis,
        lll_basis,
        lll_transform,
        lll_selection,
        lll_stages,
        flatter_input,
        flatter_current,
        flatter_transform,
        flatter_total_work,
        flatter_step_t,
        flatter_step_s,
        flatter_product,
        flatter_next_basis,
        qr_input,
        qr,
        qr_vectors,
        qr_betas,
        qr_norms,
        qr_column,
        flatter_y,
        flatter_diagnostic,
        flatter_r1,
        flatter_r2,
        flatter_r3,
        flatter_t1,
        flatter_t2,
        flatter_t3,
        flatter_integers,
        flatter_inverse,
        flatter_first,
        flatter_second,
        flatter_final,
        flatter_rounded,
        lll_mu,
        lll_r,
        lll_s,
        lll_approximate,
        lll_exponents,
        lll_float_gram,
        lll_gram,
        lll_mu_exponents,
        lll_r_exponents,
        lll_s_exponents,
        lll_alpha,
        lll_column_exponents,
        lll_float_scratch,
        lll_temporary,
        current,
    )
    if candidate_cursor[0] != 5:
        raise ValueError("unexpected frozen computed-T2 schedule")

    candidate_cursor[0] = 0
    return pari_cubic_genback_tape(
        prime_ideals,
        relation_exponents,
        prime_count,
        multiplication_table,
        candidate_trace,
        candidate_cursor,
        output_kinds,
        output_values,
        output_exponents,
        output_metadata,
        term_kinds,
        term_values,
        term_exponents,
        term_metadata,
        base,
        term,
        current,
        matrix_scratch,
        generators,
        hnf_input,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        hnf_intermediate,
        inverse_basis,
        congruence_row,
        candidate,
        content,
        multiplication_matrix,
        product,
        inverse_numerator,
        inverse_denominator,
        output,
    )


@native
def pari_signed_genback_computed_t2_assembly(
    matrix_m: IntegerBuffer,
    matrix_p: IntegerBuffer,
    matrix_e: IntegerBuffer,
    relation_hnf: IntegerBuffer,
    relation_logs: IntegerBuffer,
    prime_ideals: IntegerBuffer,
    prime_count: int,
    multiplication_table: IntegerBuffer,
    rounded_t2: IntegerBuffer,
    candidate_trace: IntegerBuffer,
    inverse_trace: IntegerBuffer,
    weighted_trace: IntegerBuffer,
    transform_trace: IntegerBuffer,
    candidate_cursor: IntegerBuffer,
    dimension: int,
    generator_count: int,
    precision: int,
    generator_ideal: IntegerBuffer,
    relation_exponents: IntegerBuffer,
    factor_offsets: IntegerBuffer,
    factor_kinds: IntegerBuffer,
    factor_numerators: IntegerBuffer,
    factor_denominators: IntegerBuffer,
    factor_coordinates: IntegerBuffer,
    factor_exponents: IntegerBuffer,
    compact_values: IntegerBuffer,
    compact_metadata: IntegerBuffer,
    term_kinds: IntegerBuffer,
    term_values: IntegerBuffer,
    term_exponents: IntegerBuffer,
    term_metadata: IntegerBuffer,
    base: IntegerBuffer,
    term: IntegerBuffer,
    current: IntegerBuffer,
    matrix_scratch: IntegerBuffer,
    generators: IntegerBuffer,
    hnf_input: IntegerBuffer,
    hnf_work: IntegerBuffer,
    hnf_triangular: IntegerBuffer,
    hnf_moduli: IntegerBuffer,
    hnf_intermediate: IntegerBuffer,
    inverse_basis: IntegerBuffer,
    congruence_row: IntegerBuffer,
    candidate: IntegerBuffer,
    content: IntegerBuffer,
    multiplication_matrix: IntegerBuffer,
    product: IntegerBuffer,
    inverse_numerator: IntegerBuffer,
    inverse_denominator: IntegerBuffer,
    generated_ideal: IntegerBuffer,
    inverse_ideal: IntegerBuffer,
    weighted_basis: IntegerBuffer,
    lll_basis: IntegerBuffer,
    lll_transform: IntegerBuffer,
    lll_selection: IntegerBuffer,
    lll_stages: IntegerBuffer,
    flatter_input: IntegerBuffer,
    flatter_current: IntegerBuffer,
    flatter_transform: IntegerBuffer,
    flatter_total_work: IntegerBuffer,
    flatter_step_t: IntegerBuffer,
    flatter_step_s: IntegerBuffer,
    flatter_product: IntegerBuffer,
    flatter_next_basis: IntegerBuffer,
    qr_input: IntegerBuffer,
    qr: IntegerBuffer,
    qr_vectors: IntegerBuffer,
    qr_betas: IntegerBuffer,
    qr_norms: IntegerBuffer,
    qr_column: IntegerBuffer,
    flatter_y: IntegerBuffer,
    flatter_diagnostic: IntegerBuffer,
    flatter_r1: IntegerBuffer,
    flatter_r2: IntegerBuffer,
    flatter_r3: IntegerBuffer,
    flatter_t1: IntegerBuffer,
    flatter_t2: IntegerBuffer,
    flatter_t3: IntegerBuffer,
    flatter_integers: IntegerBuffer,
    flatter_inverse: IntegerBuffer,
    flatter_first: IntegerBuffer,
    flatter_second: IntegerBuffer,
    flatter_final: IntegerBuffer,
    flatter_rounded: IntegerBuffer,
    lll_mu: Float64Buffer,
    lll_r: Float64Buffer,
    lll_s: Float64Buffer,
    lll_approximate: Float64Buffer,
    lll_exponents: IntegerBuffer,
    lll_float_gram: Float64Buffer,
    lll_gram: IntegerBuffer,
    lll_mu_exponents: IntegerBuffer,
    lll_r_exponents: IntegerBuffer,
    lll_s_exponents: IntegerBuffer,
    lll_alpha: IntegerBuffer,
    lll_column_exponents: IntegerBuffer,
    lll_float_scratch: Float64Buffer,
    lll_temporary: Float64Buffer,
    smith: IntegerBuffer,
    left: IntegerBuffer,
    left_inverse: IntegerBuffer,
    right: IntegerBuffer,
    ur: IntegerBuffer,
    y: IntegerBuffer,
    uir: IntegerBuffer,
    x: IntegerBuffer,
    m1: IntegerBuffer,
    m2: IntegerBuffer,
    invariants: IntegerBuffer,
    class_number: IntegerBuffer,
    ga: IntegerBuffer,
    gd: IntegerBuffer,
    generator_arch: IntegerBuffer,
    smith_column: IntegerBuffer,
    smith_product: IntegerBuffer,
    smith_augmented: IntegerBuffer,
    left_inverse_state: Int64Buffer,
    right_inverse_state: Int64Buffer,
    first_division_state: Int64Buffer,
    second_division_state: Int64Buffer,
    smith_state: Int64Buffer,
    cx_state: IntegerBuffer,
    cx_coordinates: IntegerBuffer,
    cx_column: IntegerBuffer,
    cx_accumulator: IntegerBuffer,
    log_cache: IntegerBuffer,
    pi_cache: IntegerBuffer,
    arithmetic_a: IntegerBuffer,
    arithmetic_b: IntegerBuffer,
    arithmetic_p: IntegerBuffer,
    arithmetic_q: IntegerBuffer,
    arithmetic_stack: IntegerBuffer,
    ga_full: IntegerBuffer,
    c_m1: IntegerBuffer,
    ga_diagonal: IntegerBuffer,
    c_m2: IntegerBuffer,
    ga_ur: IntegerBuffer,
    gd_work: IntegerBuffer,
    generator_arch_work: IntegerBuffer,
    assembly_state: Int64Buffer,
    connection_state: Int64Buffer,
) -> int:
    """Run the authenticated class assembly without a supplied candidate tape.

    Candidate and witness owners are outputs.  A preliminary Smith transform
    obtains the source relation, the computed-T2 pass fills the five-vector
    trace, and the established assembly consumes that internally produced
    trace.  Final publication remains transactional in the established leaf.
    """
    if dimension != 2 or prime_count != 2 or generator_count != 1:
        raise ValueError("unsupported computed-T2 assembly shape")
    smith_status = pari_class_group_smith_transform(
        relation_hnf,
        dimension,
        smith,
        left,
        left_inverse,
        right,
        ur,
        y,
        uir,
        x,
        m1,
        m2,
        invariants,
        class_number,
        smith_column,
        smith_product,
        smith_augmented,
        left_inverse_state,
        right_inverse_state,
        first_division_state,
        second_division_state,
        smith_state,
    )
    if smith_status != 0 or smith_state[1] != 1:
        return -1
    relation_exponents[0] = uir[0]
    relation_exponents[1] = uir[1]
    pari_cubic_genback_computed_t2_frozen(
        prime_ideals,
        relation_exponents,
        prime_count,
        multiplication_table,
        rounded_t2,
        candidate_trace,
        inverse_trace,
        weighted_trace,
        transform_trace,
        candidate_cursor,
        factor_kinds,
        compact_values,
        factor_exponents,
        compact_metadata,
        term_kinds,
        term_values,
        term_exponents,
        term_metadata,
        base,
        term,
        current,
        matrix_scratch,
        generators,
        hnf_input,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        hnf_intermediate,
        inverse_basis,
        congruence_row,
        candidate,
        content,
        multiplication_matrix,
        product,
        inverse_numerator,
        inverse_denominator,
        inverse_ideal,
        weighted_basis,
        lll_basis,
        lll_transform,
        lll_selection,
        lll_stages,
        flatter_input,
        flatter_current,
        flatter_transform,
        flatter_total_work,
        flatter_step_t,
        flatter_step_s,
        flatter_product,
        flatter_next_basis,
        qr_input,
        qr,
        qr_vectors,
        qr_betas,
        qr_norms,
        qr_column,
        flatter_y,
        flatter_diagnostic,
        flatter_r1,
        flatter_r2,
        flatter_r3,
        flatter_t1,
        flatter_t2,
        flatter_t3,
        flatter_integers,
        flatter_inverse,
        flatter_first,
        flatter_second,
        flatter_final,
        flatter_rounded,
        lll_mu,
        lll_r,
        lll_s,
        lll_approximate,
        lll_exponents,
        lll_float_gram,
        lll_gram,
        lll_mu_exponents,
        lll_r_exponents,
        lll_s_exponents,
        lll_alpha,
        lll_column_exponents,
        lll_float_scratch,
        lll_temporary,
        generated_ideal,
    )
    candidate_cursor[0] = 0
    return pari_signed_genback_class_group_assembly(
        matrix_m,
        matrix_p,
        matrix_e,
        relation_hnf,
        relation_logs,
        prime_ideals,
        prime_count,
        multiplication_table,
        candidate_trace,
        candidate_cursor,
        dimension,
        generator_count,
        precision,
        generator_ideal,
        relation_exponents,
        factor_offsets,
        factor_kinds,
        factor_numerators,
        factor_denominators,
        factor_coordinates,
        factor_exponents,
        compact_values,
        compact_metadata,
        term_kinds,
        term_values,
        term_exponents,
        term_metadata,
        base,
        term,
        current,
        matrix_scratch,
        generators,
        hnf_input,
        hnf_work,
        hnf_triangular,
        hnf_moduli,
        hnf_intermediate,
        inverse_basis,
        congruence_row,
        candidate,
        content,
        multiplication_matrix,
        product,
        inverse_numerator,
        inverse_denominator,
        generated_ideal,
        smith,
        left,
        left_inverse,
        right,
        ur,
        y,
        uir,
        x,
        m1,
        m2,
        invariants,
        class_number,
        ga,
        gd,
        generator_arch,
        smith_column,
        smith_product,
        smith_augmented,
        left_inverse_state,
        right_inverse_state,
        first_division_state,
        second_division_state,
        smith_state,
        cx_state,
        cx_coordinates,
        cx_column,
        cx_accumulator,
        log_cache,
        pi_cache,
        arithmetic_a,
        arithmetic_b,
        arithmetic_p,
        arithmetic_q,
        arithmetic_stack,
        ga_full,
        c_m1,
        ga_diagonal,
        c_m2,
        ga_ur,
        gd_work,
        generator_arch_work,
        assembly_state,
        connection_state,
    )
