#!/usr/bin/env node
"use strict";

// Lightweight contract coverage for the durable stage graph. This deliberately
// does not invoke PARI or any native compilation.

const assert = require("node:assert/strict");
const childProcess = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");
const {
  definitionIdentity,
  sealedDependencyReceipts,
} = require("./run_phase0_integration_replay.cjs");

const directory = __dirname;
const runner = path.join(directory, "run_phase0_integration_replay.cjs");
const result = childProcess.spawnSync(process.execPath, [runner, "list"], {
  encoding: "utf8",
});
assert.equal(result.status, 0, result.stderr || String(result.error));

const graph = new Map(result.stdout.trim().split("\n").map((line) => {
  const [name, dependencies] = line.split("\t");
  return [name, dependencies === "-" ? [] : dependencies.split(",")];
}));

assert.deepEqual(graph.get("quartic-hnfadd-trace"), ["quartic-driver"]);
assert.deepEqual(graph.get("quartic-continuation"), [
  "quartic-collector",
  "quartic-hnfadd-trace",
]);
for (const name of [
  "quartic-retry-cpython",
  "quartic-retry-javascript",
  "quartic-retry-gmp",
  "quartic-retry-tagged",
]) {
  assert(graph.get(name).includes("quartic-hnfadd-trace"), name);
  assert(graph.get(name).includes("quartic-continuation"), name);
}

const source = fs.readFileSync(runner, "utf8");
assert.match(source, /commandNode\("check_actual_hnfadd_inputs\.cjs",\s*\n\s*context\.pariRoot, context\.pariArchive, "--field2"\)/);
assert.match(source, /identityInputs: \(\) => \[checker\("hnfadd\.py"\)\]/);
assert.equal(
  [...source.matchAll(/tracePath\(context, "quartic-driver"\)/g)].length,
  0,
  "continuation and retry stages must not consume the summarized driver trace",
);
assert.equal(
  [...source.matchAll(/tracePath\(context, "quartic-hnfadd-trace"\)/g)].length,
  3,
  "continuation and both retry command factories consume the extended trace",
);

const context = {
  gitCommit: "frozen-commit",
  gitTree: "frozen-tree",
};
const specification = {
  name: "generated-stage",
  requiresPari: false,
};
const logicalArguments = [
  process.execPath,
  "<generated>/continuation-launcher.cjs",
  "/artifacts/collector.json",
  "/artifacts/trace.json",
  "--source-only",
];
const generatedChecker = {
  originalSha256: "original-source",
  generatedSha256: "generated-source",
  launcherSha256: "launcher-bytes",
};
function generatedCommand(attempt) {
  return {
    command: process.execPath,
    arguments: [`/artifacts/attempt-${attempt}/generated/continuation-launcher.cjs`,
      ...logicalArguments.slice(2)],
    identityCommand: logicalArguments,
    identityCheckerPath: __filename,
    generatedChecker,
  };
}

const firstIdentity = definitionIdentity(context, specification,
  generatedCommand("one"), []);
const resumedIdentity = definitionIdentity(context, specification,
  generatedCommand("two"), []);
assert.deepEqual(resumedIdentity, firstIdentity,
  "identical generated bytes resume across attempt directories");

const changedArguments = generatedCommand("three");
changedArguments.identityCommand = [...logicalArguments.slice(0, -1), "--changed"];
assert.notDeepEqual(definitionIdentity(context, specification, changedArguments, []),
  firstIdentity, "logical argument mutation changes identity");

for (const field of ["originalSha256", "generatedSha256", "launcherSha256"]) {
  const changedSource = generatedCommand(`changed-${field}`);
  changedSource.generatedChecker = { ...generatedChecker, [field]: `changed-${field}` };
  assert.notDeepEqual(definitionIdentity(context, specification, changedSource, []),
    firstIdentity, `${field} mutation changes identity`);
}

const receiptSchema = "sagejs.pari-class-group/phase0-integration-replay-v1";
const temporary = fs.mkdtempSync(path.join(require("node:os").tmpdir(),
  "sagejs-phase0-sealed-test-"));
const artifactContext = { artifactRoot: temporary };
function sha256(bytes) {
  return require("node:crypto").createHash("sha256").update(bytes).digest("hex");
}
function writeReceipt(name, dependencies, outputText = name) {
  const attempt = path.join("stages", name, "attempts", "attempt-test");
  const outputRelative = path.join(attempt, "output.txt");
  const output = path.join(temporary, outputRelative);
  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, outputText);
  const identity = {
    schema: receiptSchema,
    stage: name,
    dependencies: Object.fromEntries(dependencies.map((dependency) => {
      const pointer = JSON.parse(fs.readFileSync(path.join(temporary,
        "stages", dependency, "current.json")));
      const bytes = fs.readFileSync(path.join(temporary, pointer.receipt));
      return [dependency, sha256(bytes)];
    })),
  };
  const receipt = {
    schema: receiptSchema,
    complete: true,
    stage: name,
    identity,
    identitySha256: sha256(Buffer.from(JSON.stringify(identity))),
    outputs: {
      output: {
        path: outputRelative,
        bytes: Buffer.byteLength(outputText),
        sha256: sha256(Buffer.from(outputText)),
      },
    },
  };
  const receiptRelative = path.join(attempt, "receipt.json");
  const receiptBytes = Buffer.from(`${JSON.stringify(receipt, null, 2)}\n`);
  fs.writeFileSync(path.join(temporary, receiptRelative), receiptBytes);
  fs.writeFileSync(path.join(temporary, "stages", name, "current.json"),
    `${JSON.stringify({
      schema: receiptSchema,
      stage: name,
      receipt: receiptRelative,
      receiptSha256: sha256(receiptBytes),
    }, null, 2)}\n`);
}

try {
  writeReceipt("quartic-driver", []);
  writeReceipt("quartic-hnfadd-trace", ["quartic-driver"]);
  writeReceipt("quartic-collector", []);
  writeReceipt("analytic", []);
  writeReceipt("quartic-continuation",
    ["quartic-collector", "quartic-hnfadd-trace"]);
  writeReceipt("quartic-retry-cpython", ["analytic", "quartic-collector",
    "quartic-continuation", "quartic-driver", "quartic-hnfadd-trace"]);
  const sealed = sealedDependencyReceipts(artifactContext,
    ["quartic-collector", "quartic-hnfadd-trace"]);
  assert.deepEqual(sealed.map(({ name }) => name),
    ["quartic-collector", "quartic-driver", "quartic-hnfadd-trace"],
    "sealed dependency verification returns the complete pinned closure");
  assert.equal(sealedDependencyReceipts(artifactContext,
    ["quartic-retry-cpython"]).length, 6,
  "a consumer receipt may pin exactly the declared transitive closure");

  const driverOutput = path.join(temporary, "stages", "quartic-driver",
    "attempts", "attempt-test", "output.txt");
  fs.writeFileSync(driverOutput, "mutated");
  assert.throws(() => sealedDependencyReceipts(artifactContext,
    ["quartic-hnfadd-trace"]), /quartic-driver\/output (size|hash)/,
  "mutated transitive output is rejected");
  fs.writeFileSync(driverOutput, "quartic-driver");

  const driverPointer = path.join(temporary, "stages", "quartic-driver", "current.json");
  const savedPointer = fs.readFileSync(driverPointer);
  fs.unlinkSync(driverPointer);
  assert.throws(() => sealedDependencyReceipts(artifactContext,
    ["quartic-hnfadd-trace"]), /no longer selected/,
  "missing transitive selection is rejected");
  fs.writeFileSync(driverPointer, savedPointer);

  const hnfPointer = path.join(temporary, "stages", "quartic-hnfadd-trace",
    "current.json");
  const selected = JSON.parse(fs.readFileSync(hnfPointer));
  const hnfReceiptPath = path.join(temporary, selected.receipt);
  const hnfReceipt = JSON.parse(fs.readFileSync(hnfReceiptPath));
  hnfReceipt.schema = "mutated-schema";
  const mutatedBytes = Buffer.from(`${JSON.stringify(hnfReceipt, null, 2)}\n`);
  fs.writeFileSync(hnfReceiptPath, mutatedBytes);
  selected.receiptSha256 = sha256(mutatedBytes);
  fs.writeFileSync(hnfPointer, `${JSON.stringify(selected, null, 2)}\n`);
  assert.throws(() => sealedDependencyReceipts(artifactContext,
    ["quartic-hnfadd-trace"]), /mutated-schema/,
  "mutated receipt schema is rejected even with a refreshed pointer hash");
} finally {
  fs.rmSync(temporary, { recursive: true, force: true });
}

console.log("Phase-0 quartic trace stage contract passed.");
