"""PARI 2.17.4 unreduced-ideal preparation and relation collection.

Copyright (C) The PARI group. GPL-2.0-or-later, without warranty.
Prepared nf data, factor-base decompositions and an original ideal are inputs.
No upstream reduced basis, QR or relation answer is supplied. Automorphism
images, unresolved dependencies and the outer class/unit driver remain open.
"""

from sagejs.native import Float64Buffer, Int64Buffer, IntegerBuffer, native

from .ideal_ranked_preparation import pari_ideal_ranked_preparation
from .ideal_collector import pari_collect_ideal_relations


@native
def pari_collect_unreduced_ideal(
    matrix: IntegerBuffer,
    ideal: IntegerBuffer,
    n: int,
    precision: int,
    scale: float,
    track_small: int,
    reduction: IntegerBuffer,
    vectors: IntegerBuffer,
    betas: IntegerBuffer,
    norms: IntegerBuffer,
    column: IntegerBuffer,
    float_q: Float64Buffer,
    float_v: Float64Buffer,
    bound: Float64Buffer,
    cache: IntegerBuffer,
    a: IntegerBuffer,
    b: IntegerBuffer,
    p: IntegerBuffer,
    q: IntegerBuffer,
    stack: IntegerBuffer,
    x: Int64Buffer,
    y: Float64Buffer,
    z: Float64Buffer,
    inc: Int64Buffer,
    state: Int64Buffer,
    cursor_output: Int64Buffer,
    element: IntegerBuffer,
    counters: Int64Buffer,
    admission_matrix_m: IntegerBuffer,
    admission_matrix_p: IntegerBuffer,
    admission_matrix_e: IntegerBuffer,
    admission_embedding_m: IntegerBuffer,
    admission_embedding_p: IntegerBuffer,
    admission_embedding_e: IntegerBuffer,
    admission_real_count: int,
    admission_ideal_norm: int,
    admission_ideal: IntegerBuffer,
    admission_mode: int,
    admission_factor_product: int,
    admission_primes: IntegerBuffer,
    admission_products: IntegerBuffer,
    admission_factorlimit: int,
    admission_prime_limit: int,
    admission_rational_factors: IntegerBuffer,
    admission_rational_exponents: IntegerBuffer,
    admission_prime_offsets: IntegerBuffer,
    admission_prime_counts: IntegerBuffer,
    admission_group_tau: IntegerBuffer,
    admission_group_e: IntegerBuffer,
    admission_group_f: IntegerBuffer,
    admission_group_inert: IntegerBuffer,
    admission_tau: IntegerBuffer,
    admission_x: IntegerBuffer,
    admission_y: IntegerBuffer,
    admission_spare: IntegerBuffer,
    admission_stack: IntegerBuffer,
    admission_primitive: IntegerBuffer,
    admission_columns: IntegerBuffer,
    admission_values: IntegerBuffer,
    admission_temporary: IntegerBuffer,
    admission_indices: IntegerBuffer,
    admission_exponents: IntegerBuffer,
    diagnostic: IntegerBuffer,
    nrelid: int,
    track_fact: int,
    jid: int,
    jid0: int,
    e0: int,
    subfactor: IntegerBuffer,
    extra: IntegerBuffer,
    extra_count: int,
    relation_primes: IntegerBuffer,
    ramification: IntegerBuffer,
    relation: IntegerBuffer,
    relation_state: IntegerBuffer,
    relation_basis: IntegerBuffer,
    relation_records: IntegerBuffer,
    relation_hashes: IntegerBuffer,
    relation_metadata: IntegerBuffer,
    relation_scratch: IntegerBuffer,
    generators: IntegerBuffer,
    progress: Int64Buffer,
    preparation_rounded_embedding: IntegerBuffer,
    preparation_embedding: IntegerBuffer,
    preparation_original: IntegerBuffer,
    preparation_basis: IntegerBuffer,
    preparation_transform: IntegerBuffer,
    preparation_flags: IntegerBuffer,
    preparation_rank_diagnostic: IntegerBuffer,
    preparation_selection: IntegerBuffer,
    preparation_stages: IntegerBuffer,
    preparation_flatter_input: IntegerBuffer,
    preparation_current: IntegerBuffer,
    preparation_flatter_transform: IntegerBuffer,
    preparation_total_work: IntegerBuffer,
    preparation_step_t: IntegerBuffer,
    preparation_step_s: IntegerBuffer,
    preparation_product: IntegerBuffer,
    preparation_next_basis: IntegerBuffer,
    preparation_y: IntegerBuffer,
    preparation_diagnostic: IntegerBuffer,
    preparation_r1: IntegerBuffer,
    preparation_r2: IntegerBuffer,
    preparation_r3: IntegerBuffer,
    preparation_t1: IntegerBuffer,
    preparation_t2: IntegerBuffer,
    preparation_t3: IntegerBuffer,
    preparation_integers: IntegerBuffer,
    preparation_inverse: IntegerBuffer,
    preparation_first: IntegerBuffer,
    preparation_second: IntegerBuffer,
    preparation_final: IntegerBuffer,
    preparation_rounded: IntegerBuffer,
    preparation_mu: Float64Buffer,
    preparation_r: Float64Buffer,
    preparation_s: Float64Buffer,
    preparation_approximate: Float64Buffer,
    preparation_exponents: IntegerBuffer,
    preparation_float_gram: Float64Buffer,
    preparation_gram: IntegerBuffer,
    preparation_mu_exponents: IntegerBuffer,
    preparation_r_exponents: IntegerBuffer,
    preparation_s_exponents: IntegerBuffer,
    preparation_alpha: IntegerBuffer,
    preparation_column_exponents: IntegerBuffer,
    preparation_float_scratch: Float64Buffer,
    preparation_temporary: Float64Buffer,
    preparation_state: Int64Buffer,
) -> int:
    """Prepare once, then run the resident collector with upstream stop policy.

    Preparation state is one slot: zero initially, one after success, or a
    negative dependency code. Preparation failures return -11 through -17;
    collector statuses remain unchanged. A failed preparation is sticky.
    All buffers are disjoint, and inputs/configuration must remain unchanged
    across calls. state[4] records completed QR without advancing the cursor.
    Terminal collector calls remain inert, including their preparation state.
    """
    if len(preparation_state) < 1 or len(state) < 5 or len(progress) < 4:
        raise ValueError("unreduced ideal collector state is too small")
    if progress[2] != 0:
        return int(progress[3])
    if preparation_state[0] < 0:
        return int(preparation_state[0]) - 10
    if preparation_state[0] == 0:
        status = pari_ideal_ranked_preparation(
            admission_ideal,
            preparation_rounded_embedding,
            preparation_embedding,
            n,
            precision,
            scale,
            preparation_original,
            preparation_basis,
            preparation_transform,
            ideal,
            preparation_flags,
            preparation_rank_diagnostic,
            preparation_selection,
            preparation_stages,
            preparation_flatter_input,
            preparation_current,
            preparation_flatter_transform,
            preparation_total_work,
            preparation_step_t,
            preparation_step_s,
            preparation_product,
            preparation_next_basis,
            matrix,
            reduction,
            vectors,
            betas,
            norms,
            column,
            preparation_y,
            preparation_diagnostic,
            preparation_r1,
            preparation_r2,
            preparation_r3,
            preparation_t1,
            preparation_t2,
            preparation_t3,
            preparation_integers,
            preparation_inverse,
            preparation_first,
            preparation_second,
            preparation_final,
            preparation_rounded,
            preparation_mu,
            preparation_r,
            preparation_s,
            preparation_approximate,
            preparation_exponents,
            preparation_float_gram,
            preparation_gram,
            preparation_mu_exponents,
            preparation_r_exponents,
            preparation_s_exponents,
            preparation_alpha,
            preparation_column_exponents,
            preparation_float_scratch,
            preparation_temporary,
            float_q,
            float_v,
            bound,
            cache,
            a,
            b,
            p,
            q,
            stack,
        )
        if status != 0:
            preparation_state[0] = -status
            return -10 - status
        state[4] = preparation_flags[1]
        preparation_state[0] = 1
    return pari_collect_ideal_relations(
        matrix,
        ideal,
        n,
        precision,
        scale,
        preparation_flags[0],
        track_small,
        reduction,
        vectors,
        betas,
        norms,
        column,
        float_q,
        float_v,
        bound,
        cache,
        a,
        b,
        p,
        q,
        stack,
        x,
        y,
        z,
        inc,
        state,
        cursor_output,
        element,
        counters,
        admission_matrix_m,
        admission_matrix_p,
        admission_matrix_e,
        admission_embedding_m,
        admission_embedding_p,
        admission_embedding_e,
        admission_real_count,
        admission_ideal_norm,
        admission_ideal,
        admission_mode,
        admission_factor_product,
        admission_primes,
        admission_products,
        admission_factorlimit,
        admission_prime_limit,
        admission_rational_factors,
        admission_rational_exponents,
        admission_prime_offsets,
        admission_prime_counts,
        admission_group_tau,
        admission_group_e,
        admission_group_f,
        admission_group_inert,
        admission_tau,
        admission_x,
        admission_y,
        admission_spare,
        admission_stack,
        admission_primitive,
        admission_columns,
        admission_values,
        admission_temporary,
        admission_indices,
        admission_exponents,
        diagnostic,
        nrelid,
        track_fact,
        jid,
        jid0,
        e0,
        subfactor,
        extra,
        extra_count,
        relation_primes,
        ramification,
        relation,
        relation_state,
        relation_basis,
        relation_records,
        relation_hashes,
        relation_metadata,
        relation_scratch,
        generators,
        progress,
    )
