/*
 * self.js
 * Copyright (C) 2015 Kovid Goyal <kovid at kovidgoyal.net>
 *
 * Distributed under terms of the BSD license.
 */
"use strict"; /*jshint node:true */

var path = require("path");
var crypto = require("crypto");
var fs = require("fs");
var vm = require("vm");
var zlib = require("zlib");
var {
  analyzeBaselibModules,
  moduleId: baselibModuleId,
} = require("./baselib-modules.cjs");
var {
  canonicalizeGeneratedPaths,
} = require("./reproducible-generated-paths.cjs");

const COMPILER_BASELIB_MODULES = new Set([
  "__future__.py",
  "builtins.py",
  "compiler_bootstrap.py",
  "containers.py",
  "errors.py",
  "internal.py",
  "itertools.py",
  "runtime_primitives.py",
  "str.py",
]);

async function compile_baselib(PyLang, src_path, compiler_only = false) {
  let supportsPythonOrdering = false;
  try {
    // The immutable stage-zero compiler predates this independently
    // configurable lowering policy.
    new PyLang.OutputStream({ python_ordering: false });
    supportsPythonOrdering = true;
  } catch (_error) {}
  if (compiler_only) {
    try {
      new PyLang.OutputStream({ baselib_module_id: "__probe__" });
    } catch (_error) {
      // The immutable stage-zero compiler injects the complete historical
      // runtime into every baselib parse.  Keep its first output internally
      // consistent; that output immediately rebuilds itself with lexical
      // modules and can then select the compiler-only bootstrap.
      compiler_only = false;
    }
  }
  const { createPythonCompilerFrontend } = require("./python/compiler-frontend");
  const frontend = PyLang.AST_AnnotatedAssignment
    ? await createPythonCompilerFrontend(PyLang, "python")
    : null;
  var items = fs
    .readdirSync(path.join(src_path, "baselib"))
    .filter(function (name) {
      return (
        name.endsWith(".py") &&
        name !== "compiler_bootstrap.py" &&
        (!compiler_only || COMPILER_BASELIB_MODULES.has(name))
      );
    })
    .concat(compiler_only ? ["compiler_bootstrap.py"] : []);
  var ans = { pretty: "" };
  var version_info = JSON.parse(
    fs.readFileSync(path.join(src_path, "..", "sagejs-version.json"), "utf-8"),
  );

  // The concatenated baselib is the compiler prologue.  Its low-level Python
  // object helpers must exist before another module finalizes its first class.
  // The historical parser happened not to exercise those helpers during
  // startup; the complete Tree-sitter lowering correctly does.
  items.sort(function (left, right) {
    if (left === "runtime_primitives.py") return -1;
    if (right === "runtime_primitives.py") return 1;
    if (left === "builtins.py") return -1;
    if (right === "builtins.py") return 1;
    return left.localeCompare(right);
  });

  try {
    const modules = items.map(function (fname) {
      var ast;
      var raw = fs.readFileSync(
        path.join(src_path, "baselib", fname),
        "utf-8",
      );
      try {
        ast = (frontend ? frontend.parse : PyLang.parse)(raw, {
          filename: fname,
          basedir: path.join(src_path, "baselib"),
          intrinsic_package_shells: true,
          // Baselib classes implement Python objects, so extracting a method
          // from an instance must retain that instance as ``self``.
          scoped_flags: { bound_methods: true },
          // Compiler/bootstrap sources deliberately use Python spellings for
          // JavaScript helpers generated by the emitter.  They are the sole
          // low-level exception to ordinary Python lexical hygiene.
          compiler_bootstrap: true,
        });
      } catch (e) {
        if (!(e instanceof PyLang.SyntaxError)) throw e;
        console.error(e.toString());
        process.exit(1);
      }
      const references = new Set();
      if (frontend !== null) {
        ast.walk({
          _visit: function (node, descend) {
            if (node instanceof PyLang.AST_SymbolRef) {
              references.add(node.name);
            }
            if (descend !== undefined) descend();
          },
        });
      }
      return {
        ast,
        filename: fname,
        moduleId: baselibModuleId(fname),
        exports: [...new Set(ast.exports.map((symbol) => symbol.name))],
        references: [...references],
      };
    });
    const analysis = analyzeBaselibModules(modules);
    const facadeNameSet = new Set(analysis.facadeNames);
    const namingOutput = new PyLang.OutputStream({});
    let supportsLexicalModuleMetadata = true;
    try {
      new PyLang.OutputStream({ baselib_module_id: "__probe__" });
    } catch (_error) {
      // The first self-hosting pass runs with the immutable bootstrap
      // compiler, which does not understand lexical baselib metadata.  The
      // compiler produced by that pass immediately rebuilds itself below and
      // emits the isolated form.
      supportsLexicalModuleMetadata = false;
    }

    // `sagejs.runtime` is both a compiler intrinsic and a real Python module.
    // Keep the immutable stage-zero path unchanged, then materialize its
    // readable compatibility source in the converged lexical build.  It is
    // deliberately outside facade ownership analysis because several public
    // aliases name primitives owned by other baselib modules.
    if (supportsLexicalModuleMetadata) {
      const runtimeFilename = "sagejs/runtime.py";
      const runtimePath = compiler_only
        ? path.join(src_path, "compiler_runtime.py")
        : path.join(src_path, "baselib", runtimeFilename);
      const raw = fs.readFileSync(runtimePath, "utf-8");
      const ast = frontend.parse(raw, {
        filename: runtimeFilename,
        basedir: path.dirname(runtimePath),
        intrinsic_package_shells: true,
        scoped_flags: { bound_methods: true },
        compiler_bootstrap: true,
      });
      modules.push({
        ast,
        filename: runtimeFilename,
        moduleId: "sagejs.runtime",
        exports: [...new Set(ast.exports.map((symbol) => symbol.name))],
        references: [],
      });
    }

    if (!supportsLexicalModuleMetadata) {
      // The immutable bootstrap compiler predates intrinsic sagejs.runtime
      // imports and expands the compatibility package into every baselib
      // parse.  Its output intentionally retains the historical shared scope
      // for this one self-hosting pass.  The compiler it produces immediately
      // recompiles the baselib below with lexical modules.
      ans.pretty +=
        "globalThis.__sagejs_baselib_modules__ = Object.create(null);\n";
      for (const module of modules) {
        const output = new PyLang.OutputStream({
          beautify: true,
          keep_docstrings: true,
          write_name: false,
          private_scope: false,
          omit_baselib: true,
        });
        module.ast.print(output);
        ans.pretty += output.get();
        const descriptors = module.exports.map(function (name) {
          const javascriptName = namingOutput.make_name(name);
          return (
            JSON.stringify(name) +
            ":{enumerable:true,get:function(){return " +
            javascriptName +
            "}}"
          );
        });
        ans.pretty +=
          `globalThis.__sagejs_baselib_modules__[${JSON.stringify(
            module.moduleId,
          )}] = Object.create(null);\n`;
        if (descriptors.length > 0) {
          ans.pretty +=
            `Object.defineProperties(globalThis.__sagejs_baselib_modules__[` +
            `${JSON.stringify(module.moduleId)}],{${descriptors.join(",")}});\n`;
        }
      }
      return ans;
    }

    // The intrinsic host boundary supplies class/function adapters used while
    // builtins.py initializes.  Its legacy Sage facade aliases are inert in
    // this converged path; ordinary mathematical modules publish the real
    // values later in the same deterministic sequence.
    modules.sort(function (left, right) {
      const priority = function (module) {
        if (module.filename === "runtime_primitives.py") return 0;
        if (
          module.filename === "sagejs_bootstrap.py" ||
          module.filename === "compiler_bootstrap.py"
        )
          return 1;
        if (module.filename === "builtins.py") return 2;
        if (module.filename === "containers.py") return 3;
        if (module.filename === "errors.py") return 4;
        if (module.filename === "internal.py") return 5;
        if (module.filename === "str.py") return 6;
        if (module.moduleId === "sagejs.runtime") return 8;
        return 7;
      };
      return priority(left) - priority(right);
    });

    ans.pretty +=
      "globalThis.__sagejs_version_info__ = Object.freeze(" +
      JSON.stringify(version_info) +
      ");\n" +
      "var ρσ_baselib_modules = Object.create(null);\n" +
      "var ρσ_baselib_facade = Object.create(null);\n";
    // Install the registry before module initialization.  This is the
    // baselib equivalent of sys.modules: cyclic bootstrap dependencies may
    // observe modules which have finished initialization, while the module
    // currently being evaluated still uses its local namespace fallback.
    ans.pretty +=
      "globalThis.__sagejs_baselib_modules__ = ρσ_baselib_modules;\n";
    ans.pretty +=
      'ρσ_baselib_modules["sagejs"] = Object.create(null);\n' +
      'Object.defineProperties(ρσ_baselib_modules["sagejs"],{' +
      '__name__:{enumerable:true,value:"sagejs"},' +
      '__package__:{enumerable:true,value:"sagejs"}});\n';
    // Match Python's sys.modules rule: publish every module object before its
    // body executes.  Cycles can therefore observe stable, partially
    // initialized namespaces instead of allocating a second module or
    // accidentally resolving a shared outer variable.
    for (const module of modules) {
      ans.pretty +=
        `ρσ_baselib_modules[${JSON.stringify(module.moduleId)}] = ` +
        "Object.create(null);\n";
    }
    if (analysis.facadeNames.length > 0) {
      ans.pretty +=
        "var " +
        analysis.facadeNames.map((name) => namingOutput.make_name(name)).join(", ") +
        ";\n";
    }
    // Python's object bootstrap needs array literals while the full list
    // representation is itself being defined in containers.py.  This tiny
    // declaration-phase primitive is deliberately replaced by that module's
    // real implementation before user code runs.  It is not a mathematical
    // implementation and performs no host callback.
    ans.pretty += "ρσ_list_decorate = function(answer) { return answer; };\n";

    modules.forEach(function (module) {
      const outputOptions = {
        beautify: true,
        keep_docstrings: true,
        write_name: false,
        private_scope: false,
        omit_baselib: true,
        // This first module supplies class/MRO primitives which execute
        // before builtins.py defines ρσ_bool.  It deliberately uses native
        // JavaScript arrays and `.length`; every ordinary baselib module uses
        // OutputStream's Python-truthiness default.
        python_truthiness:
          module.moduleId !== "sagejs._baselib.runtime_primitives",
      };
      if (supportsPythonOrdering) {
        // Baselib's representation layer historically uses explicit native
        // ordering.  Truth testing is independently Python-aware; separating
        // these policies prevents a truthiness correction from silently
        // changing symbolic and graphics ordering dispatch.
        outputOptions.python_ordering = false;
      }
      outputOptions.baselib_module_id = module.moduleId;
      var output = new PyLang.OutputStream(outputOptions);
      module.ast.print(output);
      const publishesFacade = module.moduleId !== "sagejs.runtime";
      const facadeAssignments = module.exports
        .filter((name) => publishesFacade && facadeNameSet.has(name))
        .map(function (name) {
          const javascriptName = namingOutput.make_name(name);
          return (
            "ρσ_baselib_facade[" + JSON.stringify(name) + "] = " +
            javascriptName + ";"
          );
        })
        .join("\n");
      ans.pretty +=
        `ρσ_baselib_modules[${JSON.stringify(module.moduleId)}] = ` +
        "(function() {\n" +
        output.get() +
        (facadeAssignments ? "\n" + facadeAssignments : "") +
        "\nreturn ρσ_modules.__main__;\n" +
        "})();\n";
      for (const name of module.exports) {
        if (publishesFacade && facadeNameSet.has(name)) {
          ans.pretty +=
            namingOutput.make_name(name) +
            " = ρσ_baselib_facade[" + JSON.stringify(name) + "];\n";
        }
      }
    });
    ans.pretty +=
      'ρσ_baselib_modules["sagejs"].runtime = ' +
      'ρσ_baselib_modules["sagejs.runtime"];\n';
    ans.pretty += "ρσ_baselib_facade = null;\n";
  } finally {
    frontend?.close();
  }
  return ans;
}

function check_for_changes(base_path, src_path, signatures) {
  // Check if any of the files involved in the build process have changed,
  // as compared to the saved sha1 hashes from the last build
  var saved_hashes = {},
    hashes = {},
    sources = {};
  var compiler_changed = false,
    compiler_hash,
    source_hash;
  try {
    saved_hashes = JSON.parse(fs.readFileSync(signatures, "utf-8"));
  } catch (e) {
    if (e.code != "ENOENT") throw e;
  }

  var src_file_names = [];

  function process_dir(p) {
    fs.readdirSync(p).forEach(function (name) {
      var fp = path.join(p, name);
      if (name.endsWith(".py")) {
        src_file_names.push(path.relative(src_path, fp));
      } else if (name != "lib" && fs.statSync(fp).isDirectory()) {
        process_dir(fp);
      }
    });
  }
  process_dir(src_path);

  compiler_hash = crypto.createHash("sha1");
  source_hash = crypto.createHash("sha1");
  src_file_names.forEach(function (fname) {
    var src = path.join(src_path, fname);
    sources[src] = fs.readFileSync(src, "utf-8");
    compiler_hash.update(sources[src]);
    source_hash.update(sources[src]);
    var h = crypto.createHash("sha1");
    h.update(sources[src]);
    hashes[fname.split(".")[0]] = h.digest("hex");
  });
  var compiler_files = [
    module.filename,
    path.join(base_path, "sagejs-version.json"),
    path.join(base_path, "tools", "baselib-modules.cjs"),
    path.join(base_path, "tools", "compiler.ts"),
    path.join(base_path, "tools", "runtime-bootstrap.ts"),
  ];
  function add_typescript_sources(p) {
    fs.readdirSync(p).forEach(function (name) {
      var fp = path.join(p, name);
      if (fs.statSync(fp).isDirectory()) {
        add_typescript_sources(fp);
      } else if (name.endsWith(".ts")) {
        compiler_files.push(fp);
      }
    });
  }
  add_typescript_sources(path.join(base_path, "tools", "python"));
  compiler_files.forEach(function (fpath) {
    var contents = fs.readFileSync(fpath, "utf-8");
    compiler_hash.update(contents);
    // Lazy-module JavaScript is produced by both the Python compiler sources
    // and the authoritative TypeScript Tree-sitter frontend.  Include both in
    // the public compiler version so a frontend semantic change cannot reuse
    // stale third-party package code from ~/.cache/sagejs/modules.
    source_hash.update(contents);
  });
  hashes["#compiler#"] = compiler_hash.digest("hex");
  hashes["#compiled_with#"] = saved_hashes["#compiler#"] || "unknown";
  source_hash = source_hash.digest("hex");
  if (hashes["#compiler#"] != saved_hashes["#compiler#"]) {
    console.log(
      "There are changes to the source files of the compiler, rebuilding"
    );
    compiler_changed = true;
  } else if (hashes["#compiled_with#"] != saved_hashes["#compiled_with#"]) {
    console.log("Re-building compiler with updated version of itself");
    compiler_changed = true;
  }

  return [source_hash, compiler_changed, sources, hashes];
}

import createCompiler from "./compiler";

async function compile(
  base_path,
  src_path,
  lib_path,
  sources,
  source_hash,
  profile,
) {
  var file = path.join(src_path, "compiler.py");
  var t1 = new Date().getTime();
  var PyLang = createCompiler();
  var output_options, profiler, cpu_profile;
  var compiled_baselib = await compile_baselib(PyLang, src_path);
  var compiler_baselib = await compile_baselib(PyLang, src_path, true);
  var out_path = lib_path;
  try {
    fs.mkdirSync(out_path);
  } catch (e) {
    if (e.code != "EEXIST") throw e;
  }
  // The compiler implementation is bootstrap infrastructure written against
  // native JavaScript objects.  Keep this sole whole-program escape hatch
  // explicit; generated Python and ordinary baselib modules default to Python
  // truth testing.
  output_options = {
    beautify: true,
    baselib_plain: compiler_baselib.pretty,
  };
  try {
    // The immutable stage-zero compiler predates this option and already
    // emits native JavaScript conditions.  Once the current OutputStream is
    // available, make the compiler-only exception explicit.
    new PyLang.OutputStream({ python_truthiness: false });
    output_options.python_truthiness = false;
  } catch (_error) {}
  try {
    new PyLang.OutputStream({ python_ordering: false });
    output_options.python_ordering = false;
  } catch (_error) {}

  var raw = sources[file],
    toplevel;

  const { createPythonCompilerFrontend } = require("./python/compiler-frontend");
  const frontend = PyLang.AST_AnnotatedAssignment
    ? await createPythonCompilerFrontend(PyLang, "python")
    : null;
  function parse_file(code, file) {
    return (frontend ? frontend.parse : PyLang.parse)(code, {
      filename: file,
      basedir: path.dirname(file),
      libdir: path.join(src_path, "lib"),
      compiler_bootstrap: true,
    });
  }

  try {
    if (profile) {
      profiler = require("v8-profiler");
      profiler.startProfiling();
    }
    toplevel = parse_file(raw, file);
    if (profile) {
      cpu_profile = profiler.stopProfiling();
      fs.writeFileSync("self.cpuprofile", JSON.stringify(cpu_profile), "utf-8");
    }
  } catch (e) {
    if (!(e instanceof PyLang.SyntaxError)) throw e;
    console.error(e.toString());
    process.exit(1);
  } finally {
    frontend?.close();
  }
  var output = new PyLang.OutputStream(output_options);
  toplevel.print(output);
  output = output.get().replace("__COMPILER_VERSION__", source_hash);
  // Module metadata is useful for tracebacks, but a production compiler must
  // not depend on the directory where it was built. Keep the real basedir and
  // libdir above for import resolution, then publish stable virtual paths.
  output = canonicalizeGeneratedPaths(output, base_path);
  compiled_baselib.pretty = canonicalizeGeneratedPaths(
    compiled_baselib.pretty,
    base_path,
  );
  fs.writeFileSync(path.join(out_path, "compiler.js"), output, "utf8");
  fs.writeFileSync(
    path.join(out_path, "baselib-plain-pretty.js"),
    compiled_baselib.pretty,
    "utf-8"
  );
  console.log(
    "Compiler built in",
    (new Date().getTime() - t1) / 1000,
    "seconds\n"
  );
  return output;
}

async function run_single_compile(base_path, src_path, lib_path, profile) {
  var out_path = lib_path;
  var signatures = path.join(out_path, "signatures.json");
  var temp = check_for_changes(base_path, src_path, signatures);
  var source_hash = temp[0],
    compiler_changed = temp[1],
    sources = temp[2],
    hashes = temp[3];

  if (compiler_changed) {
    await compile(base_path, src_path, lib_path, sources, source_hash, profile);
    fs.writeFileSync(signatures, JSON.stringify(hashes, null, 4));
  } else console.log("Compiler is built with the up-to-date version of itself");
  return compiler_changed;
}

module.exports = async function compile_self(
  base_path,
  src_path,
  lib_path,
  complete,
  profile
) {
  var changed;
  do {
    changed = await run_single_compile(base_path, src_path, lib_path, profile);
    lib_path = lib_path;
  } while (changed && complete);
};
