"""Semantic plotting documents shared by Sage.js frontends and renderers."""

from ._json import JSONScalar, JSONValue, canonical_json, materialize_json
from .axes import (
    AnnotationSettings,
    Axes2DSettings,
    AxisSettings,
    LegendSettings,
    Scene3DSettings,
    UnsupportedPresentationError,
    lower_annotations,
    lower_axes_2d,
    lower_legend,
    lower_scene_3d,
    unsupported_option_diagnostic,
)
from .composition import (
    Panel2D,
    PanelComposition2D,
    lower_panel_figure,
    qualified_layer_id,
    stable_panel_id,
)
from .diagnostics import (
    Diagnostic,
    diagnostic_definition,
    diagnostic_registry,
    materialize_diagnostic,
)
from .lowering import lower_layer, lower_plot_spec
from .model import (
    PLOTSPEC_SCHEMA_VERSION,
    PlotLayer,
    PlotSpec,
    Provenance,
    make_layer,
    next_layer_id,
    stable_layer_id,
)
from .styles import (
    NormalizedStyle,
    OptionResult,
    color_channels,
    normalize_color,
    normalize_fill_style,
    normalize_line_style,
    normalize_marker_style,
    normalize_text_style,
)
from .surface_layers import (
    MAX_MESH_TRIANGLES,
    MAX_MESH_VERTICES,
    MAX_SURFACE_SAMPLES,
    lower_3d_geometry_layer,
    polygon_layer,
    rectangular_surface_layer,
    triangular_mesh_layer,
)
from .themes import (
    PlotTheme,
    contrast_ratio,
    get_theme,
    theme_contrast,
    theme_names,
    theme_registry,
)

__all__ = [
    "Diagnostic",
    "AnnotationSettings",
    "Axes2DSettings",
    "AxisSettings",
    "JSONScalar",
    "JSONValue",
    "PLOTSPEC_SCHEMA_VERSION",
    "NormalizedStyle",
    "OptionResult",
    "LegendSettings",
    "MAX_MESH_TRIANGLES",
    "MAX_MESH_VERTICES",
    "MAX_SURFACE_SAMPLES",
    "Panel2D",
    "PanelComposition2D",
    "PlotLayer",
    "PlotSpec",
    "PlotTheme",
    "Provenance",
    "Scene3DSettings",
    "UnsupportedPresentationError",
    "canonical_json",
    "color_channels",
    "contrast_ratio",
    "diagnostic_definition",
    "diagnostic_registry",
    "lower_annotations",
    "lower_3d_geometry_layer",
    "lower_axes_2d",
    "lower_layer",
    "lower_legend",
    "lower_panel_figure",
    "lower_plot_spec",
    "lower_scene_3d",
    "make_layer",
    "materialize_diagnostic",
    "materialize_json",
    "next_layer_id",
    "normalize_color",
    "normalize_fill_style",
    "normalize_line_style",
    "normalize_marker_style",
    "normalize_text_style",
    "polygon_layer",
    "qualified_layer_id",
    "rectangular_surface_layer",
    "stable_layer_id",
    "stable_panel_id",
    "get_theme",
    "theme_contrast",
    "theme_names",
    "theme_registry",
    "triangular_mesh_layer",
    "unsupported_option_diagnostic",
]
