"use strict";

const state={data:null,query:"",selected:null};
const $=(selector)=>document.querySelector(selector);
const referenceDataUrl=document.body?.dataset.referenceData||"./reference-data.json";
const node=(tag,className,text)=>{const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n};
const escapeHtml=(text)=>String(text).replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
function inline(text){return escapeHtml(text).replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>")}
function doctestUnits(text){const units=[];let current=null;for(const line of text.split("\n")){const prompt=line.match(/^\s*(sage:|\.\.\.\.:)\s?(.*)$/);if(prompt){if(prompt[1]==="sage:"){if(current)units.push(current);current={source:prompt[2],want:[]}}else if(current){current.source+=`\n${prompt[2]}`}continue}if(current)current.want.push(line.replace(/^ {4}/,""))}if(current)units.push(current);return units}
function renderDoc(text,examples){const root=node("section","doc"),consumed=new Set();let fence=null;for(const line of String(text||"").split("\n")){const marker=line.trim().match(/^```(.*)$/);if(marker){if(fence===null){fence={language:marker[1].trim(),lines:[]}}else{const raw=fence.lines.join("\n");if(fence.language==="sage"&&/^\s*sage:/m.test(raw)){const group=node("div","doc-examples");for(const unit of doctestUnits(raw)){const source=unit.source.trimEnd();const example=examples.find((item)=>!consumed.has(item.id)&&item.source.trimEnd()===source);if(example){consumed.add(example.id);group.append(exampleCard(example))}else{group.append(exampleCard({id:`inline:${source}`,source,want:`${unit.want.join("\n").trimEnd()}\n`,language:"sage",verification:{status:"unverified"}}))}}root.append(group)}else{const pre=node("pre"),code=node("code","",raw);pre.append(code);highlightCode(code,fence.language);root.append(pre)}fence=null}continue}if(fence){fence.lines.push(line);continue}if(/^###\s+/.test(line)){root.append(node("h3","",line.replace(/^###\s+/,"")));continue}if(/^[-*]\s+/.test(line)){const item=node("div");item.innerHTML=`• ${inline(line.replace(/^[-*]\s+/,""))}`;root.append(item);continue}if(line.trim()){const paragraph=node("div");paragraph.innerHTML=inline(line);root.append(paragraph)}else{root.append(document.createElement("br"))}}return {root,consumed}}
function searchable(entry){return [entry.name,entry.signature,entry.summary,entry.doc,...entry.aliases,...entry.tags,...entry.backends,...entry.examples.flatMap((x)=>[x.source,x.want,x.owner])].join(" ").toLowerCase()}
function filtered(){const terms=state.query.toLowerCase().trim().split(/\s+/).filter(Boolean);return state.data.entries.filter((entry)=>terms.every((term)=>searchable(entry).includes(term))).sort((a,b)=>{const q=state.query.toLowerCase();const score=(x)=>x.name.toLowerCase()===q?0:x.name.toLowerCase().startsWith(q)?1:x.name.toLowerCase().includes(q)?2:3;return score(a)-score(b)||a.name.localeCompare(b.name)})}
function setUrl(){const url=new URL(location.href);state.query?url.searchParams.set("q",state.query):url.searchParams.delete("q");state.selected?url.hash=encodeURIComponent(state.selected):url.hash="";history.replaceState(null,"",url)}
function coverage(){const c=state.data.coverage,e=c.examples,d=c.documentation;const values=[[d.registry_entries,"declared APIs"],[d.with_docstring,"with docs"],[e.documented,"examples"],[e.verified,"CI verified"]];const root=$("#coverage");for(const [value,label] of values){const item=node("span","metric");item.innerHTML=`<b>${value}</b> ${label}`;root.append(item)}const warning=node("span","metric warning","Denominator: DocSpec registry · semantic/performance coverage separate");root.append(warning)}
function renderResults(){const entries=filtered();$("#result-count").textContent=`${entries.length} ${entries.length===1?"entry":"entries"}`;const list=$("#result-list");list.replaceChildren();for(const entry of entries){const button=node("button",`result${entry.name===state.selected?" active":""}`);button.type="button";button.append(node("code","",entry.name),node("small","",entry.summary||entry.signature));button.onclick=()=>select(entry.name);list.append(button)}if(!state.selected&&entries.length)select(entries[0].name,false)}
function chip(value,kind=""){return node("span",`chip ${kind}`,value)}
async function copy(button,text){await navigator.clipboard.writeText(text);const before=button.textContent;button.textContent="Copied";setTimeout(()=>button.textContent=before,1000)}
function prismLanguage(language){return ["sage","python","py"].includes(String(language||"").toLowerCase())?"python":null}
function highlightCode(code,language){const pre=code.parentElement;for(const element of [code,pre]){if(!element)continue;for(const name of [...element.classList])if(name.startsWith("language-"))element.classList.remove(name)}const resolved=prismLanguage(language);if(!resolved||!window.Prism?.languages?.[resolved])return;code.classList.add(`language-${resolved}`);pre?.classList.add(`language-${resolved}`);window.Prism.highlightElement(code)}
function examplePane(label,role,text,language=""){const pane=node("div","example-pane");pane.append(node("div","example-label",label));const pre=node("pre");pre.dataset.exampleRole=role;const code=node("code","",text);pre.append(code);if(role==="input")highlightCode(code,language);pane.append(pre);return pane}
function graphPreview(display){if(display?.mime!=="application/vnd.plotly.v1+json")return null;const figure=display.data;const edges=figure?.data?.find((trace)=>trace.mode==="lines");const vertices=figure?.data?.find((trace)=>String(trace.mode).includes("markers"));if(!edges||!vertices)return null;const allX=[...edges.x,...vertices.x].filter(Number.isFinite),allY=[...edges.y,...vertices.y].filter(Number.isFinite);if(!allX.length||!allY.length)return null;const width=640,height=390,padding=42,minX=Math.min(...allX),maxX=Math.max(...allX),minY=Math.min(...allY),maxY=Math.max(...allY),scale=Math.min((width-2*padding)/(maxX-minX||1),(height-2*padding)/(maxY-minY||1)),point=(x,y)=>[width/2+(x-(minX+maxX)/2)*scale,height/2-(y-(minY+maxY)/2)*scale];const namespace="http://www.w3.org/2000/svg",svg=document.createElementNS(namespace,"svg");svg.classList.add("example-visual");svg.setAttribute("viewBox",`0 0 ${width} ${height}`);svg.setAttribute("role","img");svg.setAttribute("aria-label",figure.layout?.title||"Verified graph plot");for(let index=0;index<edges.x.length-1;index++){if(!Number.isFinite(edges.x[index])||!Number.isFinite(edges.x[index+1]))continue;const [x1,y1]=point(edges.x[index],edges.y[index]),[x2,y2]=point(edges.x[index+1],edges.y[index+1]),line=document.createElementNS(namespace,"line");for(const [name,value] of [["x1",x1],["y1",y1],["x2",x2],["y2",y2]])line.setAttribute(name,String(value));line.setAttribute("stroke",edges.line?.color||"#64748b");line.setAttribute("stroke-width",String(edges.line?.width||1.5));svg.append(line)}for(let index=0;index<vertices.x.length;index++){const [x,y]=point(vertices.x[index],vertices.y[index]),circle=document.createElementNS(namespace,"circle"),label=document.createElementNS(namespace,"text");circle.setAttribute("cx",String(x));circle.setAttribute("cy",String(y));circle.setAttribute("r",String(Math.max(8,(vertices.marker?.size||24)/2)));circle.setAttribute("fill",vertices.marker?.color||"#377eb8");circle.setAttribute("stroke","#fff");circle.setAttribute("stroke-width","1.5");label.setAttribute("x",String(x));label.setAttribute("y",String(y+4));label.setAttribute("text-anchor","middle");label.textContent=String(vertices.text?.[index]??index);svg.append(circle,label)}const preview=node("figure","example-preview");preview.append(node("figcaption","",`Verified graphical output · ${figure.layout?.title||"graph plot"}`),svg);return preview}
function exampleCard(example){
  const article=node("section","example");
  const status=example.verification?.status||"unverified";
  const head=node("div","example-head");
  const label=status==="pass"?"✓ CI verified":status;
  head.append(node("span",`status ${status}`,`${label}${example.origin==="upstream-sage"?" · upstream Sage":""}`));
  const copyButton=node("button","copy","Copy input");
  copyButton.type="button";
  copyButton.onclick=()=>copy(copyButton,article.querySelector('[data-example-role="input"] code').textContent);
  head.append(copyButton);
  article.append(head);
  const variants=example.variants||[{language:example.language||"sage",source:example.source,want:example.want}];
  if(typeof variants[0]?.source!=="string"||!variants[0].source.trim())throw new Error(`reference example ${example.id||"(unknown)"} has no source`);
  if(variants.length>1){
    const tabs=node("div","language-tabs");
    for(const [index,variant] of variants.entries()){
      const button=node("button",index===0?"active":"",variant.language);
      button.onclick=()=>{
        const before=article.getBoundingClientRect().top;
        article.querySelectorAll(".language-tabs button").forEach((x)=>x.classList.remove("active"));
        button.classList.add("active");
        const input=article.querySelector('[data-example-role="input"] code');
        input.textContent=variant.source;
        highlightCode(input,variant.language);
        article.querySelector('[data-example-role="output"] code').textContent=variant.want?.trimEnd()||"(no textual output)";
        requestAnimationFrame(()=>scrollBy(0,article.getBoundingClientRect().top-before));
      };
      tabs.append(button);
    }
    article.append(tabs);
  }
  const body=node("div","example-body");
  body.append(
    examplePane("Input","input",variants[0].source,variants[0].language),
    examplePane("Expected output","output",variants[0].want?.trimEnd()||"(no textual output)"),
  );
  article.append(body);
  const preview=graphPreview(example.verification?.display);
  if(preview)article.append(preview);
  if(example.tags?.length)article.append(node("p","example-note",example.tags.map((x)=>`# ${x.name}${x.value?` ${x.value}`:""}`).join(" · ")));
  if(example.verification?.reason)article.append(node("p","example-note",example.verification.reason));
  return article;
}
function sourceBlock(source){if(!source)return null;const details=node("details","source");details.id="source";details.append(node("summary","",`Browse relevant source · ${source.path}:${source.line}`));const toolbar=node("div","source-toolbar"),link=node("a","source-file-link");link.href=`https://github.com/sagemathinc/sagejs/blob/main/${encodeURI(source.path)}#L${source.line}`;link.target="_blank";link.rel="noopener noreferrer";link.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 .7a11.5 11.5 0 0 0-3.64 22.41c.58.11.79-.25.79-.56v-2.23c-3.22.7-3.9-1.37-3.9-1.37-.52-1.34-1.29-1.69-1.29-1.69-1.05-.72.08-.71.08-.71 1.17.08 1.78 1.2 1.78 1.2 1.04 1.78 2.72 1.27 3.38.97.1-.75.4-1.27.74-1.56-2.57-.29-5.27-1.28-5.27-5.68 0-1.26.45-2.28 1.19-3.09-.12-.29-.52-1.46.11-3.05 0 0 .97-.31 3.16 1.18a10.9 10.9 0 0 1 5.75 0c2.2-1.49 3.16-1.18 3.16-1.18.63 1.59.23 2.76.11 3.05.74.81 1.19 1.83 1.19 3.09 0 4.41-2.71 5.38-5.29 5.67.42.36.79 1.06.79 2.14v3.18c0 .31.21.67.8.56A11.5 11.5 0 0 0 12 .7Z"/></svg><span>Open full file on GitHub</span>';toolbar.append(link);details.append(toolbar);const pre=node("pre","line-numbers"),code=node("code","",source.excerpt.text);pre.dataset.start=String(source.excerpt.start_line);pre.append(code);highlightCode(code,"python");details.append(pre);return details}
function select(name,update=true){const entry=state.data.entries.find((x)=>x.name===name);if(!entry)return;state.selected=name;if(update)setUrl();renderResults();const root=$("#entry");root.replaceChildren();const header=node("header","entry-header");header.append(node("p","eyebrow",`${entry.kind} · ${entry.module||"Sage.js runtime"}`),node("h2","",entry.name));const chips=node("div","chips");for(const item of entry.tags)chips.append(chip(item));for(const item of entry.backends)chips.append(chip(item,"backend"));header.append(chips);root.append(header);const signature=node("pre","signature");signature.append(node("code","",entry.signature));root.append(signature);const compatibility=node("div",`notice ${entry.sage_compatibility.status}`);compatibility.innerHTML=`<strong>Sage compatibility: ${escapeHtml(entry.sage_compatibility.status)}</strong>${entry.sage_compatibility.notes?` — ${escapeHtml(entry.sage_compatibility.notes)}`:""}`;root.append(compatibility);const rendered=renderDoc(entry.doc,entry.examples);root.append(rendered.root);const additional=entry.examples.filter((example)=>!rendered.consumed.has(example.id));if(additional.length){root.append(node("h3","section-title",`${additional.length} additional executable ${additional.length===1?"example":"examples"}`));for(const example of additional)root.append(exampleCard(example))}else if(!entry.examples.length){root.append(node("div","notice partial","No executable public example is attached yet. This is counted as a documentation gap."))}const meta=node("div","meta-grid");const provenance=node("section","meta-card");provenance.append(node("h4","","Provenance"),node("p","",entry.provenance.map((x)=>[x.kind,x.source,x.license].filter(Boolean).join(" · ")).join("; ")||"Not recorded"));const limits=node("section","meta-card");limits.append(node("h4","","Limitations"),node("p","",entry.limitations.join(" ")||"None recorded for the supported surface."));meta.append(provenance,limits);root.append(meta);const source=sourceBlock(entry.source);if(source)root.append(source)}
async function start(){const response=await fetch(referenceDataUrl);if(!response.ok)throw new Error(`HTTP ${response.status}`);state.data=await response.json();const url=new URL(location.href);state.query=url.searchParams.get("q")||"";state.selected=decodeURIComponent(url.hash.slice(1));$("#search").value=state.query;coverage();renderResults();if(state.selected)select(state.selected,false);$("#search").addEventListener("input",(event)=>{state.query=event.target.value;state.selected=null;setUrl();renderResults()});window.addEventListener("hashchange",()=>{const name=decodeURIComponent(location.hash.slice(1));if(name)select(name,false)});document.documentElement.dataset.referenceReady="true"}
start().catch((error)=>{$("#result-count").textContent=`Reference failed to load: ${error.message}`});
